// Copyright David Stone 2020.
// Distributed under the Boost Software License, Version 1.0.
// (See accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt)

module;

#include <bounded/conditional.hpp>

export module tm.move.accuracy;

import tm.move.move_name;

import tm.environment;
import tm.generation;

import bounded;
import tv;

namespace technicalmachine {
using namespace bounded::literal;

// A value that is not present indicates that the move cannot miss.
export using BaseAccuracy = tv::optional<bounded::integer<30, 100>>;
export constexpr auto accuracy(Generation const generation, MoveName const move, Environment const environment, bool const weather_blocked, bool const user_is_poison) -> BaseAccuracy {
	using tv::none;
	switch (move) {
		case MoveName::Pass: return none;
		case MoveName::Switch0: return none;
		case MoveName::Switch1: return none;
		case MoveName::Switch2: return none;
		case MoveName::Switch3: return none;
		case MoveName::Switch4: return none;
		case MoveName::Switch5: return none;
		case MoveName::Hit_Self: return none;
		case MoveName::Pound: return 100_bi;
		case MoveName::Karate_Chop: return 100_bi;
		case MoveName::Double_Slap: return 85_bi;
		case MoveName::Comet_Punch: return 85_bi;
		case MoveName::Mega_Punch: return 85_bi;
		case MoveName::Pay_Day: return 100_bi;
		case MoveName::Fire_Punch: return 100_bi;
		case MoveName::Ice_Punch: return 100_bi;
		case MoveName::Thunder_Punch: return 100_bi;
		case MoveName::Scratch: return 100_bi;
		case MoveName::Vise_Grip: return 100_bi;
		case MoveName::Guillotine: return 30_bi;
		case MoveName::Razor_Wind: return BOUNDED_CONDITIONAL(generation <= Generation::two, 75_bi, 100_bi);
		case MoveName::Swords_Dance: return none;
		case MoveName::Cut: return 95_bi;
		case MoveName::Gust: return 100_bi;
		case MoveName::Wing_Attack: return 100_bi;
		case MoveName::Whirlwind:
			switch (generation) {
				case Generation::one:
					return 85_bi;
				case Generation::two:
				case Generation::three:
				case Generation::four:
				case Generation::five:
					return 100_bi;
				default:
					return none;
			}
		case MoveName::Fly: return 95_bi;
		case MoveName::Bind: return BOUNDED_CONDITIONAL(generation <= Generation::four, 75_bi, 85_bi);
		case MoveName::Slam: return 75_bi;
		case MoveName::Vine_Whip: return 100_bi;
		case MoveName::Stomp: return 100_bi;
		case MoveName::Double_Kick: return 100_bi;
		case MoveName::Mega_Kick: return 75_bi;
		case MoveName::Jump_Kick: return 95_bi;
		case MoveName::Rolling_Kick: return 85_bi;
		case MoveName::Sand_Attack: return 100_bi;
		case MoveName::Headbutt: return 100_bi;
		case MoveName::Horn_Attack: return 100_bi;
		case MoveName::Fury_Attack: return 85_bi;
		case MoveName::Horn_Drill: return 30_bi;
		case MoveName::Tackle: return BOUNDED_CONDITIONAL(generation <= Generation::four, 95_bi, 100_bi);
		case MoveName::Body_Slam: return 100_bi;
		case MoveName::Wrap: return BOUNDED_CONDITIONAL(generation <= Generation::four, 85_bi, 90_bi);
		case MoveName::Take_Down: return 85_bi;
		case MoveName::Thrash: return 100_bi;
		case MoveName::Double_Edge: return 100_bi;
		case MoveName::Tail_Whip: return 100_bi;
		case MoveName::Poison_Sting: return 100_bi;
		case MoveName::Twineedle: return 100_bi;
		case MoveName::Pin_Missile: return BOUNDED_CONDITIONAL(generation <= Generation::five, 85_bi, 95_bi);
		case MoveName::Leer: return 100_bi;
		case MoveName::Bite: return 100_bi;
		case MoveName::Growl: return 100_bi;
		case MoveName::Roar: return generation <= Generation::five ? BaseAccuracy(100_bi) : none;
		case MoveName::Sing: return 55_bi;
		case MoveName::Supersonic: return 55_bi;
		case MoveName::Sonic_Boom: return 90_bi;
		case MoveName::Disable:
			switch (generation) {
				case Generation::one:
				case Generation::two:
				case Generation::three:
					return 55_bi;
				case Generation::four:
					return 80_bi;
				default:
					return 100_bi;
			}
		case MoveName::Acid: return 100_bi;
		case MoveName::Ember: return 100_bi;
		case MoveName::Flamethrower: return 100_bi;
		case MoveName::Mist: return none;
		case MoveName::Water_Gun: return 100_bi;
		case MoveName::Hydro_Pump: return 80_bi;
		case MoveName::Surf: return 100_bi;
		case MoveName::Ice_Beam: return 100_bi;
		case MoveName::Blizzard:
			if (environment.hail() and !weather_blocked) {
				return none;
			}
			return BOUNDED_CONDITIONAL(generation == Generation::one, 90_bi, 70_bi);
		case MoveName::Psybeam: return 100_bi;
		case MoveName::Bubble_Beam: return 100_bi;
		case MoveName::Aurora_Beam: return 100_bi;
		case MoveName::Hyper_Beam: return 90_bi;
		case MoveName::Peck: return 100_bi;
		case MoveName::Drill_Peck: return 100_bi;
		case MoveName::Submission: return 80_bi;
		case MoveName::Low_Kick: return BOUNDED_CONDITIONAL(generation <= Generation::two, 90_bi, 100_bi);
		case MoveName::Counter: return 100_bi;
		case MoveName::Seismic_Toss: return 100_bi;
		case MoveName::Strength: return 100_bi;
		case MoveName::Absorb: return 100_bi;
		case MoveName::Mega_Drain: return 100_bi;
		case MoveName::Leech_Seed: return 90_bi;
		case MoveName::Growth: return none;
		case MoveName::Razor_Leaf: return 95_bi;
		case MoveName::Solar_Beam: return 100_bi;
		case MoveName::Poison_Powder: return 75_bi;
		case MoveName::Stun_Spore: return 75_bi;
		case MoveName::Sleep_Powder: return 75_bi;
		case MoveName::Petal_Dance: return 100_bi;
		case MoveName::String_Shot: return 95_bi;
		case MoveName::Dragon_Rage: return 100_bi;
		case MoveName::Fire_Spin: return BOUNDED_CONDITIONAL(generation <= Generation::four, 70_bi, 85_bi);
		case MoveName::Thunder_Shock: return 100_bi;
		case MoveName::Thunderbolt: return 100_bi;
		case MoveName::Thunder_Wave: return BOUNDED_CONDITIONAL(generation <= Generation::six, 100_bi, 90_bi);
		case MoveName::Thunder: {
			constexpr auto default_value = BaseAccuracy(70_bi);
			if (weather_blocked) {
				return default_value;
			}
			return
				environment.rain() ? none :
				environment.sun() ? BaseAccuracy(50_bi) :
				default_value;
		}
		case MoveName::Rock_Throw: return BOUNDED_CONDITIONAL(generation == Generation::one, 65_bi, 90_bi);
		case MoveName::Earthquake: return 100_bi;
		case MoveName::Fissure: return 30_bi;
		case MoveName::Dig: return 100_bi;
		case MoveName::Toxic:
			switch (generation) {
				case Generation::one:
				case Generation::two:
				case Generation::three:
				case Generation::four:
					return 85_bi;
				case Generation::five:
					return 90_bi;
				default:
					return user_is_poison ? none : BaseAccuracy(90_bi);
			}
		case MoveName::Confusion: return 100_bi;
		case MoveName::Psychic: return 100_bi;
		case MoveName::Hypnosis: return 60_bi;
		case MoveName::Meditate: return none;
		case MoveName::Agility: return none;
		case MoveName::Quick_Attack: return 100_bi;
		case MoveName::Rage: return 100_bi;
		case MoveName::Teleport: return none;
		case MoveName::Night_Shade: return 100_bi;
		case MoveName::Mimic: return generation <= Generation::two ? BaseAccuracy(100_bi) : none;
		case MoveName::Screech: return 85_bi;
		case MoveName::Double_Team: return none;
		case MoveName::Recover: return none;
		case MoveName::Harden: return none;
		case MoveName::Minimize: return none;
		case MoveName::Smokescreen: return 100_bi;
		case MoveName::Confuse_Ray: return 100_bi;
		case MoveName::Withdraw: return none;
		case MoveName::Defense_Curl: return none;
		case MoveName::Barrier: return none;
		case MoveName::Light_Screen: return none;
		case MoveName::Haze: return none;
		case MoveName::Reflect: return none;
		case MoveName::Focus_Energy: return none;
		case MoveName::Bide:
			switch (generation) {
				case Generation::one:
					return none;
				case Generation::two:
				case Generation::three:
					return 100_bi;
				default:
					return none;
			}
		case MoveName::Metronome: return none;
		case MoveName::Mirror_Move: return none;
		case MoveName::Self_Destruct: return 100_bi;
		case MoveName::Egg_Bomb: return 75_bi;
		case MoveName::Lick: return 100_bi;
		case MoveName::Smog: return 70_bi;
		case MoveName::Sludge: return 100_bi;
		case MoveName::Bone_Club: return 85_bi;
		case MoveName::Fire_Blast: return 85_bi;
		case MoveName::Waterfall: return 100_bi;
		case MoveName::Clamp: return BOUNDED_CONDITIONAL(generation <= Generation::four, 75_bi, 85_bi);
		case MoveName::Swift: return none;
		case MoveName::Skull_Bash: return 100_bi;
		case MoveName::Spike_Cannon: return 100_bi;
		case MoveName::Constrict: return 100_bi;
		case MoveName::Amnesia: return none;
		case MoveName::Kinesis: return 80_bi;
		case MoveName::Soft_Boiled: return none;
		case MoveName::High_Jump_Kick: return 90_bi;
		case MoveName::Glare:
			switch (generation) {
				case Generation::one:
				case Generation::two:
				case Generation::three:
				case Generation::four:
					return 75_bi;
				case Generation::five:
					return 90_bi;
				default:
					return 100_bi;
			}
		case MoveName::Dream_Eater: return 100_bi;
		case MoveName::Poison_Gas:
			switch (generation) {
				case Generation::one:
				case Generation::two:
				case Generation::three:
				case Generation::four:
					return 55_bi;
				case Generation::five:
					return 80_bi;
				default:
					return 90_bi;
			}
		case MoveName::Barrage: return 85_bi;
		case MoveName::Leech_Life: return 100_bi;
		case MoveName::Lovely_Kiss: return 75_bi;
		case MoveName::Sky_Attack: return 90_bi;
		case MoveName::Transform: return none;
		case MoveName::Bubble: return 100_bi;
		case MoveName::Dizzy_Punch: return 100_bi;
		case MoveName::Spore: return 100_bi;
		case MoveName::Flash: return BOUNDED_CONDITIONAL(generation <= Generation::three, 70_bi, 100_bi);
		case MoveName::Psywave: return BOUNDED_CONDITIONAL(generation <= Generation::five, 80_bi, 100_bi);
		case MoveName::Splash: return none;
		case MoveName::Acid_Armor: return none;
		case MoveName::Crabhammer: return BOUNDED_CONDITIONAL(generation <= Generation::four, 85_bi, 90_bi);
		case MoveName::Explosion: return 100_bi;
		case MoveName::Fury_Swipes: return 80_bi;
		case MoveName::Bonemerang: return 90_bi;
		case MoveName::Rest: return none;
		case MoveName::Rock_Slide: return 90_bi;
		case MoveName::Hyper_Fang: return 90_bi;
		case MoveName::Sharpen: return none;
		case MoveName::Conversion: return none;
		case MoveName::Tri_Attack: return 100_bi;
		case MoveName::Super_Fang: return 90_bi;
		case MoveName::Slash: return 100_bi;
		case MoveName::Substitute: return none;
		case MoveName::Struggle: return generation <= Generation::three ? BaseAccuracy(100_bi) : none;
		case MoveName::Sketch: return none;
		case MoveName::Triple_Kick: return 90_bi;
		case MoveName::Thief: return 100_bi;
		case MoveName::Spider_Web: return none;
		case MoveName::Mind_Reader: return generation <= Generation::three ? BaseAccuracy(100_bi) : none;
		case MoveName::Nightmare: return generation <= Generation::three ? none : BaseAccuracy(100_bi);
		case MoveName::Flame_Wheel: return 100_bi;
		case MoveName::Snore: return 100_bi;
		case MoveName::Curse: return none;
		case MoveName::Flail: return 100_bi;
		case MoveName::Conversion_2: return none;
		case MoveName::Aeroblast: return 95_bi;
		case MoveName::Cotton_Spore: return BOUNDED_CONDITIONAL(generation <= Generation::four, 85_bi, 100_bi);
		case MoveName::Reversal: return 100_bi;
		case MoveName::Spite: return 100_bi;
		case MoveName::Powder_Snow: return 100_bi;
		case MoveName::Protect: return none;
		case MoveName::Mach_Punch: return 100_bi;
		case MoveName::Scary_Face: return BOUNDED_CONDITIONAL(generation <= Generation::four, 90_bi, 100_bi);
		case MoveName::Feint_Attack: return none;
		case MoveName::Sweet_Kiss: return 75_bi;
		case MoveName::Belly_Drum: return none;
		case MoveName::Sludge_Bomb: return 100_bi;
		case MoveName::Mud_Slap: return 100_bi;
		case MoveName::Octazooka: return 85_bi;
		case MoveName::Spikes: return none;
		case MoveName::Zap_Cannon: return 50_bi;
		case MoveName::Foresight: return generation <= Generation::three ? BaseAccuracy(100_bi) : none;
		case MoveName::Destiny_Bond: return none;
		case MoveName::Perish_Song: return none;
		case MoveName::Icy_Wind: return 95_bi;
		case MoveName::Detect: return none;
		case MoveName::Bone_Rush: return BOUNDED_CONDITIONAL(generation <= Generation::four, 80_bi, 90_bi);
		case MoveName::Lock_On: return generation <= Generation::three ? BaseAccuracy(100_bi) : none;
		case MoveName::Outrage: return 100_bi;
		case MoveName::Sandstorm: return none;
		case MoveName::Giga_Drain: return 100_bi;
		case MoveName::Endure: return none;
		case MoveName::Charm: return 100_bi;
		case MoveName::Rollout: return 90_bi;
		case MoveName::False_Swipe: return 100_bi;
		case MoveName::Swagger: return BOUNDED_CONDITIONAL(generation <= Generation::six, 90_bi, 85_bi);
		case MoveName::Milk_Drink: return none;
		case MoveName::Spark: return 100_bi;
		case MoveName::Fury_Cutter: return 95_bi;
		case MoveName::Steel_Wing: return 90_bi;
		case MoveName::Mean_Look: return none;
		case MoveName::Attract: return 100_bi;
		case MoveName::Sleep_Talk: return none;
		case MoveName::Heal_Bell: return none;
		case MoveName::Return: return 100_bi;
		case MoveName::Present: return 90_bi;
		case MoveName::Frustration: return 100_bi;
		case MoveName::Safeguard: return none;
		case MoveName::Pain_Split: return generation <= Generation::two ? BaseAccuracy(100_bi) : none;
		case MoveName::Sacred_Fire: return 95_bi;
		case MoveName::Magnitude: return 100_bi;
		case MoveName::Dynamic_Punch: return 50_bi;
		case MoveName::Megahorn: return 85_bi;
		case MoveName::Dragon_Breath: return 100_bi;
		case MoveName::Baton_Pass: return none;
		case MoveName::Encore: return 100_bi;
		case MoveName::Pursuit: return 100_bi;
		case MoveName::Rapid_Spin: return 100_bi;
		case MoveName::Sweet_Scent: return 100_bi;
		case MoveName::Iron_Tail: return 75_bi;
		case MoveName::Metal_Claw: return 95_bi;
		case MoveName::Vital_Throw: return none;
		case MoveName::Morning_Sun: return none;
		case MoveName::Synthesis: return none;
		case MoveName::Moonlight: return none;
		case MoveName::Hidden_Power: return 100_bi;
		case MoveName::Cross_Chop: return 80_bi;
		case MoveName::Twister: return 100_bi;
		case MoveName::Rain_Dance: return none;
		case MoveName::Sunny_Day: return none;
		case MoveName::Crunch: return 100_bi;
		case MoveName::Mirror_Coat: return 100_bi;
		case MoveName::Psych_Up: return none;
		case MoveName::Extreme_Speed: return 100_bi;
		case MoveName::Ancient_Power: return 100_bi;
		case MoveName::Shadow_Ball: return 100_bi;
		case MoveName::Future_Sight: return BOUNDED_CONDITIONAL(generation <= Generation::four, 90_bi, 100_bi);
		case MoveName::Rock_Smash: return 100_bi;
		case MoveName::Whirlpool: return BOUNDED_CONDITIONAL(generation <= Generation::four, 70_bi, 85_bi);
		case MoveName::Beat_Up: return 100_bi;
		case MoveName::Fake_Out: return 100_bi;
		case MoveName::Uproar: return 100_bi;
		case MoveName::Stockpile: return none;
		case MoveName::Spit_Up: return 100_bi;
		case MoveName::Swallow: return none;
		case MoveName::Heat_Wave: return 90_bi;
		case MoveName::Hail: return none;
		case MoveName::Torment: return 100_bi;
		case MoveName::Flatter: return 100_bi;
		case MoveName::Will_O_Wisp: return BOUNDED_CONDITIONAL(generation <= Generation::five, 75_bi, 85_bi);
		case MoveName::Memento: return generation <= Generation::three ? none : BaseAccuracy(100_bi);
		case MoveName::Facade: return 100_bi;
		case MoveName::Focus_Punch: return 100_bi;
		case MoveName::Smelling_Salts: return 100_bi;
		case MoveName::Follow_Me: return none;
		case MoveName::Nature_Power: return none;
		case MoveName::Charge: return none;
		case MoveName::Taunt: return 100_bi;
		case MoveName::Helping_Hand: return none;
		case MoveName::Trick: return 100_bi;
		case MoveName::Role_Play: return none;
		case MoveName::Wish: return none;
		case MoveName::Assist: return none;
		case MoveName::Ingrain: return none;
		case MoveName::Superpower: return 100_bi;
		case MoveName::Magic_Coat: return none;
		case MoveName::Recycle: return none;
		case MoveName::Revenge: return 100_bi;
		case MoveName::Brick_Break: return 100_bi;
		case MoveName::Yawn: return none;
		case MoveName::Knock_Off: return 100_bi;
		case MoveName::Endeavor: return 100_bi;
		case MoveName::Eruption: return 100_bi;
		case MoveName::Skill_Swap: return none;
		case MoveName::Imprison: return none;
		case MoveName::Refresh: return none;
		case MoveName::Grudge: return none;
		case MoveName::Snatch: return none;
		case MoveName::Secret_Power: return 100_bi;
		case MoveName::Dive: return 100_bi;
		case MoveName::Arm_Thrust: return 100_bi;
		case MoveName::Camouflage: return none;
		case MoveName::Tail_Glow: return none;
		case MoveName::Luster_Purge: return 100_bi;
		case MoveName::Mist_Ball: return 100_bi;
		case MoveName::Feather_Dance: return 100_bi;
		case MoveName::Teeter_Dance: return 100_bi;
		case MoveName::Blaze_Kick: return 90_bi;
		case MoveName::Mud_Sport: return none;
		case MoveName::Ice_Ball: return 90_bi;
		case MoveName::Needle_Arm: return 100_bi;
		case MoveName::Slack_Off: return none;
		case MoveName::Hyper_Voice: return 100_bi;
		case MoveName::Poison_Fang: return 100_bi;
		case MoveName::Crush_Claw: return 95_bi;
		case MoveName::Blast_Burn: return 90_bi;
		case MoveName::Hydro_Cannon: return 90_bi;
		case MoveName::Meteor_Mash: return BOUNDED_CONDITIONAL(generation <= Generation::five, 85_bi, 90_bi);
		case MoveName::Astonish: return 100_bi;
		case MoveName::Weather_Ball: return 100_bi;
		case MoveName::Aromatherapy: return none;
		case MoveName::Fake_Tears: return 100_bi;
		case MoveName::Air_Cutter: return 95_bi;
		case MoveName::Overheat: return 90_bi;
		case MoveName::Odor_Sleuth: return generation <= Generation::three ? BaseAccuracy(100_bi) : none;
		case MoveName::Rock_Tomb: return BOUNDED_CONDITIONAL(generation <= Generation::five, 80_bi, 95_bi);
		case MoveName::Silver_Wind: return 100_bi;
		case MoveName::Metal_Sound: return 85_bi;
		case MoveName::Grass_Whistle: return 55_bi;
		case MoveName::Tickle: return 100_bi;
		case MoveName::Cosmic_Power: return none;
		case MoveName::Water_Spout: return 100_bi;
		case MoveName::Signal_Beam: return 100_bi;
		case MoveName::Shadow_Punch: return none;
		case MoveName::Extrasensory: return 100_bi;
		case MoveName::Sky_Uppercut: return 90_bi;
		case MoveName::Sand_Tomb: return BOUNDED_CONDITIONAL(generation <= Generation::four, 70_bi, 85_bi);
		case MoveName::Sheer_Cold: return none;
		case MoveName::Muddy_Water: return 85_bi;
		case MoveName::Bullet_Seed: return 100_bi;
		case MoveName::Aerial_Ace: return none;
		case MoveName::Icicle_Spear: return 100_bi;
		case MoveName::Iron_Defense: return none;
		case MoveName::Block: return none;
		case MoveName::Howl: return none;
		case MoveName::Dragon_Claw: return 100_bi;
		case MoveName::Frenzy_Plant: return 90_bi;
		case MoveName::Bulk_Up: return none;
		case MoveName::Bounce: return 85_bi;
		case MoveName::Mud_Shot: return 95_bi;
		case MoveName::Poison_Tail: return 100_bi;
		case MoveName::Covet: return 100_bi;
		case MoveName::Volt_Tackle: return 100_bi;
		case MoveName::Magical_Leaf: return none;
		case MoveName::Water_Sport: return none;
		case MoveName::Calm_Mind: return none;
		case MoveName::Leaf_Blade: return 100_bi;
		case MoveName::Dragon_Dance: return none;
		case MoveName::Rock_Blast: return BOUNDED_CONDITIONAL(generation <= Generation::four, 80_bi, 90_bi);
		case MoveName::Shock_Wave: return none;
		case MoveName::Water_Pulse: return 100_bi;
		case MoveName::Doom_Desire: return BOUNDED_CONDITIONAL(generation <= Generation::four, 85_bi, 100_bi);
		case MoveName::Psycho_Boost: return 90_bi;
		case MoveName::Roost: return none;
		case MoveName::Gravity: return none;
		case MoveName::Miracle_Eye: return none;
		case MoveName::Wake_Up_Slap: return 100_bi;
		case MoveName::Hammer_Arm: return 90_bi;
		case MoveName::Gyro_Ball: return 100_bi;
		case MoveName::Healing_Wish: return none;
		case MoveName::Brine: return 100_bi;
		case MoveName::Natural_Gift: return 100_bi;
		case MoveName::Feint: return 100_bi;
		case MoveName::Pluck: return 100_bi;
		case MoveName::Tailwind: return none;
		case MoveName::Acupressure: return none;
		case MoveName::Metal_Burst: return 100_bi;
		case MoveName::U_turn: return 100_bi;
		case MoveName::Close_Combat: return 100_bi;
		case MoveName::Payback: return 100_bi;
		case MoveName::Assurance: return 100_bi;
		case MoveName::Embargo: return 100_bi;
		case MoveName::Fling: return 100_bi;
		case MoveName::Psycho_Shift: return BOUNDED_CONDITIONAL(generation <= Generation::five, 90_bi, 100_bi);
		case MoveName::Trump_Card: return none;
		case MoveName::Heal_Block: return 100_bi;
		case MoveName::Wring_Out: return 100_bi;
		case MoveName::Power_Trick: return none;
		case MoveName::Gastro_Acid: return 100_bi;
		case MoveName::Lucky_Chant: return none;
		case MoveName::Me_First: return none;
		case MoveName::Copycat: return none;
		case MoveName::Power_Swap: return none;
		case MoveName::Guard_Swap: return none;
		case MoveName::Punishment: return 100_bi;
		case MoveName::Last_Resort: return 100_bi;
		case MoveName::Worry_Seed: return 100_bi;
		case MoveName::Sucker_Punch: return 100_bi;
		case MoveName::Toxic_Spikes: return none;
		case MoveName::Heart_Swap: return none;
		case MoveName::Aqua_Ring: return none;
		case MoveName::Magnet_Rise: return none;
		case MoveName::Flare_Blitz: return 100_bi;
		case MoveName::Force_Palm: return 100_bi;
		case MoveName::Aura_Sphere: return none;
		case MoveName::Rock_Polish: return none;
		case MoveName::Poison_Jab: return 100_bi;
		case MoveName::Dark_Pulse: return 100_bi;
		case MoveName::Night_Slash: return 100_bi;
		case MoveName::Aqua_Tail: return 90_bi;
		case MoveName::Seed_Bomb: return 100_bi;
		case MoveName::Air_Slash: return 95_bi;
		case MoveName::X_Scissor: return 100_bi;
		case MoveName::Bug_Buzz: return 100_bi;
		case MoveName::Dragon_Pulse: return 100_bi;
		case MoveName::Dragon_Rush: return 75_bi;
		case MoveName::Power_Gem: return 100_bi;
		case MoveName::Drain_Punch: return 100_bi;
		case MoveName::Vacuum_Wave: return 100_bi;
		case MoveName::Focus_Blast: return 70_bi;
		case MoveName::Energy_Ball: return 100_bi;
		case MoveName::Brave_Bird: return 100_bi;
		case MoveName::Earth_Power: return 100_bi;
		case MoveName::Switcheroo: return 100_bi;
		case MoveName::Giga_Impact: return 90_bi;
		case MoveName::Nasty_Plot: return none;
		case MoveName::Bullet_Punch: return 100_bi;
		case MoveName::Avalanche: return 100_bi;
		case MoveName::Ice_Shard: return 100_bi;
		case MoveName::Shadow_Claw: return 100_bi;
		case MoveName::Thunder_Fang: return 95_bi;
		case MoveName::Ice_Fang: return 95_bi;
		case MoveName::Fire_Fang: return 95_bi;
		case MoveName::Shadow_Sneak: return 100_bi;
		case MoveName::Mud_Bomb: return 85_bi;
		case MoveName::Psycho_Cut: return 100_bi;
		case MoveName::Zen_Headbutt: return 90_bi;
		case MoveName::Mirror_Shot: return 85_bi;
		case MoveName::Flash_Cannon: return 100_bi;
		case MoveName::Rock_Climb: return 85_bi;
		case MoveName::Defog: return none;
		case MoveName::Trick_Room: return none;
		case MoveName::Draco_Meteor: return 90_bi;
		case MoveName::Discharge: return 100_bi;
		case MoveName::Lava_Plume: return 100_bi;
		case MoveName::Leaf_Storm: return 90_bi;
		case MoveName::Power_Whip: return 85_bi;
		case MoveName::Rock_Wrecker: return 90_bi;
		case MoveName::Cross_Poison: return 100_bi;
		case MoveName::Gunk_Shot: return BOUNDED_CONDITIONAL(generation <= Generation::five, 70_bi, 80_bi);
		case MoveName::Iron_Head: return 100_bi;
		case MoveName::Magnet_Bomb: return none;
		case MoveName::Stone_Edge: return 80_bi;
		case MoveName::Captivate: return 100_bi;
		case MoveName::Stealth_Rock: return none;
		case MoveName::Grass_Knot: return 100_bi;
		case MoveName::Chatter: return 100_bi;
		case MoveName::Judgment: return 100_bi;
		case MoveName::Bug_Bite: return 100_bi;
		case MoveName::Charge_Beam: return 90_bi;
		case MoveName::Wood_Hammer: return 100_bi;
		case MoveName::Aqua_Jet: return 100_bi;
		case MoveName::Attack_Order: return 100_bi;
		case MoveName::Defend_Order: return none;
		case MoveName::Heal_Order: return none;
		case MoveName::Head_Smash: return 80_bi;
		case MoveName::Double_Hit: return 90_bi;
		case MoveName::Roar_of_Time: return 90_bi;
		case MoveName::Spacial_Rend: return 95_bi;
		case MoveName::Lunar_Dance: return none;
		case MoveName::Crush_Grip: return 100_bi;
		case MoveName::Magma_Storm: return BOUNDED_CONDITIONAL(generation <= Generation::four, 70_bi, 75_bi);
		case MoveName::Dark_Void: return BOUNDED_CONDITIONAL(generation <= Generation::six, 80_bi, 50_bi);
		case MoveName::Seed_Flare: return 85_bi;
		case MoveName::Ominous_Wind: return 100_bi;
		case MoveName::Shadow_Force: return 100_bi;
		case MoveName::Hone_Claws: return none;
		case MoveName::Wide_Guard: return none;
		case MoveName::Guard_Split: return none;
		case MoveName::Power_Split: return none;
		case MoveName::Wonder_Room: return none;
		case MoveName::Psyshock: return 100_bi;
		case MoveName::Venoshock: return 100_bi;
		case MoveName::Autotomize: return none;
		case MoveName::Rage_Powder: return none;
		case MoveName::Telekinesis: return none;
		case MoveName::Magic_Room: return none;
		case MoveName::Smack_Down: return 100_bi;
		case MoveName::Storm_Throw: return 100_bi;
		case MoveName::Flame_Burst: return 100_bi;
		case MoveName::Sludge_Wave: return 100_bi;
		case MoveName::Quiver_Dance: return none;
		case MoveName::Heavy_Slam: return 100_bi;
		case MoveName::Synchronoise: return 100_bi;
		case MoveName::Electro_Ball: return 100_bi;
		case MoveName::Soak: return 100_bi;
		case MoveName::Flame_Charge: return 100_bi;
		case MoveName::Coil: return none;
		case MoveName::Low_Sweep: return 100_bi;
		case MoveName::Acid_Spray: return 100_bi;
		case MoveName::Foul_Play: return 100_bi;
		case MoveName::Simple_Beam: return 100_bi;
		case MoveName::Entrainment: return 100_bi;
		case MoveName::After_You: return none;
		case MoveName::Round: return 100_bi;
		case MoveName::Echoed_Voice: return 100_bi;
		case MoveName::Chip_Away: return 100_bi;
		case MoveName::Clear_Smog: return none;
		case MoveName::Stored_Power: return 100_bi;
		case MoveName::Quick_Guard: return none;
		case MoveName::Ally_Switch: return none;
		case MoveName::Scald: return 100_bi;
		case MoveName::Shell_Smash: return none;
		case MoveName::Heal_Pulse: return none;
		case MoveName::Hex: return 100_bi;
		case MoveName::Sky_Drop: return 100_bi;
		case MoveName::Shift_Gear: return none;
		case MoveName::Circle_Throw: return 90_bi;
		case MoveName::Incinerate: return 100_bi;
		case MoveName::Quash: return 100_bi;
		case MoveName::Acrobatics: return 100_bi;
		case MoveName::Reflect_Type: return none;
		case MoveName::Retaliate: return 100_bi;
		case MoveName::Final_Gambit: return 100_bi;
		case MoveName::Bestow: return none;
		case MoveName::Inferno: return 50_bi;
		case MoveName::Water_Pledge: return 100_bi;
		case MoveName::Fire_Pledge: return 100_bi;
		case MoveName::Grass_Pledge: return 100_bi;
		case MoveName::Volt_Switch: return 100_bi;
		case MoveName::Struggle_Bug: return 100_bi;
		case MoveName::Bulldoze: return 100_bi;
		case MoveName::Frost_Breath: return 90_bi;
		case MoveName::Dragon_Tail: return 90_bi;
		case MoveName::Work_Up: return none;
		case MoveName::Electroweb: return 95_bi;
		case MoveName::Wild_Charge: return 100_bi;
		case MoveName::Drill_Run: return 95_bi;
		case MoveName::Dual_Chop: return 90_bi;
		case MoveName::Heart_Stamp: return 100_bi;
		case MoveName::Horn_Leech: return 100_bi;
		case MoveName::Sacred_Sword: return 100_bi;
		case MoveName::Razor_Shell: return 95_bi;
		case MoveName::Heat_Crash: return 100_bi;
		case MoveName::Leaf_Tornado: return 90_bi;
		case MoveName::Steamroller: return 100_bi;
		case MoveName::Cotton_Guard: return none;
		case MoveName::Night_Daze: return 95_bi;
		case MoveName::Psystrike: return 100_bi;
		case MoveName::Tail_Slap: return 85_bi;
		case MoveName::Hurricane: return 70_bi;
		case MoveName::Head_Charge: return 100_bi;
		case MoveName::Gear_Grind: return 85_bi;
		case MoveName::Searing_Shot: return 100_bi;
		case MoveName::Techno_Blast: return 100_bi;
		case MoveName::Relic_Song: return 100_bi;
		case MoveName::Secret_Sword: return 100_bi;
		case MoveName::Glaciate: return 95_bi;
		case MoveName::Bolt_Strike: return 85_bi;
		case MoveName::Blue_Flare: return 85_bi;
		case MoveName::Fiery_Dance: return 100_bi;
		case MoveName::Freeze_Shock: return 90_bi;
		case MoveName::Ice_Burn: return 90_bi;
		case MoveName::Snarl: return 95_bi;
		case MoveName::Icicle_Crash: return 90_bi;
		case MoveName::V_create: return 95_bi;
		case MoveName::Fusion_Flare: return 100_bi;
		case MoveName::Fusion_Bolt: return 100_bi;
		case MoveName::Flying_Press: return 95_bi;
		case MoveName::Mat_Block: return none;
		case MoveName::Belch: return 90_bi;
		case MoveName::Rototiller: return none;
		case MoveName::Sticky_Web: return none;
		case MoveName::Fell_Stinger: return 100_bi;
		case MoveName::Phantom_Force: return 100_bi;
		case MoveName::Trick_or_Treat: return 100_bi;
		case MoveName::Noble_Roar: return 100_bi;
		case MoveName::Ion_Deluge: return none;
		case MoveName::Parabolic_Charge: return 100_bi;
		case MoveName::Forests_Curse: return 100_bi;
		case MoveName::Petal_Blizzard: return 100_bi;
		case MoveName::Freeze_Dry: return 100_bi;
		case MoveName::Disarming_Voice: return none;
		case MoveName::Parting_Shot: return 100_bi;
		case MoveName::Topsy_Turvy: return generation <= Generation::six ? BaseAccuracy(100_bi) : none;
		case MoveName::Draining_Kiss: return 100_bi;
		case MoveName::Crafty_Shield: return none;
		case MoveName::Flower_Shield: return none;
		case MoveName::Grassy_Terrain: return none;
		case MoveName::Misty_Terrain: return none;
		case MoveName::Electrify: return none;
		case MoveName::Play_Rough: return 90_bi;
		case MoveName::Fairy_Wind: return 100_bi;
		case MoveName::Moonblast: return 100_bi;
		case MoveName::Boomburst: return 100_bi;
		case MoveName::Fairy_Lock: return none;
		case MoveName::Kings_Shield: return none;
		case MoveName::Play_Nice: return none;
		case MoveName::Confide: return none;
		case MoveName::Diamond_Storm: return 95_bi;
		case MoveName::Steam_Eruption: return 95_bi;
		case MoveName::Hyperspace_Hole: return none;
		case MoveName::Water_Shuriken: return 100_bi;
		case MoveName::Mystical_Fire: return 100_bi;
		case MoveName::Spiky_Shield: return none;
		case MoveName::Aromatic_Mist: return none;
		case MoveName::Eerie_Impulse: return 100_bi;
		case MoveName::Venom_Drench: return 100_bi;
		case MoveName::Powder: return 100_bi;
		case MoveName::Geomancy: return none;
		case MoveName::Magnetic_Flux: return none;
		case MoveName::Happy_Hour: return none;
		case MoveName::Electric_Terrain: return none;
		case MoveName::Dazzling_Gleam: return 100_bi;
		case MoveName::Celebrate: return none;
		case MoveName::Hold_Hands: return none;
		case MoveName::Baby_Doll_Eyes: return 100_bi;
		case MoveName::Nuzzle: return 100_bi;
		case MoveName::Hold_Back: return 100_bi;
		case MoveName::Infestation: return 100_bi;
		case MoveName::Power_Up_Punch: return 100_bi;
		case MoveName::Oblivion_Wing: return 100_bi;
		case MoveName::Thousand_Arrows: return 100_bi;
		case MoveName::Thousand_Waves: return 100_bi;
		case MoveName::Lands_Wrath: return 100_bi;
		case MoveName::Light_of_Ruin: return 90_bi;
		case MoveName::Origin_Pulse: return 85_bi;
		case MoveName::Precipice_Blades: return 85_bi;
		case MoveName::Dragon_Ascent: return 100_bi;
		case MoveName::Hyperspace_Fury: return none;
		case MoveName::Breakneck_Blitz: return none;
		case MoveName::All_Out_Pummeling: return none;
		case MoveName::Supersonic_Skystrike: return none;
		case MoveName::Acid_Downpour: return none;
		case MoveName::Tectonic_Rage: return none;
		case MoveName::Continental_Crush: return none;
		case MoveName::Savage_Spin_Out: return none;
		case MoveName::Never_Ending_Nightmare: return none;
		case MoveName::Corkscrew_Crash: return none;
		case MoveName::Inferno_Overdrive: return none;
		case MoveName::Hydro_Vortex: return none;
		case MoveName::Bloom_Doom: return none;
		case MoveName::Gigavolt_Havoc: return none;
		case MoveName::Shattered_Psyche: return none;
		case MoveName::Subzero_Slammer: return none;
		case MoveName::Devastating_Drake: return none;
		case MoveName::Black_Hole_Eclipse: return none;
		case MoveName::Twinkle_Tackle: return none;
		case MoveName::Catastropika: return none;
		case MoveName::Shore_Up: return none;
		case MoveName::First_Impression: return 100_bi;
		case MoveName::Baneful_Bunker: return none;
		case MoveName::Spirit_Shackle: return 100_bi;
		case MoveName::Darkest_Lariat: return 100_bi;
		case MoveName::Sparkling_Aria: return 100_bi;
		case MoveName::Ice_Hammer: return 90_bi;
		case MoveName::Floral_Healing: return none;
		case MoveName::High_Horsepower: return 95_bi;
		case MoveName::Strength_Sap: return 100_bi;
		case MoveName::Solar_Blade: return 100_bi;
		case MoveName::Leafage: return 100_bi;
		case MoveName::Spotlight: return none;
		case MoveName::Toxic_Thread: return 100_bi;
		case MoveName::Laser_Focus: return none;
		case MoveName::Gear_Up: return none;
		case MoveName::Throat_Chop: return 100_bi;
		case MoveName::Pollen_Puff: return 100_bi;
		case MoveName::Anchor_Shot: return 100_bi;
		case MoveName::Psychic_Terrain: return none;
		case MoveName::Lunge: return 100_bi;
		case MoveName::Fire_Lash: return 100_bi;
		case MoveName::Power_Trip: return 100_bi;
		case MoveName::Burn_Up: return 100_bi;
		case MoveName::Speed_Swap: return none;
		case MoveName::Smart_Strike: return none;
		case MoveName::Purify: return none;
		case MoveName::Revelation_Dance: return 100_bi;
		case MoveName::Core_Enforcer: return 100_bi;
		case MoveName::Trop_Kick: return 100_bi;
		case MoveName::Instruct: return none;
		case MoveName::Beak_Blast: return 100_bi;
		case MoveName::Clanging_Scales: return 100_bi;
		case MoveName::Dragon_Hammer: return 100_bi;
		case MoveName::Brutal_Swing: return 100_bi;
		case MoveName::Aurora_Veil: return none;
		case MoveName::Sinister_Arrow_Raid: return none;
		case MoveName::Malicious_Moonsault: return none;
		case MoveName::Oceanic_Operetta: return none;
		case MoveName::Guardian_of_Alola: return none;
		case MoveName::Soul_Stealing_7_Star_Strike: return none;
		case MoveName::Stoked_Sparksurfer: return none;
		case MoveName::Pulverizing_Pancake: return none;
		case MoveName::Extreme_Evoboost: return none;
		case MoveName::Genesis_Supernova: return none;
		case MoveName::Shell_Trap: return 100_bi;
		case MoveName::Fleur_Cannon: return 90_bi;
		case MoveName::Psychic_Fangs: return 100_bi;
		case MoveName::Stomping_Tantrum: return 100_bi;
		case MoveName::Shadow_Bone: return 100_bi;
		case MoveName::Accelerock: return 100_bi;
		case MoveName::Liquidation: return 100_bi;
		case MoveName::Prismatic_Laser: return 100_bi;
		case MoveName::Spectral_Thief: return 100_bi;
		case MoveName::Sunsteel_Strike: return 100_bi;
		case MoveName::Moongeist_Beam: return 100_bi;
		case MoveName::Tearful_Look: return none;
		case MoveName::Zing_Zap: return 100_bi;
		case MoveName::Natures_Madness: return 90_bi;
		case MoveName::Multi_Attack: return 100_bi;
		case MoveName::m10000000_Volt_Thunderbolt: return none;
		case MoveName::Mind_Blown: return 100_bi;
		case MoveName::Plasma_Fists: return 100_bi;
		case MoveName::Photon_Geyser: return 100_bi;
		case MoveName::Light_That_Burns_the_Sky: return none;
		case MoveName::Searing_Sunraze_Smash: return none;
		case MoveName::Menacing_Moonraze_Maelstrom: return none;
		case MoveName::Lets_Snuggle_Forever: return none;
		case MoveName::Splintered_Stormshards: return none;
		case MoveName::Clangorous_Soulblaze: return none;
		case MoveName::Double_Iron_Bash: return 100_bi;

		// Generation 8
		case MoveName::Max_Guard: return none;
		case MoveName::Dynamax_Cannon: return 100_bi;
		case MoveName::Snipe_Shot: return 100_bi;
		case MoveName::Jaw_Lock: return 100_bi;
		case MoveName::Stuff_Cheeks: return none;
		case MoveName::No_Retreat: return none;
		case MoveName::Tar_Shot: return 100_bi;
		case MoveName::Magic_Powder: return 100_bi;
		case MoveName::Dragon_Darts: return 100_bi;
		case MoveName::Teatime: return none;
		case MoveName::Octolock: return 100_bi;
		case MoveName::Bolt_Beak: return 100_bi;
		case MoveName::Fishious_Rend: return 100_bi;
		case MoveName::Court_Change: return 100_bi;
		case MoveName::Max_Flare: return none;
		case MoveName::Max_Flutterby: return none;
		case MoveName::Max_Lightning: return none;
		case MoveName::Max_Strike: return none;
		case MoveName::Max_Knuckle: return none;
		case MoveName::Max_Phantasm: return none;
		case MoveName::Max_Hailstorm: return none;
		case MoveName::Max_Ooze: return none;
		case MoveName::Max_Geyser: return none;
		case MoveName::Max_Airstream: return none;
		case MoveName::Max_Starfall: return none;
		case MoveName::Max_Wyrmwind: return none;
		case MoveName::Max_Mindstorm: return none;
		case MoveName::Max_Rockfall: return none;
		case MoveName::Max_Quake: return none;
		case MoveName::Max_Darkness: return none;
		case MoveName::Max_Overgrowth: return none;
		case MoveName::Max_Steelspike: return none;
		case MoveName::Clangorous_Soul: return none;
		case MoveName::Body_Press: return 100_bi;
		case MoveName::Decorate: return none;
		case MoveName::Drum_Beating: return 100_bi;
		case MoveName::Snap_Trap: return 100_bi;
		case MoveName::Pyro_Ball: return 90_bi;
		case MoveName::Behemoth_Blade: return 100_bi;
		case MoveName::Behemoth_Bash: return 100_bi;
		case MoveName::Aura_Wheel: return 100_bi;
		case MoveName::Breaking_Swipe: return 100_bi;
		case MoveName::Branch_Poke: return 100_bi;
		case MoveName::Overdrive: return 100_bi;
		case MoveName::Apple_Acid: return 100_bi;
		case MoveName::Grav_Apple: return 100_bi;
		case MoveName::Spirit_Break: return 100_bi;
		case MoveName::Strange_Steam: return 95_bi;
		case MoveName::Life_Dew: return none;
		case MoveName::Obstruct: return 100_bi;
		case MoveName::False_Surrender: return none;
		case MoveName::Meteor_Assault: return 100_bi;
		case MoveName::Eternabeam: return 90_bi;
		case MoveName::Steel_Beam: return 95_bi;
		case MoveName::Expanding_Force: return 100_bi;
		case MoveName::Steel_Roller: return 100_bi;
		case MoveName::Scale_Shot: return 90_bi;
		case MoveName::Meteor_Beam: return 90_bi;
		case MoveName::Shell_Side_Arm: return 100_bi;
		case MoveName::Misty_Explosion: return 100_bi;
		case MoveName::Grassy_Glide: return 100_bi;
		case MoveName::Rising_Voltage: return 100_bi;
		case MoveName::Terrain_Pulse: return 100_bi;
		case MoveName::Skitter_Smack: return 90_bi;
		case MoveName::Burning_Jealousy: return 100_bi;
		case MoveName::Lash_Out: return 100_bi;
		case MoveName::Poltergeist: return 90_bi;
		case MoveName::Corrosive_Gas: return 100_bi;
		case MoveName::Coaching: return none;
		case MoveName::Flip_Turn: return 100_bi;
		case MoveName::Triple_Axel: return 90_bi;
		case MoveName::Dual_Wingbeat: return 90_bi;
		case MoveName::Scorching_Sands: return 100_bi;
		case MoveName::Jungle_Healing: return none;
		case MoveName::Wicked_Blow: return 100_bi;
		case MoveName::Surging_Strikes: return 100_bi;
		case MoveName::Thunder_Cage: return 90_bi;
		case MoveName::Dragon_Energy: return 100_bi;
		case MoveName::Freezing_Glare: return 100_bi;
		case MoveName::Fiery_Wrath: return 100_bi;
		case MoveName::Thunderous_Kick: return 100_bi;
		case MoveName::Glacial_Lance: return 100_bi;
		case MoveName::Astral_Barrage: return 100_bi;
		case MoveName::Eerie_Spell: return 100_bi;

		// Generation 9
		case MoveName::Tera_Blast: return 100_bi;
		case MoveName::Silk_Trap: return none;
		case MoveName::Axe_Kick: return 90_bi;
		case MoveName::Last_Respects: return 100_bi;
		case MoveName::Lumina_Crash: return 100_bi;
		case MoveName::Order_Up: return 100_bi;
		case MoveName::Jet_Punch: return 100_bi;
		case MoveName::Spicy_Extract: return none;
		case MoveName::Spin_Out: return 100_bi;
		case MoveName::Population_Bomb: return 90_bi;
		case MoveName::Ice_Spinner: return 100_bi;
		case MoveName::Glaive_Rush: return 100_bi;
		case MoveName::Revival_Blessing: return none;
		case MoveName::Salt_Cure: return 100_bi;
		case MoveName::Triple_Dive: return 95_bi;
		case MoveName::Mortal_Spin: return 100_bi;
		case MoveName::Doodle: return 100_bi;
		case MoveName::Fillet_Away: return none;
		case MoveName::Kowtow_Cleave: return none;
		case MoveName::Flower_Trick: return none;
		case MoveName::Torch_Song: return 100_bi;
		case MoveName::Aqua_Step: return 100_bi;
		case MoveName::Raging_Bull: return 100_bi;
		case MoveName::Make_It_Rain: return 100_bi;
		case MoveName::Psyblade: return 100_bi;
		case MoveName::Hydro_Steam: return 100_bi;
		case MoveName::Ruination: return 90_bi;
		case MoveName::Collision_Course: return 100_bi;
		case MoveName::Electro_Drift: return 100_bi;
		case MoveName::Shed_Tail: return none;
		case MoveName::Chilly_Reception: return none;
		case MoveName::Tidy_Up: return none;
		case MoveName::Snowscape: return none;
		case MoveName::Pounce: return 100_bi;
		case MoveName::Trailblaze: return 100_bi;
		case MoveName::Chilling_Water: return 100_bi;
		case MoveName::Hyper_Drill: return 100_bi;
		case MoveName::Twin_Beam: return 100_bi;
		case MoveName::Rage_Fist: return 100_bi;
		case MoveName::Armor_Cannon: return 100_bi;
		case MoveName::Bitter_Blade: return 100_bi;
		case MoveName::Double_Shock: return 100_bi;
		case MoveName::Gigaton_Hammer: return 100_bi;
		case MoveName::Comeuppance: return 100_bi;
		case MoveName::Aqua_Cutter: return 100_bi;
		case MoveName::Blazing_Torque: return 100_bi;
		case MoveName::Wicked_Torque: return 100_bi;
		case MoveName::Noxious_Torque: return 100_bi;
		case MoveName::Combat_Torque: return 100_bi;
		case MoveName::Magical_Torque: return 100_bi;
		case MoveName::Blood_Moon: return 100_bi;
		case MoveName::Matcha_Gotcha: return 90_bi;
		case MoveName::Syrup_Bomb: return 85_bi;
		case MoveName::Ivy_Cudgel: return 100_bi;
		case MoveName::Electro_Shot: return 100_bi;
		case MoveName::Thunderclap: return 100_bi;
		case MoveName::Tachyon_Cutter: return 100_bi;
		case MoveName::Upper_Hand: return 100_bi;
		case MoveName::Psychic_Noise: return 100_bi;
	}
}

} // namespace technicalmachine
