// Copyright David Stone 2020.
// Distributed under the Boost Software License, Version 1.0.
// (See accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt)

module;

#include <bounded/conditional.hpp>

export module tm.move.base_power;

import tm.move.executed_move;
import tm.move.move_name;

import tm.pokemon.happiness;
import tm.pokemon.hp_ratio;
import tm.pokemon.species;

import tm.stat.calculate;
import tm.stat.stage;

import tm.any_team;
import tm.environment;
import tm.generation;
import tm.held_item;
import tm.item;

import bounded;
import containers;
import std_module;

namespace technicalmachine {
using namespace bounded::literal;

constexpr auto power_of_mass_based_moves(Species const species) -> bounded::integer<20, 120> {
	switch (species) {
		// Generation 1
		case Species::Bulbasaur: return 20_bi;
		case Species::Ivysaur: return 40_bi;
		case Species::Venusaur: return 100_bi;
		case Species::Charmander: return 20_bi;
		case Species::Charmeleon: return 40_bi;
		case Species::Charizard: return 80_bi;
		case Species::Squirtle: return 20_bi;
		case Species::Wartortle: return 40_bi;
		case Species::Blastoise: return 80_bi;
		case Species::Caterpie: return 20_bi;
		case Species::Metapod: return 20_bi;
		case Species::Butterfree: return 60_bi;
		case Species::Weedle: return 20_bi;
		case Species::Kakuna: return 40_bi;
		case Species::Beedrill: return 60_bi;
		case Species::Pidgey: return 20_bi;
		case Species::Pidgeotto: return 60_bi;
		case Species::Pidgeot: return 60_bi;
		case Species::Rattata: return 20_bi;
		case Species::Raticate: return 40_bi;
		case Species::Spearow: return 20_bi;
		case Species::Fearow: return 60_bi;
		case Species::Ekans: return 20_bi;
		case Species::Arbok: return 80_bi;
		case Species::Pikachu: return 20_bi;
		case Species::Raichu: return 60_bi;
		case Species::Sandshrew: return 40_bi;
		case Species::Sandslash: return 60_bi;
		case Species::Nidoran_F: return 20_bi;
		case Species::Nidorina: return 40_bi;
		case Species::Nidoqueen: return 80_bi;
		case Species::Nidoran_M: return 20_bi;
		case Species::Nidorino: return 40_bi;
		case Species::Nidoking: return 80_bi;
		case Species::Clefairy: return 20_bi;
		case Species::Clefable: return 60_bi;
		case Species::Vulpix: return 20_bi;
		case Species::Ninetales: return 40_bi;
		case Species::Jigglypuff: return 20_bi;
		case Species::Wigglytuff: return 40_bi;
		case Species::Zubat: return 20_bi;
		case Species::Golbat: return 80_bi;
		case Species::Oddish: return 20_bi;
		case Species::Gloom: return 20_bi;
		case Species::Vileplume: return 40_bi;
		case Species::Paras: return 20_bi;
		case Species::Parasect: return 60_bi;
		case Species::Venonat: return 60_bi;
		case Species::Venomoth: return 40_bi;
		case Species::Diglett: return 20_bi;
		case Species::Dugtrio: return 60_bi;
		case Species::Meowth: return 20_bi;
		case Species::Persian: return 60_bi;
		case Species::Psyduck: return 40_bi;
		case Species::Golduck: return 80_bi;
		case Species::Mankey: return 60_bi;
		case Species::Primeape: return 60_bi;
		case Species::Growlithe: return 40_bi;
		case Species::Arcanine: return 100_bi;
		case Species::Poliwag: return 40_bi;
		case Species::Poliwhirl: return 40_bi;
		case Species::Poliwrath: return 80_bi;
		case Species::Abra: return 40_bi;
		case Species::Kadabra: return 80_bi;
		case Species::Alakazam: return 60_bi;
		case Species::Machop: return 40_bi;
		case Species::Machoke: return 80_bi;
		case Species::Machamp: return 100_bi;
		case Species::Bellsprout: return 20_bi;
		case Species::Weepinbell: return 20_bi;
		case Species::Victreebel: return 40_bi;
		case Species::Tentacool: return 60_bi;
		case Species::Tentacruel: return 80_bi;
		case Species::Geodude: return 40_bi;
		case Species::Graveler: return 100_bi;
		case Species::Golem: return 120_bi;
		case Species::Ponyta: return 60_bi;
		case Species::Rapidash: return 80_bi;
		case Species::Slowpoke: return 60_bi;
		case Species::Slowbro: return 80_bi;
		case Species::Magnemite: return 20_bi;
		case Species::Magneton: return 80_bi;
		case Species::Farfetchd: return 40_bi;
		case Species::Doduo: return 60_bi;
		case Species::Dodrio: return 80_bi;
		case Species::Seel: return 80_bi;
		case Species::Dewgong: return 100_bi;
		case Species::Grimer: return 60_bi;
		case Species::Muk: return 60_bi;
		case Species::Shellder: return 20_bi;
		case Species::Cloyster: return 100_bi;
		case Species::Gastly: return 20_bi;
		case Species::Haunter: return 20_bi;
		case Species::Gengar: return 60_bi;
		case Species::Onix: return 120_bi;
		case Species::Drowzee: return 60_bi;
		case Species::Hypno: return 80_bi;
		case Species::Krabby: return 20_bi;
		case Species::Kingler: return 80_bi;
		case Species::Voltorb: return 40_bi;
		case Species::Electrode: return 80_bi;
		case Species::Exeggcute: return 20_bi;
		case Species::Exeggutor: return 100_bi;
		case Species::Cubone: return 20_bi;
		case Species::Marowak: return 60_bi;
		case Species::Hitmonlee: return 60_bi;
		case Species::Hitmonchan: return 80_bi;
		case Species::Lickitung: return 80_bi;
		case Species::Koffing: return 20_bi;
		case Species::Weezing: return 20_bi;
		case Species::Rhyhorn: return 100_bi;
		case Species::Rhydon: return 100_bi;
		case Species::Chansey: return 60_bi;
		case Species::Tangela: return 60_bi;
		case Species::Kangaskhan: return 80_bi;
		case Species::Horsea: return 20_bi;
		case Species::Seadra: return 60_bi;
		case Species::Goldeen: return 40_bi;
		case Species::Seaking: return 60_bi;
		case Species::Staryu: return 60_bi;
		case Species::Starmie: return 80_bi;
		case Species::Mr_Mime: return 80_bi;
		case Species::Scyther: return 80_bi;
		case Species::Jynx: return 60_bi;
		case Species::Electabuzz: return 60_bi;
		case Species::Magmar: return 60_bi;
		case Species::Pinsir: return 80_bi;
		case Species::Tauros: return 80_bi;
		case Species::Magikarp: return 40_bi;
		case Species::Gyarados: return 120_bi;
		case Species::Lapras: return 120_bi;
		case Species::Ditto: return 20_bi;
		case Species::Eevee: return 20_bi;
		case Species::Vaporeon: return 60_bi;
		case Species::Jolteon: return 40_bi;
		case Species::Flareon: return 60_bi;
		case Species::Porygon: return 60_bi;
		case Species::Omanyte: return 20_bi;
		case Species::Omastar: return 60_bi;
		case Species::Kabuto: return 40_bi;
		case Species::Kabutops: return 60_bi;
		case Species::Aerodactyl: return 80_bi;
		case Species::Snorlax: return 120_bi;
		case Species::Articuno: return 80_bi;
		case Species::Zapdos: return 80_bi;
		case Species::Moltres: return 80_bi;
		case Species::Dratini: return 20_bi;
		case Species::Dragonair: return 40_bi;
		case Species::Dragonite: return 120_bi;
		case Species::Mewtwo: return 100_bi;
		case Species::Mew: return 20_bi;

		// Generation 2
		case Species::Chikorita: return 20_bi;
		case Species::Bayleef: return 40_bi;
		case Species::Meganium: return 100_bi;
		case Species::Cyndaquil: return 20_bi;
		case Species::Quilava: return 40_bi;
		case Species::Typhlosion: return 80_bi;
		case Species::Totodile: return 20_bi;
		case Species::Croconaw: return 60_bi;
		case Species::Feraligatr: return 80_bi;
		case Species::Sentret: return 20_bi;
		case Species::Furret: return 60_bi;
		case Species::Hoothoot: return 40_bi;
		case Species::Noctowl: return 60_bi;
		case Species::Ledyba: return 40_bi;
		case Species::Ledian: return 60_bi;
		case Species::Spinarak: return 20_bi;
		case Species::Ariados: return 60_bi;
		case Species::Crobat: return 80_bi;
		case Species::Chinchou: return 40_bi;
		case Species::Lanturn: return 40_bi;
		case Species::Pichu: return 20_bi;
		case Species::Cleffa: return 20_bi;
		case Species::Igglybuff: return 20_bi;
		case Species::Togepi: return 20_bi;
		case Species::Togetic: return 20_bi;
		case Species::Natu: return 20_bi;
		case Species::Xatu: return 40_bi;
		case Species::Mareep: return 20_bi;
		case Species::Flaaffy: return 40_bi;
		case Species::Ampharos: return 80_bi;
		case Species::Bellossom: return 20_bi;
		case Species::Marill: return 20_bi;
		case Species::Azumarill: return 60_bi;
		case Species::Sudowoodo: return 60_bi;
		case Species::Politoed: return 60_bi;
		case Species::Hoppip: return 20_bi;
		case Species::Skiploom: return 20_bi;
		case Species::Jumpluff: return 20_bi;
		case Species::Aipom: return 40_bi;
		case Species::Sunkern: return 20_bi;
		case Species::Sunflora: return 20_bi;
		case Species::Yanma: return 60_bi;
		case Species::Wooper: return 20_bi;
		case Species::Quagsire: return 80_bi;
		case Species::Espeon: return 60_bi;
		case Species::Umbreon: return 60_bi;
		case Species::Murkrow: return 20_bi;
		case Species::Slowking: return 80_bi;
		case Species::Misdreavus: return 20_bi;
		case Species::Unown: return 20_bi;
		case Species::Wobbuffet: return 60_bi;
		case Species::Girafarig: return 60_bi;
		case Species::Pineco: return 20_bi;
		case Species::Forretress: return 100_bi;
		case Species::Dunsparce: return 40_bi;
		case Species::Gligar: return 80_bi;
		case Species::Steelix: return 120_bi;
		case Species::Snubbull: return 20_bi;
		case Species::Granbull: return 60_bi;
		case Species::Qwilfish: return 20_bi;
		case Species::Scizor: return 100_bi;
		case Species::Shuckle: return 40_bi;
		case Species::Heracross: return 80_bi;
		case Species::Sneasel: return 60_bi;
		case Species::Teddiursa: return 20_bi;
		case Species::Ursaring: return 100_bi;
		case Species::Slugma: return 60_bi;
		case Species::Magcargo: return 80_bi;
		case Species::Swinub: return 20_bi;
		case Species::Piloswine: return 80_bi;
		case Species::Corsola: return 20_bi;
		case Species::Remoraid: return 40_bi;
		case Species::Octillery: return 60_bi;
		case Species::Delibird: return 40_bi;
		case Species::Mantine: return 120_bi;
		case Species::Skarmory: return 80_bi;
		case Species::Houndour: return 40_bi;
		case Species::Houndoom: return 60_bi;
		case Species::Kingdra: return 100_bi;
		case Species::Phanpy: return 60_bi;
		case Species::Donphan: return 100_bi;
		case Species::Porygon2: return 60_bi;
		case Species::Stantler: return 80_bi;
		case Species::Smeargle: return 80_bi;
		case Species::Tyrogue: return 40_bi;
		case Species::Hitmontop: return 60_bi;
		case Species::Smoochum: return 20_bi;
		case Species::Elekid: return 40_bi;
		case Species::Magby: return 40_bi;
		case Species::Miltank: return 80_bi;
		case Species::Blissey: return 60_bi;
		case Species::Raikou: return 100_bi;
		case Species::Entei: return 100_bi;
		case Species::Suicune: return 100_bi;
		case Species::Larvitar: return 80_bi;
		case Species::Pupitar: return 100_bi;
		case Species::Tyranitar: return 120_bi;
		case Species::Lugia: return 120_bi;
		case Species::Ho_Oh: return 100_bi;
		case Species::Celebi: return 20_bi;

		// Generation 3
		case Species::Treecko: return 20_bi;
		case Species::Grovyle: return 40_bi;
		case Species::Sceptile: return 80_bi;
		case Species::Torchic: return 20_bi;
		case Species::Combusken: return 40_bi;
		case Species::Blaziken: return 80_bi;
		case Species::Mudkip: return 20_bi;
		case Species::Marshtomp: return 60_bi;
		case Species::Swampert: return 80_bi;
		case Species::Poochyena: return 40_bi;
		case Species::Mightyena: return 60_bi;
		case Species::Zigzagoon: return 40_bi;
		case Species::Linoone: return 60_bi;
		case Species::Wurmple: return 20_bi;
		case Species::Silcoon: return 40_bi;
		case Species::Beautifly: return 60_bi;
		case Species::Cascoon: return 40_bi;
		case Species::Dustox: return 60_bi;
		case Species::Lotad: return 20_bi;
		case Species::Lombre: return 60_bi;
		case Species::Ludicolo: return 80_bi;
		case Species::Seedot: return 20_bi;
		case Species::Nuzleaf: return 60_bi;
		case Species::Shiftry: return 80_bi;
		case Species::Taillow: return 20_bi;
		case Species::Swellow: return 40_bi;
		case Species::Wingull: return 20_bi;
		case Species::Pelipper: return 60_bi;
		case Species::Ralts: return 20_bi;
		case Species::Kirlia: return 40_bi;
		case Species::Gardevoir: return 60_bi;
		case Species::Surskit: return 20_bi;
		case Species::Masquerain: return 20_bi;
		case Species::Shroomish: return 20_bi;
		case Species::Breloom: return 60_bi;
		case Species::Slakoth: return 40_bi;
		case Species::Vigoroth: return 60_bi;
		case Species::Slaking: return 100_bi;
		case Species::Nincada: return 20_bi;
		case Species::Ninjask: return 40_bi;
		case Species::Shedinja: return 20_bi;
		case Species::Whismur: return 40_bi;
		case Species::Loudred: return 60_bi;
		case Species::Exploud: return 80_bi;
		case Species::Makuhita: return 80_bi;
		case Species::Hariyama: return 120_bi;
		case Species::Azurill: return 20_bi;
		case Species::Nosepass: return 80_bi;
		case Species::Skitty: return 40_bi;
		case Species::Delcatty: return 60_bi;
		case Species::Sableye: return 40_bi;
		case Species::Mawile: return 40_bi;
		case Species::Aron: return 80_bi;
		case Species::Lairon: return 100_bi;
		case Species::Aggron: return 120_bi;
		case Species::Meditite: return 40_bi;
		case Species::Medicham: return 60_bi;
		case Species::Electrike: return 40_bi;
		case Species::Manectric: return 60_bi;
		case Species::Plusle: return 20_bi;
		case Species::Minun: return 20_bi;
		case Species::Volbeat: return 40_bi;
		case Species::Illumise: return 40_bi;
		case Species::Roselia: return 20_bi;
		case Species::Gulpin: return 40_bi;
		case Species::Swalot: return 80_bi;
		case Species::Carvanha: return 40_bi;
		case Species::Sharpedo: return 80_bi;
		case Species::Wailmer: return 100_bi;
		case Species::Wailord: return 120_bi;
		case Species::Numel: return 40_bi;
		case Species::Camerupt: return 120_bi;
		case Species::Torkoal: return 80_bi;
		case Species::Spoink: return 60_bi;
		case Species::Grumpig: return 80_bi;
		case Species::Spinda: return 20_bi;
		case Species::Trapinch: return 40_bi;
		case Species::Vibrava: return 40_bi;
		case Species::Flygon: return 80_bi;
		case Species::Cacnea: return 80_bi;
		case Species::Cacturne: return 80_bi;
		case Species::Swablu: return 20_bi;
		case Species::Altaria: return 40_bi;
		case Species::Zangoose: return 60_bi;
		case Species::Seviper: return 80_bi;
		case Species::Lunatone: return 100_bi;
		case Species::Solrock: return 100_bi;
		case Species::Barboach: return 20_bi;
		case Species::Whiscash: return 40_bi;
		case Species::Corphish: return 40_bi;
		case Species::Crawdaunt: return 60_bi;
		case Species::Baltoy: return 40_bi;
		case Species::Claydol: return 100_bi;
		case Species::Lileep: return 40_bi;
		case Species::Cradily: return 80_bi;
		case Species::Anorith: return 40_bi;
		case Species::Armaldo: return 80_bi;
		case Species::Feebas: return 20_bi;
		case Species::Milotic: return 100_bi;
		case Species::Castform: return 20_bi;
		case Species::Kecleon: return 40_bi;
		case Species::Shuppet: return 20_bi;
		case Species::Banette: return 40_bi;
		case Species::Duskull: return 40_bi;
		case Species::Dusclops: return 60_bi;
		case Species::Tropius: return 100_bi;
		case Species::Chimecho: return 20_bi;
		case Species::Absol: return 60_bi;
		case Species::Wynaut: return 40_bi;
		case Species::Snorunt: return 40_bi;
		case Species::Glalie: return 120_bi;
		case Species::Spheal: return 60_bi;
		case Species::Sealeo: return 80_bi;
		case Species::Walrein: return 100_bi;
		case Species::Clamperl: return 80_bi;
		case Species::Huntail: return 60_bi;
		case Species::Gorebyss: return 40_bi;
		case Species::Relicanth: return 40_bi;
		case Species::Luvdisc: return 20_bi;
		case Species::Bagon: return 60_bi;
		case Species::Shelgon: return 100_bi;
		case Species::Salamence: return 100_bi;
		case Species::Beldum: return 80_bi;
		case Species::Metang: return 120_bi;
		case Species::Metagross: return 120_bi;
		case Species::Regirock: return 120_bi;
		case Species::Regice: return 100_bi;
		case Species::Registeel: return 120_bi;
		case Species::Latias: return 60_bi;
		case Species::Latios: return 80_bi;
		case Species::Kyogre: return 120_bi;
		case Species::Groudon: return 120_bi;
		case Species::Rayquaza: return 120_bi;
		case Species::Jirachi: return 20_bi;
		case Species::Deoxys_Normal: return 80_bi;
		case Species::Deoxys_Attack: return 80_bi;
		case Species::Deoxys_Defense: return 80_bi;
		case Species::Deoxys_Speed: return 80_bi;

		// Generation 4
		case Species::Turtwig: return 40_bi;
		case Species::Grotle: return 80_bi;
		case Species::Torterra: return 120_bi;
		case Species::Chimchar: return 20_bi;
		case Species::Monferno: return 40_bi;
		case Species::Infernape: return 80_bi;
		case Species::Piplup: return 20_bi;
		case Species::Prinplup: return 40_bi;
		case Species::Empoleon: return 80_bi;
		case Species::Starly: return 20_bi;
		case Species::Staravia: return 40_bi;
		case Species::Staraptor: return 40_bi;
		case Species::Bidoof: return 40_bi;
		case Species::Bibarel: return 60_bi;
		case Species::Kricketot: return 20_bi;
		case Species::Kricketune: return 60_bi;
		case Species::Shinx: return 20_bi;
		case Species::Luxio: return 60_bi;
		case Species::Luxray: return 60_bi;
		case Species::Budew: return 20_bi;
		case Species::Roserade: return 40_bi;
		case Species::Cranidos: return 60_bi;
		case Species::Rampardos: return 100_bi;
		case Species::Shieldon: return 80_bi;
		case Species::Bastiodon: return 100_bi;
		case Species::Burmy: return 20_bi;
		case Species::Wormadam_Plant: return 20_bi;
		case Species::Wormadam_Sandy: return 20_bi;
		case Species::Wormadam_Trash: return 20_bi;
		case Species::Mothim: return 40_bi;
		case Species::Combee: return 20_bi;
		case Species::Vespiquen: return 60_bi;
		case Species::Pachirisu: return 20_bi;
		case Species::Buizel: return 60_bi;
		case Species::Floatzel: return 60_bi;
		case Species::Cherubi: return 20_bi;
		case Species::Cherrim: return 20_bi;
		case Species::Shellos: return 20_bi;
		case Species::Gastrodon: return 60_bi;
		case Species::Ambipom: return 40_bi;
		case Species::Drifloon: return 20_bi;
		case Species::Drifblim: return 40_bi;
		case Species::Buneary: return 20_bi;
		case Species::Lopunny: return 60_bi;
		case Species::Mismagius: return 20_bi;
		case Species::Honchkrow: return 60_bi;
		case Species::Glameow: return 20_bi;
		case Species::Purugly: return 60_bi;
		case Species::Chingling: return 20_bi;
		case Species::Stunky: return 40_bi;
		case Species::Skuntank: return 60_bi;
		case Species::Bronzor: return 80_bi;
		case Species::Bronzong: return 100_bi;
		case Species::Bonsly: return 40_bi;
		case Species::Mime_Jr: return 40_bi;
		case Species::Happiny: return 40_bi;
		case Species::Chatot: return 20_bi;
		case Species::Spiritomb: return 100_bi;
		case Species::Gible: return 40_bi;
		case Species::Gabite: return 80_bi;
		case Species::Garchomp: return 80_bi;
		case Species::Munchlax: return 100_bi;
		case Species::Riolu: return 40_bi;
		case Species::Lucario: return 80_bi;
		case Species::Hippopotas: return 60_bi;
		case Species::Hippowdon: return 120_bi;
		case Species::Skorupi: return 40_bi;
		case Species::Drapion: return 80_bi;
		case Species::Croagunk: return 40_bi;
		case Species::Toxicroak: return 60_bi;
		case Species::Carnivine: return 60_bi;
		case Species::Finneon: return 20_bi;
		case Species::Lumineon: return 40_bi;
		case Species::Mantyke: return 80_bi;
		case Species::Snover: return 80_bi;
		case Species::Abomasnow: return 100_bi;
		case Species::Weavile: return 60_bi;
		case Species::Magnezone: return 100_bi;
		case Species::Lickilicky: return 100_bi;
		case Species::Rhyperior: return 120_bi;
		case Species::Tangrowth: return 100_bi;
		case Species::Electivire: return 100_bi;
		case Species::Magmortar: return 80_bi;
		case Species::Togekiss: return 60_bi;
		case Species::Yanmega: return 80_bi;
		case Species::Leafeon: return 60_bi;
		case Species::Glaceon: return 60_bi;
		case Species::Gliscor: return 60_bi;
		case Species::Mamoswine: return 120_bi;
		case Species::Porygon_Z: return 60_bi;
		case Species::Gallade: return 80_bi;
		case Species::Probopass: return 120_bi;
		case Species::Dusknoir: return 100_bi;
		case Species::Froslass: return 60_bi;
		case Species::Rotom: return 20_bi;
		case Species::Rotom_Heat: return 20_bi;
		case Species::Rotom_Wash: return 20_bi;
		case Species::Rotom_Frost: return 20_bi;
		case Species::Rotom_Fan: return 20_bi;
		case Species::Rotom_Mow: return 20_bi;
		case Species::Uxie: return 20_bi;
		case Species::Mesprit: return 20_bi;
		case Species::Azelf: return 20_bi;
		case Species::Dialga: return 120_bi;
		case Species::Palkia: return 120_bi;
		case Species::Heatran: return 120_bi;
		case Species::Regigigas: return 120_bi;
		case Species::Giratina_Altered: return 120_bi;
		case Species::Giratina_Origin: return 120_bi;
		case Species::Cresselia: return 80_bi;
		case Species::Phione: return 20_bi;
		case Species::Manaphy: return 20_bi;
		case Species::Darkrai: return 80_bi;
		case Species::Shaymin_Land: return 20_bi;
		case Species::Shaymin_Sky: return 20_bi;
		case Species::Arceus: return 120_bi;

		// Generation 5
		case Species::Victini: return 20_bi;
		case Species::Snivy: return 20_bi;
		case Species::Servine: return 40_bi;
		case Species::Serperior: return 80_bi;
		case Species::Tepig: return 20_bi;
		case Species::Pignite: return 80_bi;
		case Species::Emboar: return 100_bi;
		case Species::Oshawott: return 20_bi;
		case Species::Dewott: return 40_bi;
		case Species::Samurott: return 80_bi;
		case Species::Patrat: return 40_bi;
		case Species::Watchog: return 60_bi;
		case Species::Lillipup: return 20_bi;
		case Species::Herdier: return 40_bi;
		case Species::Stoutland: return 80_bi;
		case Species::Purrloin: return 40_bi;
		case Species::Liepard: return 60_bi;
		case Species::Pansage: return 40_bi;
		case Species::Simisage: return 60_bi;
		case Species::Pansear: return 40_bi;
		case Species::Simisear: return 60_bi;
		case Species::Panpour: return 40_bi;
		case Species::Simipour: return 60_bi;
		case Species::Munna: return 40_bi;
		case Species::Musharna: return 80_bi;
		case Species::Pidove: return 20_bi;
		case Species::Tranquill: return 40_bi;
		case Species::Unfezant: return 60_bi;
		case Species::Blitzle: return 60_bi;
		case Species::Zebstrika: return 80_bi;
		case Species::Roggenrola: return 40_bi;
		case Species::Boldore: return 100_bi;
		case Species::Gigalith: return 120_bi;
		case Species::Woobat: return 20_bi;
		case Species::Swoobat: return 40_bi;
		case Species::Drilbur: return 20_bi;
		case Species::Excadrill: return 60_bi;
		case Species::Audino: return 60_bi;
		case Species::Timburr: return 40_bi;
		case Species::Gurdurr: return 60_bi;
		case Species::Conkeldurr: return 80_bi;
		case Species::Tympole: return 20_bi;
		case Species::Palpitoad: return 40_bi;
		case Species::Seismitoad: return 80_bi;
		case Species::Throh: return 80_bi;
		case Species::Sawk: return 80_bi;
		case Species::Sewaddle: return 20_bi;
		case Species::Swadloon: return 20_bi;
		case Species::Leavanny: return 40_bi;
		case Species::Venipede: return 20_bi;
		case Species::Whirlipede: return 80_bi;
		case Species::Scolipede: return 120_bi;
		case Species::Cottonee: return 20_bi;
		case Species::Whimsicott: return 20_bi;
		case Species::Petilil: return 20_bi;
		case Species::Lilligant: return 40_bi;
		case Species::Basculin: return 40_bi;
		case Species::Sandile: return 40_bi;
		case Species::Krokorok: return 60_bi;
		case Species::Krookodile: return 80_bi;
		case Species::Darumaka: return 60_bi;
		case Species::Darmanitan: return 80_bi;
		case Species::Maractus: return 60_bi;
		case Species::Dwebble: return 40_bi;
		case Species::Crustle: return 120_bi;
		case Species::Scraggy: return 40_bi;
		case Species::Scrafty: return 60_bi;
		case Species::Sigilyph: return 40_bi;
		case Species::Yamask: return 20_bi;
		case Species::Cofagrigus: return 80_bi;
		case Species::Tirtouga: return 40_bi;
		case Species::Carracosta: return 80_bi;
		case Species::Archen: return 20_bi;
		case Species::Archeops: return 60_bi;
		case Species::Trubbish: return 60_bi;
		case Species::Garbodor: return 100_bi;
		case Species::Zorua: return 40_bi;
		case Species::Zoroark: return 80_bi;
		case Species::Minccino: return 20_bi;
		case Species::Cinccino: return 20_bi;
		case Species::Gothita: return 20_bi;
		case Species::Gothorita: return 40_bi;
		case Species::Gothitelle: return 60_bi;
		case Species::Solosis: return 20_bi;
		case Species::Duosion: return 20_bi;
		case Species::Reuniclus: return 40_bi;
		case Species::Ducklett: return 20_bi;
		case Species::Swanna: return 40_bi;
		case Species::Vanillite: return 20_bi;
		case Species::Vanillish: return 60_bi;
		case Species::Vanilluxe: return 80_bi;
		case Species::Deerling: return 40_bi;
		case Species::Sawsbuck: return 80_bi;
		case Species::Emolga: return 20_bi;
		case Species::Karrablast: return 20_bi;
		case Species::Escavalier: return 60_bi;
		case Species::Foongus: return 20_bi;
		case Species::Amoonguss: return 40_bi;
		case Species::Frillish: return 60_bi;
		case Species::Jellicent: return 100_bi;
		case Species::Alomomola: return 60_bi;
		case Species::Joltik: return 20_bi;
		case Species::Galvantula: return 40_bi;
		case Species::Ferroseed: return 40_bi;
		case Species::Ferrothorn: return 100_bi;
		case Species::Klink: return 40_bi;
		case Species::Klang: return 80_bi;
		case Species::Klinklang: return 80_bi;
		case Species::Tynamo: return 20_bi;
		case Species::Eelektrik: return 40_bi;
		case Species::Eelektross: return 80_bi;
		case Species::Elgyem: return 20_bi;
		case Species::Beheeyem: return 60_bi;
		case Species::Litwick: return 20_bi;
		case Species::Lampent: return 40_bi;
		case Species::Chandelure: return 60_bi;
		case Species::Axew: return 40_bi;
		case Species::Fraxure: return 60_bi;
		case Species::Haxorus: return 100_bi;
		case Species::Cubchoo: return 20_bi;
		case Species::Beartic: return 120_bi;
		case Species::Cryogonal: return 100_bi;
		case Species::Shelmet: return 20_bi;
		case Species::Accelgor: return 60_bi;
		case Species::Stunfisk: return 40_bi;
		case Species::Mienfoo: return 40_bi;
		case Species::Mienshao: return 60_bi;
		case Species::Druddigon: return 100_bi;
		case Species::Golett: return 80_bi;
		case Species::Golurk: return 120_bi;
		case Species::Pawniard: return 40_bi;
		case Species::Bisharp: return 80_bi;
		case Species::Bouffalant: return 80_bi;
		case Species::Rufflet: return 40_bi;
		case Species::Braviary: return 60_bi;
		case Species::Vullaby: return 20_bi;
		case Species::Mandibuzz: return 60_bi;
		case Species::Heatmor: return 80_bi;
		case Species::Durant: return 60_bi;
		case Species::Deino: return 40_bi;
		case Species::Zweilous: return 80_bi;
		case Species::Hydreigon: return 100_bi;
		case Species::Larvesta: return 60_bi;
		case Species::Volcarona: return 60_bi;
		case Species::Cobalion: return 120_bi;
		case Species::Terrakion: return 120_bi;
		case Species::Virizion: return 120_bi;
		case Species::Tornadus_Incarnate: return 80_bi;
		case Species::Tornadus_Therian: return 80_bi;
		case Species::Thundurus_Incarnate: return 80_bi;
		case Species::Thundurus_Therian: return 80_bi;
		case Species::Reshiram: return 120_bi;
		case Species::Zekrom: return 120_bi;
		case Species::Landorus_Incarnate: return 80_bi;
		case Species::Landorus_Therian: return 80_bi;
		case Species::Kyurem: return 120_bi;
		case Species::Kyurem_Black: return 120_bi;
		case Species::Kyurem_White: return 120_bi;
		case Species::Keldeo: return 60_bi;
		case Species::Keldeo_Resolute: return 60_bi;
		case Species::Meloetta: return 20_bi;
		case Species::Genesect: return 80_bi;

		// Generation 6
		case Species::Chespin: return 20_bi;
		case Species::Quilladin: return 60_bi;
		case Species::Chesnaught: return 80_bi;
		case Species::Fennekin: return 20_bi;
		case Species::Braixen: return 40_bi;
		case Species::Delphox: return 60_bi;
		case Species::Froakie: return 20_bi;
		case Species::Frogadier: return 40_bi;
		case Species::Greninja: return 60_bi;
		case Species::Bunnelby: return 20_bi;
		case Species::Diggersby: return 60_bi;
		case Species::Fletchling: return 20_bi;
		case Species::Fletchinder: return 40_bi;
		case Species::Talonflame: return 40_bi;
		case Species::Scatterbug: return 20_bi;
		case Species::Spewpa: return 20_bi;
		case Species::Vivillon: return 40_bi;
		case Species::Litleo: return 40_bi;
		case Species::Pyroar: return 80_bi;
		case Species::Flabebe: return 20_bi;
		case Species::Floette: return 20_bi;
		case Species::Florges: return 40_bi;
		case Species::Skiddo: return 60_bi;
		case Species::Gogoat: return 80_bi;
		case Species::Pancham: return 20_bi;
		case Species::Pangoro: return 100_bi;
		case Species::Furfrou: return 60_bi;
		case Species::Espurr: return 20_bi;
		case Species::Meowstic_F: return 20_bi;
		case Species::Meowstic_M: return 20_bi;
		case Species::Honedge: return 20_bi;
		case Species::Doublade: return 20_bi;
		case Species::Aegislash: return 80_bi;
		case Species::Spritzee: return 20_bi;
		case Species::Aromatisse: return 40_bi;
		case Species::Swirlix: return 20_bi;
		case Species::Slurpuff: return 20_bi;
		case Species::Inkay: return 20_bi;
		case Species::Malamar: return 60_bi;
		case Species::Binacle: return 60_bi;
		case Species::Barbaracle: return 80_bi;
		case Species::Skrelp: return 20_bi;
		case Species::Dragalge: return 80_bi;
		case Species::Clauncher: return 20_bi;
		case Species::Clawitzer: return 60_bi;
		case Species::Helioptile: return 20_bi;
		case Species::Heliolisk: return 40_bi;
		case Species::Tyrunt: return 60_bi;
		case Species::Tyrantrum: return 120_bi;
		case Species::Amaura: return 60_bi;
		case Species::Aurorus: return 120_bi;
		case Species::Sylveon: return 40_bi;
		case Species::Hawlucha: return 40_bi;
		case Species::Dedenne: return 20_bi;
		case Species::Carbink: return 20_bi;
		case Species::Goomy: return 20_bi;
		case Species::Sliggoo: return 40_bi;
		case Species::Goodra: return 100_bi;
		case Species::Klefki: return 20_bi;
		case Species::Phantump: return 20_bi;
		case Species::Trevenant: return 80_bi;
		case Species::Pumpkaboo_Small: return 20_bi;
		case Species::Pumpkaboo_Average: return 20_bi;
		case Species::Pumpkaboo_Large: return 20_bi;
		case Species::Pumpkaboo_Super: return 40_bi;
		case Species::Gourgeist_Small: return 20_bi;
		case Species::Gourgeist_Average: return 40_bi;
		case Species::Gourgeist_Large: return 40_bi;
		case Species::Gourgeist_Super: return 60_bi;
		case Species::Bergmite: return 80_bi;
		case Species::Avalugg: return 120_bi;
		case Species::Noibat: return 20_bi;
		case Species::Noivern: return 80_bi;
		case Species::Xerneas: return 120_bi;
		case Species::Yveltal: return 120_bi;
		case Species::Zygarde_50: return 120_bi;
		case Species::Zygarde_10: return 60_bi;
		case Species::Zygarde_Complete: return 120_bi;
		case Species::Diancie: return 20_bi;
		case Species::Hoopa_Confined: return 20_bi;
		case Species::Hoopa_Unbound: return 120_bi;
		case Species::Volcanion: return 100_bi;

		// Generation 7
		case Species::Rowlet: return 20_bi;
		case Species::Dartrix: return 40_bi;
		case Species::Decidueye: return 60_bi;
		case Species::Litten: return 20_bi;
		case Species::Torracat: return 60_bi;
		case Species::Incineroar: return 80_bi;
		case Species::Popplio: return 20_bi;
		case Species::Brionne: return 40_bi;
		case Species::Primarina: return 60_bi;
		case Species::Pikipek: return 20_bi;
		case Species::Trumbeak: return 40_bi;
		case Species::Toucannon: return 60_bi;
		case Species::Yungoos: return 20_bi;
		case Species::Gumshoos: return 40_bi;
		case Species::Grubbin: return 20_bi;
		case Species::Charjabug: return 40_bi;
		case Species::Vikavolt: return 60_bi;
		case Species::Crabrawler: return 20_bi;
		case Species::Crabominable: return 100_bi;
		case Species::Oricorio_Baile: return 20_bi;
		case Species::Oricorio_Pau: return 20_bi;
		case Species::Oricorio_Pom_Pom: return 20_bi;
		case Species::Oricorio_Sensu: return 20_bi;
		case Species::Cutiefly: return 20_bi;
		case Species::Ribombee: return 20_bi;
		case Species::Rockruff: return 20_bi;
		case Species::Lycanroc_Midday: return 60_bi;
		case Species::Lycanroc_Midnight: return 60_bi;
		case Species::Lycanroc_Dusk: return 60_bi;
		case Species::Wishiwashi_Solo: return 20_bi;
		case Species::Wishiwashi_School: return 80_bi;
		case Species::Mareanie: return 20_bi;
		case Species::Toxapex: return 40_bi;
		case Species::Mudbray: return 100_bi;
		case Species::Mudsdale: return 120_bi;
		case Species::Dewpider: return 20_bi;
		case Species::Araquanid: return 80_bi;
		case Species::Fomantis: return 20_bi;
		case Species::Lurantis: return 40_bi;
		case Species::Morelull: return 20_bi;
		case Species::Shiinotic: return 40_bi;
		case Species::Salandit: return 20_bi;
		case Species::Salazzle: return 40_bi;
		case Species::Stufful: return 20_bi;
		case Species::Bewear: return 100_bi;
		case Species::Bounsweet: return 20_bi;
		case Species::Steenee: return 20_bi;
		case Species::Tsareena: return 40_bi;
		case Species::Comfey: return 20_bi;
		case Species::Oranguru: return 80_bi;
		case Species::Passimian: return 80_bi;
		case Species::Wimpod: return 40_bi;
		case Species::Golisopod: return 100_bi;
		case Species::Sandygast: return 80_bi;
		case Species::Palossand: return 120_bi;
		case Species::Pyukumuku: return 20_bi;
		case Species::Type_Null: return 100_bi;
		case Species::Silvally: return 100_bi;
		case Species::Minior_Meteor: return 60_bi;
		case Species::Minior_Core: return 20_bi;
		case Species::Komala: return 40_bi;
		case Species::Turtonator: return 120_bi;
		case Species::Togedemaru: return 20_bi;
		case Species::Mimikyu: return 20_bi;
		case Species::Bruxish: return 40_bi;
		case Species::Drampa: return 100_bi;
		case Species::Dhelmise: return 120_bi;
		case Species::Jangmo_o: return 60_bi;
		case Species::Hakamo_o: return 60_bi;
		case Species::Kommo_o: return 80_bi;
		case Species::Tapu_Koko: return 40_bi;
		case Species::Tapu_Lele: return 40_bi;
		case Species::Tapu_Bulu: return 60_bi;
		case Species::Tapu_Fini: return 40_bi;
		case Species::Cosmog: return 20_bi;
		case Species::Cosmoem: return 120_bi;
		case Species::Solgaleo: return 120_bi;
		case Species::Lunala: return 100_bi;
		case Species::Nihilego: return 80_bi;
		case Species::Buzzwole: return 120_bi;
		case Species::Pheromosa: return 60_bi;
		case Species::Xurkitree: return 100_bi;
		case Species::Celesteela: return 120_bi;
		case Species::Kartana: return 20_bi;
		case Species::Guzzlord: return 120_bi;
		case Species::Necrozma: return 120_bi;
		case Species::Necrozma_Dusk_Mane: return 120_bi;
		case Species::Necrozma_Dawn_Wings: return 120_bi;
		case Species::Necrozma_Ultra: return 120_bi;
		case Species::Magearna: return 80_bi;
		case Species::Marshadow: return 40_bi;
		case Species::Poipole: return 20_bi;
		case Species::Naganadel: return 100_bi;
		case Species::Stakataka: return 120_bi;
		case Species::Blacephalon: return 40_bi;
		case Species::Zeraora: return 60_bi;
		case Species::Meltan: return 20_bi;
		case Species::Melmetal: return 120_bi;
		case Species::Rattata_Alola: return 20_bi;
		case Species::Raticate_Alola: return 60_bi;
		case Species::Raichu_Alola: return 40_bi;
		case Species::Sandshrew_Alola: return 60_bi;
		case Species::Sandslash_Alola: return 80_bi;
		case Species::Vulpix_Alola: return 20_bi;
		case Species::Ninetales_Alola: return 40_bi;
		case Species::Diglett_Alola: return 20_bi;
		case Species::Dugtrio_Alola: return 80_bi;
		case Species::Meowth_Alola: return 20_bi;
		case Species::Persian_Alola: return 60_bi;
		case Species::Geodude_Alola: return 40_bi;
		case Species::Graveler_Alola: return 100_bi;
		case Species::Golem_Alola: return 120_bi;
		case Species::Grimer_Alola: return 60_bi;
		case Species::Muk_Alola: return 80_bi;
		case Species::Exeggutor_Alola: return 120_bi;
		case Species::Marowak_Alola: return 60_bi;

		// Generation 8
		case Species::Grookey: return 20_bi;
		case Species::Thwackey: return 40_bi;
		case Species::Rillaboom: return 80_bi;
		case Species::Scorbunny: return 20_bi;
		case Species::Raboot: return 20_bi;
		case Species::Cinderace: return 60_bi;
		case Species::Sobble: return 20_bi;
		case Species::Drizzile: return 40_bi;
		case Species::Inteleon: return 60_bi;
		case Species::Skwovet: return 20_bi;
		case Species::Greedent: return 20_bi;
		case Species::Rookidee: return 20_bi;
		case Species::Corvisquire: return 40_bi;
		case Species::Corviknight: return 80_bi;
		case Species::Blipbug: return 20_bi;
		case Species::Dottler: return 40_bi;
		case Species::Orbeetle: return 60_bi;
		case Species::Nickit: return 20_bi;
		case Species::Thievul: return 40_bi;
		case Species::Gossifleur: return 20_bi;
		case Species::Eldegoss: return 20_bi;
		case Species::Wooloo: return 20_bi;
		case Species::Dubwool: return 60_bi;
		case Species::Chewtle: return 20_bi;
		case Species::Drednaw: return 100_bi;
		case Species::Yamper: return 40_bi;
		case Species::Boltund: return 60_bi;
		case Species::Rolycoly: return 40_bi;
		case Species::Carkol: return 80_bi;
		case Species::Coalossal: return 120_bi;
		case Species::Applin: return 20_bi;
		case Species::Flapple: return 20_bi;
		case Species::Appletun: return 40_bi;
		case Species::Silicobra: return 20_bi;
		case Species::Sandaconda: return 80_bi;
		case Species::Cramorant: return 40_bi;
		case Species::Arrokuda: return 20_bi;
		case Species::Barraskewda: return 60_bi;
		case Species::Toxel: return 40_bi;
		case Species::Toxtricity_Amped: return 60_bi;
		case Species::Toxtricity_Low_Key: return 60_bi;
		case Species::Sizzlipede: return 20_bi;
		case Species::Centiskorch: return 100_bi;
		case Species::Clobbopus: return 20_bi;
		case Species::Grapploct: return 60_bi;
		case Species::Sinistea: return 20_bi;
		case Species::Polteageist: return 20_bi;
		case Species::Hatenna: return 20_bi;
		case Species::Hattrem: return 20_bi;
		case Species::Hatterene: return 20_bi;
		case Species::Impidimp: return 20_bi;
		case Species::Morgrem: return 40_bi;
		case Species::Grimmsnarl: return 80_bi;
		case Species::Obstagoon: return 60_bi;
		case Species::Perrserker: return 60_bi;
		case Species::Cursola: return 20_bi;
		case Species::Sirfetchd: return 100_bi;
		case Species::Mr_Rime: return 80_bi;
		case Species::Runerigus: return 80_bi;
		case Species::Milcery: return 20_bi;
		case Species::Alcremie: return 20_bi;
		case Species::Falinks: return 80_bi;
		case Species::Pincurchin: return 20_bi;
		case Species::Snom: return 20_bi;
		case Species::Frosmoth: return 60_bi;
		case Species::Stonjourner: return 120_bi;
		case Species::Eiscue: return 80_bi;
		case Species::Indeedee_F: return 60_bi;
		case Species::Indeedee_M: return 60_bi;
		case Species::Morpeko: return 20_bi;
		case Species::Cufant: return 100_bi;
		case Species::Copperajah: return 120_bi;
		case Species::Dracozolt: return 100_bi;
		case Species::Arctozolt: return 100_bi;
		case Species::Dracovish: return 120_bi;
		case Species::Arctovish: return 100_bi;
		case Species::Duraludon: return 60_bi;
		case Species::Dreepy: return 20_bi;
		case Species::Drakloak: return 40_bi;
		case Species::Dragapult: return 80_bi;
		case Species::Zacian: return 100_bi;
		case Species::Zacian_Crowned_Sword: return 120_bi;
		case Species::Zamazenta: return 120_bi;
		case Species::Zamazenta_Crowned_Shield: return 120_bi;
		case Species::Eternatus: return 120_bi;
		case Species::Kubfu: return 40_bi;
		case Species::Urshifu_Single_Strike: return 100_bi;
		case Species::Urshifu_Rapid_Strike: return 100_bi;
		case Species::Zarude: return 80_bi;
		case Species::Regieleki: return 100_bi;
		case Species::Regidrago: return 120_bi;
		case Species::Glastrier: return 120_bi;
		case Species::Spectrier: return 60_bi;
		case Species::Calyrex: return 20_bi;
		case Species::Calyrex_Ice_Rider: return 120_bi;
		case Species::Calyrex_Shadow_Rider: return 80_bi;
		case Species::Meowth_Galar: return 20_bi;
		case Species::Ponyta_Galar: return 40_bi;
		case Species::Rapidash_Galar: return 80_bi;
		case Species::Farfetchd_Galar: return 60_bi;
		case Species::Weezing_Galar: return 40_bi;
		case Species::Mr_Mime_Galar: return 80_bi;
		case Species::Corsola_Galar: return 20_bi;
		case Species::Zigzagoon_Galar: return 40_bi;
		case Species::Linoone_Galar: return 60_bi;
		case Species::Darumaka_Galar: return 60_bi;
		case Species::Darmanitan_Galar: return 100_bi;
		case Species::Yamask_Galar: return 20_bi;
		case Species::Stunfisk_Galar: return 40_bi;
		case Species::Slowpoke_Galar: return 60_bi;
		case Species::Slowbro_Galar: return 80_bi;
		case Species::Articuno_Galar: return 80_bi;
		case Species::Zapdos_Galar: return 80_bi;
		case Species::Moltres_Galar: return 80_bi;
		case Species::Slowking_Galar: return 80_bi;
		// case Species::Basculegion: return 100_bi;
		// case Species::Greninja_Ash: return 60_bi;
		// case Species::Kleavor: return 80_bi;
		// case Species::Mega_Abomasnow: return 100_bi;
		// case Species::Mega_Absol: return 60_bi;
		// case Species::Mega_Aerodactyl: return 80_bi;
		// case Species::Mega_Aggron: return 120_bi;
		// case Species::Mega_Altaria: return 40_bi;
		// case Species::Mega_Audino: return 60_bi;
		// case Species::Mega_Banette: return 40_bi;
		// case Species::Mega_Beedrill: return 60_bi;
		// case Species::Mega_Blastoise: return 100_bi;
		// case Species::Mega_Camerupt: return 120_bi;
		// case Species::Mega_Charizard_X: return 100_bi;
		// case Species::Mega_Charizard_Y: return 100_bi;
		// case Species::Mega_Diancie: return 60_bi;
		// case Species::Mega_Gallade: return 80_bi;
		// case Species::Mega_Glalie: return 120_bi;
		// case Species::Mega_Gyarados: return 120_bi;
		// case Species::Mega_Heracross: return 80_bi;
		// case Species::Mega_Houndoom: return 60_bi;
		// case Species::Mega_Kangaskhan: return 100_bi;
		// case Species::Mega_Latias: return 80_bi;
		// case Species::Mega_Latios: return 80_bi;
		// case Species::Mega_Lopunny: return 60_bi;
		// case Species::Mega_Lucario: return 80_bi;
		// case Species::Mega_Manectric: return 60_bi;
		// case Species::Mega_Mawile: return 40_bi;
		// case Species::Mega_Metagross: return 120_bi;
		// case Species::Mega_Mewtwo_X: return 100_bi;
		// case Species::Mega_Mewtwo_Y: return 60_bi;
		// case Species::Mega_Pidgeot: return 80_bi;
		// case Species::Mega_Pinsir: return 80_bi;
		// case Species::Mega_Rayquaza: return 120_bi;
		// case Species::Mega_Sableye: return 100_bi;
		// case Species::Mega_Salamence: return 100_bi;
		// case Species::Mega_Sceptile: return 80_bi;
		// case Species::Mega_Scizor: return 100_bi;
		// case Species::Mega_Sharpedo: return 100_bi;
		// case Species::Mega_Slowbro: return 100_bi;
		// case Species::Mega_Steelix: return 120_bi;
		// case Species::Mega_Swampert: return 100_bi;
		// case Species::Mega_Tyranitar: return 120_bi;
		// case Species::Mega_Venusaur: return 100_bi;
		// case Species::Meloetta_Pirouette: return 20_bi;
		// case Species::Primal_Groudon: return 120_bi;
		// case Species::Primal_Kyogre: return 120_bi;
		// case Species::Wyrdeer: return 80_bi;
	}
}

// Fling gives 0, Rollout gives 480
export using BasePower = bounded::integer<0, 480>;

// It is undefined behavior to get the base power of a move without a base power
// (Dragon Rage, Guillotine, etc.).
export template<any_team UserTeam, any_team DefenderTeam>
constexpr auto base_power(UserTeam const & attacker_team, ExecutedMove<UserTeam> const executed, DefenderTeam const & defender_team, Environment const environment) -> BasePower {
	constexpr auto generation = generation_from<UserTeam>;
	auto const & attacker = attacker_team.pokemon();
	auto const & defender = defender_team.pokemon();
	switch (executed.move.name) {
		case MoveName::Pass: return 0_bi;
		case MoveName::Switch0: return 0_bi;
		case MoveName::Switch1: return 0_bi;
		case MoveName::Switch2: return 0_bi;
		case MoveName::Switch3: return 0_bi;
		case MoveName::Switch4: return 0_bi;
		case MoveName::Switch5: return 0_bi;
		case MoveName::Hit_Self: return 40_bi;
		case MoveName::Pound: return 40_bi;
		case MoveName::Karate_Chop: return 50_bi;
		case MoveName::Double_Slap: return 15_bi;
		case MoveName::Comet_Punch: return 18_bi;
		case MoveName::Mega_Punch: return 80_bi;
		case MoveName::Pay_Day: return 40_bi;
		case MoveName::Fire_Punch: return 75_bi;
		case MoveName::Ice_Punch: return 75_bi;
		case MoveName::Thunder_Punch: return 75_bi;
		case MoveName::Scratch: return 40_bi;
		case MoveName::Vise_Grip: return 55_bi;
		case MoveName::Guillotine: std::unreachable();
		case MoveName::Razor_Wind: return 80_bi;
		case MoveName::Swords_Dance: return 0_bi;
		case MoveName::Cut: return 50_bi;
		case MoveName::Gust: return 40_bi;
		case MoveName::Wing_Attack: return BOUNDED_CONDITIONAL(generation == Generation::one, 35_bi, 60_bi);
		case MoveName::Whirlwind: return 0_bi;
		case MoveName::Fly: return BOUNDED_CONDITIONAL(generation <= Generation::three, 70_bi, 90_bi);
		case MoveName::Bind: return 15_bi;
		case MoveName::Slam: return 80_bi;
		case MoveName::Vine_Whip: return BOUNDED_CONDITIONAL(generation <= Generation::five, 35_bi, 45_bi);
		case MoveName::Stomp: return 65_bi;
		case MoveName::Double_Kick: return 30_bi;
		case MoveName::Mega_Kick: return 120_bi;
		case MoveName::Jump_Kick:
			switch (generation) {
				case Generation::one:
				case Generation::two:
				case Generation::three:
					return 70_bi;
				case Generation::four:
					return 85_bi;
				default:
					return 100_bi;
			}
		case MoveName::Rolling_Kick: return 60_bi;
		case MoveName::Sand_Attack: return 0_bi;
		case MoveName::Headbutt: return 70_bi;
		case MoveName::Horn_Attack: return 65_bi;
		case MoveName::Fury_Attack: return 15_bi;
		case MoveName::Horn_Drill: std::unreachable();
		case MoveName::Tackle:
			switch (generation) {
				case Generation::one:
				case Generation::two:
				case Generation::three:
				case Generation::four:
					return 35_bi;
				case Generation::five:
				case Generation::six:
					return 50_bi;
				default:
					return 40_bi;
			}
		case MoveName::Body_Slam: return 85_bi;
		case MoveName::Wrap: return 15_bi;
		case MoveName::Take_Down: return 90_bi;
		case MoveName::Thrash: return BOUNDED_CONDITIONAL(generation <= Generation::four, 90_bi, 120_bi);
		case MoveName::Double_Edge: return BOUNDED_CONDITIONAL(generation == Generation::one, 100_bi, 120_bi);
		case MoveName::Tail_Whip: return 0_bi;
		case MoveName::Poison_Sting: return 15_bi;
		case MoveName::Twineedle: return 25_bi;
		case MoveName::Pin_Missile: return BOUNDED_CONDITIONAL(generation <= Generation::five, 14_bi, 25_bi);
		case MoveName::Leer: return 0_bi;
		case MoveName::Bite: return 60_bi;
		case MoveName::Growl: return 0_bi;
		case MoveName::Roar: return 0_bi;
		case MoveName::Sing: return 0_bi;
		case MoveName::Supersonic: return 0_bi;
		case MoveName::Sonic_Boom: std::unreachable();
		case MoveName::Disable: return 0_bi;
		case MoveName::Acid: return 40_bi;
		case MoveName::Ember: return 40_bi;
		case MoveName::Flamethrower: return BOUNDED_CONDITIONAL(generation <= Generation::five, 95_bi, 90_bi);
		case MoveName::Mist: return 0_bi;
		case MoveName::Water_Gun: return 40_bi;
		case MoveName::Hydro_Pump: return BOUNDED_CONDITIONAL(generation <= Generation::five, 120_bi, 110_bi);
		case MoveName::Surf: return BOUNDED_CONDITIONAL(generation <= Generation::five, 95_bi, 90_bi);
		case MoveName::Ice_Beam: return BOUNDED_CONDITIONAL(generation <= Generation::five, 95_bi, 90_bi);
		case MoveName::Blizzard: return BOUNDED_CONDITIONAL(generation <= Generation::five, 120_bi, 110_bi);
		case MoveName::Psybeam: return 65_bi;
		case MoveName::Bubble_Beam: return 65_bi;
		case MoveName::Aurora_Beam: return 65_bi;
		case MoveName::Hyper_Beam: return 150_bi;
		case MoveName::Peck: return 35_bi;
		case MoveName::Drill_Peck: return 80_bi;
		case MoveName::Submission: return 80_bi;
		case MoveName::Low_Kick:
		case MoveName::Grass_Knot:
			return BOUNDED_CONDITIONAL(generation <= Generation::two, 50_bi, power_of_mass_based_moves(defender.species()));
		case MoveName::Counter: std::unreachable();
		case MoveName::Seismic_Toss: std::unreachable();
		case MoveName::Strength: return 80_bi;
		case MoveName::Absorb: return 20_bi;
		case MoveName::Mega_Drain: return 40_bi;
		case MoveName::Leech_Seed: return 0_bi;
		case MoveName::Growth: return 0_bi;
		case MoveName::Razor_Leaf: return 55_bi;
		// Base power is doubled in certain weather, including clear weather
		case MoveName::Solar_Beam: return 60_bi;
		case MoveName::Poison_Powder: return 0_bi;
		case MoveName::Stun_Spore: return 0_bi;
		case MoveName::Sleep_Powder: return 0_bi;
		case MoveName::Petal_Dance:
			switch (generation) {
				case Generation::one:
				case Generation::two:
				case Generation::three:
					return 70_bi;
				case Generation::four:
					return 90_bi;
				default:
					return 120_bi;
			}
		case MoveName::String_Shot: return 0_bi;
		case MoveName::Dragon_Rage: std::unreachable();
		case MoveName::Fire_Spin: return BOUNDED_CONDITIONAL(generation <= Generation::four, 15_bi, 35_bi);
		case MoveName::Thunder_Shock: return 40_bi;
		case MoveName::Thunderbolt: return BOUNDED_CONDITIONAL(generation <= Generation::five, 95_bi, 90_bi);
		case MoveName::Thunder_Wave: return 0_bi;
		case MoveName::Thunder: return BOUNDED_CONDITIONAL(generation <= Generation::five, 120_bi, 110_bi);
		case MoveName::Rock_Throw: return 50_bi;
		case MoveName::Earthquake: return 100_bi;
		case MoveName::Fissure: std::unreachable();
		case MoveName::Dig:
			switch (generation) {
				case Generation::one:
					return 100_bi;
				case Generation::two:
				case Generation::three:
					return 60_bi;
				default:
					return 80_bi;
			}
		case MoveName::Toxic: return 0_bi;
		case MoveName::Confusion: return 50_bi;
		case MoveName::Psychic: return 90_bi;
		case MoveName::Hypnosis: return 0_bi;
		case MoveName::Meditate: return 0_bi;
		case MoveName::Agility: return 0_bi;
		case MoveName::Quick_Attack: return 40_bi;
		case MoveName::Rage: return 20_bi;
		case MoveName::Teleport: return 0_bi;
		case MoveName::Night_Shade: std::unreachable();
		case MoveName::Mimic: return 0_bi;
		case MoveName::Screech: return 0_bi;
		case MoveName::Double_Team: return 0_bi;
		case MoveName::Recover: return 0_bi;
		case MoveName::Harden: return 0_bi;
		case MoveName::Minimize: return 0_bi;
		case MoveName::Smokescreen: return 0_bi;
		case MoveName::Confuse_Ray: return 0_bi;
		case MoveName::Withdraw: return 0_bi;
		case MoveName::Defense_Curl: return 0_bi;
		case MoveName::Barrier: return 0_bi;
		case MoveName::Light_Screen: return 0_bi;
		case MoveName::Haze: return 0_bi;
		case MoveName::Reflect: return 0_bi;
		case MoveName::Focus_Energy: return 0_bi;
		case MoveName::Bide: std::unreachable();
		case MoveName::Metronome: return 0_bi;
		case MoveName::Mirror_Move: return 0_bi;
		case MoveName::Self_Destruct: return BOUNDED_CONDITIONAL(generation == Generation::one, 130_bi, 200_bi);
		case MoveName::Egg_Bomb: return 100_bi;
		case MoveName::Lick: return BOUNDED_CONDITIONAL(generation <= Generation::five, 20_bi, 30_bi);
		case MoveName::Smog: return BOUNDED_CONDITIONAL(generation <= Generation::five, 20_bi, 30_bi);
		case MoveName::Sludge: return 65_bi;
		case MoveName::Bone_Club: return 65_bi;
		case MoveName::Fire_Blast: return BOUNDED_CONDITIONAL(generation <= Generation::five, 120_bi, 110_bi);
		case MoveName::Waterfall: return 80_bi;
		case MoveName::Clamp: return 35_bi;
		case MoveName::Swift: return 60_bi;
		case MoveName::Skull_Bash: return BOUNDED_CONDITIONAL(generation <= Generation::five, 100_bi, 130_bi);
		case MoveName::Spike_Cannon: return 20_bi;
		case MoveName::Constrict: return 10_bi;
		case MoveName::Amnesia: return 0_bi;
		case MoveName::Kinesis: return 0_bi;
		case MoveName::Soft_Boiled: return 0_bi;
		case MoveName::High_Jump_Kick:
			switch (generation) {
				case Generation::one:
				case Generation::two:
				case Generation::three:
					return 85_bi;
				case Generation::four:
					return 100_bi;
				default:
					return 130_bi;
			}
		case MoveName::Glare: return 0_bi;
		case MoveName::Dream_Eater: return 100_bi;
		case MoveName::Poison_Gas: return 0_bi;
		case MoveName::Barrage: return 15_bi;
		case MoveName::Leech_Life: return BOUNDED_CONDITIONAL(generation <= Generation::six, 20_bi, 80_bi);
		case MoveName::Lovely_Kiss: return 0_bi;
		case MoveName::Sky_Attack: return 140_bi;
		case MoveName::Transform: return 0_bi;
		case MoveName::Bubble: return BOUNDED_CONDITIONAL(generation <= Generation::five, 20_bi, 40_bi);
		case MoveName::Dizzy_Punch: return 70_bi;
		case MoveName::Spore: return 0_bi;
		case MoveName::Flash: return 0_bi;
		case MoveName::Psywave: std::unreachable();
		case MoveName::Splash: return 0_bi;
		case MoveName::Acid_Armor: return 0_bi;
		case MoveName::Crabhammer: return BOUNDED_CONDITIONAL(generation <= Generation::five, 90_bi, 100_bi);
		case MoveName::Explosion: return BOUNDED_CONDITIONAL(generation == Generation::one, 170_bi, 250_bi);
		case MoveName::Fury_Swipes: return 18_bi;
		case MoveName::Bonemerang: return 50_bi;
		case MoveName::Rest: return 0_bi;
		case MoveName::Rock_Slide: return 75_bi;
		case MoveName::Hyper_Fang: return 80_bi;
		case MoveName::Sharpen: return 0_bi;
		case MoveName::Conversion: return 0_bi;
		case MoveName::Tri_Attack: return 80_bi;
		case MoveName::Super_Fang: std::unreachable();
		case MoveName::Slash: return 70_bi;
		case MoveName::Substitute: return 0_bi;
		case MoveName::Struggle: return 50_bi;
		case MoveName::Sketch: return 0_bi;
		case MoveName::Triple_Kick: return attacker.last_used_move().triple_kick_power();
		case MoveName::Thief: return BOUNDED_CONDITIONAL(generation <= Generation::five, 40_bi, 60_bi);
		case MoveName::Spider_Web: return 0_bi;
		case MoveName::Mind_Reader: return 0_bi;
		case MoveName::Nightmare: return 0_bi;
		case MoveName::Flame_Wheel: return 60_bi;
		case MoveName::Snore: return BOUNDED_CONDITIONAL(generation <= Generation::five, 40_bi, 50_bi);
		case MoveName::Curse: return 0_bi;
		case MoveName::Flail:
		case MoveName::Reversal: {
			auto const k = 64_bi * hp_ratio(attacker);
			if (k <= 1_bi) return 200_bi;
			else if (k <= 5_bi) return 150_bi;
			else if (k <= 12_bi) return 100_bi;
			else if (k <= 21_bi) return 80_bi;
			else if (k <= 42_bi) return 40_bi;
			else return 20_bi;
		}
		case MoveName::Conversion_2: return 0_bi;
		case MoveName::Aeroblast: return 100_bi;
		case MoveName::Cotton_Spore: return 0_bi;
		case MoveName::Spite: return 0_bi;
		case MoveName::Powder_Snow: return 40_bi;
		case MoveName::Protect: return 0_bi;
		case MoveName::Mach_Punch: return 40_bi;
		case MoveName::Scary_Face: return 0_bi;
		case MoveName::Feint_Attack: return 60_bi;
		case MoveName::Sweet_Kiss: return 0_bi;
		case MoveName::Belly_Drum: return 0_bi;
		case MoveName::Sludge_Bomb: return 90_bi;
		case MoveName::Mud_Slap: return 20_bi;
		case MoveName::Octazooka: return 65_bi;
		case MoveName::Spikes: return 0_bi;
		case MoveName::Zap_Cannon: return BOUNDED_CONDITIONAL(generation <= Generation::three, 100_bi, 120_bi);
		case MoveName::Foresight: return 0_bi;
		case MoveName::Destiny_Bond: return 0_bi;
		case MoveName::Perish_Song: return 0_bi;
		case MoveName::Icy_Wind: return 55_bi;
		case MoveName::Detect: return 0_bi;
		case MoveName::Bone_Rush: return 25_bi;
		case MoveName::Lock_On: return 0_bi;
		case MoveName::Outrage: return BOUNDED_CONDITIONAL(generation <= Generation::three, 90_bi, 120_bi);
		case MoveName::Sandstorm: return 0_bi;
		case MoveName::Giga_Drain: return BOUNDED_CONDITIONAL(generation <= Generation::four, 60_bi, 75_bi);
		case MoveName::Endure: return 0_bi;
		case MoveName::Charm: return 0_bi;
		case MoveName::Rollout:
		case MoveName::Ice_Ball:
			return attacker.last_used_move().momentum_move_power();
		case MoveName::False_Swipe: return 40_bi;
		case MoveName::Swagger: return 0_bi;
		case MoveName::Milk_Drink: return 0_bi;
		case MoveName::Spark: return 65_bi;
		case MoveName::Fury_Cutter: return attacker.last_used_move().fury_cutter_power(generation);
		case MoveName::Steel_Wing: return 70_bi;
		case MoveName::Mean_Look: return 0_bi;
		case MoveName::Attract: return 0_bi;
		case MoveName::Sleep_Talk: return 0_bi;
		case MoveName::Heal_Bell: return 0_bi;
		case MoveName::Return: return return_power(attacker.happiness());
		// TODO
		case MoveName::Present: return 80_bi;
		case MoveName::Frustration: return frustration_power(attacker.happiness());
		case MoveName::Safeguard: return 0_bi;
		case MoveName::Pain_Split: return 0_bi;
		case MoveName::Sacred_Fire: return 100_bi;
		// TODO:
		case MoveName::Magnitude: return 70_bi;
		case MoveName::Dynamic_Punch: return 100_bi;
		case MoveName::Megahorn: return 120_bi;
		case MoveName::Dragon_Breath: return 60_bi;
		case MoveName::Baton_Pass: return 0_bi;
		case MoveName::Encore: return 0_bi;
		case MoveName::Pursuit: return 40_bi;
		case MoveName::Rapid_Spin: return BOUNDED_CONDITIONAL(generation <= Generation::seven, 20_bi, 50_bi);
		case MoveName::Sweet_Scent: return 0_bi;
		case MoveName::Iron_Tail: return 100_bi;
		case MoveName::Metal_Claw: return 50_bi;
		case MoveName::Vital_Throw: return 70_bi;
		case MoveName::Morning_Sun: return 0_bi;
		case MoveName::Synthesis: return 0_bi;
		case MoveName::Moonlight: return 0_bi;
		case MoveName::Hidden_Power: return attacker.hidden_power()->power();
		case MoveName::Cross_Chop: return 100_bi;
		case MoveName::Twister: return 40_bi;
		case MoveName::Rain_Dance: return 0_bi;
		case MoveName::Sunny_Day: return 0_bi;
		case MoveName::Crunch: return 80_bi;
		case MoveName::Mirror_Coat: std::unreachable();
		case MoveName::Psych_Up: return 0_bi;
		case MoveName::Extreme_Speed: return 80_bi;
		case MoveName::Ancient_Power: return 60_bi;
		case MoveName::Shadow_Ball: return 80_bi;
		case MoveName::Future_Sight:
			switch (generation) {
				case Generation::one:
				case Generation::two:
				case Generation::three:
				case Generation::four:
					return 80_bi;
				case Generation::five:
					return 100_bi;
				default:
					return 120_bi;
			}
		case MoveName::Rock_Smash: return BOUNDED_CONDITIONAL(generation <= Generation::three, 20_bi, 40_bi);
		case MoveName::Whirlpool: return BOUNDED_CONDITIONAL(generation <= Generation::four, 15_bi, 35_bi);
		// TODO: Beat Up
		case MoveName::Beat_Up: return 1_bi;
		case MoveName::Fake_Out: return 40_bi;
		case MoveName::Uproar: return BOUNDED_CONDITIONAL(generation <= Generation::four, 50_bi, 90_bi);
		case MoveName::Stockpile: return 0_bi;
		case MoveName::Spit_Up: return attacker.spit_up_power();
		case MoveName::Swallow: return 0_bi;
		case MoveName::Heat_Wave: return BOUNDED_CONDITIONAL(generation <= Generation::five, 100_bi, 95_bi);
		case MoveName::Hail: return 0_bi;
		case MoveName::Torment: return 0_bi;
		case MoveName::Flatter: return 0_bi;
		case MoveName::Will_O_Wisp: return 0_bi;
		case MoveName::Memento: return 0_bi;
		case MoveName::Facade: return 70_bi;
		case MoveName::Focus_Punch: return 150_bi;
		case MoveName::Smelling_Salts: return BOUNDED_CONDITIONAL(generation <= Generation::five, 60_bi, 70_bi);
		case MoveName::Follow_Me: return 0_bi;
		case MoveName::Nature_Power: return 0_bi;
		case MoveName::Charge: return 0_bi;
		case MoveName::Taunt: return 0_bi;
		case MoveName::Helping_Hand: return 0_bi;
		case MoveName::Trick: return 0_bi;
		case MoveName::Role_Play: return 0_bi;
		case MoveName::Wish: return 0_bi;
		case MoveName::Assist: return 0_bi;
		case MoveName::Ingrain: return 0_bi;
		case MoveName::Superpower: return 120_bi;
		case MoveName::Magic_Coat: return 0_bi;
		case MoveName::Recycle: return 0_bi;
		case MoveName::Revenge: return 60_bi;
		case MoveName::Brick_Break: return 75_bi;
		case MoveName::Yawn: return 0_bi;
		case MoveName::Knock_Off: return BOUNDED_CONDITIONAL(generation <= Generation::five, 20_bi, 65_bi);
		case MoveName::Endeavor: std::unreachable();
		case MoveName::Dragon_Energy:
		case MoveName::Eruption:
		case MoveName::Water_Spout:
			return bounded::assume_in_range(bounded::max(150_bi * hp_ratio(attacker), 1_bi), 1_bi, 150_bi);
		case MoveName::Skill_Swap: return 0_bi;
		case MoveName::Imprison: return 0_bi;
		case MoveName::Refresh: return 0_bi;
		case MoveName::Grudge: return 0_bi;
		case MoveName::Snatch: return 0_bi;
		case MoveName::Secret_Power: return 70_bi;
		case MoveName::Dive: return BOUNDED_CONDITIONAL(generation <= Generation::three, 60_bi, 80_bi);
		case MoveName::Arm_Thrust: return 15_bi;
		case MoveName::Camouflage: return 0_bi;
		case MoveName::Tail_Glow: return 0_bi;
		case MoveName::Luster_Purge: return 70_bi;
		case MoveName::Mist_Ball: return 70_bi;
		case MoveName::Feather_Dance: return 0_bi;
		case MoveName::Teeter_Dance: return 0_bi;
		case MoveName::Blaze_Kick: return 85_bi;
		case MoveName::Mud_Sport: return 0_bi;
		case MoveName::Needle_Arm: return 60_bi;
		case MoveName::Slack_Off: return 0_bi;
		case MoveName::Hyper_Voice: return 90_bi;
		case MoveName::Poison_Fang: return 50_bi;
		case MoveName::Crush_Claw: return 75_bi;
		case MoveName::Blast_Burn: return 150_bi;
		case MoveName::Hydro_Cannon: return 150_bi;
		case MoveName::Meteor_Mash: return BOUNDED_CONDITIONAL(generation <= Generation::five, 100_bi, 90_bi);
		case MoveName::Astonish: return 30_bi;
		case MoveName::Weather_Ball: return 50_bi;
		case MoveName::Aromatherapy: return 0_bi;
		case MoveName::Fake_Tears: return 0_bi;
		case MoveName::Air_Cutter: return BOUNDED_CONDITIONAL(generation <= Generation::five, 55_bi, 60_bi);
		case MoveName::Overheat: return BOUNDED_CONDITIONAL(generation <= Generation::five, 140_bi, 130_bi);
		case MoveName::Odor_Sleuth: return 0_bi;
		case MoveName::Rock_Tomb: return BOUNDED_CONDITIONAL(generation <= Generation::five, 50_bi, 60_bi);
		case MoveName::Silver_Wind: return 60_bi;
		case MoveName::Metal_Sound: return 0_bi;
		case MoveName::Grass_Whistle: return 0_bi;
		case MoveName::Tickle: return 0_bi;
		case MoveName::Cosmic_Power: return 0_bi;
		case MoveName::Signal_Beam: return 75_bi;
		case MoveName::Shadow_Punch: return 60_bi;
		case MoveName::Extrasensory: return 80_bi;
		case MoveName::Sky_Uppercut: return 85_bi;
		case MoveName::Sand_Tomb: return BOUNDED_CONDITIONAL(generation <= Generation::four, 15_bi, 35_bi);
		case MoveName::Sheer_Cold: std::unreachable();
		case MoveName::Muddy_Water: return BOUNDED_CONDITIONAL(generation <= Generation::five, 95_bi, 90_bi);
		case MoveName::Bullet_Seed: return BOUNDED_CONDITIONAL(generation <= Generation::four, 10_bi, 25_bi);
		case MoveName::Aerial_Ace: return 60_bi;
		case MoveName::Icicle_Spear: return BOUNDED_CONDITIONAL(generation <= Generation::four, 10_bi, 25_bi);
		case MoveName::Iron_Defense: return 0_bi;
		case MoveName::Block: return 0_bi;
		case MoveName::Howl: return 0_bi;
		case MoveName::Dragon_Claw: return 80_bi;
		case MoveName::Frenzy_Plant: return 150_bi;
		case MoveName::Bulk_Up: return 0_bi;
		case MoveName::Bounce: return 85_bi;
		case MoveName::Mud_Shot: return 55_bi;
		case MoveName::Poison_Tail: return 50_bi;
		case MoveName::Covet: return BOUNDED_CONDITIONAL(generation <= Generation::four, 40_bi, 60_bi);
		case MoveName::Volt_Tackle: return 120_bi;
		case MoveName::Magical_Leaf: return 60_bi;
		case MoveName::Water_Sport: return 0_bi;
		case MoveName::Calm_Mind: return 0_bi;
		case MoveName::Leaf_Blade: return BOUNDED_CONDITIONAL(generation <= Generation::three, 70_bi, 90_bi);
		case MoveName::Dragon_Dance: return 0_bi;
		case MoveName::Rock_Blast: return 25_bi;
		case MoveName::Shock_Wave: return 60_bi;
		case MoveName::Water_Pulse: return 60_bi;
		case MoveName::Doom_Desire: return BOUNDED_CONDITIONAL(generation <= Generation::four, 120_bi, 140_bi);
		case MoveName::Psycho_Boost: return 140_bi;
		case MoveName::Roost: return 0_bi;
		case MoveName::Gravity: return 0_bi;
		case MoveName::Miracle_Eye: return 0_bi;
		case MoveName::Wake_Up_Slap: return BOUNDED_CONDITIONAL(generation <= Generation::five, 60_bi, 70_bi);
		case MoveName::Hammer_Arm: return 100_bi;
		case MoveName::Gyro_Ball: {
			auto const defender_speed = calculate_speed(defender_team, attacker.ability(), environment);
			auto const attacker_speed = calculate_speed(attacker_team, defender.ability(), environment);
			auto const uncapped_power = 25_bi * defender_speed / attacker_speed + 1_bi;
			return bounded::min(uncapped_power, 150_bi);
		}
		case MoveName::Healing_Wish: return 0_bi;
		case MoveName::Brine: return 65_bi;
		case MoveName::Natural_Gift: return berry_power(attacker.item(environment));
		case MoveName::Feint: return BOUNDED_CONDITIONAL(generation <= Generation::four, 50_bi, 30_bi);
		case MoveName::Pluck: return 60_bi;
		case MoveName::Tailwind: return 0_bi;
		case MoveName::Acupressure: return 0_bi;
		case MoveName::Metal_Burst: std::unreachable();
		case MoveName::U_turn: return 70_bi;
		case MoveName::Close_Combat: return 120_bi;
		case MoveName::Payback: return 50_bi;
		case MoveName::Assurance: return BOUNDED_CONDITIONAL(generation <= Generation::five, 50_bi, 60_bi);
		case MoveName::Embargo: return 0_bi;
		case MoveName::Fling: return fling_power(attacker.item(environment));
		case MoveName::Psycho_Shift: return 0_bi;
		case MoveName::Trump_Card:
			// Safe to dereference because we know Trump Card is not unlimited
			switch (executed.pp.remaining()->value()) {
				case 0: return 200_bi;
				case 1: return 80_bi;
				case 2: return 60_bi;
				case 3: return 50_bi;
				default: return 40_bi;
			}
		case MoveName::Heal_Block: return 0_bi;
		case MoveName::Power_Trick: return 0_bi;
		case MoveName::Gastro_Acid: return 0_bi;
		case MoveName::Lucky_Chant: return 0_bi;
		case MoveName::Me_First: return 0_bi;
		case MoveName::Copycat: return 0_bi;
		case MoveName::Power_Swap: return 0_bi;
		case MoveName::Guard_Swap: return 0_bi;
		case MoveName::Punishment: {
			auto is_positive = [](auto const value) { return value > 0_bi; };
			auto const uncapped_power = 60_bi + 20_bi * bounded::increase_min<0>(containers::sum(containers::transform(containers::filter(defender.stages(), is_positive), &Stage::value)));
			return bounded::min(uncapped_power, 200_bi);
		}
		case MoveName::Last_Resort: return BOUNDED_CONDITIONAL(generation <= Generation::four, 130_bi, 140_bi);
		case MoveName::Worry_Seed: return 0_bi;
		case MoveName::Sucker_Punch: return BOUNDED_CONDITIONAL(generation <= Generation::six, 80_bi, 70_bi);
		case MoveName::Toxic_Spikes: return 0_bi;
		case MoveName::Heart_Swap: return 0_bi;
		case MoveName::Aqua_Ring: return 0_bi;
		case MoveName::Magnet_Rise: return 0_bi;
		case MoveName::Flare_Blitz: return 120_bi;
		case MoveName::Force_Palm: return 60_bi;
		case MoveName::Aura_Sphere: return BOUNDED_CONDITIONAL(generation <= Generation::five, 90_bi, 80_bi);
		case MoveName::Rock_Polish: return 0_bi;
		case MoveName::Poison_Jab: return 80_bi;
		case MoveName::Dark_Pulse: return 80_bi;
		case MoveName::Night_Slash: return 70_bi;
		case MoveName::Aqua_Tail: return 90_bi;
		case MoveName::Seed_Bomb: return 80_bi;
		case MoveName::Air_Slash: return 75_bi;
		case MoveName::X_Scissor: return 80_bi;
		case MoveName::Bug_Buzz: return 90_bi;
		case MoveName::Dragon_Pulse: return BOUNDED_CONDITIONAL(generation <= Generation::five, 90_bi, 85_bi);
		case MoveName::Dragon_Rush: return 100_bi;
		case MoveName::Power_Gem: return BOUNDED_CONDITIONAL(generation <= Generation::five, 70_bi, 80_bi);
		case MoveName::Drain_Punch: return BOUNDED_CONDITIONAL(generation <= Generation::four, 60_bi, 75_bi);
		case MoveName::Vacuum_Wave: return 40_bi;
		case MoveName::Focus_Blast: return 120_bi;
		case MoveName::Energy_Ball: return BOUNDED_CONDITIONAL(generation <= Generation::five, 80_bi, 90_bi);
		case MoveName::Brave_Bird: return 120_bi;
		case MoveName::Earth_Power: return 90_bi;
		case MoveName::Switcheroo: return 0_bi;
		case MoveName::Giga_Impact: return 150_bi;
		case MoveName::Nasty_Plot: return 0_bi;
		case MoveName::Bullet_Punch: return 40_bi;
		case MoveName::Avalanche: return 60_bi;
		case MoveName::Ice_Shard: return 40_bi;
		case MoveName::Shadow_Claw: return 70_bi;
		case MoveName::Thunder_Fang: return 65_bi;
		case MoveName::Ice_Fang: return 65_bi;
		case MoveName::Fire_Fang: return 65_bi;
		case MoveName::Shadow_Sneak: return 40_bi;
		case MoveName::Mud_Bomb: return 65_bi;
		case MoveName::Psycho_Cut: return 70_bi;
		case MoveName::Zen_Headbutt: return 80_bi;
		case MoveName::Mirror_Shot: return 65_bi;
		case MoveName::Flash_Cannon: return 80_bi;
		case MoveName::Rock_Climb: return 90_bi;
		case MoveName::Defog: return 0_bi;
		case MoveName::Trick_Room: return 0_bi;
		case MoveName::Draco_Meteor: return BOUNDED_CONDITIONAL(generation <= Generation::five, 140_bi, 130_bi);
		case MoveName::Discharge: return 80_bi;
		case MoveName::Lava_Plume: return 80_bi;
		case MoveName::Leaf_Storm: return BOUNDED_CONDITIONAL(generation <= Generation::five, 140_bi, 130_bi);
		case MoveName::Power_Whip: return 120_bi;
		case MoveName::Rock_Wrecker: return 150_bi;
		case MoveName::Cross_Poison: return 70_bi;
		case MoveName::Gunk_Shot: return 120_bi;
		case MoveName::Iron_Head: return 80_bi;
		case MoveName::Magnet_Bomb: return 60_bi;
		case MoveName::Stone_Edge: return 100_bi;
		case MoveName::Captivate: return 0_bi;
		case MoveName::Stealth_Rock: return 0_bi;
		case MoveName::Chatter: return BOUNDED_CONDITIONAL(generation <= Generation::five, 60_bi, 65_bi);
		case MoveName::Judgment: return 100_bi;
		case MoveName::Bug_Bite: return 60_bi;
		case MoveName::Charge_Beam: return 50_bi;
		case MoveName::Wood_Hammer: return 120_bi;
		case MoveName::Aqua_Jet: return 40_bi;
		case MoveName::Attack_Order: return 90_bi;
		case MoveName::Defend_Order: return 0_bi;
		case MoveName::Heal_Order: return 0_bi;
		case MoveName::Head_Smash: return 150_bi;
		case MoveName::Double_Hit: return 35_bi;
		case MoveName::Roar_of_Time: return 150_bi;
		case MoveName::Spacial_Rend: return 100_bi;
		case MoveName::Lunar_Dance: return 0_bi;
		case MoveName::Crush_Grip:
		case MoveName::Wring_Out:
			return bounded::assume_in_range(120_bi * hp_ratio(defender) + 1_bi, 1_bi, 121_bi);
		case MoveName::Magma_Storm: return BOUNDED_CONDITIONAL(generation <= Generation::five, 120_bi, 100_bi);
		case MoveName::Dark_Void: return 0_bi;
		case MoveName::Seed_Flare: return 120_bi;
		case MoveName::Ominous_Wind: return 60_bi;
		case MoveName::Shadow_Force: return 120_bi;
		case MoveName::Hone_Claws: return 0_bi;
		case MoveName::Wide_Guard: return 0_bi;
		case MoveName::Guard_Split: return 0_bi;
		case MoveName::Power_Split: return 0_bi;
		case MoveName::Wonder_Room: return 0_bi;
		case MoveName::Psyshock: return 80_bi;
		case MoveName::Venoshock: return 65_bi;
		case MoveName::Autotomize: return 0_bi;
		case MoveName::Rage_Powder: return 0_bi;
		case MoveName::Telekinesis: return 0_bi;
		case MoveName::Magic_Room: return 0_bi;
		case MoveName::Smack_Down: return 50_bi;
		case MoveName::Storm_Throw: return BOUNDED_CONDITIONAL(generation <= Generation::five, 40_bi, 60_bi);
		case MoveName::Flame_Burst: return 70_bi;
		case MoveName::Sludge_Wave: return 95_bi;
		case MoveName::Quiver_Dance: return 0_bi;
		// TODO
		case MoveName::Heavy_Slam:
		case MoveName::Heat_Crash:
			return 1_bi;
		case MoveName::Synchronoise: return BOUNDED_CONDITIONAL(generation <= Generation::five, 70_bi, 120_bi);
		case MoveName::Electro_Ball: {
			auto const defender_speed = calculate_speed(defender_team, attacker.ability(), environment);
			auto const attacker_speed = calculate_speed(attacker_team, defender.ability(), environment);
			auto const quotient = attacker_speed / defender_speed;
			switch (quotient.value()) {
				case 0: return 40_bi;
				case 1: return 60_bi;
				case 2: return 80_bi;
				case 3: return 120_bi;
				default: return 150_bi;
			}
		}
		case MoveName::Soak: return 0_bi;
		case MoveName::Flame_Charge: return 50_bi;
		case MoveName::Coil: return 0_bi;
		case MoveName::Low_Sweep: return BOUNDED_CONDITIONAL(generation <= Generation::five, 60_bi, 65_bi);
		case MoveName::Acid_Spray: return 40_bi;
		case MoveName::Foul_Play: return 95_bi;
		case MoveName::Simple_Beam: return 0_bi;
		case MoveName::Entrainment: return 0_bi;
		case MoveName::After_You: return 0_bi;
		case MoveName::Round: return 60_bi;
		case MoveName::Echoed_Voice: return 40_bi;
		case MoveName::Chip_Away: return 70_bi;
		case MoveName::Clear_Smog: return 50_bi;
		case MoveName::Stored_Power: return 20_bi;
		case MoveName::Quick_Guard: return 0_bi;
		case MoveName::Ally_Switch: return 0_bi;
		case MoveName::Scald: return 80_bi;
		case MoveName::Shell_Smash: return 0_bi;
		case MoveName::Heal_Pulse: return 0_bi;
		case MoveName::Hex: return BOUNDED_CONDITIONAL(generation <= Generation::five, 50_bi, 65_bi);
		case MoveName::Sky_Drop: return 60_bi;
		case MoveName::Shift_Gear: return 0_bi;
		case MoveName::Circle_Throw: return 60_bi;
		case MoveName::Incinerate: return BOUNDED_CONDITIONAL(generation <= Generation::five, 30_bi, 60_bi);
		case MoveName::Quash: return 0_bi;
		case MoveName::Acrobatics: return 55_bi;
		case MoveName::Reflect_Type: return 0_bi;
		case MoveName::Retaliate: return 70_bi;
		case MoveName::Final_Gambit: std::unreachable();
		case MoveName::Bestow: return 0_bi;
		case MoveName::Inferno: return 100_bi;
		case MoveName::Water_Pledge: return BOUNDED_CONDITIONAL(generation <= Generation::five, 50_bi, 80_bi);
		case MoveName::Fire_Pledge: return BOUNDED_CONDITIONAL(generation <= Generation::five, 50_bi, 80_bi);
		case MoveName::Grass_Pledge: return BOUNDED_CONDITIONAL(generation <= Generation::five, 50_bi, 80_bi);
		case MoveName::Volt_Switch: return 70_bi;
		case MoveName::Struggle_Bug: return BOUNDED_CONDITIONAL(generation <= Generation::five, 30_bi, 50_bi);
		case MoveName::Bulldoze: return 60_bi;
		case MoveName::Frost_Breath: return BOUNDED_CONDITIONAL(generation <= Generation::five, 40_bi, 60_bi);
		case MoveName::Dragon_Tail: return 60_bi;
		case MoveName::Work_Up: return 0_bi;
		case MoveName::Electroweb: return 55_bi;
		case MoveName::Wild_Charge: return 90_bi;
		case MoveName::Drill_Run: return 80_bi;
		case MoveName::Dual_Chop: return 40_bi;
		case MoveName::Heart_Stamp: return 60_bi;
		case MoveName::Horn_Leech: return 75_bi;
		case MoveName::Sacred_Sword: return 90_bi;
		case MoveName::Razor_Shell: return 75_bi;
		case MoveName::Leaf_Tornado: return 65_bi;
		case MoveName::Steamroller: return 65_bi;
		case MoveName::Cotton_Guard: return 0_bi;
		case MoveName::Night_Daze: return 85_bi;
		case MoveName::Psystrike: return 100_bi;
		case MoveName::Tail_Slap: return 25_bi;
		case MoveName::Hurricane: return BOUNDED_CONDITIONAL(generation <= Generation::five, 120_bi, 110_bi);
		case MoveName::Head_Charge: return 120_bi;
		case MoveName::Gear_Grind: return 50_bi;
		case MoveName::Searing_Shot: return 100_bi;
		case MoveName::Techno_Blast: return BOUNDED_CONDITIONAL(generation <= Generation::five, 85_bi, 120_bi);
		case MoveName::Relic_Song: return 75_bi;
		case MoveName::Secret_Sword: return 85_bi;
		case MoveName::Glaciate: return 65_bi;
		case MoveName::Bolt_Strike: return 130_bi;
		case MoveName::Blue_Flare: return 130_bi;
		case MoveName::Fiery_Dance: return 80_bi;
		case MoveName::Freeze_Shock: return 140_bi;
		case MoveName::Ice_Burn: return 140_bi;
		case MoveName::Snarl: return 55_bi;
		case MoveName::Icicle_Crash: return 85_bi;
		case MoveName::V_create: return 180_bi;
		case MoveName::Fusion_Flare: return 100_bi;
		case MoveName::Fusion_Bolt: return 100_bi;
		case MoveName::Flying_Press: return BOUNDED_CONDITIONAL(generation <= Generation::six, 80_bi, 100_bi);
		case MoveName::Mat_Block: return 0_bi;
		case MoveName::Belch: return 120_bi;
		case MoveName::Rototiller: return 0_bi;
		case MoveName::Sticky_Web: return 0_bi;
		case MoveName::Fell_Stinger: return BOUNDED_CONDITIONAL(generation <= Generation::six, 30_bi, 50_bi);
		case MoveName::Phantom_Force: return 90_bi;
		case MoveName::Trick_or_Treat: return 0_bi;
		case MoveName::Noble_Roar: return 0_bi;
		case MoveName::Ion_Deluge: return 0_bi;
		case MoveName::Parabolic_Charge: return BOUNDED_CONDITIONAL(generation <= Generation::six, 50_bi, 65_bi);
		case MoveName::Forests_Curse: return 0_bi;
		case MoveName::Petal_Blizzard: return 90_bi;
		case MoveName::Freeze_Dry: return 70_bi;
		case MoveName::Disarming_Voice: return 40_bi;
		case MoveName::Parting_Shot: return 0_bi;
		case MoveName::Topsy_Turvy: return 0_bi;
		case MoveName::Draining_Kiss: return 50_bi;
		case MoveName::Crafty_Shield: return 0_bi;
		case MoveName::Flower_Shield: return 0_bi;
		case MoveName::Grassy_Terrain: return 0_bi;
		case MoveName::Misty_Terrain: return 0_bi;
		case MoveName::Electrify: return 0_bi;
		case MoveName::Play_Rough: return 90_bi;
		case MoveName::Fairy_Wind: return 40_bi;
		case MoveName::Moonblast: return 95_bi;
		case MoveName::Boomburst: return 140_bi;
		case MoveName::Fairy_Lock: return 0_bi;
		case MoveName::Kings_Shield: return 0_bi;
		case MoveName::Play_Nice: return 0_bi;
		case MoveName::Confide: return 0_bi;
		case MoveName::Diamond_Storm: return 100_bi;
		case MoveName::Steam_Eruption: return 110_bi;
		case MoveName::Hyperspace_Hole: return 80_bi;
		case MoveName::Water_Shuriken: return 15_bi;
		case MoveName::Mystical_Fire: return BOUNDED_CONDITIONAL(generation <= Generation::six, 65_bi, 75_bi);
		case MoveName::Spiky_Shield: return 0_bi;
		case MoveName::Aromatic_Mist: return 0_bi;
		case MoveName::Eerie_Impulse: return 0_bi;
		case MoveName::Venom_Drench: return 0_bi;
		case MoveName::Powder: return 0_bi;
		case MoveName::Geomancy: return 0_bi;
		case MoveName::Magnetic_Flux: return 0_bi;
		case MoveName::Happy_Hour: return 0_bi;
		case MoveName::Electric_Terrain: return 0_bi;
		case MoveName::Dazzling_Gleam: return 80_bi;
		case MoveName::Celebrate: return 0_bi;
		case MoveName::Hold_Hands: return 0_bi;
		case MoveName::Baby_Doll_Eyes: return 0_bi;
		case MoveName::Nuzzle: return 20_bi;
		case MoveName::Hold_Back: return 40_bi;
		case MoveName::Infestation: return 20_bi;
		case MoveName::Power_Up_Punch: return 40_bi;
		case MoveName::Oblivion_Wing: return 80_bi;
		case MoveName::Thousand_Arrows: return 90_bi;
		case MoveName::Thousand_Waves: return 90_bi;
		case MoveName::Lands_Wrath: return 90_bi;
		case MoveName::Light_of_Ruin: return 140_bi;
		case MoveName::Origin_Pulse: return 110_bi;
		case MoveName::Precipice_Blades: return 120_bi;
		case MoveName::Dragon_Ascent: return 120_bi;
		case MoveName::Hyperspace_Fury: return 100_bi;
		case MoveName::Breakneck_Blitz: return 0_bi;
		case MoveName::All_Out_Pummeling: return 0_bi;
		case MoveName::Supersonic_Skystrike: return 0_bi;
		case MoveName::Acid_Downpour: return 0_bi;
		case MoveName::Tectonic_Rage: return 0_bi;
		case MoveName::Continental_Crush: return 0_bi;
		case MoveName::Savage_Spin_Out: return 0_bi;
		case MoveName::Never_Ending_Nightmare: return 0_bi;
		case MoveName::Corkscrew_Crash: return 0_bi;
		case MoveName::Inferno_Overdrive: return 0_bi;
		case MoveName::Hydro_Vortex: return 0_bi;
		case MoveName::Bloom_Doom: return 0_bi;
		case MoveName::Gigavolt_Havoc: return 0_bi;
		case MoveName::Shattered_Psyche: return 0_bi;
		case MoveName::Subzero_Slammer: return 0_bi;
		case MoveName::Devastating_Drake: return 0_bi;
		case MoveName::Black_Hole_Eclipse: return 0_bi;
		case MoveName::Twinkle_Tackle: return 0_bi;
		case MoveName::Catastropika: return 210_bi;
		case MoveName::Shore_Up: return 0_bi;
		case MoveName::First_Impression: return 90_bi;
		case MoveName::Baneful_Bunker: return 0_bi;
		case MoveName::Spirit_Shackle: return 80_bi;
		case MoveName::Darkest_Lariat: return 85_bi;
		case MoveName::Sparkling_Aria: return 90_bi;
		case MoveName::Ice_Hammer: return 100_bi;
		case MoveName::Floral_Healing: return 0_bi;
		case MoveName::High_Horsepower: return 95_bi;
		case MoveName::Strength_Sap: return 0_bi;
		case MoveName::Solar_Blade: return 125_bi;
		case MoveName::Leafage: return 40_bi;
		case MoveName::Spotlight: return 0_bi;
		case MoveName::Toxic_Thread: return 0_bi;
		case MoveName::Laser_Focus: return 0_bi;
		case MoveName::Gear_Up: return 0_bi;
		case MoveName::Throat_Chop: return 80_bi;
		case MoveName::Pollen_Puff: return 90_bi;
		case MoveName::Anchor_Shot: return 80_bi;
		case MoveName::Psychic_Terrain: return 0_bi;
		case MoveName::Lunge: return 80_bi;
		case MoveName::Fire_Lash: return 80_bi;
		case MoveName::Power_Trip: return 20_bi;
		case MoveName::Burn_Up: return 130_bi;
		case MoveName::Speed_Swap: return 0_bi;
		case MoveName::Smart_Strike: return 70_bi;
		case MoveName::Purify: return 0_bi;
		case MoveName::Revelation_Dance: return 90_bi;
		case MoveName::Core_Enforcer: return 100_bi;
		case MoveName::Trop_Kick: return 70_bi;
		case MoveName::Instruct: return 0_bi;
		case MoveName::Beak_Blast: return 100_bi;
		case MoveName::Clanging_Scales: return 110_bi;
		case MoveName::Dragon_Hammer: return 90_bi;
		case MoveName::Brutal_Swing: return 60_bi;
		case MoveName::Aurora_Veil: return 0_bi;
		case MoveName::Sinister_Arrow_Raid: return 180_bi;
		case MoveName::Malicious_Moonsault: return 180_bi;
		case MoveName::Oceanic_Operetta: return 195_bi;
		case MoveName::Guardian_of_Alola: return 0_bi;
		case MoveName::Soul_Stealing_7_Star_Strike: return 195_bi;
		case MoveName::Stoked_Sparksurfer: return 175_bi;
		case MoveName::Pulverizing_Pancake: return 210_bi;
		case MoveName::Extreme_Evoboost: return 0_bi;
		case MoveName::Genesis_Supernova: return 185_bi;
		case MoveName::Shell_Trap: return 150_bi;
		case MoveName::Fleur_Cannon: return 130_bi;
		case MoveName::Psychic_Fangs: return 85_bi;
		case MoveName::Stomping_Tantrum: return 75_bi;
		case MoveName::Shadow_Bone: return 85_bi;
		case MoveName::Accelerock: return 40_bi;
		case MoveName::Liquidation: return 85_bi;
		case MoveName::Prismatic_Laser: return 160_bi;
		case MoveName::Spectral_Thief: return 90_bi;
		case MoveName::Sunsteel_Strike: return 100_bi;
		case MoveName::Moongeist_Beam: return 100_bi;
		case MoveName::Tearful_Look: return 0_bi;
		case MoveName::Zing_Zap: return 80_bi;
		case MoveName::Natures_Madness: return 0_bi;
		case MoveName::Multi_Attack: return BOUNDED_CONDITIONAL(generation <= Generation::seven, 90_bi, 120_bi);
		case MoveName::m10000000_Volt_Thunderbolt: return 195_bi;
		case MoveName::Mind_Blown: return 150_bi;
		case MoveName::Plasma_Fists: return 100_bi;
		case MoveName::Photon_Geyser: return 100_bi;
		case MoveName::Light_That_Burns_the_Sky: return 200_bi;
		case MoveName::Searing_Sunraze_Smash: return 200_bi;
		case MoveName::Menacing_Moonraze_Maelstrom: return 200_bi;
		case MoveName::Lets_Snuggle_Forever: return 190_bi;
		case MoveName::Splintered_Stormshards: return 190_bi;
		case MoveName::Clangorous_Soulblaze: return 185_bi;
		case MoveName::Double_Iron_Bash: return 60_bi;

		// Generation 8
		case MoveName::Max_Guard: return 0_bi;
		case MoveName::Dynamax_Cannon: return 100_bi;
		case MoveName::Snipe_Shot: return 80_bi;
		case MoveName::Jaw_Lock: return 80_bi;
		case MoveName::Stuff_Cheeks: return 0_bi;
		case MoveName::No_Retreat: return 0_bi;
		case MoveName::Tar_Shot: return 0_bi;
		case MoveName::Magic_Powder: return 0_bi;
		case MoveName::Dragon_Darts: return 50_bi;
		case MoveName::Teatime: return 0_bi;
		case MoveName::Octolock: return 0_bi;
		case MoveName::Bolt_Beak: return 85_bi;
		case MoveName::Fishious_Rend: return 85_bi;
		case MoveName::Court_Change: return 0_bi;
		case MoveName::Max_Flare: return 0_bi;
		case MoveName::Max_Flutterby: return 0_bi;
		case MoveName::Max_Lightning: return 0_bi;
		case MoveName::Max_Strike: return 0_bi;
		case MoveName::Max_Knuckle: return 0_bi;
		case MoveName::Max_Phantasm: return 0_bi;
		case MoveName::Max_Hailstorm: return 0_bi;
		case MoveName::Max_Ooze: return 0_bi;
		case MoveName::Max_Geyser: return 0_bi;
		case MoveName::Max_Airstream: return 0_bi;
		case MoveName::Max_Starfall: return 0_bi;
		case MoveName::Max_Wyrmwind: return 0_bi;
		case MoveName::Max_Mindstorm: return 0_bi;
		case MoveName::Max_Rockfall: return 0_bi;
		case MoveName::Max_Quake: return 0_bi;
		case MoveName::Max_Darkness: return 0_bi;
		case MoveName::Max_Overgrowth: return 0_bi;
		case MoveName::Max_Steelspike: return 0_bi;
		case MoveName::Clangorous_Soul: return 0_bi;
		case MoveName::Body_Press: return 80_bi;
		case MoveName::Decorate: return 0_bi;
		case MoveName::Drum_Beating: return 80_bi;
		case MoveName::Snap_Trap: return 35_bi;
		case MoveName::Pyro_Ball: return 120_bi;
		case MoveName::Behemoth_Blade: return 100_bi;
		case MoveName::Behemoth_Bash: return 100_bi;
		case MoveName::Aura_Wheel: return 110_bi;
		case MoveName::Breaking_Swipe: return 60_bi;
		case MoveName::Branch_Poke: return 40_bi;
		case MoveName::Overdrive: return 80_bi;
		case MoveName::Apple_Acid: return 80_bi;
		case MoveName::Grav_Apple: return 80_bi;
		case MoveName::Spirit_Break: return 75_bi;
		case MoveName::Strange_Steam: return 90_bi;
		case MoveName::Life_Dew: return 0_bi;
		case MoveName::Obstruct: return 0_bi;
		case MoveName::False_Surrender: return 80_bi;
		case MoveName::Meteor_Assault: return 150_bi;
		case MoveName::Eternabeam: return 160_bi;
		case MoveName::Steel_Beam: return 140_bi;
		case MoveName::Expanding_Force: return 80_bi;
		case MoveName::Steel_Roller: return 130_bi;
		case MoveName::Scale_Shot: return 25_bi;
		case MoveName::Meteor_Beam: return 120_bi;
		case MoveName::Shell_Side_Arm: return 90_bi;
		case MoveName::Misty_Explosion: return 100_bi;
		case MoveName::Grassy_Glide: return 70_bi;
		case MoveName::Rising_Voltage: return 70_bi;
		case MoveName::Terrain_Pulse: return 50_bi;
		case MoveName::Skitter_Smack: return 70_bi;
		case MoveName::Burning_Jealousy: return 70_bi;
		case MoveName::Lash_Out: return 75_bi;
		case MoveName::Poltergeist: return 110_bi;
		case MoveName::Corrosive_Gas: return 0_bi;
		case MoveName::Coaching: return 0_bi;
		case MoveName::Flip_Turn: return 60_bi;
		case MoveName::Triple_Axel: return 20_bi;
		case MoveName::Dual_Wingbeat: return 40_bi;
		case MoveName::Scorching_Sands: return 70_bi;
		case MoveName::Jungle_Healing: return 0_bi;
		case MoveName::Wicked_Blow: return 80_bi;
		case MoveName::Surging_Strikes: return 25_bi;
		case MoveName::Thunder_Cage: return 80_bi;
		case MoveName::Freezing_Glare: return 90_bi;
		case MoveName::Fiery_Wrath: return 90_bi;
		case MoveName::Thunderous_Kick: return 90_bi;
		case MoveName::Glacial_Lance: return 130_bi;
		case MoveName::Astral_Barrage: return 120_bi;
		case MoveName::Eerie_Spell: return 80_bi;
	}
}

} // namespace technicalmachine
