// Copyright David Stone 2020.
// Distributed under the Boost Software License, Version 1.0.
// (See accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt)

#include <tm/move/base_power.hpp>

#include <tm/move/moves.hpp>

#include <tm/known_team.hpp>
#include <tm/seen_team.hpp>
#include <tm/team.hpp>

#include <bounded/unreachable.hpp>

#include <containers/algorithms/accumulate.hpp>
#include <containers/algorithms/filter_iterator.hpp>

namespace technicalmachine {
namespace {
using namespace bounded::literal;

auto power_of_mass_based_moves(Species const species) -> bounded::integer<20, 120> {
	switch (species) {
		// Generation 1
		case Species::Bulbasaur: return 20_bi;
		case Species::Ivysaur: return 40_bi;
		case Species::Venusaur: return 100_bi;
		case Species::Charmander: return 20_bi;
		case Species::Charmeleon: return 40_bi;
		case Species::Charizard: return 80_bi;
		case Species::Squirtle: return 20_bi;
		case Species::Wartortle: return 40_bi;
		case Species::Blastoise: return 80_bi;
		case Species::Caterpie: return 20_bi;
		case Species::Metapod: return 20_bi;
		case Species::Butterfree: return 60_bi;
		case Species::Weedle: return 20_bi;
		case Species::Kakuna: return 40_bi;
		case Species::Beedrill: return 60_bi;
		case Species::Pidgey: return 20_bi;
		case Species::Pidgeotto: return 60_bi;
		case Species::Pidgeot: return 60_bi;
		case Species::Rattata: return 20_bi;
		case Species::Raticate: return 40_bi;
		case Species::Spearow: return 20_bi;
		case Species::Fearow: return 60_bi;
		case Species::Ekans: return 20_bi;
		case Species::Arbok: return 80_bi;
		case Species::Pikachu: return 20_bi;
		case Species::Raichu: return 60_bi;
		case Species::Sandshrew: return 40_bi;
		case Species::Sandslash: return 60_bi;
		case Species::Nidoran_F: return 20_bi;
		case Species::Nidorina: return 40_bi;
		case Species::Nidoqueen: return 80_bi;
		case Species::Nidoran_M: return 20_bi;
		case Species::Nidorino: return 40_bi;
		case Species::Nidoking: return 80_bi;
		case Species::Clefairy: return 20_bi;
		case Species::Clefable: return 60_bi;
		case Species::Vulpix: return 20_bi;
		case Species::Ninetales: return 40_bi;
		case Species::Jigglypuff: return 20_bi;
		case Species::Wigglytuff: return 40_bi;
		case Species::Zubat: return 20_bi;
		case Species::Golbat: return 80_bi;
		case Species::Oddish: return 20_bi;
		case Species::Gloom: return 20_bi;
		case Species::Vileplume: return 40_bi;
		case Species::Paras: return 20_bi;
		case Species::Parasect: return 60_bi;
		case Species::Venonat: return 60_bi;
		case Species::Venomoth: return 40_bi;
		case Species::Diglett: return 20_bi;
		case Species::Dugtrio: return 60_bi;
		case Species::Meowth: return 20_bi;
		case Species::Persian: return 60_bi;
		case Species::Psyduck: return 40_bi;
		case Species::Golduck: return 80_bi;
		case Species::Mankey: return 60_bi;
		case Species::Primeape: return 60_bi;
		case Species::Growlithe: return 40_bi;
		case Species::Arcanine: return 100_bi;
		case Species::Poliwag: return 40_bi;
		case Species::Poliwhirl: return 40_bi;
		case Species::Poliwrath: return 80_bi;
		case Species::Abra: return 40_bi;
		case Species::Kadabra: return 80_bi;
		case Species::Alakazam: return 60_bi;
		case Species::Machop: return 40_bi;
		case Species::Machoke: return 80_bi;
		case Species::Machamp: return 100_bi;
		case Species::Bellsprout: return 20_bi;
		case Species::Weepinbell: return 20_bi;
		case Species::Victreebel: return 40_bi;
		case Species::Tentacool: return 60_bi;
		case Species::Tentacruel: return 80_bi;
		case Species::Geodude: return 40_bi;
		case Species::Graveler: return 100_bi;
		case Species::Golem: return 120_bi;
		case Species::Ponyta: return 60_bi;
		case Species::Rapidash: return 80_bi;
		case Species::Slowpoke: return 60_bi;
		case Species::Slowbro: return 80_bi;
		case Species::Magnemite: return 20_bi;
		case Species::Magneton: return 80_bi;
		case Species::Farfetchd: return 40_bi;
		case Species::Doduo: return 60_bi;
		case Species::Dodrio: return 80_bi;
		case Species::Seel: return 80_bi;
		case Species::Dewgong: return 100_bi;
		case Species::Grimer: return 60_bi;
		case Species::Muk: return 60_bi;
		case Species::Shellder: return 20_bi;
		case Species::Cloyster: return 100_bi;
		case Species::Gastly: return 20_bi;
		case Species::Haunter: return 20_bi;
		case Species::Gengar: return 60_bi;
		case Species::Onix: return 120_bi;
		case Species::Drowzee: return 60_bi;
		case Species::Hypno: return 80_bi;
		case Species::Krabby: return 20_bi;
		case Species::Kingler: return 80_bi;
		case Species::Voltorb: return 40_bi;
		case Species::Electrode: return 80_bi;
		case Species::Exeggcute: return 20_bi;
		case Species::Exeggutor: return 100_bi;
		case Species::Cubone: return 20_bi;
		case Species::Marowak: return 60_bi;
		case Species::Hitmonlee: return 60_bi;
		case Species::Hitmonchan: return 80_bi;
		case Species::Lickitung: return 80_bi;
		case Species::Koffing: return 20_bi;
		case Species::Weezing: return 20_bi;
		case Species::Rhyhorn: return 100_bi;
		case Species::Rhydon: return 100_bi;
		case Species::Chansey: return 60_bi;
		case Species::Tangela: return 60_bi;
		case Species::Kangaskhan: return 80_bi;
		case Species::Horsea: return 20_bi;
		case Species::Seadra: return 60_bi;
		case Species::Goldeen: return 40_bi;
		case Species::Seaking: return 60_bi;
		case Species::Staryu: return 60_bi;
		case Species::Starmie: return 80_bi;
		case Species::Mr_Mime: return 80_bi;
		case Species::Scyther: return 80_bi;
		case Species::Jynx: return 60_bi;
		case Species::Electabuzz: return 60_bi;
		case Species::Magmar: return 60_bi;
		case Species::Pinsir: return 80_bi;
		case Species::Tauros: return 80_bi;
		case Species::Magikarp: return 40_bi;
		case Species::Gyarados: return 120_bi;
		case Species::Lapras: return 120_bi;
		case Species::Ditto: return 20_bi;
		case Species::Eevee: return 20_bi;
		case Species::Vaporeon: return 60_bi;
		case Species::Jolteon: return 40_bi;
		case Species::Flareon: return 60_bi;
		case Species::Porygon: return 60_bi;
		case Species::Omanyte: return 20_bi;
		case Species::Omastar: return 60_bi;
		case Species::Kabuto: return 40_bi;
		case Species::Kabutops: return 60_bi;
		case Species::Aerodactyl: return 80_bi;
		case Species::Snorlax: return 120_bi;
		case Species::Articuno: return 80_bi;
		case Species::Zapdos: return 80_bi;
		case Species::Moltres: return 80_bi;
		case Species::Dratini: return 20_bi;
		case Species::Dragonair: return 40_bi;
		case Species::Dragonite: return 120_bi;
		case Species::Mewtwo: return 100_bi;
		case Species::Mew: return 20_bi;

		// Generation 2
		case Species::Chikorita: return 20_bi;
		case Species::Bayleef: return 40_bi;
		case Species::Meganium: return 100_bi;
		case Species::Cyndaquil: return 20_bi;
		case Species::Quilava: return 40_bi;
		case Species::Typhlosion: return 80_bi;
		case Species::Totodile: return 20_bi;
		case Species::Croconaw: return 60_bi;
		case Species::Feraligatr: return 80_bi;
		case Species::Sentret: return 20_bi;
		case Species::Furret: return 60_bi;
		case Species::Hoothoot: return 40_bi;
		case Species::Noctowl: return 60_bi;
		case Species::Ledyba: return 40_bi;
		case Species::Ledian: return 60_bi;
		case Species::Spinarak: return 20_bi;
		case Species::Ariados: return 60_bi;
		case Species::Crobat: return 80_bi;
		case Species::Chinchou: return 40_bi;
		case Species::Lanturn: return 40_bi;
		case Species::Pichu: return 20_bi;
		case Species::Cleffa: return 20_bi;
		case Species::Igglybuff: return 20_bi;
		case Species::Togepi: return 20_bi;
		case Species::Togetic: return 20_bi;
		case Species::Natu: return 20_bi;
		case Species::Xatu: return 40_bi;
		case Species::Mareep: return 20_bi;
		case Species::Flaaffy: return 40_bi;
		case Species::Ampharos: return 80_bi;
		case Species::Bellossom: return 20_bi;
		case Species::Marill: return 20_bi;
		case Species::Azumarill: return 60_bi;
		case Species::Sudowoodo: return 60_bi;
		case Species::Politoed: return 60_bi;
		case Species::Hoppip: return 20_bi;
		case Species::Skiploom: return 20_bi;
		case Species::Jumpluff: return 20_bi;
		case Species::Aipom: return 40_bi;
		case Species::Sunkern: return 20_bi;
		case Species::Sunflora: return 20_bi;
		case Species::Yanma: return 60_bi;
		case Species::Wooper: return 20_bi;
		case Species::Quagsire: return 80_bi;
		case Species::Espeon: return 60_bi;
		case Species::Umbreon: return 60_bi;
		case Species::Murkrow: return 20_bi;
		case Species::Slowking: return 80_bi;
		case Species::Misdreavus: return 20_bi;
		case Species::Unown: return 20_bi;
		case Species::Wobbuffet: return 60_bi;
		case Species::Girafarig: return 60_bi;
		case Species::Pineco: return 20_bi;
		case Species::Forretress: return 100_bi;
		case Species::Dunsparce: return 40_bi;
		case Species::Gligar: return 80_bi;
		case Species::Steelix: return 120_bi;
		case Species::Snubbull: return 20_bi;
		case Species::Granbull: return 60_bi;
		case Species::Qwilfish: return 20_bi;
		case Species::Scizor: return 100_bi;
		case Species::Shuckle: return 40_bi;
		case Species::Heracross: return 80_bi;
		case Species::Sneasel: return 60_bi;
		case Species::Teddiursa: return 20_bi;
		case Species::Ursaring: return 100_bi;
		case Species::Slugma: return 60_bi;
		case Species::Magcargo: return 80_bi;
		case Species::Swinub: return 20_bi;
		case Species::Piloswine: return 80_bi;
		case Species::Corsola: return 20_bi;
		case Species::Remoraid: return 40_bi;
		case Species::Octillery: return 60_bi;
		case Species::Delibird: return 40_bi;
		case Species::Mantine: return 120_bi;
		case Species::Skarmory: return 80_bi;
		case Species::Houndour: return 40_bi;
		case Species::Houndoom: return 60_bi;
		case Species::Kingdra: return 100_bi;
		case Species::Phanpy: return 60_bi;
		case Species::Donphan: return 100_bi;
		case Species::Porygon2: return 60_bi;
		case Species::Stantler: return 80_bi;
		case Species::Smeargle: return 80_bi;
		case Species::Tyrogue: return 40_bi;
		case Species::Hitmontop: return 60_bi;
		case Species::Smoochum: return 20_bi;
		case Species::Elekid: return 40_bi;
		case Species::Magby: return 40_bi;
		case Species::Miltank: return 80_bi;
		case Species::Blissey: return 60_bi;
		case Species::Raikou: return 100_bi;
		case Species::Entei: return 100_bi;
		case Species::Suicune: return 100_bi;
		case Species::Larvitar: return 80_bi;
		case Species::Pupitar: return 100_bi;
		case Species::Tyranitar: return 120_bi;
		case Species::Lugia: return 120_bi;
		case Species::Ho_Oh: return 100_bi;
		case Species::Celebi: return 20_bi;

		// Generation 3
		case Species::Treecko: return 20_bi;
		case Species::Grovyle: return 40_bi;
		case Species::Sceptile: return 80_bi;
		case Species::Torchic: return 20_bi;
		case Species::Combusken: return 40_bi;
		case Species::Blaziken: return 80_bi;
		case Species::Mudkip: return 20_bi;
		case Species::Marshtomp: return 60_bi;
		case Species::Swampert: return 80_bi;
		case Species::Poochyena: return 40_bi;
		case Species::Mightyena: return 60_bi;
		case Species::Zigzagoon: return 40_bi;
		case Species::Linoone: return 60_bi;
		case Species::Wurmple: return 20_bi;
		case Species::Silcoon: return 40_bi;
		case Species::Beautifly: return 60_bi;
		case Species::Cascoon: return 40_bi;
		case Species::Dustox: return 60_bi;
		case Species::Lotad: return 20_bi;
		case Species::Lombre: return 60_bi;
		case Species::Ludicolo: return 80_bi;
		case Species::Seedot: return 20_bi;
		case Species::Nuzleaf: return 60_bi;
		case Species::Shiftry: return 80_bi;
		case Species::Taillow: return 20_bi;
		case Species::Swellow: return 40_bi;
		case Species::Wingull: return 20_bi;
		case Species::Pelipper: return 60_bi;
		case Species::Ralts: return 20_bi;
		case Species::Kirlia: return 40_bi;
		case Species::Gardevoir: return 60_bi;
		case Species::Surskit: return 20_bi;
		case Species::Masquerain: return 20_bi;
		case Species::Shroomish: return 20_bi;
		case Species::Breloom: return 60_bi;
		case Species::Slakoth: return 40_bi;
		case Species::Vigoroth: return 60_bi;
		case Species::Slaking: return 100_bi;
		case Species::Nincada: return 20_bi;
		case Species::Ninjask: return 40_bi;
		case Species::Shedinja: return 20_bi;
		case Species::Whismur: return 40_bi;
		case Species::Loudred: return 60_bi;
		case Species::Exploud: return 80_bi;
		case Species::Makuhita: return 80_bi;
		case Species::Hariyama: return 120_bi;
		case Species::Azurill: return 20_bi;
		case Species::Nosepass: return 80_bi;
		case Species::Skitty: return 40_bi;
		case Species::Delcatty: return 60_bi;
		case Species::Sableye: return 40_bi;
		case Species::Mawile: return 40_bi;
		case Species::Aron: return 80_bi;
		case Species::Lairon: return 100_bi;
		case Species::Aggron: return 120_bi;
		case Species::Meditite: return 40_bi;
		case Species::Medicham: return 60_bi;
		case Species::Electrike: return 40_bi;
		case Species::Manectric: return 60_bi;
		case Species::Plusle: return 20_bi;
		case Species::Minun: return 20_bi;
		case Species::Volbeat: return 40_bi;
		case Species::Illumise: return 40_bi;
		case Species::Roselia: return 20_bi;
		case Species::Gulpin: return 40_bi;
		case Species::Swalot: return 80_bi;
		case Species::Carvanha: return 40_bi;
		case Species::Sharpedo: return 80_bi;
		case Species::Wailmer: return 100_bi;
		case Species::Wailord: return 120_bi;
		case Species::Numel: return 40_bi;
		case Species::Camerupt: return 120_bi;
		case Species::Torkoal: return 80_bi;
		case Species::Spoink: return 60_bi;
		case Species::Grumpig: return 80_bi;
		case Species::Spinda: return 20_bi;
		case Species::Trapinch: return 40_bi;
		case Species::Vibrava: return 40_bi;
		case Species::Flygon: return 80_bi;
		case Species::Cacnea: return 80_bi;
		case Species::Cacturne: return 80_bi;
		case Species::Swablu: return 20_bi;
		case Species::Altaria: return 40_bi;
		case Species::Zangoose: return 60_bi;
		case Species::Seviper: return 80_bi;
		case Species::Lunatone: return 100_bi;
		case Species::Solrock: return 100_bi;
		case Species::Barboach: return 20_bi;
		case Species::Whiscash: return 40_bi;
		case Species::Corphish: return 40_bi;
		case Species::Crawdaunt: return 60_bi;
		case Species::Baltoy: return 40_bi;
		case Species::Claydol: return 100_bi;
		case Species::Lileep: return 40_bi;
		case Species::Cradily: return 80_bi;
		case Species::Anorith: return 40_bi;
		case Species::Armaldo: return 80_bi;
		case Species::Feebas: return 20_bi;
		case Species::Milotic: return 100_bi;
		case Species::Castform: return 20_bi;
		case Species::Kecleon: return 40_bi;
		case Species::Shuppet: return 20_bi;
		case Species::Banette: return 40_bi;
		case Species::Duskull: return 40_bi;
		case Species::Dusclops: return 60_bi;
		case Species::Tropius: return 100_bi;
		case Species::Chimecho: return 20_bi;
		case Species::Absol: return 60_bi;
		case Species::Wynaut: return 40_bi;
		case Species::Snorunt: return 40_bi;
		case Species::Glalie: return 120_bi;
		case Species::Spheal: return 60_bi;
		case Species::Sealeo: return 80_bi;
		case Species::Walrein: return 100_bi;
		case Species::Clamperl: return 80_bi;
		case Species::Huntail: return 60_bi;
		case Species::Gorebyss: return 40_bi;
		case Species::Relicanth: return 40_bi;
		case Species::Luvdisc: return 20_bi;
		case Species::Bagon: return 60_bi;
		case Species::Shelgon: return 100_bi;
		case Species::Salamence: return 100_bi;
		case Species::Beldum: return 80_bi;
		case Species::Metang: return 120_bi;
		case Species::Metagross: return 120_bi;
		case Species::Regirock: return 120_bi;
		case Species::Regice: return 100_bi;
		case Species::Registeel: return 120_bi;
		case Species::Latias: return 60_bi;
		case Species::Latios: return 80_bi;
		case Species::Kyogre: return 120_bi;
		case Species::Groudon: return 120_bi;
		case Species::Rayquaza: return 120_bi;
		case Species::Jirachi: return 20_bi;
		case Species::Deoxys_Normal: return 80_bi;
		case Species::Deoxys_Attack: return 80_bi;
		case Species::Deoxys_Defense: return 80_bi;
		case Species::Deoxys_Speed: return 80_bi;

		// Generation 4
		case Species::Turtwig: return 40_bi;
		case Species::Grotle: return 80_bi;
		case Species::Torterra: return 120_bi;
		case Species::Chimchar: return 20_bi;
		case Species::Monferno: return 40_bi;
		case Species::Infernape: return 80_bi;
		case Species::Piplup: return 20_bi;
		case Species::Prinplup: return 40_bi;
		case Species::Empoleon: return 80_bi;
		case Species::Starly: return 20_bi;
		case Species::Staravia: return 40_bi;
		case Species::Staraptor: return 40_bi;
		case Species::Bidoof: return 40_bi;
		case Species::Bibarel: return 60_bi;
		case Species::Kricketot: return 20_bi;
		case Species::Kricketune: return 60_bi;
		case Species::Shinx: return 20_bi;
		case Species::Luxio: return 60_bi;
		case Species::Luxray: return 60_bi;
		case Species::Budew: return 20_bi;
		case Species::Roserade: return 40_bi;
		case Species::Cranidos: return 60_bi;
		case Species::Rampardos: return 100_bi;
		case Species::Shieldon: return 80_bi;
		case Species::Bastiodon: return 100_bi;
		case Species::Burmy: return 20_bi;
		case Species::Wormadam_Plant: return 20_bi;
		case Species::Wormadam_Sandy: return 20_bi;
		case Species::Wormadam_Trash: return 20_bi;
		case Species::Mothim: return 40_bi;
		case Species::Combee: return 20_bi;
		case Species::Vespiquen: return 60_bi;
		case Species::Pachirisu: return 20_bi;
		case Species::Buizel: return 60_bi;
		case Species::Floatzel: return 60_bi;
		case Species::Cherubi: return 20_bi;
		case Species::Cherrim: return 20_bi;
		case Species::Shellos: return 20_bi;
		case Species::Gastrodon: return 60_bi;
		case Species::Ambipom: return 40_bi;
		case Species::Drifloon: return 20_bi;
		case Species::Drifblim: return 40_bi;
		case Species::Buneary: return 20_bi;
		case Species::Lopunny: return 60_bi;
		case Species::Mismagius: return 20_bi;
		case Species::Honchkrow: return 60_bi;
		case Species::Glameow: return 20_bi;
		case Species::Purugly: return 60_bi;
		case Species::Chingling: return 20_bi;
		case Species::Stunky: return 40_bi;
		case Species::Skuntank: return 60_bi;
		case Species::Bronzor: return 80_bi;
		case Species::Bronzong: return 100_bi;
		case Species::Bonsly: return 40_bi;
		case Species::Mime_Jr: return 40_bi;
		case Species::Happiny: return 40_bi;
		case Species::Chatot: return 20_bi;
		case Species::Spiritomb: return 100_bi;
		case Species::Gible: return 40_bi;
		case Species::Gabite: return 80_bi;
		case Species::Garchomp: return 80_bi;
		case Species::Munchlax: return 100_bi;
		case Species::Riolu: return 40_bi;
		case Species::Lucario: return 80_bi;
		case Species::Hippopotas: return 60_bi;
		case Species::Hippowdon: return 120_bi;
		case Species::Skorupi: return 40_bi;
		case Species::Drapion: return 80_bi;
		case Species::Croagunk: return 40_bi;
		case Species::Toxicroak: return 60_bi;
		case Species::Carnivine: return 60_bi;
		case Species::Finneon: return 20_bi;
		case Species::Lumineon: return 40_bi;
		case Species::Mantyke: return 80_bi;
		case Species::Snover: return 80_bi;
		case Species::Abomasnow: return 100_bi;
		case Species::Weavile: return 60_bi;
		case Species::Magnezone: return 100_bi;
		case Species::Lickilicky: return 100_bi;
		case Species::Rhyperior: return 120_bi;
		case Species::Tangrowth: return 100_bi;
		case Species::Electivire: return 100_bi;
		case Species::Magmortar: return 80_bi;
		case Species::Togekiss: return 60_bi;
		case Species::Yanmega: return 80_bi;
		case Species::Leafeon: return 60_bi;
		case Species::Glaceon: return 60_bi;
		case Species::Gliscor: return 60_bi;
		case Species::Mamoswine: return 120_bi;
		case Species::Porygon_Z: return 60_bi;
		case Species::Gallade: return 80_bi;
		case Species::Probopass: return 120_bi;
		case Species::Dusknoir: return 100_bi;
		case Species::Froslass: return 60_bi;
		case Species::Rotom: return 20_bi;
		case Species::Rotom_Heat: return 20_bi;
		case Species::Rotom_Wash: return 20_bi;
		case Species::Rotom_Frost: return 20_bi;
		case Species::Rotom_Fan: return 20_bi;
		case Species::Rotom_Mow: return 20_bi;
		case Species::Uxie: return 20_bi;
		case Species::Mesprit: return 20_bi;
		case Species::Azelf: return 20_bi;
		case Species::Dialga: return 120_bi;
		case Species::Palkia: return 120_bi;
		case Species::Heatran: return 120_bi;
		case Species::Regigigas: return 120_bi;
		case Species::Giratina_Altered: return 120_bi;
		case Species::Giratina_Origin: return 120_bi;
		case Species::Cresselia: return 80_bi;
		case Species::Phione: return 20_bi;
		case Species::Manaphy: return 20_bi;
		case Species::Darkrai: return 80_bi;
		case Species::Shaymin_Land: return 20_bi;
		case Species::Shaymin_Sky: return 20_bi;
		case Species::Arceus: return 120_bi;

		// Generation 5
		case Species::Victini: return 20_bi;
		case Species::Snivy: return 20_bi;
		case Species::Servine: return 40_bi;
		case Species::Serperior: return 80_bi;
		case Species::Tepig: return 20_bi;
		case Species::Pignite: return 80_bi;
		case Species::Emboar: return 100_bi;
		case Species::Oshawott: return 20_bi;
		case Species::Dewott: return 40_bi;
		case Species::Samurott: return 80_bi;
		case Species::Patrat: return 40_bi;
		case Species::Watchog: return 60_bi;
		case Species::Lillipup: return 20_bi;
		case Species::Herdier: return 40_bi;
		case Species::Stoutland: return 80_bi;
		case Species::Purrloin: return 40_bi;
		case Species::Liepard: return 60_bi;
		case Species::Pansage: return 40_bi;
		case Species::Simisage: return 60_bi;
		case Species::Pansear: return 40_bi;
		case Species::Simisear: return 60_bi;
		case Species::Panpour: return 40_bi;
		case Species::Simipour: return 60_bi;
		case Species::Munna: return 40_bi;
		case Species::Musharna: return 80_bi;
		case Species::Pidove: return 20_bi;
		case Species::Tranquill: return 40_bi;
		case Species::Unfezant: return 60_bi;
		case Species::Blitzle: return 60_bi;
		case Species::Zebstrika: return 80_bi;
		case Species::Roggenrola: return 40_bi;
		case Species::Boldore: return 100_bi;
		case Species::Gigalith: return 120_bi;
		case Species::Woobat: return 20_bi;
		case Species::Swoobat: return 40_bi;
		case Species::Drilbur: return 20_bi;
		case Species::Excadrill: return 60_bi;
		case Species::Audino: return 60_bi;
		case Species::Timburr: return 40_bi;
		case Species::Gurdurr: return 60_bi;
		case Species::Conkeldurr: return 80_bi;
		case Species::Tympole: return 20_bi;
		case Species::Palpitoad: return 40_bi;
		case Species::Seismitoad: return 80_bi;
		case Species::Throh: return 80_bi;
		case Species::Sawk: return 80_bi;
		case Species::Sewaddle: return 20_bi;
		case Species::Swadloon: return 20_bi;
		case Species::Leavanny: return 40_bi;
		case Species::Venipede: return 20_bi;
		case Species::Whirlipede: return 80_bi;
		case Species::Scolipede: return 120_bi;
		case Species::Cottonee: return 20_bi;
		case Species::Whimsicott: return 20_bi;
		case Species::Petilil: return 20_bi;
		case Species::Lilligant: return 40_bi;
		case Species::Basculin: return 40_bi;
		case Species::Sandile: return 40_bi;
		case Species::Krokorok: return 60_bi;
		case Species::Krookodile: return 80_bi;
		case Species::Darumaka: return 60_bi;
		case Species::Darmanitan: return 80_bi;
		case Species::Maractus: return 60_bi;
		case Species::Dwebble: return 40_bi;
		case Species::Crustle: return 120_bi;
		case Species::Scraggy: return 40_bi;
		case Species::Scrafty: return 60_bi;
		case Species::Sigilyph: return 40_bi;
		case Species::Yamask: return 20_bi;
		case Species::Cofagrigus: return 80_bi;
		case Species::Tirtouga: return 40_bi;
		case Species::Carracosta: return 80_bi;
		case Species::Archen: return 20_bi;
		case Species::Archeops: return 60_bi;
		case Species::Trubbish: return 60_bi;
		case Species::Garbodor: return 100_bi;
		case Species::Zorua: return 40_bi;
		case Species::Zoroark: return 80_bi;
		case Species::Minccino: return 20_bi;
		case Species::Cinccino: return 20_bi;
		case Species::Gothita: return 20_bi;
		case Species::Gothorita: return 40_bi;
		case Species::Gothitelle: return 60_bi;
		case Species::Solosis: return 20_bi;
		case Species::Duosion: return 20_bi;
		case Species::Reuniclus: return 40_bi;
		case Species::Ducklett: return 20_bi;
		case Species::Swanna: return 40_bi;
		case Species::Vanillite: return 20_bi;
		case Species::Vanillish: return 60_bi;
		case Species::Vanilluxe: return 80_bi;
		case Species::Deerling: return 40_bi;
		case Species::Sawsbuck: return 80_bi;
		case Species::Emolga: return 20_bi;
		case Species::Karrablast: return 20_bi;
		case Species::Escavalier: return 60_bi;
		case Species::Foongus: return 20_bi;
		case Species::Amoonguss: return 40_bi;
		case Species::Frillish: return 60_bi;
		case Species::Jellicent: return 100_bi;
		case Species::Alomomola: return 60_bi;
		case Species::Joltik: return 20_bi;
		case Species::Galvantula: return 40_bi;
		case Species::Ferroseed: return 40_bi;
		case Species::Ferrothorn: return 100_bi;
		case Species::Klink: return 40_bi;
		case Species::Klang: return 80_bi;
		case Species::Klinklang: return 80_bi;
		case Species::Tynamo: return 20_bi;
		case Species::Eelektrik: return 40_bi;
		case Species::Eelektross: return 80_bi;
		case Species::Elgyem: return 20_bi;
		case Species::Beheeyem: return 60_bi;
		case Species::Litwick: return 20_bi;
		case Species::Lampent: return 40_bi;
		case Species::Chandelure: return 60_bi;
		case Species::Axew: return 40_bi;
		case Species::Fraxure: return 60_bi;
		case Species::Haxorus: return 100_bi;
		case Species::Cubchoo: return 20_bi;
		case Species::Beartic: return 120_bi;
		case Species::Cryogonal: return 100_bi;
		case Species::Shelmet: return 20_bi;
		case Species::Accelgor: return 60_bi;
		case Species::Stunfisk: return 40_bi;
		case Species::Mienfoo: return 40_bi;
		case Species::Mienshao: return 60_bi;
		case Species::Druddigon: return 100_bi;
		case Species::Golett: return 80_bi;
		case Species::Golurk: return 120_bi;
		case Species::Pawniard: return 40_bi;
		case Species::Bisharp: return 80_bi;
		case Species::Bouffalant: return 80_bi;
		case Species::Rufflet: return 40_bi;
		case Species::Braviary: return 60_bi;
		case Species::Vullaby: return 20_bi;
		case Species::Mandibuzz: return 60_bi;
		case Species::Heatmor: return 80_bi;
		case Species::Durant: return 60_bi;
		case Species::Deino: return 40_bi;
		case Species::Zweilous: return 80_bi;
		case Species::Hydreigon: return 100_bi;
		case Species::Larvesta: return 60_bi;
		case Species::Volcarona: return 60_bi;
		case Species::Cobalion: return 120_bi;
		case Species::Terrakion: return 120_bi;
		case Species::Virizion: return 120_bi;
		case Species::Tornadus_Incarnate: return 80_bi;
		case Species::Tornadus_Therian: return 80_bi;
		case Species::Thundurus_Incarnate: return 80_bi;
		case Species::Thundurus_Therian: return 80_bi;
		case Species::Reshiram: return 120_bi;
		case Species::Zekrom: return 120_bi;
		case Species::Landorus_Incarnate: return 80_bi;
		case Species::Landorus_Therian: return 80_bi;
		case Species::Kyurem: return 120_bi;
		case Species::Kyurem_Black: return 120_bi;
		case Species::Kyurem_White: return 120_bi;
		case Species::Keldeo: return 60_bi;
		case Species::Meloetta: return 20_bi;
		case Species::Genesect: return 80_bi;

		// Generation 6
		case Species::Chespin: return 20_bi;
		case Species::Quilladin: return 60_bi;
		case Species::Chesnaught: return 80_bi;
		case Species::Fennekin: return 20_bi;
		case Species::Braixen: return 40_bi;
		case Species::Delphox: return 60_bi;
		case Species::Froakie: return 20_bi;
		case Species::Frogadier: return 40_bi;
		case Species::Greninja: return 60_bi;
		case Species::Bunnelby: return 20_bi;
		case Species::Diggersby: return 60_bi;
		case Species::Fletchling: return 20_bi;
		case Species::Fletchinder: return 40_bi;
		case Species::Talonflame: return 40_bi;
		case Species::Scatterbug: return 20_bi;
		case Species::Spewpa: return 20_bi;
		case Species::Vivillon: return 40_bi;
		case Species::Litleo: return 40_bi;
		case Species::Pyroar: return 80_bi;
		case Species::Flabebe: return 20_bi;
		case Species::Floette: return 20_bi;
		case Species::Florges: return 40_bi;
		case Species::Skiddo: return 60_bi;
		case Species::Gogoat: return 80_bi;
		case Species::Pancham: return 20_bi;
		case Species::Pangoro: return 100_bi;
		case Species::Furfrou: return 60_bi;
		case Species::Espurr: return 20_bi;
		case Species::Meowstic: return 20_bi;
		case Species::Honedge: return 20_bi;
		case Species::Doublade: return 20_bi;
		case Species::Aegislash: return 80_bi;
		case Species::Spritzee: return 20_bi;
		case Species::Aromatisse: return 40_bi;
		case Species::Swirlix: return 20_bi;
		case Species::Slurpuff: return 20_bi;
		case Species::Inkay: return 20_bi;
		case Species::Malamar: return 60_bi;
		case Species::Binacle: return 60_bi;
		case Species::Barbaracle: return 80_bi;
		case Species::Skrelp: return 20_bi;
		case Species::Dragalge: return 80_bi;
		case Species::Clauncher: return 20_bi;
		case Species::Clawitzer: return 60_bi;
		case Species::Helioptile: return 20_bi;
		case Species::Heliolisk: return 40_bi;
		case Species::Tyrunt: return 60_bi;
		case Species::Tyrantrum: return 120_bi;
		case Species::Amaura: return 60_bi;
		case Species::Aurorus: return 120_bi;
		case Species::Sylveon: return 40_bi;
		case Species::Hawlucha: return 40_bi;
		case Species::Dedenne: return 20_bi;
		case Species::Carbink: return 20_bi;
		case Species::Goomy: return 20_bi;
		case Species::Sliggoo: return 40_bi;
		case Species::Goodra: return 100_bi;
		case Species::Klefki: return 20_bi;
		case Species::Phantump: return 20_bi;
		case Species::Trevenant: return 80_bi;
		case Species::Pumpkaboo_Small: return 20_bi;
		case Species::Pumpkaboo_Average: return 20_bi;
		case Species::Pumpkaboo_Large: return 20_bi;
		case Species::Pumpkaboo_Super: return 40_bi;
		case Species::Gourgeist_Small: return 20_bi;
		case Species::Gourgeist_Average: return 40_bi;
		case Species::Gourgeist_Large: return 40_bi;
		case Species::Gourgeist_Super: return 60_bi;
		case Species::Bergmite: return 80_bi;
		case Species::Avalugg: return 120_bi;
		case Species::Noibat: return 20_bi;
		case Species::Noivern: return 80_bi;
		case Species::Xerneas: return 120_bi;
		case Species::Yveltal: return 120_bi;
		case Species::Zygarde_50: return 120_bi;
		case Species::Zygarde_10: return 60_bi;
		case Species::Zygarde_Complete: return 120_bi;
		case Species::Diancie: return 20_bi;
		case Species::Hoopa_Confined: return 20_bi;
		case Species::Hoopa_Unbound: return 120_bi;
		case Species::Volcanion: return 100_bi;

		// Generation 7
		case Species::Rowlet: return 20_bi;
		case Species::Dartrix: return 40_bi;
		case Species::Decidueye: return 60_bi;
		case Species::Litten: return 20_bi;
		case Species::Torracat: return 60_bi;
		case Species::Incineroar: return 80_bi;
		case Species::Popplio: return 20_bi;
		case Species::Brionne: return 40_bi;
		case Species::Primarina: return 60_bi;
		case Species::Pikipek: return 20_bi;
		case Species::Trumbeak: return 40_bi;
		case Species::Toucannon: return 60_bi;
		case Species::Yungoos: return 20_bi;
		case Species::Gumshoos: return 40_bi;
		case Species::Grubbin: return 20_bi;
		case Species::Charjabug: return 40_bi;
		case Species::Vikavolt: return 60_bi;
		case Species::Crabrawler: return 20_bi;
		case Species::Crabominable: return 100_bi;
		case Species::Oricorio_Baile: return 20_bi;
		case Species::Oricorio_Pau: return 20_bi;
		case Species::Oricorio_Pom_Pom: return 20_bi;
		case Species::Oricorio_Sensu: return 20_bi;
		case Species::Cutiefly: return 20_bi;
		case Species::Ribombee: return 20_bi;
		case Species::Rockruff: return 20_bi;
		case Species::Lycanroc_Midday: return 60_bi;
		case Species::Lycanroc_Midnight: return 60_bi;
		case Species::Lycanroc_Dusk: return 60_bi;
		case Species::Wishiwashi_Solo: return 20_bi;
		case Species::Wishiwashi_School: return 80_bi;
		case Species::Mareanie: return 20_bi;
		case Species::Toxapex: return 40_bi;
		case Species::Mudbray: return 100_bi;
		case Species::Mudsdale: return 120_bi;
		case Species::Dewpider: return 20_bi;
		case Species::Araquanid: return 80_bi;
		case Species::Fomantis: return 20_bi;
		case Species::Lurantis: return 40_bi;
		case Species::Morelull: return 20_bi;
		case Species::Shiinotic: return 40_bi;
		case Species::Salandit: return 20_bi;
		case Species::Salazzle: return 40_bi;
		case Species::Stufful: return 20_bi;
		case Species::Bewear: return 100_bi;
		case Species::Bounsweet: return 20_bi;
		case Species::Steenee: return 20_bi;
		case Species::Tsareena: return 40_bi;
		case Species::Comfey: return 20_bi;
		case Species::Oranguru: return 80_bi;
		case Species::Passimian: return 80_bi;
		case Species::Wimpod: return 40_bi;
		case Species::Golisopod: return 100_bi;
		case Species::Sandygast: return 80_bi;
		case Species::Palossand: return 120_bi;
		case Species::Pyukumuku: return 20_bi;
		case Species::Type_Null: return 100_bi;
		case Species::Silvally: return 100_bi;
		case Species::Minior_Meteor: return 60_bi;
		case Species::Minior_Core: return 20_bi;
		case Species::Komala: return 40_bi;
		case Species::Turtonator: return 120_bi;
		case Species::Togedemaru: return 20_bi;
		case Species::Mimikyu: return 20_bi;
		case Species::Bruxish: return 40_bi;
		case Species::Drampa: return 100_bi;
		case Species::Dhelmise: return 120_bi;
		case Species::Jangmo_o: return 60_bi;
		case Species::Hakamo_o: return 60_bi;
		case Species::Kommo_o: return 80_bi;
		case Species::Tapu_Koko: return 40_bi;
		case Species::Tapu_Lele: return 40_bi;
		case Species::Tapu_Bulu: return 60_bi;
		case Species::Tapu_Fini: return 40_bi;
		case Species::Cosmog: return 20_bi;
		case Species::Cosmoem: return 120_bi;
		case Species::Solgaleo: return 120_bi;
		case Species::Lunala: return 100_bi;
		case Species::Nihilego: return 80_bi;
		case Species::Buzzwole: return 120_bi;
		case Species::Pheromosa: return 60_bi;
		case Species::Xurkitree: return 100_bi;
		case Species::Celesteela: return 120_bi;
		case Species::Kartana: return 20_bi;
		case Species::Guzzlord: return 120_bi;
		case Species::Necrozma: return 120_bi;
		case Species::Necrozma_Dusk_Mane: return 120_bi;
		case Species::Necrozma_Dawn_Wings: return 120_bi;
		case Species::Necrozma_Ultra: return 120_bi;
		case Species::Magearna: return 80_bi;
		case Species::Marshadow: return 40_bi;
		case Species::Poipole: return 20_bi;
		case Species::Naganadel: return 100_bi;
		case Species::Stakataka: return 120_bi;
		case Species::Blacephalon: return 40_bi;
		case Species::Zeraora: return 60_bi;
		case Species::Rattata_Alolan: return 20_bi;
		case Species::Raticate_Alolan: return 60_bi;
		case Species::Raichu_Alolan: return 40_bi;
		case Species::Sandshrew_Alolan: return 60_bi;
		case Species::Sandslash_Alolan: return 80_bi;
		case Species::Vulpix_Alolan: return 20_bi;
		case Species::Ninetales_Alolan: return 40_bi;
		case Species::Diglett_Alolan: return 20_bi;
		case Species::Dugtrio_Alolan: return 80_bi;
		case Species::Meowth_Alolan: return 20_bi;
		case Species::Persian_Alolan: return 60_bi;
		case Species::Geodude_Alolan: return 40_bi;
		case Species::Graveler_Alolan: return 100_bi;
		case Species::Golem_Alolan: return 120_bi;
		case Species::Grimer_Alolan: return 60_bi;
		case Species::Muk_Alolan: return 80_bi;
		case Species::Exeggutor_Alolan: return 120_bi;
		case Species::Marowak_Alolan: return 60_bi;
		// case Species::Basculegion: return 100_bi;
		// case Species::Greninja_Ash: return 60_bi;
		// case Species::Kleavor: return 80_bi;
		// case Species::Mega_Abomasnow: return 100_bi;
		// case Species::Mega_Absol: return 60_bi;
		// case Species::Mega_Aerodactyl: return 80_bi;
		// case Species::Mega_Aggron: return 120_bi;
		// case Species::Mega_Altaria: return 40_bi;
		// case Species::Mega_Audino: return 60_bi;
		// case Species::Mega_Banette: return 40_bi;
		// case Species::Mega_Beedrill: return 60_bi;
		// case Species::Mega_Blastoise: return 100_bi;
		// case Species::Mega_Camerupt: return 120_bi;
		// case Species::Mega_Charizard_X: return 100_bi;
		// case Species::Mega_Charizard_Y: return 100_bi;
		// case Species::Mega_Diancie: return 60_bi;
		// case Species::Mega_Gallade: return 80_bi;
		// case Species::Mega_Glalie: return 120_bi;
		// case Species::Mega_Gyarados: return 120_bi;
		// case Species::Mega_Heracross: return 80_bi;
		// case Species::Mega_Houndoom: return 60_bi;
		// case Species::Mega_Kangaskhan: return 100_bi;
		// case Species::Mega_Latias: return 80_bi;
		// case Species::Mega_Latios: return 80_bi;
		// case Species::Mega_Lopunny: return 60_bi;
		// case Species::Mega_Lucario: return 80_bi;
		// case Species::Mega_Manectric: return 60_bi;
		// case Species::Mega_Mawile: return 40_bi;
		// case Species::Mega_Metagross: return 120_bi;
		// case Species::Mega_Mewtwo_X: return 100_bi;
		// case Species::Mega_Mewtwo_Y: return 60_bi;
		// case Species::Mega_Pidgeot: return 80_bi;
		// case Species::Mega_Pinsir: return 80_bi;
		// case Species::Mega_Rayquaza: return 120_bi;
		// case Species::Mega_Sableye: return 100_bi;
		// case Species::Mega_Salamence: return 100_bi;
		// case Species::Mega_Sceptile: return 80_bi;
		// case Species::Mega_Scizor: return 100_bi;
		// case Species::Mega_Sharpedo: return 100_bi;
		// case Species::Mega_Slowbro: return 100_bi;
		// case Species::Mega_Steelix: return 120_bi;
		// case Species::Mega_Swampert: return 100_bi;
		// case Species::Mega_Tyranitar: return 120_bi;
		// case Species::Mega_Venusaur: return 100_bi;
		// case Species::Meloetta_Pirouette: return 20_bi;
		// case Species::Primal_Groudon: return 120_bi;
		// case Species::Primal_Kyogre: return 120_bi;
		// case Species::Wyrdeer: return 80_bi;
	}
}

} // namespace

template<any_team UserTeam, any_team DefenderTeam>
auto base_power(UserTeam const & attacker_team, ExecutedMove<UserTeam> const executed, DefenderTeam const & defender_team, Weather const weather) -> BasePower {
	constexpr auto generation = generation_from<UserTeam>;
	auto const & attacker = attacker_team.pokemon();
	auto const & defender = defender_team.pokemon();
	switch (executed.move.name) {
		case Moves::Pass: return 0_bi;
		case Moves::Switch0: return 0_bi;
		case Moves::Switch1: return 0_bi;
		case Moves::Switch2: return 0_bi;
		case Moves::Switch3: return 0_bi;
		case Moves::Switch4: return 0_bi;
		case Moves::Switch5: return 0_bi;
		case Moves::Hit_Self: return 40_bi;
		case Moves::Pound: return 40_bi;
		case Moves::Karate_Chop: return 50_bi;
		case Moves::Double_Slap: return 15_bi;
		case Moves::Comet_Punch: return 18_bi;
		case Moves::Mega_Punch: return 80_bi;
		case Moves::Pay_Day: return 40_bi;
		case Moves::Fire_Punch: return 75_bi;
		case Moves::Ice_Punch: return 75_bi;
		case Moves::Thunder_Punch: return 75_bi;
		case Moves::Scratch: return 40_bi;
		case Moves::Vice_Grip: return 55_bi;
		case Moves::Guillotine: bounded::unreachable();
		case Moves::Razor_Wind: return 80_bi;
		case Moves::Swords_Dance: return 0_bi;
		case Moves::Cut: return 50_bi;
		case Moves::Gust: return 40_bi;
		case Moves::Wing_Attack: return BOUNDED_CONDITIONAL(generation == Generation::one, 35_bi, 60_bi);
		case Moves::Whirlwind: return 0_bi;
		case Moves::Fly: return BOUNDED_CONDITIONAL(generation <= Generation::three, 70_bi, 90_bi);
		case Moves::Bind: return 15_bi;
		case Moves::Slam: return 80_bi;
		case Moves::Vine_Whip: return BOUNDED_CONDITIONAL(generation <= Generation::five, 35_bi, 45_bi);
		case Moves::Stomp: return 65_bi;
		case Moves::Double_Kick: return 30_bi;
		case Moves::Mega_Kick: return 120_bi;
		case Moves::Jump_Kick:
			switch (generation) {
				case Generation::one:
				case Generation::two:
				case Generation::three:
					return 70_bi;
				case Generation::four:
					return 85_bi;
				default:
					return 100_bi;
			}
		case Moves::Rolling_Kick: return 60_bi;
		case Moves::Sand_Attack: return 0_bi;
		case Moves::Headbutt: return 70_bi;
		case Moves::Horn_Attack: return 65_bi;
		case Moves::Fury_Attack: return 15_bi;
		case Moves::Horn_Drill: bounded::unreachable();
		case Moves::Tackle:
			switch (generation) {
				case Generation::one:
				case Generation::two:
				case Generation::three:
				case Generation::four:
					return 35_bi;
				case Generation::five:
				case Generation::six:
					return 50_bi;
				default:
					return 40_bi;
			}
		case Moves::Body_Slam: return 85_bi;
		case Moves::Wrap: return 15_bi;
		case Moves::Take_Down: return 90_bi;
		case Moves::Thrash: return BOUNDED_CONDITIONAL(generation <= Generation::four, 90_bi, 120_bi);
		case Moves::Double_Edge: return BOUNDED_CONDITIONAL(generation == Generation::one, 100_bi, 120_bi);
		case Moves::Tail_Whip: return 0_bi;
		case Moves::Poison_Sting: return 15_bi;
		case Moves::Twineedle: return 25_bi;
		case Moves::Pin_Missile: return BOUNDED_CONDITIONAL(generation <= Generation::five, 14_bi, 25_bi);
		case Moves::Leer: return 0_bi;
		case Moves::Bite: return 60_bi;
		case Moves::Growl: return 0_bi;
		case Moves::Roar: return 0_bi;
		case Moves::Sing: return 0_bi;
		case Moves::Supersonic: return 0_bi;
		case Moves::Sonic_Boom: bounded::unreachable();
		case Moves::Disable: return 0_bi;
		case Moves::Acid: return 40_bi;
		case Moves::Ember: return 40_bi;
		case Moves::Flamethrower: return BOUNDED_CONDITIONAL(generation <= Generation::five, 95_bi, 90_bi);
		case Moves::Mist: return 0_bi;
		case Moves::Water_Gun: return 40_bi;
		case Moves::Hydro_Pump: return BOUNDED_CONDITIONAL(generation <= Generation::five, 120_bi, 110_bi);
		case Moves::Surf: return BOUNDED_CONDITIONAL(generation <= Generation::five, 95_bi, 90_bi);
		case Moves::Ice_Beam: return BOUNDED_CONDITIONAL(generation <= Generation::five, 95_bi, 90_bi);
		case Moves::Blizzard: return BOUNDED_CONDITIONAL(generation <= Generation::five, 120_bi, 110_bi);
		case Moves::Psybeam: return 65_bi;
		case Moves::Bubble_Beam: return 65_bi;
		case Moves::Aurora_Beam: return 65_bi;
		case Moves::Hyper_Beam: return 150_bi;
		case Moves::Peck: return 35_bi;
		case Moves::Drill_Peck: return 80_bi;
		case Moves::Submission: return 80_bi;
		case Moves::Low_Kick:
		case Moves::Grass_Knot:
			return BOUNDED_CONDITIONAL(generation <= Generation::two, 50_bi, power_of_mass_based_moves(defender.species()));
		case Moves::Counter: bounded::unreachable();
		case Moves::Seismic_Toss: bounded::unreachable();
		case Moves::Strength: return 80_bi;
		case Moves::Absorb: return 20_bi;
		case Moves::Mega_Drain: return 40_bi;
		case Moves::Leech_Seed: return 0_bi;
		case Moves::Growth: return 0_bi;
		case Moves::Razor_Leaf: return 55_bi;
		// Base power is doubled in certain weather, including clear weather
		case Moves::Solar_Beam: return 60_bi;
		case Moves::Poison_Powder: return 0_bi;
		case Moves::Stun_Spore: return 0_bi;
		case Moves::Sleep_Powder: return 0_bi;
		case Moves::Petal_Dance:
			switch (generation) {
				case Generation::one:
				case Generation::two:
				case Generation::three:
					return 70_bi;
				case Generation::four:
					return 90_bi;
				default:
					return 120_bi;
			}
		case Moves::String_Shot: return 0_bi;
		case Moves::Dragon_Rage: bounded::unreachable();
		case Moves::Fire_Spin: return BOUNDED_CONDITIONAL(generation <= Generation::four, 15_bi, 35_bi);
		case Moves::Thunder_Shock: return 40_bi;
		case Moves::Thunderbolt: return BOUNDED_CONDITIONAL(generation <= Generation::five, 95_bi, 90_bi);
		case Moves::Thunder_Wave: return 0_bi;
		case Moves::Thunder: return BOUNDED_CONDITIONAL(generation <= Generation::five, 120_bi, 110_bi);
		case Moves::Rock_Throw: return 50_bi;
		case Moves::Earthquake: return 100_bi;
		case Moves::Fissure: bounded::unreachable();
		case Moves::Dig:
			switch (generation) {
				case Generation::one:
					return 100_bi;
				case Generation::two:
				case Generation::three:
					return 60_bi;
				default:
					return 80_bi;
			}
		case Moves::Toxic: return 0_bi;
		case Moves::Confusion: return 50_bi;
		case Moves::Psychic: return 90_bi;
		case Moves::Hypnosis: return 0_bi;
		case Moves::Meditate: return 0_bi;
		case Moves::Agility: return 0_bi;
		case Moves::Quick_Attack: return 40_bi;
		case Moves::Rage: return 20_bi;
		case Moves::Teleport: return 0_bi;
		case Moves::Night_Shade: bounded::unreachable();
		case Moves::Mimic: return 0_bi;
		case Moves::Screech: return 0_bi;
		case Moves::Double_Team: return 0_bi;
		case Moves::Recover: return 0_bi;
		case Moves::Harden: return 0_bi;
		case Moves::Minimize: return 0_bi;
		case Moves::Smokescreen: return 0_bi;
		case Moves::Confuse_Ray: return 0_bi;
		case Moves::Withdraw: return 0_bi;
		case Moves::Defense_Curl: return 0_bi;
		case Moves::Barrier: return 0_bi;
		case Moves::Light_Screen: return 0_bi;
		case Moves::Haze: return 0_bi;
		case Moves::Reflect: return 0_bi;
		case Moves::Focus_Energy: return 0_bi;
		case Moves::Bide: bounded::unreachable();
		case Moves::Metronome: return 0_bi;
		case Moves::Mirror_Move: return 0_bi;
		case Moves::Self_Destruct: return BOUNDED_CONDITIONAL(generation == Generation::one, 130_bi, 200_bi);
		case Moves::Egg_Bomb: return 100_bi;
		case Moves::Lick: return BOUNDED_CONDITIONAL(generation <= Generation::five, 20_bi, 30_bi);
		case Moves::Smog: return BOUNDED_CONDITIONAL(generation <= Generation::five, 20_bi, 30_bi);
		case Moves::Sludge: return 65_bi;
		case Moves::Bone_Club: return 65_bi;
		case Moves::Fire_Blast: return BOUNDED_CONDITIONAL(generation <= Generation::five, 120_bi, 110_bi);
		case Moves::Waterfall: return 80_bi;
		case Moves::Clamp: return 35_bi;
		case Moves::Swift: return 60_bi;
		case Moves::Skull_Bash: return BOUNDED_CONDITIONAL(generation <= Generation::five, 100_bi, 130_bi);
		case Moves::Spike_Cannon: return 20_bi;
		case Moves::Constrict: return 10_bi;
		case Moves::Amnesia: return 0_bi;
		case Moves::Kinesis: return 0_bi;
		case Moves::Soft_Boiled: return 0_bi;
		case Moves::High_Jump_Kick:
			switch (generation) {
				case Generation::one:
				case Generation::two:
				case Generation::three:
					return 85_bi;
				case Generation::four:
					return 100_bi;
				default:
					return 130_bi;
			}
		case Moves::Glare: return 0_bi;
		case Moves::Dream_Eater: return 100_bi;
		case Moves::Poison_Gas: return 0_bi;
		case Moves::Barrage: return 15_bi;
		case Moves::Leech_Life: return BOUNDED_CONDITIONAL(generation <= Generation::six, 20_bi, 80_bi);
		case Moves::Lovely_Kiss: return 0_bi;
		case Moves::Sky_Attack: return 140_bi;
		case Moves::Transform: return 0_bi;
		case Moves::Bubble: return BOUNDED_CONDITIONAL(generation <= Generation::five, 20_bi, 40_bi);
		case Moves::Dizzy_Punch: return 70_bi;
		case Moves::Spore: return 0_bi;
		case Moves::Flash: return 0_bi;
		case Moves::Psywave: bounded::unreachable();
		case Moves::Splash: return 0_bi;
		case Moves::Acid_Armor: return 0_bi;
		case Moves::Crabhammer: return BOUNDED_CONDITIONAL(generation <= Generation::five, 90_bi, 100_bi);
		case Moves::Explosion: return BOUNDED_CONDITIONAL(generation == Generation::one, 170_bi, 250_bi);
		case Moves::Fury_Swipes: return 18_bi;
		case Moves::Bonemerang: return 50_bi;
		case Moves::Rest: return 0_bi;
		case Moves::Rock_Slide: return 75_bi;
		case Moves::Hyper_Fang: return 80_bi;
		case Moves::Sharpen: return 0_bi;
		case Moves::Conversion: return 0_bi;
		case Moves::Tri_Attack: return 80_bi;
		case Moves::Super_Fang: bounded::unreachable();
		case Moves::Slash: return 70_bi;
		case Moves::Substitute: return 0_bi;
		case Moves::Struggle: return 50_bi;
		case Moves::Sketch: return 0_bi;
		case Moves::Triple_Kick: return attacker.last_used_move().triple_kick_power();
		case Moves::Thief: return BOUNDED_CONDITIONAL(generation <= Generation::five, 40_bi, 60_bi);
		case Moves::Spider_Web: return 0_bi;
		case Moves::Mind_Reader: return 0_bi;
		case Moves::Nightmare: return 0_bi;
		case Moves::Flame_Wheel: return 60_bi;
		case Moves::Snore: return BOUNDED_CONDITIONAL(generation <= Generation::five, 40_bi, 50_bi);
		case Moves::Curse: return 0_bi;
		case Moves::Flail:
		case Moves::Reversal: {
			auto const k = 64_bi * hp_ratio(attacker);
			if (k <= 1_bi) return 200_bi;
			else if (k <= 5_bi) return 150_bi;
			else if (k <= 12_bi) return 100_bi;
			else if (k <= 21_bi) return 80_bi;
			else if (k <= 42_bi) return 40_bi;
			else return 20_bi;
		}
		case Moves::Conversion_2: return 0_bi;
		case Moves::Aeroblast: return 100_bi;
		case Moves::Cotton_Spore: return 0_bi;
		case Moves::Spite: return 0_bi;
		case Moves::Powder_Snow: return 40_bi;
		case Moves::Protect: return 0_bi;
		case Moves::Mach_Punch: return 40_bi;
		case Moves::Scary_Face: return 0_bi;
		case Moves::Feint_Attack: return 60_bi;
		case Moves::Sweet_Kiss: return 0_bi;
		case Moves::Belly_Drum: return 0_bi;
		case Moves::Sludge_Bomb: return 90_bi;
		case Moves::Mud_Slap: return 20_bi;
		case Moves::Octazooka: return 65_bi;
		case Moves::Spikes: return 0_bi;
		case Moves::Zap_Cannon: return BOUNDED_CONDITIONAL(generation <= Generation::three, 100_bi, 120_bi);
		case Moves::Foresight: return 0_bi;
		case Moves::Destiny_Bond: return 0_bi;
		case Moves::Perish_Song: return 0_bi;
		case Moves::Icy_Wind: return 55_bi;
		case Moves::Detect: return 0_bi;
		case Moves::Bone_Rush: return 25_bi;
		case Moves::Lock_On: return 0_bi;
		case Moves::Outrage: return BOUNDED_CONDITIONAL(generation <= Generation::three, 90_bi, 120_bi);
		case Moves::Sandstorm: return 0_bi;
		case Moves::Giga_Drain: return BOUNDED_CONDITIONAL(generation <= Generation::four, 60_bi, 75_bi);
		case Moves::Endure: return 0_bi;
		case Moves::Charm: return 0_bi;
		case Moves::Rollout:
		case Moves::Ice_Ball:
			return attacker.last_used_move().momentum_move_power();
		case Moves::False_Swipe: return 40_bi;
		case Moves::Swagger: return 0_bi;
		case Moves::Milk_Drink: return 0_bi;
		case Moves::Spark: return 65_bi;
		case Moves::Fury_Cutter: return attacker.last_used_move().fury_cutter_power(generation);
		case Moves::Steel_Wing: return 70_bi;
		case Moves::Mean_Look: return 0_bi;
		case Moves::Attract: return 0_bi;
		case Moves::Sleep_Talk: return 0_bi;
		case Moves::Heal_Bell: return 0_bi;
		case Moves::Return: return return_power(attacker.happiness());
		// TODO
		case Moves::Present: return 80_bi;
		case Moves::Frustration: return frustration_power(attacker.happiness());
		case Moves::Safeguard: return 0_bi;
		case Moves::Pain_Split: return 0_bi;
		case Moves::Sacred_Fire: return 100_bi;
		// TODO:
		case Moves::Magnitude: return 70_bi;
		case Moves::Dynamic_Punch: return 100_bi;
		case Moves::Megahorn: return 120_bi;
		case Moves::Dragon_Breath: return 60_bi;
		case Moves::Baton_Pass: return 0_bi;
		case Moves::Encore: return 0_bi;
		case Moves::Pursuit: return 40_bi;
		case Moves::Rapid_Spin: return BOUNDED_CONDITIONAL(generation <= Generation::seven, 20_bi, 50_bi);
		case Moves::Sweet_Scent: return 0_bi;
		case Moves::Iron_Tail: return 100_bi;
		case Moves::Metal_Claw: return 50_bi;
		case Moves::Vital_Throw: return 70_bi;
		case Moves::Morning_Sun: return 0_bi;
		case Moves::Synthesis: return 0_bi;
		case Moves::Moonlight: return 0_bi;
		case Moves::Hidden_Power: return attacker.hidden_power()->power();
		case Moves::Cross_Chop: return 100_bi;
		case Moves::Twister: return 40_bi;
		case Moves::Rain_Dance: return 0_bi;
		case Moves::Sunny_Day: return 0_bi;
		case Moves::Crunch: return 80_bi;
		case Moves::Mirror_Coat: bounded::unreachable();
		case Moves::Psych_Up: return 0_bi;
		case Moves::Extreme_Speed: return 80_bi;
		case Moves::Ancient_Power: return 60_bi;
		case Moves::Shadow_Ball: return 80_bi;
		case Moves::Future_Sight:
			switch (generation) {
				case Generation::one:
				case Generation::two:
				case Generation::three:
				case Generation::four:
					return 80_bi;
				case Generation::five:
					return 100_bi;
				default:
					return 120_bi;
			}
		case Moves::Rock_Smash: return BOUNDED_CONDITIONAL(generation <= Generation::three, 20_bi, 40_bi);
		case Moves::Whirlpool: return BOUNDED_CONDITIONAL(generation <= Generation::four, 15_bi, 35_bi);
		// TODO: Beat Up
		case Moves::Beat_Up: return 1_bi;
		case Moves::Fake_Out: return 40_bi;
		case Moves::Uproar: return BOUNDED_CONDITIONAL(generation <= Generation::four, 50_bi, 90_bi);
		case Moves::Stockpile: return 0_bi;
		case Moves::Spit_Up: return attacker.spit_up_power();
		case Moves::Swallow: return 0_bi;
		case Moves::Heat_Wave: return BOUNDED_CONDITIONAL(generation <= Generation::five, 100_bi, 95_bi);
		case Moves::Hail: return 0_bi;
		case Moves::Torment: return 0_bi;
		case Moves::Flatter: return 0_bi;
		case Moves::Will_O_Wisp: return 0_bi;
		case Moves::Memento: return 0_bi;
		case Moves::Facade: return 70_bi;
		case Moves::Focus_Punch: return 150_bi;
		case Moves::Smelling_Salts: return BOUNDED_CONDITIONAL(generation <= Generation::five, 60_bi, 70_bi);
		case Moves::Follow_Me: return 0_bi;
		case Moves::Nature_Power: return 0_bi;
		case Moves::Charge: return 0_bi;
		case Moves::Taunt: return 0_bi;
		case Moves::Helping_Hand: return 0_bi;
		case Moves::Trick: return 0_bi;
		case Moves::Role_Play: return 0_bi;
		case Moves::Wish: return 0_bi;
		case Moves::Assist: return 0_bi;
		case Moves::Ingrain: return 0_bi;
		case Moves::Superpower: return 120_bi;
		case Moves::Magic_Coat: return 0_bi;
		case Moves::Recycle: return 0_bi;
		case Moves::Revenge: return 60_bi;
		case Moves::Brick_Break: return 75_bi;
		case Moves::Yawn: return 0_bi;
		case Moves::Knock_Off: return BOUNDED_CONDITIONAL(generation <= Generation::five, 20_bi, 65_bi);
		case Moves::Endeavor: bounded::unreachable();
		case Moves::Eruption:
		case Moves::Water_Spout:
			return bounded::assume_in_range(bounded::max(150_bi * hp_ratio(attacker), 1_bi), 1_bi, 150_bi);
		case Moves::Skill_Swap: return 0_bi;
		case Moves::Imprison: return 0_bi;
		case Moves::Refresh: return 0_bi;
		case Moves::Grudge: return 0_bi;
		case Moves::Snatch: return 0_bi;
		case Moves::Secret_Power: return 70_bi;
		case Moves::Dive: return BOUNDED_CONDITIONAL(generation <= Generation::three, 60_bi, 80_bi);
		case Moves::Arm_Thrust: return 15_bi;
		case Moves::Camouflage: return 0_bi;
		case Moves::Tail_Glow: return 0_bi;
		case Moves::Luster_Purge: return 70_bi;
		case Moves::Mist_Ball: return 70_bi;
		case Moves::Feather_Dance: return 0_bi;
		case Moves::Teeter_Dance: return 0_bi;
		case Moves::Blaze_Kick: return 85_bi;
		case Moves::Mud_Sport: return 0_bi;
		case Moves::Needle_Arm: return 60_bi;
		case Moves::Slack_Off: return 0_bi;
		case Moves::Hyper_Voice: return 90_bi;
		case Moves::Poison_Fang: return 50_bi;
		case Moves::Crush_Claw: return 75_bi;
		case Moves::Blast_Burn: return 150_bi;
		case Moves::Hydro_Cannon: return 150_bi;
		case Moves::Meteor_Mash: return BOUNDED_CONDITIONAL(generation <= Generation::five, 100_bi, 90_bi);
		case Moves::Astonish: return 30_bi;
		case Moves::Weather_Ball: return 50_bi;
		case Moves::Aromatherapy: return 0_bi;
		case Moves::Fake_Tears: return 0_bi;
		case Moves::Air_Cutter: return BOUNDED_CONDITIONAL(generation <= Generation::five, 55_bi, 60_bi);
		case Moves::Overheat: return BOUNDED_CONDITIONAL(generation <= Generation::five, 140_bi, 130_bi);
		case Moves::Odor_Sleuth: return 0_bi;
		case Moves::Rock_Tomb: return BOUNDED_CONDITIONAL(generation <= Generation::five, 50_bi, 60_bi);
		case Moves::Silver_Wind: return 60_bi;
		case Moves::Metal_Sound: return 0_bi;
		case Moves::Grass_Whistle: return 0_bi;
		case Moves::Tickle: return 0_bi;
		case Moves::Cosmic_Power: return 0_bi;
		case Moves::Signal_Beam: return 75_bi;
		case Moves::Shadow_Punch: return 60_bi;
		case Moves::Extrasensory: return 80_bi;
		case Moves::Sky_Uppercut: return 85_bi;
		case Moves::Sand_Tomb: return BOUNDED_CONDITIONAL(generation <= Generation::four, 15_bi, 35_bi);
		case Moves::Sheer_Cold: bounded::unreachable();
		case Moves::Muddy_Water: return BOUNDED_CONDITIONAL(generation <= Generation::five, 95_bi, 90_bi);
		case Moves::Bullet_Seed: return BOUNDED_CONDITIONAL(generation <= Generation::four, 10_bi, 25_bi);
		case Moves::Aerial_Ace: return 60_bi;
		case Moves::Icicle_Spear: return BOUNDED_CONDITIONAL(generation <= Generation::four, 10_bi, 25_bi);
		case Moves::Iron_Defense: return 0_bi;
		case Moves::Block: return 0_bi;
		case Moves::Howl: return 0_bi;
		case Moves::Dragon_Claw: return 80_bi;
		case Moves::Frenzy_Plant: return 150_bi;
		case Moves::Bulk_Up: return 0_bi;
		case Moves::Bounce: return 85_bi;
		case Moves::Mud_Shot: return 55_bi;
		case Moves::Poison_Tail: return 50_bi;
		case Moves::Covet: return BOUNDED_CONDITIONAL(generation <= Generation::four, 40_bi, 60_bi);
		case Moves::Volt_Tackle: return 120_bi;
		case Moves::Magical_Leaf: return 60_bi;
		case Moves::Water_Sport: return 0_bi;
		case Moves::Calm_Mind: return 0_bi;
		case Moves::Leaf_Blade: return BOUNDED_CONDITIONAL(generation <= Generation::three, 70_bi, 90_bi);
		case Moves::Dragon_Dance: return 0_bi;
		case Moves::Rock_Blast: return 25_bi;
		case Moves::Shock_Wave: return 60_bi;
		case Moves::Water_Pulse: return 60_bi;
		case Moves::Doom_Desire: return BOUNDED_CONDITIONAL(generation <= Generation::four, 120_bi, 140_bi);
		case Moves::Psycho_Boost: return 140_bi;
		case Moves::Roost: return 0_bi;
		case Moves::Gravity: return 0_bi;
		case Moves::Miracle_Eye: return 0_bi;
		case Moves::Wake_Up_Slap: return BOUNDED_CONDITIONAL(generation <= Generation::five, 60_bi, 70_bi);
		case Moves::Hammer_Arm: return 100_bi;
		case Moves::Gyro_Ball: {
			auto const defender_speed = calculate_speed(defender_team, attacker.ability(), weather);
			auto const attacker_speed = calculate_speed(attacker_team, defender.ability(), weather);
			auto const uncapped_power = 25_bi * defender_speed / attacker_speed + 1_bi;
			return bounded::min(uncapped_power, 150_bi);
		}
		case Moves::Healing_Wish: return 0_bi;
		case Moves::Brine: return 65_bi;
		case Moves::Natural_Gift: return berry_power(attacker.item(weather));
		case Moves::Feint: return BOUNDED_CONDITIONAL(generation <= Generation::four, 50_bi, 30_bi);
		case Moves::Pluck: return 60_bi;
		case Moves::Tailwind: return 0_bi;
		case Moves::Acupressure: return 0_bi;
		case Moves::Metal_Burst: bounded::unreachable();
		case Moves::U_turn: return 70_bi;
		case Moves::Close_Combat: return 120_bi;
		case Moves::Payback: return 50_bi;
		case Moves::Assurance: return BOUNDED_CONDITIONAL(generation <= Generation::five, 50_bi, 60_bi);
		case Moves::Embargo: return 0_bi;
		case Moves::Fling: return fling_power(attacker.item(weather));
		case Moves::Psycho_Shift: return 0_bi;
		case Moves::Trump_Card:
			// Safe to dereference because we know Trump Card is not unlimited
			switch (executed.pp.remaining()->value()) {
				case 0: return 200_bi;
				case 1: return 80_bi;
				case 2: return 60_bi;
				case 3: return 50_bi;
				default: return 40_bi;
			}
		case Moves::Heal_Block: return 0_bi;
		case Moves::Power_Trick: return 0_bi;
		case Moves::Gastro_Acid: return 0_bi;
		case Moves::Lucky_Chant: return 0_bi;
		case Moves::Me_First: return 0_bi;
		case Moves::Copycat: return 0_bi;
		case Moves::Power_Swap: return 0_bi;
		case Moves::Guard_Swap: return 0_bi;
		case Moves::Punishment: {
			auto is_positive = [](auto const value) { return value > 0_bi; };
			auto const uncapped_power = 60_bi + 20_bi * bounded::increase_min<0>(containers::sum(containers::transform(containers::filter(defender.stages(), is_positive), &Stage::value)));
			return bounded::min(uncapped_power, 200_bi);
		}
		case Moves::Last_Resort: return BOUNDED_CONDITIONAL(generation <= Generation::four, 130_bi, 140_bi);
		case Moves::Worry_Seed: return 0_bi;
		case Moves::Sucker_Punch: return BOUNDED_CONDITIONAL(generation <= Generation::six, 80_bi, 70_bi);
		case Moves::Toxic_Spikes: return 0_bi;
		case Moves::Heart_Swap: return 0_bi;
		case Moves::Aqua_Ring: return 0_bi;
		case Moves::Magnet_Rise: return 0_bi;
		case Moves::Flare_Blitz: return 120_bi;
		case Moves::Force_Palm: return 60_bi;
		case Moves::Aura_Sphere: return BOUNDED_CONDITIONAL(generation <= Generation::five, 90_bi, 80_bi);
		case Moves::Rock_Polish: return 0_bi;
		case Moves::Poison_Jab: return 80_bi;
		case Moves::Dark_Pulse: return 80_bi;
		case Moves::Night_Slash: return 70_bi;
		case Moves::Aqua_Tail: return 90_bi;
		case Moves::Seed_Bomb: return 80_bi;
		case Moves::Air_Slash: return 75_bi;
		case Moves::X_Scissor: return 80_bi;
		case Moves::Bug_Buzz: return 90_bi;
		case Moves::Dragon_Pulse: return BOUNDED_CONDITIONAL(generation <= Generation::five, 90_bi, 85_bi);
		case Moves::Dragon_Rush: return 100_bi;
		case Moves::Power_Gem: return BOUNDED_CONDITIONAL(generation <= Generation::five, 70_bi, 80_bi);
		case Moves::Drain_Punch: return BOUNDED_CONDITIONAL(generation <= Generation::four, 60_bi, 75_bi);
		case Moves::Vacuum_Wave: return 40_bi;
		case Moves::Focus_Blast: return 120_bi;
		case Moves::Energy_Ball: return BOUNDED_CONDITIONAL(generation <= Generation::five, 80_bi, 90_bi);
		case Moves::Brave_Bird: return 120_bi;
		case Moves::Earth_Power: return 90_bi;
		case Moves::Switcheroo: return 0_bi;
		case Moves::Giga_Impact: return 150_bi;
		case Moves::Nasty_Plot: return 0_bi;
		case Moves::Bullet_Punch: return 40_bi;
		case Moves::Avalanche: return 60_bi;
		case Moves::Ice_Shard: return 40_bi;
		case Moves::Shadow_Claw: return 70_bi;
		case Moves::Thunder_Fang: return 65_bi;
		case Moves::Ice_Fang: return 65_bi;
		case Moves::Fire_Fang: return 65_bi;
		case Moves::Shadow_Sneak: return 40_bi;
		case Moves::Mud_Bomb: return 65_bi;
		case Moves::Psycho_Cut: return 70_bi;
		case Moves::Zen_Headbutt: return 80_bi;
		case Moves::Mirror_Shot: return 65_bi;
		case Moves::Flash_Cannon: return 80_bi;
		case Moves::Rock_Climb: return 90_bi;
		case Moves::Defog: return 0_bi;
		case Moves::Trick_Room: return 0_bi;
		case Moves::Draco_Meteor: return BOUNDED_CONDITIONAL(generation <= Generation::five, 140_bi, 130_bi);
		case Moves::Discharge: return 80_bi;
		case Moves::Lava_Plume: return 80_bi;
		case Moves::Leaf_Storm: return BOUNDED_CONDITIONAL(generation <= Generation::five, 140_bi, 130_bi);
		case Moves::Power_Whip: return 120_bi;
		case Moves::Rock_Wrecker: return 150_bi;
		case Moves::Cross_Poison: return 70_bi;
		case Moves::Gunk_Shot: return 120_bi;
		case Moves::Iron_Head: return 80_bi;
		case Moves::Magnet_Bomb: return 60_bi;
		case Moves::Stone_Edge: return 100_bi;
		case Moves::Captivate: return 0_bi;
		case Moves::Stealth_Rock: return 0_bi;
		case Moves::Chatter: return BOUNDED_CONDITIONAL(generation <= Generation::five, 60_bi, 65_bi);
		case Moves::Judgment: return 100_bi;
		case Moves::Bug_Bite: return 60_bi;
		case Moves::Charge_Beam: return 50_bi;
		case Moves::Wood_Hammer: return 120_bi;
		case Moves::Aqua_Jet: return 40_bi;
		case Moves::Attack_Order: return 90_bi;
		case Moves::Defend_Order: return 0_bi;
		case Moves::Heal_Order: return 0_bi;
		case Moves::Head_Smash: return 150_bi;
		case Moves::Double_Hit: return 35_bi;
		case Moves::Roar_of_Time: return 150_bi;
		case Moves::Spacial_Rend: return 100_bi;
		case Moves::Lunar_Dance: return 0_bi;
		case Moves::Crush_Grip:
		case Moves::Wring_Out:
			return bounded::assume_in_range(120_bi * hp_ratio(defender) + 1_bi, 1_bi, 121_bi);
		case Moves::Magma_Storm: return BOUNDED_CONDITIONAL(generation <= Generation::five, 120_bi, 100_bi);
		case Moves::Dark_Void: return 0_bi;
		case Moves::Seed_Flare: return 120_bi;
		case Moves::Ominous_Wind: return 60_bi;
		case Moves::Shadow_Force: return 120_bi;
		case Moves::Hone_Claws: return 0_bi;
		case Moves::Wide_Guard: return 0_bi;
		case Moves::Guard_Split: return 0_bi;
		case Moves::Power_Split: return 0_bi;
		case Moves::Wonder_Room: return 0_bi;
		case Moves::Psyshock: return 80_bi;
		case Moves::Venoshock: return 65_bi;
		case Moves::Autotomize: return 0_bi;
		case Moves::Rage_Powder: return 0_bi;
		case Moves::Telekinesis: return 0_bi;
		case Moves::Magic_Room: return 0_bi;
		case Moves::Smack_Down: return 50_bi;
		case Moves::Storm_Throw: return BOUNDED_CONDITIONAL(generation <= Generation::five, 40_bi, 60_bi);
		case Moves::Flame_Burst: return 70_bi;
		case Moves::Sludge_Wave: return 95_bi;
		case Moves::Quiver_Dance: return 0_bi;
		// TODO
		case Moves::Heavy_Slam:
		case Moves::Heat_Crash:
			return 1_bi;
		case Moves::Synchronoise: return BOUNDED_CONDITIONAL(generation <= Generation::five, 70_bi, 120_bi);
		case Moves::Electro_Ball: {
			auto const defender_speed = calculate_speed(defender_team, attacker.ability(), weather);
			auto const attacker_speed = calculate_speed(attacker_team, defender.ability(), weather);
			auto const quotient = attacker_speed / defender_speed;
			switch (quotient.value()) {
				case 0: return 40_bi;
				case 1: return 60_bi;
				case 2: return 80_bi;
				case 3: return 120_bi;
				default: return 150_bi;
			}
		}
		case Moves::Soak: return 0_bi;
		case Moves::Flame_Charge: return 50_bi;
		case Moves::Coil: return 0_bi;
		case Moves::Low_Sweep: return BOUNDED_CONDITIONAL(generation <= Generation::five, 60_bi, 65_bi);
		case Moves::Acid_Spray: return 40_bi;
		case Moves::Foul_Play: return 95_bi;
		case Moves::Simple_Beam: return 0_bi;
		case Moves::Entrainment: return 0_bi;
		case Moves::After_You: return 0_bi;
		case Moves::Round: return 60_bi;
		case Moves::Echoed_Voice: return 40_bi;
		case Moves::Chip_Away: return 70_bi;
		case Moves::Clear_Smog: return 50_bi;
		case Moves::Stored_Power: return 20_bi;
		case Moves::Quick_Guard: return 0_bi;
		case Moves::Ally_Switch: return 0_bi;
		case Moves::Scald: return 80_bi;
		case Moves::Shell_Smash: return 0_bi;
		case Moves::Heal_Pulse: return 0_bi;
		case Moves::Hex: return BOUNDED_CONDITIONAL(generation <= Generation::five, 50_bi, 65_bi);
		case Moves::Sky_Drop: return 60_bi;
		case Moves::Shift_Gear: return 0_bi;
		case Moves::Circle_Throw: return 60_bi;
		case Moves::Incinerate: return BOUNDED_CONDITIONAL(generation <= Generation::five, 30_bi, 60_bi);
		case Moves::Quash: return 0_bi;
		case Moves::Acrobatics: return 55_bi;
		case Moves::Reflect_Type: return 0_bi;
		case Moves::Retaliate: return 70_bi;
		case Moves::Final_Gambit: bounded::unreachable();
		case Moves::Bestow: return 0_bi;
		case Moves::Inferno: return 100_bi;
		case Moves::Water_Pledge: return BOUNDED_CONDITIONAL(generation <= Generation::five, 50_bi, 80_bi);
		case Moves::Fire_Pledge: return BOUNDED_CONDITIONAL(generation <= Generation::five, 50_bi, 80_bi);
		case Moves::Grass_Pledge: return BOUNDED_CONDITIONAL(generation <= Generation::five, 50_bi, 80_bi);
		case Moves::Volt_Switch: return 70_bi;
		case Moves::Struggle_Bug: return BOUNDED_CONDITIONAL(generation <= Generation::five, 30_bi, 50_bi);
		case Moves::Bulldoze: return 60_bi;
		case Moves::Frost_Breath: return BOUNDED_CONDITIONAL(generation <= Generation::five, 40_bi, 60_bi);
		case Moves::Dragon_Tail: return 60_bi;
		case Moves::Work_Up: return 0_bi;
		case Moves::Electroweb: return 55_bi;
		case Moves::Wild_Charge: return 90_bi;
		case Moves::Drill_Run: return 80_bi;
		case Moves::Dual_Chop: return 40_bi;
		case Moves::Heart_Stamp: return 60_bi;
		case Moves::Horn_Leech: return 75_bi;
		case Moves::Sacred_Sword: return 90_bi;
		case Moves::Razor_Shell: return 75_bi;
		case Moves::Leaf_Tornado: return 65_bi;
		case Moves::Steamroller: return 65_bi;
		case Moves::Cotton_Guard: return 0_bi;
		case Moves::Night_Daze: return 85_bi;
		case Moves::Psystrike: return 100_bi;
		case Moves::Tail_Slap: return 25_bi;
		case Moves::Hurricane: return BOUNDED_CONDITIONAL(generation <= Generation::five, 120_bi, 110_bi);
		case Moves::Head_Charge: return 120_bi;
		case Moves::Gear_Grind: return 50_bi;
		case Moves::Searing_Shot: return 100_bi;
		case Moves::Techno_Blast: return BOUNDED_CONDITIONAL(generation <= Generation::five, 85_bi, 120_bi);
		case Moves::Relic_Song: return 75_bi;
		case Moves::Secret_Sword: return 85_bi;
		case Moves::Glaciate: return 65_bi;
		case Moves::Bolt_Strike: return 130_bi;
		case Moves::Blue_Flare: return 130_bi;
		case Moves::Fiery_Dance: return 80_bi;
		case Moves::Freeze_Shock: return 140_bi;
		case Moves::Ice_Burn: return 140_bi;
		case Moves::Snarl: return 55_bi;
		case Moves::Icicle_Crash: return 85_bi;
		case Moves::V_create: return 180_bi;
		case Moves::Fusion_Flare: return 100_bi;
		case Moves::Fusion_Bolt: return 100_bi;
		case Moves::Flying_Press: return BOUNDED_CONDITIONAL(generation <= Generation::six, 80_bi, 100_bi);
		case Moves::Mat_Block: return 0_bi;
		case Moves::Belch: return 120_bi;
		case Moves::Rototiller: return 0_bi;
		case Moves::Sticky_Web: return 0_bi;
		case Moves::Fell_Stinger: return BOUNDED_CONDITIONAL(generation <= Generation::six, 30_bi, 50_bi);
		case Moves::Phantom_Force: return 90_bi;
		case Moves::Trick_or_Treat: return 0_bi;
		case Moves::Noble_Roar: return 0_bi;
		case Moves::Ion_Deluge: return 0_bi;
		case Moves::Parabolic_Charge: return BOUNDED_CONDITIONAL(generation <= Generation::six, 50_bi, 65_bi);
		case Moves::Forests_Curse: return 0_bi;
		case Moves::Petal_Blizzard: return 90_bi;
		case Moves::Freeze_Dry: return 70_bi;
		case Moves::Disarming_Voice: return 40_bi;
		case Moves::Parting_Shot: return 0_bi;
		case Moves::Topsy_Turvy: return 0_bi;
		case Moves::Draining_Kiss: return 50_bi;
		case Moves::Crafty_Shield: return 0_bi;
		case Moves::Flower_Shield: return 0_bi;
		case Moves::Grassy_Terrain: return 0_bi;
		case Moves::Misty_Terrain: return 0_bi;
		case Moves::Electrify: return 0_bi;
		case Moves::Play_Rough: return 90_bi;
		case Moves::Fairy_Wind: return 40_bi;
		case Moves::Moonblast: return 95_bi;
		case Moves::Boomburst: return 140_bi;
		case Moves::Fairy_Lock: return 0_bi;
		case Moves::Kings_Shield: return 0_bi;
		case Moves::Play_Nice: return 0_bi;
		case Moves::Confide: return 0_bi;
		case Moves::Diamond_Storm: return 100_bi;
		case Moves::Steam_Eruption: return 110_bi;
		case Moves::Hyperspace_Hole: return 80_bi;
		case Moves::Water_Shuriken: return 15_bi;
		case Moves::Mystical_Fire: return BOUNDED_CONDITIONAL(generation <= Generation::six, 65_bi, 75_bi);
		case Moves::Spiky_Shield: return 0_bi;
		case Moves::Aromatic_Mist: return 0_bi;
		case Moves::Eerie_Impulse: return 0_bi;
		case Moves::Venom_Drench: return 0_bi;
		case Moves::Powder: return 0_bi;
		case Moves::Geomancy: return 0_bi;
		case Moves::Magnetic_Flux: return 0_bi;
		case Moves::Happy_Hour: return 0_bi;
		case Moves::Electric_Terrain: return 0_bi;
		case Moves::Dazzling_Gleam: return 80_bi;
		case Moves::Celebrate: return 0_bi;
		case Moves::Hold_Hands: return 0_bi;
		case Moves::Baby_Doll_Eyes: return 0_bi;
		case Moves::Nuzzle: return 20_bi;
		case Moves::Hold_Back: return 40_bi;
		case Moves::Infestation: return 20_bi;
		case Moves::Power_Up_Punch: return 40_bi;
		case Moves::Oblivion_Wing: return 80_bi;
		case Moves::Thousand_Arrows: return 90_bi;
		case Moves::Thousand_Waves: return 90_bi;
		case Moves::Lands_Wrath: return 90_bi;
		case Moves::Light_of_Ruin: return 140_bi;
		case Moves::Origin_Pulse: return 110_bi;
		case Moves::Precipice_Blades: return 120_bi;
		case Moves::Dragon_Ascent: return 120_bi;
		case Moves::Hyperspace_Fury: return 100_bi;
		case Moves::Breakneck_Blitz: return 0_bi;
		case Moves::All_Out_Pummeling: return 0_bi;
		case Moves::Supersonic_Skystrike: return 0_bi;
		case Moves::Acid_Downpour: return 0_bi;
		case Moves::Tectonic_Rage: return 0_bi;
		case Moves::Continental_Crush: return 0_bi;
		case Moves::Savage_Spin_Out: return 0_bi;
		case Moves::Never_Ending_Nightmare: return 0_bi;
		case Moves::Corkscrew_Crash: return 0_bi;
		case Moves::Inferno_Overdrive: return 0_bi;
		case Moves::Hydro_Vortex: return 0_bi;
		case Moves::Bloom_Doom: return 0_bi;
		case Moves::Gigavolt_Havoc: return 0_bi;
		case Moves::Shattered_Psyche: return 0_bi;
		case Moves::Subzero_Slammer: return 0_bi;
		case Moves::Devastating_Drake: return 0_bi;
		case Moves::Black_Hole_Eclipse: return 0_bi;
		case Moves::Twinkle_Tackle: return 0_bi;
		case Moves::Catastropika: return 210_bi;
		case Moves::Shore_Up: return 0_bi;
		case Moves::First_Impression: return 90_bi;
		case Moves::Baneful_Bunker: return 0_bi;
		case Moves::Spirit_Shackle: return 80_bi;
		case Moves::Darkest_Lariat: return 85_bi;
		case Moves::Sparkling_Aria: return 90_bi;
		case Moves::Ice_Hammer: return 100_bi;
		case Moves::Floral_Healing: return 0_bi;
		case Moves::High_Horsepower: return 95_bi;
		case Moves::Strength_Sap: return 0_bi;
		case Moves::Solar_Blade: return 125_bi;
		case Moves::Leafage: return 40_bi;
		case Moves::Spotlight: return 0_bi;
		case Moves::Toxic_Thread: return 0_bi;
		case Moves::Laser_Focus: return 0_bi;
		case Moves::Gear_Up: return 0_bi;
		case Moves::Throat_Chop: return 80_bi;
		case Moves::Pollen_Puff: return 90_bi;
		case Moves::Anchor_Shot: return 80_bi;
		case Moves::Psychic_Terrain: return 0_bi;
		case Moves::Lunge: return 80_bi;
		case Moves::Fire_Lash: return 80_bi;
		case Moves::Power_Trip: return 20_bi;
		case Moves::Burn_Up: return 130_bi;
		case Moves::Speed_Swap: return 0_bi;
		case Moves::Smart_Strike: return 70_bi;
		case Moves::Purify: return 0_bi;
		case Moves::Revelation_Dance: return 90_bi;
		case Moves::Core_Enforcer: return 100_bi;
		case Moves::Trop_Kick: return 70_bi;
		case Moves::Instruct: return 0_bi;
		case Moves::Beak_Blast: return 100_bi;
		case Moves::Clanging_Scales: return 110_bi;
		case Moves::Dragon_Hammer: return 90_bi;
		case Moves::Brutal_Swing: return 60_bi;
		case Moves::Aurora_Veil: return 0_bi;
		case Moves::Sinister_Arrow_Raid: return 180_bi;
		case Moves::Malicious_Moonsault: return 180_bi;
		case Moves::Oceanic_Operetta: return 195_bi;
		case Moves::Guardian_of_Alola: return 0_bi;
		case Moves::Soul_Stealing_7_Star_Strike: return 195_bi;
		case Moves::Stoked_Sparksurfer: return 175_bi;
		case Moves::Pulverizing_Pancake: return 210_bi;
		case Moves::Extreme_Evoboost: return 0_bi;
		case Moves::Genesis_Supernova: return 185_bi;
		case Moves::Shell_Trap: return 150_bi;
		case Moves::Fleur_Cannon: return 130_bi;
		case Moves::Psychic_Fangs: return 85_bi;
		case Moves::Stomping_Tantrum: return 75_bi;
		case Moves::Shadow_Bone: return 85_bi;
		case Moves::Accelerock: return 40_bi;
		case Moves::Liquidation: return 85_bi;
		case Moves::Prismatic_Laser: return 160_bi;
		case Moves::Spectral_Thief: return 90_bi;
		case Moves::Sunsteel_Strike: return 100_bi;
		case Moves::Moongeist_Beam: return 100_bi;
		case Moves::Tearful_Look: return 0_bi;
		case Moves::Zing_Zap: return 80_bi;
		case Moves::Natures_Madness: return 0_bi;
		case Moves::Multi_Attack: return BOUNDED_CONDITIONAL(generation <= Generation::seven, 90_bi, 120_bi);
		case Moves::m10000000_Volt_Thunderbolt: return 195_bi;
		case Moves::Mind_Blown: return 150_bi;
		case Moves::Plasma_Fists: return 100_bi;
		case Moves::Photon_Geyser: return 100_bi;
		case Moves::Light_That_Burns_the_Sky: return 200_bi;
		case Moves::Searing_Sunraze_Smash: return 200_bi;
		case Moves::Menacing_Moonraze_Maelstrom: return 200_bi;
		case Moves::Lets_Snuggle_Forever: return 190_bi;
		case Moves::Splintered_Stormshards: return 190_bi;
		case Moves::Clangorous_Soulblaze: return 185_bi;
		case Moves::Zippy_Zap: return 50_bi;
		case Moves::Splishy_Splash: return 90_bi;
		case Moves::Floaty_Fall: return 90_bi;
		case Moves::Pika_Papow: return 0_bi;
		case Moves::Bouncy_Bubble: return 90_bi;
		case Moves::Buzzy_Buzz: return 90_bi;
		case Moves::Sizzly_Slide: return 90_bi;
		case Moves::Glitzy_Glow: return 90_bi;
		case Moves::Baddy_Bad: return 90_bi;
		case Moves::Sappy_Seed: return 90_bi;
		case Moves::Freezy_Frost: return 90_bi;
		case Moves::Sparkly_Swirl: return 90_bi;
		case Moves::Veevee_Volley: return 0_bi;
		case Moves::Double_Iron_Bash: return 60_bi;
	}
}

#define TECHNICALMACHINE_EXPLICIT_INSTANTIATION_IMPL(UserTeam, DefenderTeam) \
	template auto base_power(UserTeam const &, ExecutedMove<UserTeam>, DefenderTeam const &, Weather) -> BasePower

#define TECHNICALMACHINE_EXPLICIT_INSTANTIATION(generation) \
	TECHNICALMACHINE_EXPLICIT_INSTANTIATION_IMPL(Team<generation>, Team<generation>); \
	TECHNICALMACHINE_EXPLICIT_INSTANTIATION_IMPL(KnownTeam<generation>, KnownTeam<generation>); \
	TECHNICALMACHINE_EXPLICIT_INSTANTIATION_IMPL(KnownTeam<generation>, SeenTeam<generation>); \
	TECHNICALMACHINE_EXPLICIT_INSTANTIATION_IMPL(SeenTeam<generation>, KnownTeam<generation>); \
	TECHNICALMACHINE_EXPLICIT_INSTANTIATION_IMPL(SeenTeam<generation>, SeenTeam<generation>)

TECHNICALMACHINE_EXPLICIT_INSTANTIATION(Generation::one);
TECHNICALMACHINE_EXPLICIT_INSTANTIATION(Generation::two);
TECHNICALMACHINE_EXPLICIT_INSTANTIATION(Generation::three);
TECHNICALMACHINE_EXPLICIT_INSTANTIATION(Generation::four);
TECHNICALMACHINE_EXPLICIT_INSTANTIATION(Generation::five);
TECHNICALMACHINE_EXPLICIT_INSTANTIATION(Generation::six);
TECHNICALMACHINE_EXPLICIT_INSTANTIATION(Generation::seven);
TECHNICALMACHINE_EXPLICIT_INSTANTIATION(Generation::eight);

} // namespace technicalmachine
