// Copyright David Stone 2020.
// Distributed under the Boost Software License, Version 1.0.
// (See accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt)

export module tm.move.category;

import tm.move.known_move;
import tm.move.move_name;

import tm.type.type;

import tm.generation;

namespace technicalmachine {

enum class MoveCategory { physical, special, other };

constexpr auto type_based_category(Type const type) {
	switch (type) {
		case Type::Bug: return MoveCategory::physical;
		case Type::Dark: return MoveCategory::special;
		case Type::Dragon: return MoveCategory::special;
		case Type::Electric: return MoveCategory::special;
		case Type::Fairy: return MoveCategory::physical; // unreachable?
		case Type::Fighting: return MoveCategory::physical;
		case Type::Fire: return MoveCategory::special;
		case Type::Flying: return MoveCategory::physical;
		case Type::Ghost: return MoveCategory::physical;
		case Type::Grass: return MoveCategory::special;
		case Type::Ground: return MoveCategory::physical;
		case Type::Ice: return MoveCategory::special;
		case Type::Normal: return MoveCategory::physical;
		case Type::Poison: return MoveCategory::physical;
		case Type::Psychic: return MoveCategory::special;
		case Type::Rock: return MoveCategory::physical;
		case Type::Steel: return MoveCategory::physical;
		case Type::Water: return MoveCategory::special;
		case Type::Typeless: return MoveCategory::physical;
	}
}

constexpr auto move_category(Generation const generation, KnownMove const move) {
	switch (move.name) {
		case MoveName::Hit_Self:
		case MoveName::Pound:
		case MoveName::Karate_Chop:
		case MoveName::Double_Slap:
		case MoveName::Comet_Punch:
		case MoveName::Mega_Punch:
		case MoveName::Pay_Day:
		case MoveName::Fire_Punch:
		case MoveName::Ice_Punch:
		case MoveName::Thunder_Punch:
		case MoveName::Scratch:
		case MoveName::Vise_Grip:
		case MoveName::Guillotine:
		case MoveName::Cut:
		case MoveName::Wing_Attack:
		case MoveName::Fly:
		case MoveName::Bind:
		case MoveName::Slam:
		case MoveName::Vine_Whip:
		case MoveName::Stomp:
		case MoveName::Double_Kick:
		case MoveName::Mega_Kick:
		case MoveName::Jump_Kick:
		case MoveName::Rolling_Kick:
		case MoveName::Headbutt:
		case MoveName::Horn_Attack:
		case MoveName::Fury_Attack:
		case MoveName::Horn_Drill:
		case MoveName::Tackle:
		case MoveName::Body_Slam:
		case MoveName::Wrap:
		case MoveName::Take_Down:
		case MoveName::Thrash:
		case MoveName::Double_Edge:
		case MoveName::Poison_Sting:
		case MoveName::Twineedle:
		case MoveName::Pin_Missile:
		case MoveName::Bite:
		case MoveName::Peck:
		case MoveName::Drill_Peck:
		case MoveName::Submission:
		case MoveName::Low_Kick:
		case MoveName::Counter:
		case MoveName::Seismic_Toss:
		case MoveName::Strength:
		case MoveName::Razor_Leaf:
		case MoveName::Rock_Throw:
		case MoveName::Earthquake:
		case MoveName::Fissure:
		case MoveName::Dig:
		case MoveName::Quick_Attack:
		case MoveName::Rage:
		case MoveName::Bide:
		case MoveName::Self_Destruct:
		case MoveName::Egg_Bomb:
		case MoveName::Lick:
		case MoveName::Bone_Club:
		case MoveName::Waterfall:
		case MoveName::Clamp:
		case MoveName::Skull_Bash:
		case MoveName::Spike_Cannon:
		case MoveName::Constrict:
		case MoveName::High_Jump_Kick:
		case MoveName::Barrage:
		case MoveName::Leech_Life:
		case MoveName::Sky_Attack:
		case MoveName::Dizzy_Punch:
		case MoveName::Crabhammer:
		case MoveName::Explosion:
		case MoveName::Fury_Swipes:
		case MoveName::Bonemerang:
		case MoveName::Rock_Slide:
		case MoveName::Hyper_Fang:
		case MoveName::Super_Fang:
		case MoveName::Slash:
		case MoveName::Struggle:
		case MoveName::Triple_Kick:
		case MoveName::Thief:
		case MoveName::Flame_Wheel:
		case MoveName::Flail:
		case MoveName::Reversal:
		case MoveName::Mach_Punch:
		case MoveName::Feint_Attack:
		case MoveName::Bone_Rush:
		case MoveName::Outrage:
		case MoveName::Rollout:
		case MoveName::False_Swipe:
		case MoveName::Spark:
		case MoveName::Fury_Cutter:
		case MoveName::Steel_Wing:
		case MoveName::Return:
		case MoveName::Present:
		case MoveName::Frustration:
		case MoveName::Sacred_Fire:
		case MoveName::Magnitude:
		case MoveName::Dynamic_Punch:
		case MoveName::Megahorn:
		case MoveName::Pursuit:
		case MoveName::Rapid_Spin:
		case MoveName::Iron_Tail:
		case MoveName::Metal_Claw:
		case MoveName::Vital_Throw:
		case MoveName::Cross_Chop:
		case MoveName::Crunch:
		case MoveName::Extreme_Speed:
		case MoveName::Rock_Smash:
		case MoveName::Beat_Up:
		case MoveName::Fake_Out:
		case MoveName::Facade:
		case MoveName::Focus_Punch:
		case MoveName::Smelling_Salts:
		case MoveName::Superpower:
		case MoveName::Revenge:
		case MoveName::Brick_Break:
		case MoveName::Knock_Off:
		case MoveName::Endeavor:
		case MoveName::Secret_Power:
		case MoveName::Dive:
		case MoveName::Arm_Thrust:
		case MoveName::Blaze_Kick:
		case MoveName::Ice_Ball:
		case MoveName::Needle_Arm:
		case MoveName::Poison_Fang:
		case MoveName::Crush_Claw:
		case MoveName::Meteor_Mash:
		case MoveName::Astonish:
		case MoveName::Rock_Tomb:
		case MoveName::Shadow_Punch:
		case MoveName::Sky_Uppercut:
		case MoveName::Sand_Tomb:
		case MoveName::Bullet_Seed:
		case MoveName::Aerial_Ace:
		case MoveName::Icicle_Spear:
		case MoveName::Dragon_Claw:
		case MoveName::Bounce:
		case MoveName::Poison_Tail:
		case MoveName::Covet:
		case MoveName::Volt_Tackle:
		case MoveName::Leaf_Blade:
		case MoveName::Rock_Blast:
		case MoveName::Wake_Up_Slap:
		case MoveName::Hammer_Arm:
		case MoveName::Gyro_Ball:
		case MoveName::Natural_Gift:
		case MoveName::Feint:
		case MoveName::Pluck:
		case MoveName::Metal_Burst:
		case MoveName::U_turn:
		case MoveName::Close_Combat:
		case MoveName::Payback:
		case MoveName::Assurance:
		case MoveName::Fling:
		case MoveName::Punishment:
		case MoveName::Last_Resort:
		case MoveName::Sucker_Punch:
		case MoveName::Flare_Blitz:
		case MoveName::Force_Palm:
		case MoveName::Poison_Jab:
		case MoveName::Night_Slash:
		case MoveName::Aqua_Tail:
		case MoveName::Seed_Bomb:
		case MoveName::X_Scissor:
		case MoveName::Dragon_Rush:
		case MoveName::Drain_Punch:
		case MoveName::Brave_Bird:
		case MoveName::Giga_Impact:
		case MoveName::Bullet_Punch:
		case MoveName::Avalanche:
		case MoveName::Ice_Shard:
		case MoveName::Shadow_Claw:
		case MoveName::Thunder_Fang:
		case MoveName::Ice_Fang:
		case MoveName::Fire_Fang:
		case MoveName::Shadow_Sneak:
		case MoveName::Psycho_Cut:
		case MoveName::Zen_Headbutt:
		case MoveName::Rock_Climb:
		case MoveName::Power_Whip:
		case MoveName::Rock_Wrecker:
		case MoveName::Cross_Poison:
		case MoveName::Gunk_Shot:
		case MoveName::Iron_Head:
		case MoveName::Magnet_Bomb:
		case MoveName::Stone_Edge:
		case MoveName::Bug_Bite:
		case MoveName::Wood_Hammer:
		case MoveName::Aqua_Jet:
		case MoveName::Attack_Order:
		case MoveName::Head_Smash:
		case MoveName::Double_Hit:
		case MoveName::Crush_Grip:
		case MoveName::Shadow_Force:
		case MoveName::Smack_Down:
		case MoveName::Storm_Throw:
		case MoveName::Heavy_Slam:
		case MoveName::Flame_Charge:
		case MoveName::Low_Sweep:
		case MoveName::Foul_Play:
		case MoveName::Chip_Away:
		case MoveName::Sky_Drop:
		case MoveName::Circle_Throw:
		case MoveName::Acrobatics:
		case MoveName::Retaliate:
		case MoveName::Bulldoze:
		case MoveName::Dragon_Tail:
		case MoveName::Wild_Charge:
		case MoveName::Drill_Run:
		case MoveName::Dual_Chop:
		case MoveName::Heart_Stamp:
		case MoveName::Horn_Leech:
		case MoveName::Sacred_Sword:
		case MoveName::Razor_Shell:
		case MoveName::Heat_Crash:
		case MoveName::Steamroller:
		case MoveName::Tail_Slap:
		case MoveName::Head_Charge:
		case MoveName::Gear_Grind:
		case MoveName::Bolt_Strike:
		case MoveName::Freeze_Shock:
		case MoveName::Icicle_Crash:
		case MoveName::V_create:
		case MoveName::Fusion_Bolt:
		case MoveName::Flying_Press:
		case MoveName::Fell_Stinger:
		case MoveName::Phantom_Force:
		case MoveName::Petal_Blizzard:
		case MoveName::Play_Rough:
		case MoveName::Diamond_Storm:
		case MoveName::Nuzzle:
		case MoveName::Hold_Back:
		case MoveName::Power_Up_Punch:
		case MoveName::Thousand_Arrows:
		case MoveName::Thousand_Waves:
		case MoveName::Lands_Wrath:
		case MoveName::Precipice_Blades:
		case MoveName::Dragon_Ascent:
		case MoveName::Hyperspace_Fury:
		case MoveName::Catastropika:
		case MoveName::First_Impression:
		case MoveName::Spirit_Shackle:
		case MoveName::Darkest_Lariat:
		case MoveName::Ice_Hammer:
		case MoveName::High_Horsepower:
		case MoveName::Solar_Blade:
		case MoveName::Leafage:
		case MoveName::Throat_Chop:
		case MoveName::Anchor_Shot:
		case MoveName::Lunge:
		case MoveName::Fire_Lash:
		case MoveName::Power_Trip:
		case MoveName::Smart_Strike:
		case MoveName::Trop_Kick:
		case MoveName::Beak_Blast:
		case MoveName::Dragon_Hammer:
		case MoveName::Brutal_Swing:
		case MoveName::Sinister_Arrow_Raid:
		case MoveName::Malicious_Moonsault:
		case MoveName::Soul_Stealing_7_Star_Strike:
		case MoveName::Pulverizing_Pancake:
		case MoveName::Psychic_Fangs:
		case MoveName::Stomping_Tantrum:
		case MoveName::Shadow_Bone:
		case MoveName::Accelerock:
		case MoveName::Liquidation:
		case MoveName::Spectral_Thief:
		case MoveName::Sunsteel_Strike:
		case MoveName::Zing_Zap:
		case MoveName::Multi_Attack:
		case MoveName::Plasma_Fists:
		case MoveName::Lets_Snuggle_Forever:
		case MoveName::Splintered_Stormshards:
		case MoveName::Double_Iron_Bash:
		case MoveName::Jaw_Lock:
		case MoveName::Dragon_Darts:
		case MoveName::Bolt_Beak:
		case MoveName::Fishious_Rend:
		case MoveName::Body_Press:
		case MoveName::Drum_Beating:
		case MoveName::Snap_Trap:
		case MoveName::Pyro_Ball:
		case MoveName::Behemoth_Blade:
		case MoveName::Behemoth_Bash:
		case MoveName::Aura_Wheel:
		case MoveName::Breaking_Swipe:
		case MoveName::Branch_Poke:
		case MoveName::Grav_Apple:
		case MoveName::Spirit_Break:
		case MoveName::False_Surrender:
		case MoveName::Meteor_Assault:
		case MoveName::Steel_Roller:
		case MoveName::Scale_Shot:
		case MoveName::Grassy_Glide:
		case MoveName::Skitter_Smack:
		case MoveName::Lash_Out:
		case MoveName::Poltergeist:
		case MoveName::Flip_Turn:
		case MoveName::Triple_Axel:
		case MoveName::Dual_Wingbeat:
		case MoveName::Wicked_Blow:
		case MoveName::Surging_Strikes:
		case MoveName::Thunderous_Kick:
		case MoveName::Glacial_Lance:
			return generation <= Generation::three ?
				type_based_category(move.type) :
				MoveCategory::physical;
		case MoveName::Razor_Wind:
		case MoveName::Gust:
		case MoveName::Sonic_Boom:
		case MoveName::Acid:
		case MoveName::Ember:
		case MoveName::Flamethrower:
		case MoveName::Water_Gun:
		case MoveName::Hydro_Pump:
		case MoveName::Surf:
		case MoveName::Ice_Beam:
		case MoveName::Blizzard:
		case MoveName::Psybeam:
		case MoveName::Bubble_Beam:
		case MoveName::Aurora_Beam:
		case MoveName::Hyper_Beam:
		case MoveName::Absorb:
		case MoveName::Mega_Drain:
		case MoveName::Solar_Beam:
		case MoveName::Petal_Dance:
		case MoveName::Dragon_Rage:
		case MoveName::Fire_Spin:
		case MoveName::Thunder_Shock:
		case MoveName::Thunderbolt:
		case MoveName::Thunder:
		case MoveName::Confusion:
		case MoveName::Psychic:
		case MoveName::Night_Shade:
		case MoveName::Smog:
		case MoveName::Sludge:
		case MoveName::Fire_Blast:
		case MoveName::Swift:
		case MoveName::Dream_Eater:
		case MoveName::Bubble:
		case MoveName::Psywave:
		case MoveName::Tri_Attack:
		case MoveName::Snore:
		case MoveName::Aeroblast:
		case MoveName::Powder_Snow:
		case MoveName::Sludge_Bomb:
		case MoveName::Mud_Slap:
		case MoveName::Octazooka:
		case MoveName::Zap_Cannon:
		case MoveName::Icy_Wind:
		case MoveName::Giga_Drain:
		case MoveName::Dragon_Breath:
		case MoveName::Hidden_Power:
		case MoveName::Twister:
		case MoveName::Mirror_Coat:
		case MoveName::Ancient_Power:
		case MoveName::Shadow_Ball:
		case MoveName::Future_Sight:
		case MoveName::Whirlpool:
		case MoveName::Uproar:
		case MoveName::Spit_Up:
		case MoveName::Heat_Wave:
		case MoveName::Eruption:
		case MoveName::Luster_Purge:
		case MoveName::Mist_Ball:
		case MoveName::Hyper_Voice:
		case MoveName::Blast_Burn:
		case MoveName::Hydro_Cannon:
		case MoveName::Weather_Ball:
		case MoveName::Air_Cutter:
		case MoveName::Overheat:
		case MoveName::Silver_Wind:
		case MoveName::Water_Spout:
		case MoveName::Signal_Beam:
		case MoveName::Extrasensory:
		case MoveName::Sheer_Cold:
		case MoveName::Muddy_Water:
		case MoveName::Frenzy_Plant:
		case MoveName::Mud_Shot:
		case MoveName::Magical_Leaf:
		case MoveName::Shock_Wave:
		case MoveName::Water_Pulse:
		case MoveName::Doom_Desire:
		case MoveName::Psycho_Boost:
		case MoveName::Brine:
		case MoveName::Trump_Card:
		case MoveName::Wring_Out:
		case MoveName::Aura_Sphere:
		case MoveName::Dark_Pulse:
		case MoveName::Air_Slash:
		case MoveName::Bug_Buzz:
		case MoveName::Dragon_Pulse:
		case MoveName::Power_Gem:
		case MoveName::Vacuum_Wave:
		case MoveName::Focus_Blast:
		case MoveName::Energy_Ball:
		case MoveName::Earth_Power:
		case MoveName::Mud_Bomb:
		case MoveName::Mirror_Shot:
		case MoveName::Flash_Cannon:
		case MoveName::Draco_Meteor:
		case MoveName::Discharge:
		case MoveName::Lava_Plume:
		case MoveName::Leaf_Storm:
		case MoveName::Grass_Knot:
		case MoveName::Chatter:
		case MoveName::Judgment:
		case MoveName::Charge_Beam:
		case MoveName::Roar_of_Time:
		case MoveName::Spacial_Rend:
		case MoveName::Magma_Storm:
		case MoveName::Seed_Flare:
		case MoveName::Ominous_Wind:
		case MoveName::Psyshock:
		case MoveName::Venoshock:
		case MoveName::Flame_Burst:
		case MoveName::Sludge_Wave:
		case MoveName::Synchronoise:
		case MoveName::Electro_Ball:
		case MoveName::Acid_Spray:
		case MoveName::Round:
		case MoveName::Echoed_Voice:
		case MoveName::Clear_Smog:
		case MoveName::Stored_Power:
		case MoveName::Scald:
		case MoveName::Hex:
		case MoveName::Incinerate:
		case MoveName::Final_Gambit:
		case MoveName::Inferno:
		case MoveName::Water_Pledge:
		case MoveName::Fire_Pledge:
		case MoveName::Grass_Pledge:
		case MoveName::Volt_Switch:
		case MoveName::Struggle_Bug:
		case MoveName::Frost_Breath:
		case MoveName::Electroweb:
		case MoveName::Leaf_Tornado:
		case MoveName::Night_Daze:
		case MoveName::Psystrike:
		case MoveName::Hurricane:
		case MoveName::Searing_Shot:
		case MoveName::Techno_Blast:
		case MoveName::Relic_Song:
		case MoveName::Secret_Sword:
		case MoveName::Glaciate:
		case MoveName::Blue_Flare:
		case MoveName::Fiery_Dance:
		case MoveName::Ice_Burn:
		case MoveName::Snarl:
		case MoveName::Fusion_Flare:
		case MoveName::Belch:
		case MoveName::Parabolic_Charge:
		case MoveName::Freeze_Dry:
		case MoveName::Disarming_Voice:
		case MoveName::Draining_Kiss:
		case MoveName::Fairy_Wind:
		case MoveName::Moonblast:
		case MoveName::Boomburst:
		case MoveName::Steam_Eruption:
		case MoveName::Hyperspace_Hole:
		case MoveName::Mystical_Fire:
		case MoveName::Dazzling_Gleam:
		case MoveName::Infestation:
		case MoveName::Oblivion_Wing:
		case MoveName::Light_of_Ruin:
		case MoveName::Origin_Pulse:
		case MoveName::Sparkling_Aria:
		case MoveName::Pollen_Puff:
		case MoveName::Burn_Up:
		case MoveName::Revelation_Dance:
		case MoveName::Core_Enforcer:
		case MoveName::Clanging_Scales:
		case MoveName::Oceanic_Operetta:
		case MoveName::Guardian_of_Alola:
		case MoveName::Stoked_Sparksurfer:
		case MoveName::Genesis_Supernova:
		case MoveName::Shell_Trap:
		case MoveName::Fleur_Cannon:
		case MoveName::Prismatic_Laser:
		case MoveName::Moongeist_Beam:
		case MoveName::Natures_Madness:
		case MoveName::m10000000_Volt_Thunderbolt:
		case MoveName::Mind_Blown:
		case MoveName::Photon_Geyser:
		case MoveName::Light_That_Burns_the_Sky:
		case MoveName::Searing_Sunraze_Smash:
		case MoveName::Menacing_Moonraze_Maelstrom:
		case MoveName::Clangorous_Soulblaze:
		case MoveName::Dynamax_Cannon:
		case MoveName::Snipe_Shot:
		case MoveName::Overdrive:
		case MoveName::Apple_Acid:
		case MoveName::Strange_Steam:
		case MoveName::Eternabeam:
		case MoveName::Steel_Beam:
		case MoveName::Expanding_Force:
		case MoveName::Meteor_Beam:
		case MoveName::Shell_Side_Arm:
		case MoveName::Misty_Explosion:
		case MoveName::Rising_Voltage:
		case MoveName::Terrain_Pulse:
		case MoveName::Burning_Jealousy:
		case MoveName::Scorching_Sands:
		case MoveName::Thunder_Cage:
		case MoveName::Dragon_Energy:
		case MoveName::Freezing_Glare:
		case MoveName::Fiery_Wrath:
		case MoveName::Astral_Barrage:
		case MoveName::Eerie_Spell:
			return generation <= Generation::three ?
				type_based_category(move.type) :
				MoveCategory::special;
		case MoveName::Pass:
		case MoveName::Switch0:
		case MoveName::Switch1:
		case MoveName::Switch2:
		case MoveName::Switch3:
		case MoveName::Switch4:
		case MoveName::Switch5:
		case MoveName::Swords_Dance:
		case MoveName::Whirlwind:
		case MoveName::Sand_Attack:
		case MoveName::Tail_Whip:
		case MoveName::Leer:
		case MoveName::Growl:
		case MoveName::Roar:
		case MoveName::Sing:
		case MoveName::Supersonic:
		case MoveName::Disable:
		case MoveName::Mist:
		case MoveName::Leech_Seed:
		case MoveName::Growth:
		case MoveName::Poison_Powder:
		case MoveName::Stun_Spore:
		case MoveName::Sleep_Powder:
		case MoveName::String_Shot:
		case MoveName::Thunder_Wave:
		case MoveName::Toxic:
		case MoveName::Hypnosis:
		case MoveName::Meditate:
		case MoveName::Agility:
		case MoveName::Teleport:
		case MoveName::Mimic:
		case MoveName::Screech:
		case MoveName::Double_Team:
		case MoveName::Recover:
		case MoveName::Harden:
		case MoveName::Minimize:
		case MoveName::Smokescreen:
		case MoveName::Confuse_Ray:
		case MoveName::Withdraw:
		case MoveName::Defense_Curl:
		case MoveName::Barrier:
		case MoveName::Light_Screen:
		case MoveName::Haze:
		case MoveName::Reflect:
		case MoveName::Focus_Energy:
		case MoveName::Metronome:
		case MoveName::Mirror_Move:
		case MoveName::Amnesia:
		case MoveName::Kinesis:
		case MoveName::Soft_Boiled:
		case MoveName::Glare:
		case MoveName::Poison_Gas:
		case MoveName::Lovely_Kiss:
		case MoveName::Transform:
		case MoveName::Spore:
		case MoveName::Flash:
		case MoveName::Splash:
		case MoveName::Acid_Armor:
		case MoveName::Rest:
		case MoveName::Sharpen:
		case MoveName::Conversion:
		case MoveName::Substitute:
		case MoveName::Sketch:
		case MoveName::Spider_Web:
		case MoveName::Mind_Reader:
		case MoveName::Nightmare:
		case MoveName::Curse:
		case MoveName::Conversion_2:
		case MoveName::Cotton_Spore:
		case MoveName::Spite:
		case MoveName::Protect:
		case MoveName::Scary_Face:
		case MoveName::Sweet_Kiss:
		case MoveName::Belly_Drum:
		case MoveName::Spikes:
		case MoveName::Foresight:
		case MoveName::Destiny_Bond:
		case MoveName::Perish_Song:
		case MoveName::Detect:
		case MoveName::Lock_On:
		case MoveName::Sandstorm:
		case MoveName::Endure:
		case MoveName::Charm:
		case MoveName::Swagger:
		case MoveName::Milk_Drink:
		case MoveName::Mean_Look:
		case MoveName::Attract:
		case MoveName::Sleep_Talk:
		case MoveName::Heal_Bell:
		case MoveName::Safeguard:
		case MoveName::Pain_Split:
		case MoveName::Baton_Pass:
		case MoveName::Encore:
		case MoveName::Sweet_Scent:
		case MoveName::Morning_Sun:
		case MoveName::Synthesis:
		case MoveName::Moonlight:
		case MoveName::Rain_Dance:
		case MoveName::Sunny_Day:
		case MoveName::Psych_Up:
		case MoveName::Stockpile:
		case MoveName::Swallow:
		case MoveName::Hail:
		case MoveName::Torment:
		case MoveName::Flatter:
		case MoveName::Will_O_Wisp:
		case MoveName::Memento:
		case MoveName::Follow_Me:
		case MoveName::Nature_Power:
		case MoveName::Charge:
		case MoveName::Taunt:
		case MoveName::Helping_Hand:
		case MoveName::Trick:
		case MoveName::Role_Play:
		case MoveName::Wish:
		case MoveName::Assist:
		case MoveName::Ingrain:
		case MoveName::Magic_Coat:
		case MoveName::Recycle:
		case MoveName::Yawn:
		case MoveName::Skill_Swap:
		case MoveName::Imprison:
		case MoveName::Refresh:
		case MoveName::Grudge:
		case MoveName::Snatch:
		case MoveName::Camouflage:
		case MoveName::Tail_Glow:
		case MoveName::Feather_Dance:
		case MoveName::Teeter_Dance:
		case MoveName::Mud_Sport:
		case MoveName::Slack_Off:
		case MoveName::Aromatherapy:
		case MoveName::Fake_Tears:
		case MoveName::Odor_Sleuth:
		case MoveName::Metal_Sound:
		case MoveName::Grass_Whistle:
		case MoveName::Tickle:
		case MoveName::Cosmic_Power:
		case MoveName::Iron_Defense:
		case MoveName::Block:
		case MoveName::Howl:
		case MoveName::Bulk_Up:
		case MoveName::Water_Sport:
		case MoveName::Calm_Mind:
		case MoveName::Dragon_Dance:
		case MoveName::Roost:
		case MoveName::Gravity:
		case MoveName::Miracle_Eye:
		case MoveName::Healing_Wish:
		case MoveName::Tailwind:
		case MoveName::Acupressure:
		case MoveName::Embargo:
		case MoveName::Psycho_Shift:
		case MoveName::Heal_Block:
		case MoveName::Power_Trick:
		case MoveName::Gastro_Acid:
		case MoveName::Lucky_Chant:
		case MoveName::Me_First:
		case MoveName::Copycat:
		case MoveName::Power_Swap:
		case MoveName::Guard_Swap:
		case MoveName::Worry_Seed:
		case MoveName::Toxic_Spikes:
		case MoveName::Heart_Swap:
		case MoveName::Aqua_Ring:
		case MoveName::Magnet_Rise:
		case MoveName::Rock_Polish:
		case MoveName::Switcheroo:
		case MoveName::Nasty_Plot:
		case MoveName::Defog:
		case MoveName::Trick_Room:
		case MoveName::Captivate:
		case MoveName::Stealth_Rock:
		case MoveName::Defend_Order:
		case MoveName::Heal_Order:
		case MoveName::Lunar_Dance:
		case MoveName::Dark_Void:
		case MoveName::Hone_Claws:
		case MoveName::Wide_Guard:
		case MoveName::Guard_Split:
		case MoveName::Power_Split:
		case MoveName::Wonder_Room:
		case MoveName::Autotomize:
		case MoveName::Rage_Powder:
		case MoveName::Telekinesis:
		case MoveName::Magic_Room:
		case MoveName::Quiver_Dance:
		case MoveName::Soak:
		case MoveName::Coil:
		case MoveName::Simple_Beam:
		case MoveName::Entrainment:
		case MoveName::After_You:
		case MoveName::Quick_Guard:
		case MoveName::Ally_Switch:
		case MoveName::Shell_Smash:
		case MoveName::Heal_Pulse:
		case MoveName::Shift_Gear:
		case MoveName::Quash:
		case MoveName::Reflect_Type:
		case MoveName::Bestow:
		case MoveName::Work_Up:
		case MoveName::Cotton_Guard:
		case MoveName::Mat_Block:
		case MoveName::Rototiller:
		case MoveName::Sticky_Web:
		case MoveName::Trick_or_Treat:
		case MoveName::Noble_Roar:
		case MoveName::Ion_Deluge:
		case MoveName::Forests_Curse:
		case MoveName::Parting_Shot:
		case MoveName::Topsy_Turvy:
		case MoveName::Crafty_Shield:
		case MoveName::Flower_Shield:
		case MoveName::Grassy_Terrain:
		case MoveName::Misty_Terrain:
		case MoveName::Electrify:
		case MoveName::Fairy_Lock:
		case MoveName::Kings_Shield:
		case MoveName::Play_Nice:
		case MoveName::Confide:
		case MoveName::Spiky_Shield:
		case MoveName::Aromatic_Mist:
		case MoveName::Eerie_Impulse:
		case MoveName::Venom_Drench:
		case MoveName::Powder:
		case MoveName::Geomancy:
		case MoveName::Magnetic_Flux:
		case MoveName::Happy_Hour:
		case MoveName::Electric_Terrain:
		case MoveName::Celebrate:
		case MoveName::Hold_Hands:
		case MoveName::Baby_Doll_Eyes:
		case MoveName::Shore_Up:
		case MoveName::Baneful_Bunker:
		case MoveName::Floral_Healing:
		case MoveName::Strength_Sap:
		case MoveName::Spotlight:
		case MoveName::Toxic_Thread:
		case MoveName::Laser_Focus:
		case MoveName::Gear_Up:
		case MoveName::Psychic_Terrain:
		case MoveName::Speed_Swap:
		case MoveName::Purify:
		case MoveName::Instruct:
		case MoveName::Aurora_Veil:
		case MoveName::Extreme_Evoboost:
		case MoveName::Tearful_Look:
		case MoveName::Max_Guard:
		case MoveName::Stuff_Cheeks:
		case MoveName::No_Retreat:
		case MoveName::Tar_Shot:
		case MoveName::Magic_Powder:
		case MoveName::Teatime:
		case MoveName::Octolock:
		case MoveName::Court_Change:
		case MoveName::Clangorous_Soul:
		case MoveName::Decorate:
		case MoveName::Life_Dew:
		case MoveName::Obstruct:
		case MoveName::Corrosive_Gas:
		case MoveName::Coaching:
		case MoveName::Jungle_Healing:
			return MoveCategory::other;
		// TODO, can be either
		case MoveName::Water_Shuriken:
			return generation <= Generation::six ? MoveCategory::physical : MoveCategory::special;
		case MoveName::Breakneck_Blitz:
		case MoveName::All_Out_Pummeling:
		case MoveName::Supersonic_Skystrike:
		case MoveName::Acid_Downpour:
		case MoveName::Tectonic_Rage:
		case MoveName::Continental_Crush:
		case MoveName::Savage_Spin_Out:
		case MoveName::Never_Ending_Nightmare:
		case MoveName::Corkscrew_Crash:
		case MoveName::Inferno_Overdrive:
		case MoveName::Hydro_Vortex:
		case MoveName::Bloom_Doom:
		case MoveName::Gigavolt_Havoc:
		case MoveName::Shattered_Psyche:
		case MoveName::Subzero_Slammer:
		case MoveName::Devastating_Drake:
		case MoveName::Black_Hole_Eclipse:
		case MoveName::Twinkle_Tackle:
		case MoveName::Max_Flare:
		case MoveName::Max_Flutterby:
		case MoveName::Max_Lightning:
		case MoveName::Max_Strike:
		case MoveName::Max_Knuckle:
		case MoveName::Max_Phantasm:
		case MoveName::Max_Hailstorm:
		case MoveName::Max_Ooze:
		case MoveName::Max_Geyser:
		case MoveName::Max_Airstream:
		case MoveName::Max_Starfall:
		case MoveName::Max_Wyrmwind:
		case MoveName::Max_Mindstorm:
		case MoveName::Max_Rockfall:
		case MoveName::Max_Quake:
		case MoveName::Max_Darkness:
		case MoveName::Max_Overgrowth:
		case MoveName::Max_Steelspike:
			return MoveCategory::other;
	}
}

export constexpr auto is_physical(Generation const generation, KnownMove const move) -> bool {
	return move_category(generation, move) == MoveCategory::physical;
}

export constexpr auto is_special(Generation const generation, KnownMove const move) -> bool {
	return move_category(generation, move) == MoveCategory::special;
}

export constexpr auto is_damaging(MoveName const move) -> bool {
	// Generation and Type do not change whether a move is damaging
	return move_category(Generation::eight, {move, Type::Typeless}) != MoveCategory::other;
}

} // namespace technicalmachine
