# Makefile.in generated by automake 1.11.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008, 2009  Free Software Foundation,
# Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



# Copyright (C) 2011 David Stone
#
# This file is part of Technical Machine.
#
# Technical Machine is free software: you can redistribute it and / or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.


pkgdatadir = $(datadir)/technical-machine
pkgincludedir = $(includedir)/technical-machine
pkglibdir = $(libdir)/technical-machine
pkglibexecdir = $(libexecdir)/technical-machine
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
bin_PROGRAMS = ai$(EXEEXT)
subdir = .
DIST_COMMON = $(am__configure_deps) $(srcdir)/Makefile.am \
	$(srcdir)/Makefile.in $(top_srcdir)/configure compile depcomp \
	install-sh missing
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__installdirs = "$(DESTDIR)$(bindir)"
PROGRAMS = $(bin_PROGRAMS)
am__dirstamp = $(am__leading_dot)dirstamp
am_ai_OBJECTS = src/ai.$(OBJEXT) src/ability.$(OBJEXT) \
	src/analyze_logs.$(OBJEXT) src/battle.$(OBJEXT) \
	src/block.$(OBJEXT) src/damage.$(OBJEXT) \
	src/endofturn.$(OBJEXT) src/evaluate.$(OBJEXT) \
	src/expectiminimax.$(OBJEXT) src/gender.$(OBJEXT) \
	src/heal.$(OBJEXT) src/item.$(OBJEXT) src/load_stats.$(OBJEXT) \
	src/move.$(OBJEXT) src/pokemon.$(OBJEXT) \
	src/reorder_moves.$(OBJEXT) src/stat.$(OBJEXT) \
	src/status.$(OBJEXT) src/switch.$(OBJEXT) src/team.$(OBJEXT) \
	src/teampredictor.$(OBJEXT) src/transposition.$(OBJEXT) \
	src/type.$(OBJEXT) src/weather.$(OBJEXT) \
	src/crypt/get_md5.$(OBJEXT) src/crypt/get_sha2.$(OBJEXT) \
	src/crypt/hex.$(OBJEXT) src/crypt/md5.$(OBJEXT) \
	src/crypt/rijndael.$(OBJEXT) src/crypt/sha2.$(OBJEXT) \
	src/network/connect.$(OBJEXT) src/network/inmessage.$(OBJEXT) \
	src/network/outmessage.$(OBJEXT) \
	src/pokemon_lab/battle.$(OBJEXT) \
	src/pokemon_lab/battle_settings.$(OBJEXT) \
	src/pokemon_lab/connect.$(OBJEXT) \
	src/pokemon_lab/conversion.$(OBJEXT) \
	src/pokemon_lab/file.$(OBJEXT) \
	src/pokemon_lab/inmessage.$(OBJEXT) \
	src/pokemon_lab/outmessage.$(OBJEXT) \
	src/pokemon_online/battle.$(OBJEXT) \
	src/pokemon_online/battle_settings.$(OBJEXT) \
	src/pokemon_online/connect.$(OBJEXT) \
	src/pokemon_online/conversion.$(OBJEXT) \
	src/pokemon_online/file.$(OBJEXT) \
	src/pokemon_online/inmessage.$(OBJEXT) \
	src/pokemon_online/outmessage.$(OBJEXT) \
	src/pokemon_online/read_user_info.$(OBJEXT)
ai_OBJECTS = $(am_ai_OBJECTS)
ai_LDADD = $(LDADD)
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
CXXLD = $(CXX)
CXXLINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) \
	-o $@
SOURCES = $(ai_SOURCES)
DIST_SOURCES = $(ai_SOURCES)
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  { test ! -d "$(distdir)" \
    || { find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
         && rm -fr "$(distdir)"; }; }
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/david/technical-machine/missing --run aclocal-1.11
AMTAR = ${SHELL} /home/david/technical-machine/missing --run tar
AUTOCONF = ${SHELL} /home/david/technical-machine/missing --run autoconf
AUTOHEADER = ${SHELL} /home/david/technical-machine/missing --run autoheader
AUTOMAKE = ${SHELL} /home/david/technical-machine/missing --run automake-1.11
AWK = gawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = $(warnings) -g -std=c99
CPP = gcc -E
CPPFLAGS = 
CXX = g++
CXXDEPMODE = depmode=gcc3
CXXFLAGS = $(warnings) -g -std=c++0x
CYGPATH_W = echo
DEFS = -DPACKAGE_NAME=\"technical-machine\" -DPACKAGE_TARNAME=\"technical-machine\" -DPACKAGE_VERSION=\"1\" -DPACKAGE_STRING=\"technical-machine\ 1\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"technical-machine\" -DVERSION=\"1\" -DHAVE_LIBBOOST_FILESYSTEM=1 -DHAVE_LIBBOOST_SYSTEM=1 -DHAVE_LIBFLTK=1 -DHAVE_LIBPTHREAD=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_ARPA_INET_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_SYS_PARAM_H=1 -DHAVE__BOOL=1 -DHAVE_STDBOOL_H=1 -DHAVE_STDLIB_H=1 -DHAVE_MALLOC=1 -DHAVE_MEMSET=1 -DHAVE_SOCKET=1
DEPDIR = .deps
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EXEEXT = 
GREP = /bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = 
LIBOBJS = 
LIBS = -lpthread -lfltk -lboost_system -lboost_filesystem 
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/david/technical-machine/missing --run makeinfo
MKDIR_P = /bin/mkdir -p
OBJEXT = o
PACKAGE = technical-machine
PACKAGE_BUGREPORT = 
PACKAGE_NAME = technical-machine
PACKAGE_STRING = technical-machine 1
PACKAGE_TARNAME = technical-machine
PACKAGE_URL = 
PACKAGE_VERSION = 1
PATH_SEPARATOR = :
SET_MAKE = 
SHELL = /bin/sh
STRIP = 
VERSION = 1
abs_builddir = /home/david/technical-machine
abs_srcdir = /home/david/technical-machine
abs_top_builddir = /home/david/technical-machine
abs_top_srcdir = /home/david/technical-machine
ac_ct_CC = gcc
ac_ct_CXX = g++
am__include = include
am__leading_dot = .
am__quote = 
am__tar = ${AMTAR} chof - "$$tardir"
am__untar = ${AMTAR} xf -
bindir = ${exec_prefix}/bin
build_alias = 
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host_alias = 
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/david/technical-machine/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = /bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
warnings = -Wall -Wextra -pedantic -Wformat=2 -Wno-unused
fulloptimizations = -DNDEBUG -O3 -march=native -funsafe-loop-optimizations
tournament = $(fulloptimizations) -flto -fwhole-program
ai_SOURCES = src/ai.cpp src/ability.cpp src/analyze_logs.cpp src/battle.cpp src/block.cpp src/damage.cpp src/endofturn.cpp src/evaluate.cpp src/expectiminimax.cpp src/gender.cpp src/heal.cpp src/item.cpp src/load_stats.cpp src/move.cpp src/pokemon.cpp src/reorder_moves.cpp src/stat.cpp src/status.cpp src/switch.cpp src/team.cpp src/teampredictor.cpp src/transposition.cpp src/type.cpp src/weather.cpp \
	src/crypt/get_md5.cpp src/crypt/get_sha2.cpp src/crypt/hex.cpp src/crypt/md5.c src/crypt/rijndael.cpp src/crypt/sha2.c \
	src/network/connect.cpp src/network/inmessage.cpp src/network/outmessage.cpp \
	src/pokemon_lab/battle.cpp src/pokemon_lab/battle_settings.cpp src/pokemon_lab/connect.cpp src/pokemon_lab/conversion.cpp src/pokemon_lab/file.cpp src/pokemon_lab/inmessage.cpp src/pokemon_lab/outmessage.cpp \
	src/pokemon_online/battle.cpp src/pokemon_online/battle_settings.cpp src/pokemon_online/connect.cpp src/pokemon_online/conversion.cpp src/pokemon_online/file.cpp src/pokemon_online/inmessage.cpp src/pokemon_online/outmessage.cpp src/pokemon_online/read_user_info.cpp

all: all-am

.SUFFIXES:
.SUFFIXES: .c .cpp .o .obj
am--refresh:
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	test -z "$(bindir)" || $(MKDIR_P) "$(DESTDIR)$(bindir)"
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p; \
	  then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	      echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	      $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' `; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)
src/$(am__dirstamp):
	@$(MKDIR_P) src
	@: > src/$(am__dirstamp)
src/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/$(DEPDIR)
	@: > src/$(DEPDIR)/$(am__dirstamp)
src/ai.$(OBJEXT): src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/ability.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/analyze_logs.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/battle.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/block.$(OBJEXT): src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/damage.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/endofturn.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/evaluate.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/expectiminimax.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/gender.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/heal.$(OBJEXT): src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/item.$(OBJEXT): src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/load_stats.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/move.$(OBJEXT): src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/pokemon.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/reorder_moves.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/stat.$(OBJEXT): src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/status.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/switch.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/team.$(OBJEXT): src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/teampredictor.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/transposition.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/type.$(OBJEXT): src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/weather.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/crypt/$(am__dirstamp):
	@$(MKDIR_P) src/crypt
	@: > src/crypt/$(am__dirstamp)
src/crypt/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/crypt/$(DEPDIR)
	@: > src/crypt/$(DEPDIR)/$(am__dirstamp)
src/crypt/get_md5.$(OBJEXT): src/crypt/$(am__dirstamp) \
	src/crypt/$(DEPDIR)/$(am__dirstamp)
src/crypt/get_sha2.$(OBJEXT): src/crypt/$(am__dirstamp) \
	src/crypt/$(DEPDIR)/$(am__dirstamp)
src/crypt/hex.$(OBJEXT): src/crypt/$(am__dirstamp) \
	src/crypt/$(DEPDIR)/$(am__dirstamp)
src/crypt/md5.$(OBJEXT): src/crypt/$(am__dirstamp) \
	src/crypt/$(DEPDIR)/$(am__dirstamp)
src/crypt/rijndael.$(OBJEXT): src/crypt/$(am__dirstamp) \
	src/crypt/$(DEPDIR)/$(am__dirstamp)
src/crypt/sha2.$(OBJEXT): src/crypt/$(am__dirstamp) \
	src/crypt/$(DEPDIR)/$(am__dirstamp)
src/network/$(am__dirstamp):
	@$(MKDIR_P) src/network
	@: > src/network/$(am__dirstamp)
src/network/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/network/$(DEPDIR)
	@: > src/network/$(DEPDIR)/$(am__dirstamp)
src/network/connect.$(OBJEXT): src/network/$(am__dirstamp) \
	src/network/$(DEPDIR)/$(am__dirstamp)
src/network/inmessage.$(OBJEXT): src/network/$(am__dirstamp) \
	src/network/$(DEPDIR)/$(am__dirstamp)
src/network/outmessage.$(OBJEXT): src/network/$(am__dirstamp) \
	src/network/$(DEPDIR)/$(am__dirstamp)
src/pokemon_lab/$(am__dirstamp):
	@$(MKDIR_P) src/pokemon_lab
	@: > src/pokemon_lab/$(am__dirstamp)
src/pokemon_lab/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/pokemon_lab/$(DEPDIR)
	@: > src/pokemon_lab/$(DEPDIR)/$(am__dirstamp)
src/pokemon_lab/battle.$(OBJEXT): src/pokemon_lab/$(am__dirstamp) \
	src/pokemon_lab/$(DEPDIR)/$(am__dirstamp)
src/pokemon_lab/battle_settings.$(OBJEXT):  \
	src/pokemon_lab/$(am__dirstamp) \
	src/pokemon_lab/$(DEPDIR)/$(am__dirstamp)
src/pokemon_lab/connect.$(OBJEXT): src/pokemon_lab/$(am__dirstamp) \
	src/pokemon_lab/$(DEPDIR)/$(am__dirstamp)
src/pokemon_lab/conversion.$(OBJEXT): src/pokemon_lab/$(am__dirstamp) \
	src/pokemon_lab/$(DEPDIR)/$(am__dirstamp)
src/pokemon_lab/file.$(OBJEXT): src/pokemon_lab/$(am__dirstamp) \
	src/pokemon_lab/$(DEPDIR)/$(am__dirstamp)
src/pokemon_lab/inmessage.$(OBJEXT): src/pokemon_lab/$(am__dirstamp) \
	src/pokemon_lab/$(DEPDIR)/$(am__dirstamp)
src/pokemon_lab/outmessage.$(OBJEXT): src/pokemon_lab/$(am__dirstamp) \
	src/pokemon_lab/$(DEPDIR)/$(am__dirstamp)
src/pokemon_online/$(am__dirstamp):
	@$(MKDIR_P) src/pokemon_online
	@: > src/pokemon_online/$(am__dirstamp)
src/pokemon_online/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/pokemon_online/$(DEPDIR)
	@: > src/pokemon_online/$(DEPDIR)/$(am__dirstamp)
src/pokemon_online/battle.$(OBJEXT):  \
	src/pokemon_online/$(am__dirstamp) \
	src/pokemon_online/$(DEPDIR)/$(am__dirstamp)
src/pokemon_online/battle_settings.$(OBJEXT):  \
	src/pokemon_online/$(am__dirstamp) \
	src/pokemon_online/$(DEPDIR)/$(am__dirstamp)
src/pokemon_online/connect.$(OBJEXT):  \
	src/pokemon_online/$(am__dirstamp) \
	src/pokemon_online/$(DEPDIR)/$(am__dirstamp)
src/pokemon_online/conversion.$(OBJEXT):  \
	src/pokemon_online/$(am__dirstamp) \
	src/pokemon_online/$(DEPDIR)/$(am__dirstamp)
src/pokemon_online/file.$(OBJEXT): src/pokemon_online/$(am__dirstamp) \
	src/pokemon_online/$(DEPDIR)/$(am__dirstamp)
src/pokemon_online/inmessage.$(OBJEXT):  \
	src/pokemon_online/$(am__dirstamp) \
	src/pokemon_online/$(DEPDIR)/$(am__dirstamp)
src/pokemon_online/outmessage.$(OBJEXT):  \
	src/pokemon_online/$(am__dirstamp) \
	src/pokemon_online/$(DEPDIR)/$(am__dirstamp)
src/pokemon_online/read_user_info.$(OBJEXT):  \
	src/pokemon_online/$(am__dirstamp) \
	src/pokemon_online/$(DEPDIR)/$(am__dirstamp)
ai$(EXEEXT): $(ai_OBJECTS) $(ai_DEPENDENCIES) 
	@rm -f ai$(EXEEXT)
	$(CXXLINK) $(ai_OBJECTS) $(ai_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)
	-rm -f src/ability.$(OBJEXT)
	-rm -f src/ai.$(OBJEXT)
	-rm -f src/analyze_logs.$(OBJEXT)
	-rm -f src/battle.$(OBJEXT)
	-rm -f src/block.$(OBJEXT)
	-rm -f src/crypt/get_md5.$(OBJEXT)
	-rm -f src/crypt/get_sha2.$(OBJEXT)
	-rm -f src/crypt/hex.$(OBJEXT)
	-rm -f src/crypt/md5.$(OBJEXT)
	-rm -f src/crypt/rijndael.$(OBJEXT)
	-rm -f src/crypt/sha2.$(OBJEXT)
	-rm -f src/damage.$(OBJEXT)
	-rm -f src/endofturn.$(OBJEXT)
	-rm -f src/evaluate.$(OBJEXT)
	-rm -f src/expectiminimax.$(OBJEXT)
	-rm -f src/gender.$(OBJEXT)
	-rm -f src/heal.$(OBJEXT)
	-rm -f src/item.$(OBJEXT)
	-rm -f src/load_stats.$(OBJEXT)
	-rm -f src/move.$(OBJEXT)
	-rm -f src/network/connect.$(OBJEXT)
	-rm -f src/network/inmessage.$(OBJEXT)
	-rm -f src/network/outmessage.$(OBJEXT)
	-rm -f src/pokemon.$(OBJEXT)
	-rm -f src/pokemon_lab/battle.$(OBJEXT)
	-rm -f src/pokemon_lab/battle_settings.$(OBJEXT)
	-rm -f src/pokemon_lab/connect.$(OBJEXT)
	-rm -f src/pokemon_lab/conversion.$(OBJEXT)
	-rm -f src/pokemon_lab/file.$(OBJEXT)
	-rm -f src/pokemon_lab/inmessage.$(OBJEXT)
	-rm -f src/pokemon_lab/outmessage.$(OBJEXT)
	-rm -f src/pokemon_online/battle.$(OBJEXT)
	-rm -f src/pokemon_online/battle_settings.$(OBJEXT)
	-rm -f src/pokemon_online/connect.$(OBJEXT)
	-rm -f src/pokemon_online/conversion.$(OBJEXT)
	-rm -f src/pokemon_online/file.$(OBJEXT)
	-rm -f src/pokemon_online/inmessage.$(OBJEXT)
	-rm -f src/pokemon_online/outmessage.$(OBJEXT)
	-rm -f src/pokemon_online/read_user_info.$(OBJEXT)
	-rm -f src/reorder_moves.$(OBJEXT)
	-rm -f src/stat.$(OBJEXT)
	-rm -f src/status.$(OBJEXT)
	-rm -f src/switch.$(OBJEXT)
	-rm -f src/team.$(OBJEXT)
	-rm -f src/teampredictor.$(OBJEXT)
	-rm -f src/transposition.$(OBJEXT)
	-rm -f src/type.$(OBJEXT)
	-rm -f src/weather.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include src/$(DEPDIR)/ability.Po
include src/$(DEPDIR)/ai.Po
include src/$(DEPDIR)/analyze_logs.Po
include src/$(DEPDIR)/battle.Po
include src/$(DEPDIR)/block.Po
include src/$(DEPDIR)/damage.Po
include src/$(DEPDIR)/endofturn.Po
include src/$(DEPDIR)/evaluate.Po
include src/$(DEPDIR)/expectiminimax.Po
include src/$(DEPDIR)/gender.Po
include src/$(DEPDIR)/heal.Po
include src/$(DEPDIR)/item.Po
include src/$(DEPDIR)/load_stats.Po
include src/$(DEPDIR)/move.Po
include src/$(DEPDIR)/pokemon.Po
include src/$(DEPDIR)/reorder_moves.Po
include src/$(DEPDIR)/stat.Po
include src/$(DEPDIR)/status.Po
include src/$(DEPDIR)/switch.Po
include src/$(DEPDIR)/team.Po
include src/$(DEPDIR)/teampredictor.Po
include src/$(DEPDIR)/transposition.Po
include src/$(DEPDIR)/type.Po
include src/$(DEPDIR)/weather.Po
include src/crypt/$(DEPDIR)/get_md5.Po
include src/crypt/$(DEPDIR)/get_sha2.Po
include src/crypt/$(DEPDIR)/hex.Po
include src/crypt/$(DEPDIR)/md5.Po
include src/crypt/$(DEPDIR)/rijndael.Po
include src/crypt/$(DEPDIR)/sha2.Po
include src/network/$(DEPDIR)/connect.Po
include src/network/$(DEPDIR)/inmessage.Po
include src/network/$(DEPDIR)/outmessage.Po
include src/pokemon_lab/$(DEPDIR)/battle.Po
include src/pokemon_lab/$(DEPDIR)/battle_settings.Po
include src/pokemon_lab/$(DEPDIR)/connect.Po
include src/pokemon_lab/$(DEPDIR)/conversion.Po
include src/pokemon_lab/$(DEPDIR)/file.Po
include src/pokemon_lab/$(DEPDIR)/inmessage.Po
include src/pokemon_lab/$(DEPDIR)/outmessage.Po
include src/pokemon_online/$(DEPDIR)/battle.Po
include src/pokemon_online/$(DEPDIR)/battle_settings.Po
include src/pokemon_online/$(DEPDIR)/connect.Po
include src/pokemon_online/$(DEPDIR)/conversion.Po
include src/pokemon_online/$(DEPDIR)/file.Po
include src/pokemon_online/$(DEPDIR)/inmessage.Po
include src/pokemon_online/$(DEPDIR)/outmessage.Po
include src/pokemon_online/$(DEPDIR)/read_user_info.Po

.c.o:
	depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c -o $@ $<

.c.obj:
	depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.cpp.o:
	depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ $<

.cpp.obj:
	depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	set x; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | bzip2 -9 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-lzma: distdir
	tardir=$(distdir) && $(am__tar) | lzma -9 -c >$(distdir).tar.lzma
	$(am__remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | xz -c >$(distdir).tar.xz
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lzma*) \
	  lzma -dc $(distdir).tar.lzma | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod a+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@$(am__cd) '$(distuninstallcheck_dir)' \
	&& test `$(distuninstallcheck_listfiles) | wc -l` -le 1 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS)
installdirs:
	for dir in "$(DESTDIR)$(bindir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)
	-rm -f src/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/$(am__dirstamp)
	-rm -f src/crypt/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/crypt/$(am__dirstamp)
	-rm -f src/network/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/network/$(am__dirstamp)
	-rm -f src/pokemon_lab/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/pokemon_lab/$(am__dirstamp)
	-rm -f src/pokemon_online/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/pokemon_online/$(am__dirstamp)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf src/$(DEPDIR) src/crypt/$(DEPDIR) src/network/$(DEPDIR) src/pokemon_lab/$(DEPDIR) src/pokemon_online/$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am:

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf src/$(DEPDIR) src/crypt/$(DEPDIR) src/network/$(DEPDIR) src/pokemon_lab/$(DEPDIR) src/pokemon_online/$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS

.MAKE: install-am install-strip

.PHONY: CTAGS GTAGS all all-am am--refresh check check-am clean \
	clean-binPROGRAMS clean-generic ctags dist dist-all dist-bzip2 \
	dist-gzip dist-lzma dist-shar dist-tarZ dist-xz dist-zip \
	distcheck distclean distclean-compile distclean-generic \
	distclean-tags distcleancheck distdir distuninstallcheck dvi \
	dvi-am html html-am info info-am install install-am \
	install-binPROGRAMS install-data install-data-am install-dvi \
	install-dvi-am install-exec install-exec-am install-html \
	install-html-am install-info install-info-am install-man \
	install-pdf install-pdf-am install-ps install-ps-am \
	install-strip installcheck installcheck-am installdirs \
	maintainer-clean maintainer-clean-generic mostlyclean \
	mostlyclean-compile mostlyclean-generic pdf pdf-am ps ps-am \
	tags uninstall uninstall-am uninstall-binPROGRAMS


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
