// Pokemon string functions
// Copyright (C) 2012 David Stone
//
// This file is part of Technical Machine.
//
// Technical Machine is free software: you can redistribute it and / or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.

#include "conversion.hpp"

#include <map>
#include <string>

#include "invalid_string_conversion.hpp"

#include "../pokemon/pokemon.hpp"
#include "../pokemon/species.hpp"

namespace technicalmachine {

template<>
std::string to_string(Species const name) {
	static std::string const name_to_string [] = {
		"Abomasnow", "Abra", "Absol", "Aerodactyl", "Aggron",
		"Aipom", "Alakazam", "Altaria", "Ambipom", "Ampharos",
		"Anorith", "Arbok", "Arcanine", "Arceus", "Ariados",
		"Armaldo", "Aron", "Articuno", "Azelf", "Azumarill",
		"Azurill", "Bagon", "Baltoy", "Banette", "Barboach",
		"Bastiodon", "Bayleef", "Beautifly", "Beedrill", "Beldum",
		"Bellossom", "Bellsprout", "Bibarel", "Bidoof", "Blastoise",
		"Blaziken", "Blissey", "Bonsly", "Breloom", "Bronzong",
		"Bronzor", "Budew", "Buizel", "Bulbasaur", "Buneary",
		"Burmy", "Butterfree", "Cacnea", "Cacturne", "Camerupt",
		"Carnivine", "Carvanha", "Cascoon", "Castform", "Caterpie",
		"Celebi", "Chansey", "Charizard", "Charmander", "Charmeleon",
		"Chatot", "Cherrim", "Cherubi", "Chikorita", "Chimchar",
		"Chimecho", "Chinchou", "Chingling", "Clamperl", "Claydol",
		"Clefable", "Clefairy", "Cleffa", "Cloyster", "Combee",
		"Combusken", "Corphish", "Corsola", "Cradily", "Cranidos",
		"Crawdaunt", "Cresselia", "Croagunk", "Crobat", "Croconaw",
		"Cubone", "Cyndaquil", "Darkrai", "Delcatty", "Delibird",
		"Deoxys-A", "Deoxys-D", "Deoxys-M", "Deoxys-S", "Dewgong",
		"Dialga", "Diglett", "Ditto", "Dodrio", "Doduo",
		"Donphan", "Dragonair", "Dragonite", "Drapion", "Dratini",
		"Drifblim", "Drifloon", "Drowzee", "Dugtrio", "Dunsparce",
		"Dusclops", "Dusknoir", "Duskull", "Dustox", "Eevee",
		"Ekans", "Electabuzz", "Electivire", "Electrike", "Electrode",
		"Elekid", "Empoleon", "Entei", "Espeon", "Exeggcute",
		"Exeggutor", "Exploud", "Farfetch'd", "Fearow", "Feebas",
		"Feraligatr", "Finneon", "Flaaffy", "Flareon", "Floatzel",
		"Flygon", "Forretress", "Froslass", "Furret", "Gabite",
		"Gallade", "Garchomp", "Gardevoir", "Gastly", "Gastrodon",
		"Gengar", "Geodude", "Gible", "Girafarig", "Giratina-A",
		"Giratina-O", "Glaceon", "Glalie", "Glameow", "Gligar",
		"Gliscor", "Gloom", "Golbat", "Goldeen", "Golduck",
		"Golem", "Gorebyss", "Granbull", "Graveler", "Grimer",
		"Grotle", "Groudon", "Grovyle", "Growlithe", "Grumpig",
		"Gulpin", "Gyarados", "Happiny", "Hariyama", "Haunter",
		"Heatran", "Heracross", "Hippopotas", "Hippowdon", "Hitmonchan",
		"Hitmonlee", "Hitmontop", "Ho-Oh", "Honchkrow", "Hoothoot",
		"Hoppip", "Horsea", "Houndoom", "Houndour", "Huntail",
		"Hypno", "Igglybuff", "Illumise", "Infernape", "Ivysaur",
		"Jigglypuff", "Jirachi", "Jolteon", "Jumpluff", "Jynx",
		"Kabuto", "Kabutops", "Kadabra", "Kakuna", "Kangaskhan",
		"Kecleon", "Kingdra", "Kingler", "Kirlia", "Koffing",
		"Krabby", "Kricketot", "Kricketune", "Kyogre", "Lairon",
		"Lanturn", "Lapras", "Larvitar", "Latias", "Latios",
		"Leafeon", "Ledian", "Ledyba", "Lickilicky", "Lickitung",
		"Lileep", "Linoone", "Lombre", "Lopunny", "Lotad",
		"Loudred", "Lucario", "Ludicolo", "Lugia", "Lumineon",
		"Lunatone", "Luvdisc", "Luxio", "Luxray", "Machamp",
		"Machoke", "Machop", "Magby", "Magcargo", "Magikarp",
		"Magmar", "Magmortar", "Magnemite", "Magneton", "Magnezone",
		"Makuhita", "Mamoswine", "Manaphy", "Manectric", "Mankey",
		"Mantine", "Mantyke", "Mareep", "Marill", "Marowak",
		"Marshtomp", "Masquerain", "Mawile", "Medicham", "Meditite",
		"Meganium", "Meowth", "Mesprit", "Metagross", "Metang",
		"Metapod", "Mew", "Mewtwo", "Mightyena", "Milotic",
		"Miltank", "Mime Jr.", "Minun", "Misdreavus", "Mismagius",
		"Moltres", "Monferno", "Mothim", "Mr. Mime", "Mudkip",
		"Muk", "Munchlax", "Murkrow", "Natu", "Nidoking",
		"Nidoqueen", "Nidoran-F", "Nidoran-M", "Nidorina", "Nidorino",
		"Nincada", "Ninetales", "Ninjask", "Noctowl", "Nosepass",
		"Numel", "Nuzleaf", "Octillery", "Oddish", "Omanyte",
		"Omastar", "Onix", "Pachirisu", "Palkia", "Paras",
		"Parasect", "Pelipper", "Persian", "Phanpy", "Phione",
		"Pichu", "Pidgeot", "Pidgeotto", "Pidgey", "Pikachu",
		"Piloswine", "Pineco", "Pinsir", "Piplup", "Plusle",
		"Politoed", "Poliwag", "Poliwhirl", "Poliwrath",
		"Ponyta", "Poochyena", "Porygon", "Porygon-Z", "Porygon2",
		"Primeape", "Prinplup", "Probopass", "Psyduck", "Pupitar",
		"Purugly", "Quagsire", "Quilava", "Qwilfish",
		"Raichu", "Raikou", "Ralts", "Rampardos", "Rapidash",
		"Raticate", "Rattata", "Rayquaza", "Regice", "Regigigas",
		"Regirock", "Registeel", "Relicanth", "Remoraid", "Rhydon",
		"Rhyhorn", "Rhyperior", "Riolu", "Roselia", "Roserade",
		"Rotom", "Rotom-C", "Rotom-F", "Rotom-H", "Rotom-S",
		"Rotom-W", "Sableye", "Salamence", "Sandshrew", "Sandslash",
		"Sceptile", "Scizor", "Scyther", "Seadra", "Seaking",
		"Sealeo", "Seedot", "Seel", "Sentret", "Seviper",
		"Sharpedo", "Shaymin-L", "Shaymin-S", "Shedinja", "Shelgon",
		"Shellder", "Shellos", "Shieldon", "Shiftry", "Shinx",
		"Shroomish", "Shuckle", "Shuppet", "Silcoon", "Skarmory",
		"Skiploom", "Skitty", "Skorupi", "Skuntank", "Slaking",
		"Slakoth", "Slowbro", "Slowking", "Slowpoke", "Slugma",
		"Smeargle", "Smoochum", "Sneasel", "Snorlax", "Snorunt",
		"Snover", "Snubbull", "Solrock", "Spearow", "Spheal",
		"Spinarak", "Spinda", "Spiritomb", "Spoink", "Squirtle",
		"Stantler", "Staraptor", "Staravia", "Starly", "Starmie",
		"Staryu", "Steelix", "Stunky", "Sudowoodo", "Suicune",
		"Sunflora", "Sunkern", "Surskit", "Swablu", "Swalot",
		"Swampert", "Swellow", "Swinub", "Taillow", "Tangela",
		"Tangrowth", "Tauros", "Teddiursa", "Tentacool", "Tentacruel",
		"Togekiss", "Togepi", "Togetic", "Torchic", "Torkoal",
		"Torterra", "Totodile", "Toxicroak", "Trapinch", "Treecko",
		"Tropius", "Turtwig", "Typhlosion", "Tyranitar", "Tyrogue",
		"Umbreon", "Unown", "Ursaring", "Uxie", "Vaporeon",
		"Venomoth", "Venonat", "Venusaur", "Vespiquen", "Vibrava",
		"Victreebel", "Vigoroth", "Vileplume", "Volbeat", "Voltorb",
		"Vulpix", "Wailmer", "Wailord", "Walrein", "Wartortle",
		"Weavile", "Weedle", "Weepinbell", "Weezing", "Whiscash",
		"Whismur", "Wigglytuff", "Wingull", "Wobbuffet", "Wooper",
		"Wormadam-P", "Wormadam-S", "Wormadam-T", "Wurmple", "Wynaut",
		"Xatu", "Yanma", "Yanmega", "Zangoose", "Zapdos",
		"Zigzagoon", "Zubat"
	};
	return name_to_string[static_cast<size_t>(name)];
}

template<>
Species from_string(std::string const & str) {
	static std::map <std::string, Species> const converter {
		{ "Abomasnow", Species::ABOMASNOW },
		{ "Abra", Species::ABRA },
		{ "Absol", Species::ABSOL },
		{ "Aerodactyl", Species::AERODACTYL },
		{ "Aggron", Species::AGGRON },
		{ "Aipom", Species::AIPOM },
		{ "Alakazam", Species::ALAKAZAM },
		{ "Altaria", Species::ALTARIA },
		{ "Ambipom", Species::AMBIPOM },
		{ "Ampharos", Species::AMPHAROS },
		{ "Anorith", Species::ANORITH },
		{ "Arbok", Species::ARBOK },
		{ "Arcanine", Species::ARCANINE },
		{ "Arceus", Species::ARCEUS },
		{ "Ariados", Species::ARIADOS },
		{ "Armaldo", Species::ARMALDO },
		{ "Aron", Species::ARON },
		{ "Articuno", Species::ARTICUNO },
		{ "Azelf", Species::AZELF },
		{ "Azumarill", Species::AZUMARILL },
		{ "Azurill", Species::AZURILL },
		{ "Bagon", Species::BAGON },
		{ "Baltoy", Species::BALTOY },
		{ "Banette", Species::BANETTE },
		{ "Barboach", Species::BARBOACH },
		{ "Bastiodon", Species::BASTIODON },
		{ "Bayleef", Species::BAYLEEF },
		{ "Beautifly", Species::BEAUTIFLY },
		{ "Beedrill", Species::BEEDRILL },
		{ "Beldum", Species::BELDUM },
		{ "Bellossom", Species::BELLOSSOM },
		{ "Bellsprout", Species::BELLSPROUT },
		{ "Bibarel", Species::BIBAREL },
		{ "Bidoof", Species::BIDOOF },
		{ "Blastoise", Species::BLASTOISE },
		{ "Blaziken", Species::BLAZIKEN },
		{ "Blissey", Species::BLISSEY },
		{ "Bonsly", Species::BONSLY },
		{ "Breloom", Species::BRELOOM },
		{ "Bronzong", Species::BRONZONG },
		{ "Bronzor", Species::BRONZOR },
		{ "Budew", Species::BUDEW },
		{ "Buizel", Species::BUIZEL },
		{ "Bulbasaur", Species::BULBASAUR },
		{ "Buneary", Species::BUNEARY },
		{ "Burmy", Species::BURMY },
		{ "Butterfree", Species::BUTTERFREE },
		{ "Cacnea", Species::CACNEA },
		{ "Cacturne", Species::CACTURNE },
		{ "Camerupt", Species::CAMERUPT },
		{ "Carnivine", Species::CARNIVINE },
		{ "Carvanha", Species::CARVANHA },
		{ "Cascoon", Species::CASCOON },
		{ "Castform", Species::CASTFORM },
		{ "Caterpie", Species::CATERPIE },
		{ "Celebi", Species::CELEBI },
		{ "Chansey", Species::CHANSEY },
		{ "Charizard", Species::CHARIZARD },
		{ "Charmander", Species::CHARMANDER },
		{ "Charmeleon", Species::CHARMELEON },
		{ "Chatot", Species::CHATOT },
		{ "Cherrim", Species::CHERRIM },
		{ "Cherubi", Species::CHERUBI },
		{ "Chikorita", Species::CHIKORITA },
		{ "Chimchar", Species::CHIMCHAR },
		{ "Chimecho", Species::CHIMECHO },
		{ "Chinchou", Species::CHINCHOU },
		{ "Chingling", Species::CHINGLING },
		{ "Clamperl", Species::CLAMPERL },
		{ "Claydol", Species::CLAYDOL },
		{ "Clefable", Species::CLEFABLE },
		{ "Clefairy", Species::CLEFAIRY },
		{ "Cleffa", Species::CLEFFA },
		{ "Cloyster", Species::CLOYSTER },
		{ "Combee", Species::COMBEE },
		{ "Combusken", Species::COMBUSKEN },
		{ "Corphish", Species::CORPHISH },
		{ "Corsola", Species::CORSOLA },
		{ "Cradily", Species::CRADILY },
		{ "Cranidos", Species::CRANIDOS },
		{ "Crawdaunt", Species::CRAWDAUNT },
		{ "Cresselia", Species::CRESSELIA },
		{ "Croagunk", Species::CROAGUNK },
		{ "Crobat", Species::CROBAT },
		{ "Croconaw", Species::CROCONAW },
		{ "Cubone", Species::CUBONE },
		{ "Cyndaquil", Species::CYNDAQUIL },
		{ "Darkrai", Species::DARKRAI },
		{ "Delcatty", Species::DELCATTY },
		{ "Delibird", Species::DELIBIRD },
		{ "Deoxys-A", Species::DEOXYS_A },
		{ "Deoxys-a", Species::DEOXYS_A },
		{ "Deoxys-F", Species::DEOXYS_A },
		{ "Deoxys-f", Species::DEOXYS_A },
		{ "Deoxys-D", Species::DEOXYS_D },
		{ "Deoxys-d", Species::DEOXYS_D },
		{ "Deoxys-L", Species::DEOXYS_D },
		{ "Deoxys-l", Species::DEOXYS_D },
		{ "Deoxys", Species::DEOXYS_M },
		{ "Deoxys-M", Species::DEOXYS_M },
		{ "Deoxys-m", Species::DEOXYS_M },
		{ "Deoxys-S", Species::DEOXYS_S },
		{ "Deoxys-s", Species::DEOXYS_S },
		{ "Deoxys-E", Species::DEOXYS_S },
		{ "Deoxys-e", Species::DEOXYS_S },
		{ "Dewgong", Species::DEWGONG },
		{ "Dialga", Species::DIALGA },
		{ "Diglett", Species::DIGLETT },
		{ "Ditto", Species::DITTO },
		{ "Dodrio", Species::DODRIO },
		{ "Doduo", Species::DODUO },
		{ "Donphan", Species::DONPHAN },
		{ "Dragonair", Species::DRAGONAIR },
		{ "Dragonite", Species::DRAGONITE },
		{ "Drapion", Species::DRAPION },
		{ "Dratini", Species::DRATINI },
		{ "Drifblim", Species::DRIFBLIM },
		{ "Drifloon", Species::DRIFLOON },
		{ "Drowzee", Species::DROWZEE },
		{ "Dugtrio", Species::DUGTRIO },
		{ "Dunsparce", Species::DUNSPARCE },
		{ "Dusclops", Species::DUSCLOPS },
		{ "Dusknoir", Species::DUSKNOIR },
		{ "Duskull", Species::DUSKULL },
		{ "Dustox", Species::DUSTOX },
		{ "Eevee", Species::EEVEE },
		{ "Ekans", Species::EKANS },
		{ "Electabuzz", Species::ELECTABUZZ },
		{ "Electivire", Species::ELECTIVIRE },
		{ "Electrike", Species::ELECTRIKE },
		{ "Electrode", Species::ELECTRODE },
		{ "Elekid", Species::ELEKID },
		{ "Empoleon", Species::EMPOLEON },
		{ "Entei", Species::ENTEI },
		{ "Espeon", Species::ESPEON },
		{ "Exeggcute", Species::EXEGGCUTE },
		{ "Exeggutor", Species::EXEGGUTOR },
		{ "Exploud", Species::EXPLOUD },
		{ "Farfetch'd", Species::FARFETCHD },
		{ "Fearow", Species::FEAROW },
		{ "Feebas", Species::FEEBAS },
		{ "Feraligatr", Species::FERALIGATR },
		{ "Finneon", Species::FINNEON },
		{ "Flaaffy", Species::FLAAFFY },
		{ "Flareon", Species::FLAREON },
		{ "Floatzel", Species::FLOATZEL },
		{ "Flygon", Species::FLYGON },
		{ "Forretress", Species::FORRETRESS },
		{ "Froslass", Species::FROSLASS },
		{ "Furret", Species::FURRET },
		{ "Gabite", Species::GABITE },
		{ "Gallade", Species::GALLADE },
		{ "Garchomp", Species::GARCHOMP },
		{ "Gardevoir", Species::GARDEVOIR },
		{ "Gastly", Species::GASTLY },
		{ "Gastrodon", Species::GASTRODON },
		{ "Gengar", Species::GENGAR },
		{ "Geodude", Species::GEODUDE },
		{ "Gible", Species::GIBLE },
		{ "Girafarig", Species::GIRAFARIG },
		{ "Giratina", Species::GIRATINA_A },
		{ "Giratina-A", Species::GIRATINA_A },
		{ "Giratina-a", Species::GIRATINA_A },
		{ "Giratina-O", Species::GIRATINA_O },
		{ "Giratina-o", Species::GIRATINA_O },
		{ "Glaceon", Species::GLACEON },
		{ "Glalie", Species::GLALIE },
		{ "Glameow", Species::GLAMEOW },
		{ "Gligar", Species::GLIGAR },
		{ "Gliscor", Species::GLISCOR },
		{ "Gloom", Species::GLOOM },
		{ "Golbat", Species::GOLBAT },
		{ "Goldeen", Species::GOLDEEN },
		{ "Golduck", Species::GOLDUCK },
		{ "Golem", Species::GOLEM },
		{ "Gorebyss", Species::GOREBYSS },
		{ "Granbull", Species::GRANBULL },
		{ "Graveler", Species::GRAVELER },
		{ "Grimer", Species::GRIMER },
		{ "Grotle", Species::GROTLE },
		{ "Groudon", Species::GROUDON },
		{ "Grovyle", Species::GROVYLE },
		{ "Growlithe", Species::GROWLITHE },
		{ "Grumpig", Species::GRUMPIG },
		{ "Gulpin", Species::GULPIN },
		{ "Gyarados", Species::GYARADOS },
		{ "Happiny", Species::HAPPINY },
		{ "Hariyama", Species::HARIYAMA },
		{ "Haunter", Species::HAUNTER },
		{ "Heatran", Species::HEATRAN },
		{ "Heracross", Species::HERACROSS },
		{ "Hippopotas", Species::HIPPOPOTAS },
		{ "Hippowdon", Species::HIPPOWDON },
		{ "Hitmonchan", Species::HITMONCHAN },
		{ "Hitmonlee", Species::HITMONLEE },
		{ "Hitmontop", Species::HITMONTOP },
		{ "Ho-Oh", Species::HO_OH },
		{ "Ho-oh", Species::HO_OH },
		{ "Honchkrow", Species::HONCHKROW },
		{ "Hoothoot", Species::HOOTHOOT },
		{ "Hoppip", Species::HOPPIP },
		{ "Horsea", Species::HORSEA },
		{ "Houndoom", Species::HOUNDOOM },
		{ "Houndour", Species::HOUNDOUR },
		{ "Huntail", Species::HUNTAIL },
		{ "Hypno", Species::HYPNO },
		{ "Igglybuff", Species::IGGLYBUFF },
		{ "Illumise", Species::ILLUMISE },
		{ "Infernape", Species::INFERNAPE },
		{ "Ivysaur", Species::IVYSAUR },
		{ "Jigglypuff", Species::JIGGLYPUFF },
		{ "Jirachi", Species::JIRACHI },
		{ "Jolteon", Species::JOLTEON },
		{ "Jumpluff", Species::JUMPLUFF },
		{ "Jynx", Species::JYNX },
		{ "Kabuto", Species::KABUTO },
		{ "Kabutops", Species::KABUTOPS },
		{ "Kadabra", Species::KADABRA },
		{ "Kakuna", Species::KAKUNA },
		{ "Kangaskhan", Species::KANGASKHAN },
		{ "Kecleon", Species::KECLEON },
		{ "Kingdra", Species::KINGDRA },
		{ "Kingler", Species::KINGLER },
		{ "Kirlia", Species::KIRLIA },
		{ "Koffing", Species::KOFFING },
		{ "Krabby", Species::KRABBY },
		{ "Kricketot", Species::KRICKETOT },
		{ "Kricketune", Species::KRICKETUNE },
		{ "Kyogre", Species::KYOGRE },
		{ "Lairon", Species::LAIRON },
		{ "Lanturn", Species::LANTURN },
		{ "Lapras", Species::LAPRAS },
		{ "Larvitar", Species::LARVITAR },
		{ "Latias", Species::LATIAS },
		{ "Latios", Species::LATIOS },
		{ "Leafeon", Species::LEAFEON },
		{ "Ledian", Species::LEDIAN },
		{ "Ledyba", Species::LEDYBA },
		{ "Lickilicky", Species::LICKILICKY },
		{ "Lickitung", Species::LICKITUNG },
		{ "Lileep", Species::LILEEP },
		{ "Linoone", Species::LINOONE },
		{ "Lombre", Species::LOMBRE },
		{ "Lopunny", Species::LOPUNNY },
		{ "Lotad", Species::LOTAD },
		{ "Loudred", Species::LOUDRED },
		{ "Lucario", Species::LUCARIO },
		{ "Ludicolo", Species::LUDICOLO },
		{ "Lugia", Species::LUGIA },
		{ "Lumineon", Species::LUMINEON },
		{ "Lunatone", Species::LUNATONE },
		{ "Luvdisc", Species::LUVDISC },
		{ "Luxio", Species::LUXIO },
		{ "Luxray", Species::LUXRAY },
		{ "Machamp", Species::MACHAMP },
		{ "Machoke", Species::MACHOKE },
		{ "Machop", Species::MACHOP },
		{ "Magby", Species::MAGBY },
		{ "Magcargo", Species::MAGCARGO },
		{ "Magikarp", Species::MAGIKARP },
		{ "Magmar", Species::MAGMAR },
		{ "Magmortar", Species::MAGMORTAR },
		{ "Magnemite", Species::MAGNEMITE },
		{ "Magneton", Species::MAGNETON },
		{ "Magnezone", Species::MAGNEZONE },
		{ "Makuhita", Species::MAKUHITA },
		{ "Mamoswine", Species::MAMOSWINE },
		{ "Manaphy", Species::MANAPHY },
		{ "Manectric", Species::MANECTRIC },
		{ "Mankey", Species::MANKEY },
		{ "Mantine", Species::MANTINE },
		{ "Mantyke", Species::MANTYKE },
		{ "Mareep", Species::MAREEP },
		{ "Marill", Species::MARILL },
		{ "Marowak", Species::MAROWAK },
		{ "Marshtomp", Species::MARSHTOMP },
		{ "Masquerain", Species::MASQUERAIN },
		{ "Mawile", Species::MAWILE },
		{ "Medicham", Species::MEDICHAM },
		{ "Meditite", Species::MEDITITE },
		{ "Meganium", Species::MEGANIUM },
		{ "Meowth", Species::MEOWTH },
		{ "Mesprit", Species::MESPRIT },
		{ "Metagross", Species::METAGROSS },
		{ "Metang", Species::METANG },
		{ "Metapod", Species::METAPOD },
		{ "Mew", Species::MEW },
		{ "Mewtwo", Species::MEWTWO },
		{ "Mightyena", Species::MIGHTYENA },
		{ "Milotic", Species::MILOTIC },
		{ "Miltank", Species::MILTANK },
		{ "Mime Jr.", Species::MIME_JR },
		{ "Minun", Species::MINUN },
		{ "Misdreavus", Species::MISDREAVUS },
		{ "Mismagius", Species::MISMAGIUS },
		{ "Moltres", Species::MOLTRES },
		{ "Monferno", Species::MONFERNO },
		{ "Mothim", Species::MOTHIM },
		{ "Mr. Mime", Species::MR_MIME },
		{ "Mudkip", Species::MUDKIP },
		{ "Muk", Species::MUK },
		{ "Munchlax", Species::MUNCHLAX },
		{ "Murkrow", Species::MURKROW },
		{ "Natu", Species::NATU },
		{ "Nidoking", Species::NIDOKING },
		{ "Nidoqueen", Species::NIDOQUEEN },
		{ "Nidoran-F", Species::NIDORAN_F },
		{ "Nidoran-f", Species::NIDORAN_F },
		{ "Nidoran-M", Species::NIDORAN_M },
		{ "Nidoran-m", Species::NIDORAN_M },
		{ "Nidorina", Species::NIDORINA },
		{ "Nidorino", Species::NIDORINO },
		{ "Nincada", Species::NINCADA },
		{ "Ninetales", Species::NINETALES },
		{ "Ninjask", Species::NINJASK },
		{ "Noctowl", Species::NOCTOWL },
		{ "Nosepass", Species::NOSEPASS },
		{ "Numel", Species::NUMEL },
		{ "Nuzleaf", Species::NUZLEAF },
		{ "Octillery", Species::OCTILLERY },
		{ "Oddish", Species::ODDISH },
		{ "Omanyte", Species::OMANYTE },
		{ "Omastar", Species::OMASTAR },
		{ "Onix", Species::ONIX },
		{ "Pachirisu", Species::PACHIRISU },
		{ "Palkia", Species::PALKIA },
		{ "Paras", Species::PARAS },
		{ "Parasect", Species::PARASECT },
		{ "Pelipper", Species::PELIPPER },
		{ "Persian", Species::PERSIAN },
		{ "Phanpy", Species::PHANPY },
		{ "Phione", Species::PHIONE },
		{ "Pichu", Species::PICHU },
		{ "Pidgeot", Species::PIDGEOT },
		{ "Pidgeotto", Species::PIDGEOTTO },
		{ "Pidgey", Species::PIDGEY },
		{ "Pikachu", Species::PIKACHU },
		{ "Piloswine", Species::PILOSWINE },
		{ "Pineco", Species::PINECO },
		{ "Pinsir", Species::PINSIR },
		{ "Piplup", Species::PIPLUP },
		{ "Plusle", Species::PLUSLE },
		{ "Politoed", Species::POLITOED },
		{ "Poliwag", Species::POLIWAG },
		{ "Poliwhirl", Species::POLIWHIRL },
		{ "Poliwrath", Species::POLIWRATH },
		{ "Ponyta", Species::PONYTA },
		{ "Poochyena", Species::POOCHYENA },
		{ "Porygon", Species::PORYGON },
		{ "Porygon-Z", Species::PORYGON_Z },
		{ "Porygon-z", Species::PORYGON_Z },
		{ "Porygonz", Species::PORYGON_Z },
		{ "Porygon2", Species::PORYGON2 },
		{ "Primeape", Species::PRIMEAPE },
		{ "Prinplup", Species::PRINPLUP },
		{ "Probopass", Species::PROBOPASS },
		{ "Psyduck", Species::PSYDUCK },
		{ "Pupitar", Species::PUPITAR },
		{ "Purugly", Species::PURUGLY },
		{ "Quagsire", Species::QUAGSIRE },
		{ "Quilava", Species::QUILAVA },
		{ "Qwilfish", Species::QWILFISH },
		{ "Raichu", Species::RAICHU },
		{ "Raikou", Species::RAIKOU },
		{ "Ralts", Species::RALTS },
		{ "Rampardos", Species::RAMPARDOS },
		{ "Rapidash", Species::RAPIDASH },
		{ "Raticate", Species::RATICATE },
		{ "Rattata", Species::RATTATA },
		{ "Rayquaza", Species::RAYQUAZA },
		{ "Regice", Species::REGICE },
		{ "Regigigas", Species::REGIGIGAS },
		{ "Regirock", Species::REGIROCK },
		{ "Registeel", Species::REGISTEEL },
		{ "Relicanth", Species::RELICANTH },
		{ "Remoraid", Species::REMORAID },
		{ "Rhydon", Species::RHYDON },
		{ "Rhyhorn", Species::RHYHORN },
		{ "Rhyperior", Species::RHYPERIOR },
		{ "Riolu", Species::RIOLU },
		{ "Roselia", Species::ROSELIA },
		{ "Roserade", Species::ROSERADE },
		{ "Rotom", Species::ROTOM },
		{ "Rotom-C", Species::ROTOM_C },
		{ "Rotom-c", Species::ROTOM_C },
		{ "Rotom-F", Species::ROTOM_F },
		{ "Rotom-f", Species::ROTOM_F },
		{ "Rotom-H", Species::ROTOM_H },
		{ "Rotom-h", Species::ROTOM_H },
		{ "Rotom-S", Species::ROTOM_S },
		{ "Rotom-s", Species::ROTOM_S },
		{ "Rotom-W", Species::ROTOM_W },
		{ "Rotom-w", Species::ROTOM_W },
		{ "Sableye", Species::SABLEYE },
		{ "Salamence", Species::SALAMENCE },
		{ "Sandshrew", Species::SANDSHREW },
		{ "Sandslash", Species::SANDSLASH },
		{ "Sceptile", Species::SCEPTILE },
		{ "Scizor", Species::SCIZOR },
		{ "Scyther", Species::SCYTHER },
		{ "Seadra", Species::SEADRA },
		{ "Seaking", Species::SEAKING },
		{ "Sealeo", Species::SEALEO },
		{ "Seedot", Species::SEEDOT },
		{ "Seel", Species::SEEL },
		{ "Sentret", Species::SENTRET },
		{ "Seviper", Species::SEVIPER },
		{ "Sharpedo", Species::SHARPEDO },
		{ "Shaymin", Species::SHAYMIN_L },
		{ "Shaymin-L", Species::SHAYMIN_L },
		{ "Shaymin-l", Species::SHAYMIN_L },
		{ "Shaymin-S", Species::SHAYMIN_S },
		{ "Shaymin-s", Species::SHAYMIN_S },
		{ "Shedinja", Species::SHEDINJA },
		{ "Shelgon", Species::SHELGON },
		{ "Shellder", Species::SHELLDER },
		{ "Shellos", Species::SHELLOS },
		{ "Shieldon", Species::SHIELDON },
		{ "Shiftry", Species::SHIFTRY },
		{ "Shinx", Species::SHINX },
		{ "Shroomish", Species::SHROOMISH },
		{ "Shuckle", Species::SHUCKLE },
		{ "Shuppet", Species::SHUPPET },
		{ "Silcoon", Species::SILCOON },
		{ "Skarmory", Species::SKARMORY },
		{ "Skiploom", Species::SKIPLOOM },
		{ "Skitty", Species::SKITTY },
		{ "Skorupi", Species::SKORUPI },
		{ "Skuntank", Species::SKUNTANK },
		{ "Slaking", Species::SLAKING },
		{ "Slakoth", Species::SLAKOTH },
		{ "Slowbro", Species::SLOWBRO },
		{ "Slowking", Species::SLOWKING },
		{ "Slowpoke", Species::SLOWPOKE },
		{ "Slugma", Species::SLUGMA },
		{ "Smeargle", Species::SMEARGLE },
		{ "Smoochum", Species::SMOOCHUM },
		{ "Sneasel", Species::SNEASEL },
		{ "Snorlax", Species::SNORLAX },
		{ "Snorunt", Species::SNORUNT },
		{ "Snover", Species::SNOVER },
		{ "Snubbull", Species::SNUBBULL },
		{ "Solrock", Species::SOLROCK },
		{ "Spearow", Species::SPEAROW },
		{ "Spheal", Species::SPHEAL },
		{ "Spinarak", Species::SPINARAK },
		{ "Spinda", Species::SPINDA },
		{ "Spiritomb", Species::SPIRITOMB },
		{ "Spoink", Species::SPOINK },
		{ "Squirtle", Species::SQUIRTLE },
		{ "Stantler", Species::STANTLER },
		{ "Staraptor", Species::STARAPTOR },
		{ "Staravia", Species::STARAVIA },
		{ "Starly", Species::STARLY },
		{ "Starmie", Species::STARMIE },
		{ "Staryu", Species::STARYU },
		{ "Steelix", Species::STEELIX },
		{ "Stunky", Species::STUNKY },
		{ "Sudowoodo", Species::SUDOWOODO },
		{ "Suicune", Species::SUICUNE },
		{ "Sunflora", Species::SUNFLORA },
		{ "Sunkern", Species::SUNKERN },
		{ "Surskit", Species::SURSKIT },
		{ "Swablu", Species::SWABLU },
		{ "Swalot", Species::SWALOT },
		{ "Swampert", Species::SWAMPERT },
		{ "Swellow", Species::SWELLOW },
		{ "Swinub", Species::SWINUB },
		{ "Taillow", Species::TAILLOW },
		{ "Tangela", Species::TANGELA },
		{ "Tangrowth", Species::TANGROWTH },
		{ "Tauros", Species::TAUROS },
		{ "Teddiursa", Species::TEDDIURSA },
		{ "Tentacool", Species::TENTACOOL },
		{ "Tentacruel", Species::TENTACRUEL },
		{ "Togekiss", Species::TOGEKISS },
		{ "Togepi", Species::TOGEPI },
		{ "Togetic", Species::TOGETIC },
		{ "Torchic", Species::TORCHIC },
		{ "Torkoal", Species::TORKOAL },
		{ "Torterra", Species::TORTERRA },
		{ "Totodile", Species::TOTODILE },
		{ "Toxicroak", Species::TOXICROAK },
		{ "Trapinch", Species::TRAPINCH },
		{ "Treecko", Species::TREECKO },
		{ "Tropius", Species::TROPIUS },
		{ "Turtwig", Species::TURTWIG },
		{ "Typhlosion", Species::TYPHLOSION },
		{ "Tyranitar", Species::TYRANITAR },
		{ "Tyrogue", Species::TYROGUE },
		{ "Umbreon", Species::UMBREON },
		{ "Unown", Species::UNOWN },
		{ "Ursaring", Species::URSARING },
		{ "Uxie", Species::UXIE },
		{ "Vaporeon", Species::VAPOREON },
		{ "Venomoth", Species::VENOMOTH },
		{ "Venonat", Species::VENONAT },
		{ "Venusaur", Species::VENUSAUR },
		{ "Vespiquen", Species::VESPIQUEN },
		{ "Vibrava", Species::VIBRAVA },
		{ "Victreebel", Species::VICTREEBEL },
		{ "Vigoroth", Species::VIGOROTH },
		{ "Vileplume", Species::VILEPLUME },
		{ "Volbeat", Species::VOLBEAT },
		{ "Voltorb", Species::VOLTORB },
		{ "Vulpix", Species::VULPIX },
		{ "Wailmer", Species::WAILMER },
		{ "Wailord", Species::WAILORD },
		{ "Walrein", Species::WALREIN },
		{ "Wartortle", Species::WARTORTLE },
		{ "Weavile", Species::WEAVILE },
		{ "Weedle", Species::WEEDLE },
		{ "Weepinbell", Species::WEEPINBELL },
		{ "Weezing", Species::WEEZING },
		{ "Whiscash", Species::WHISCASH },
		{ "Whismur", Species::WHISMUR },
		{ "Wigglytuff", Species::WIGGLYTUFF },
		{ "Wingull", Species::WINGULL },
		{ "Wobbuffet", Species::WOBBUFFET },
		{ "Wooper", Species::WOOPER },
		{ "Wormadam", Species::WORMADAM_P },
		{ "Wormadam-P", Species::WORMADAM_P },
		{ "Wormadam-g", Species::WORMADAM_S },
		{ "Wormadam-S", Species::WORMADAM_S },
		{ "Wormadam-s", Species::WORMADAM_T },
		{ "Wormadam-T", Species::WORMADAM_T },
		{ "Wurmple", Species::WURMPLE },
		{ "Wynaut", Species::WYNAUT },
		{ "Xatu", Species::XATU },
		{ "Yanma", Species::YANMA },
		{ "Yanmega", Species::YANMEGA },
		{ "Zangoose", Species::ZANGOOSE },
		{ "Zapdos", Species::ZAPDOS },
		{ "Zigzagoon", Species::ZIGZAGOON },
		{ "Zubat", Species::ZUBAT }
	};
	auto const it = converter.find (str);
	if (it != converter.end ())
		return it->second;
	else
		throw InvalidFromStringConversion ("Species", str);
}

}	// namespace technicalmachine
