// Pokemon string functions
// Copyright (C) 2018 David Stone
//
// This file is part of Technical Machine.
//
// Technical Machine is free software: you can redistribute it and / or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.

#include "pokemon.hpp"

#include "invalid_string_conversion.hpp"

#include "../pokemon/species.hpp"

#include <algorithm>
#include <map>

namespace technicalmachine {

std::string_view to_string(Species const species) {
	switch (species) {
		// Generation 1
		case Species::Bulbasaur: return "Bulbasaur";
		case Species::Ivysaur: return "Ivysaur";
		case Species::Venusaur: return "Venusaur";
		case Species::Charmander: return "Charmander";
		case Species::Charmeleon: return "Charmeleon";
		case Species::Charizard: return "Charizard";
		case Species::Squirtle: return "Squirtle";
		case Species::Wartortle: return "Wartortle";
		case Species::Blastoise: return "Blastoise";
		case Species::Caterpie: return "Caterpie";
		case Species::Metapod: return "Metapod";
		case Species::Butterfree: return "Butterfree";
		case Species::Weedle: return "Weedle";
		case Species::Kakuna: return "Kakuna";
		case Species::Beedrill: return "Beedrill";
		case Species::Pidgey: return "Pidgey";
		case Species::Pidgeotto: return "Pidgeotto";
		case Species::Pidgeot: return "Pidgeot";
		case Species::Rattata: return "Rattata";
		case Species::Raticate: return "Raticate";
		case Species::Spearow: return "Spearow";
		case Species::Fearow: return "Fearow";
		case Species::Ekans: return "Ekans";
		case Species::Arbok: return "Arbok";
		case Species::Pikachu: return "Pikachu";
		case Species::Raichu: return "Raichu";
		case Species::Sandshrew: return "Sandshrew";
		case Species::Sandslash: return "Sandslash";
		case Species::Nidoran_F: return "Nidoran-F";
		case Species::Nidorina: return "Nidorina";
		case Species::Nidoqueen: return "Nidoqueen";
		case Species::Nidoran_M: return "Nidoran-M";
		case Species::Nidorino: return "Nidorino";
		case Species::Nidoking: return "Nidoking";
		case Species::Clefairy: return "Clefairy";
		case Species::Clefable: return "Clefable";
		case Species::Vulpix: return "Vulpix";
		case Species::Ninetales: return "Ninetales";
		case Species::Jigglypuff: return "Jigglypuff";
		case Species::Wigglytuff: return "Wigglytuff";
		case Species::Zubat: return "Zubat";
		case Species::Golbat: return "Golbat";
		case Species::Oddish: return "Oddish";
		case Species::Gloom: return "Gloom";
		case Species::Vileplume: return "Vileplume";
		case Species::Paras: return "Paras";
		case Species::Parasect: return "Parasect";
		case Species::Venonat: return "Venonat";
		case Species::Venomoth: return "Venomoth";
		case Species::Diglett: return "Diglett";
		case Species::Dugtrio: return "Dugtrio";
		case Species::Meowth: return "Meowth";
		case Species::Persian: return "Persian";
		case Species::Psyduck: return "Psyduck";
		case Species::Golduck: return "Golduck";
		case Species::Mankey: return "Mankey";
		case Species::Primeape: return "Primeape";
		case Species::Growlithe: return "Growlithe";
		case Species::Arcanine: return "Arcanine";
		case Species::Poliwag: return "Poliwag";
		case Species::Poliwhirl: return "Poliwhirl";
		case Species::Poliwrath: return "Poliwrath";
		case Species::Abra: return "Abra";
		case Species::Kadabra: return "Kadabra";
		case Species::Alakazam: return "Alakazam";
		case Species::Machop: return "Machop";
		case Species::Machoke: return "Machoke";
		case Species::Machamp: return "Machamp";
		case Species::Bellsprout: return "Bellsprout";
		case Species::Weepinbell: return "Weepinbell";
		case Species::Victreebel: return "Victreebel";
		case Species::Tentacool: return "Tentacool";
		case Species::Tentacruel: return "Tentacruel";
		case Species::Geodude: return "Geodude";
		case Species::Graveler: return "Graveler";
		case Species::Golem: return "Golem";
		case Species::Ponyta: return "Ponyta";
		case Species::Rapidash: return "Rapidash";
		case Species::Slowpoke: return "Slowpoke";
		case Species::Slowbro: return "Slowbro";
		case Species::Magnemite: return "Magnemite";
		case Species::Magneton: return "Magneton";
		case Species::Farfetchd: return "Farfetch'd";
		case Species::Doduo: return "Doduo";
		case Species::Dodrio: return "Dodrio";
		case Species::Seel: return "Seel";
		case Species::Dewgong: return "Dewgong";
		case Species::Grimer: return "Grimer";
		case Species::Muk: return "Muk";
		case Species::Shellder: return "Shellder";
		case Species::Cloyster: return "Cloyster";
		case Species::Gastly: return "Gastly";
		case Species::Haunter: return "Haunter";
		case Species::Gengar: return "Gengar";
		case Species::Onix: return "Onix";
		case Species::Drowzee: return "Drowzee";
		case Species::Hypno: return "Hypno";
		case Species::Krabby: return "Krabby";
		case Species::Kingler: return "Kingler";
		case Species::Voltorb: return "Voltorb";
		case Species::Electrode: return "Electrode";
		case Species::Exeggcute: return "Exeggcute";
		case Species::Exeggutor: return "Exeggutor";
		case Species::Cubone: return "Cubone";
		case Species::Marowak: return "Marowak";
		case Species::Hitmonlee: return "Hitmonlee";
		case Species::Hitmonchan: return "Hitmonchan";
		case Species::Lickitung: return "Lickitung";
		case Species::Koffing: return "Koffing";
		case Species::Weezing: return "Weezing";
		case Species::Rhyhorn: return "Rhyhorn";
		case Species::Rhydon: return "Rhydon";
		case Species::Chansey: return "Chansey";
		case Species::Tangela: return "Tangela";
		case Species::Kangaskhan: return "Kangaskhan";
		case Species::Horsea: return "Horsea";
		case Species::Seadra: return "Seadra";
		case Species::Goldeen: return "Goldeen";
		case Species::Seaking: return "Seaking";
		case Species::Staryu: return "Staryu";
		case Species::Starmie: return "Starmie";
		case Species::Mr_Mime: return "Mr. Mime";
		case Species::Scyther: return "Scyther";
		case Species::Jynx: return "Jynx";
		case Species::Electabuzz: return "Electabuzz";
		case Species::Magmar: return "Magmar";
		case Species::Pinsir: return "Pinsir";
		case Species::Tauros: return "Tauros";
		case Species::Magikarp: return "Magikarp";
		case Species::Gyarados: return "Gyarados";
		case Species::Lapras: return "Lapras";
		case Species::Ditto: return "Ditto";
		case Species::Eevee: return "Eevee";
		case Species::Vaporeon: return "Vaporeon";
		case Species::Jolteon: return "Jolteon";
		case Species::Flareon: return "Flareon";
		case Species::Porygon: return "Porygon";
		case Species::Omanyte: return "Omanyte";
		case Species::Omastar: return "Omastar";
		case Species::Kabuto: return "Kabuto";
		case Species::Kabutops: return "Kabutops";
		case Species::Aerodactyl: return "Aerodactyl";
		case Species::Snorlax: return "Snorlax";
		case Species::Articuno: return "Articuno";
		case Species::Zapdos: return "Zapdos";
		case Species::Moltres: return "Moltres";
		case Species::Dratini: return "Dratini";
		case Species::Dragonair: return "Dragonair";
		case Species::Dragonite: return "Dragonite";
		case Species::Mewtwo: return "Mewtwo";
		case Species::Mew: return "Mew";
		
		// Generation 2
		case Species::Chikorita: return "Chikorita";
		case Species::Bayleef: return "Bayleef";
		case Species::Meganium: return "Meganium";
		case Species::Cyndaquil: return "Cyndaquil";
		case Species::Quilava: return "Quilava";
		case Species::Typhlosion: return "Typhlosion";
		case Species::Totodile: return "Totodile";
		case Species::Croconaw: return "Croconaw";
		case Species::Feraligatr: return "Feraligatr";
		case Species::Sentret: return "Sentret";
		case Species::Furret: return "Furret";
		case Species::Hoothoot: return "Hoothoot";
		case Species::Noctowl: return "Noctowl";
		case Species::Ledyba: return "Ledyba";
		case Species::Ledian: return "Ledian";
		case Species::Spinarak: return "Spinarak";
		case Species::Ariados: return "Ariados";
		case Species::Crobat: return "Crobat";
		case Species::Chinchou: return "Chinchou";
		case Species::Lanturn: return "Lanturn";
		case Species::Pichu: return "Pichu";
		case Species::Cleffa: return "Cleffa";
		case Species::Igglybuff: return "Igglybuff";
		case Species::Togepi: return "Togepi";
		case Species::Togetic: return "Togetic";
		case Species::Natu: return "Natu";
		case Species::Xatu: return "Xatu";
		case Species::Mareep: return "Mareep";
		case Species::Flaaffy: return "Flaaffy";
		case Species::Ampharos: return "Ampharos";
		case Species::Bellossom: return "Bellossom";
		case Species::Marill: return "Marill";
		case Species::Azumarill: return "Azumarill";
		case Species::Sudowoodo: return "Sudowoodo";
		case Species::Politoed: return "Politoed";
		case Species::Hoppip: return "Hoppip";
		case Species::Skiploom: return "Skiploom";
		case Species::Jumpluff: return "Jumpluff";
		case Species::Aipom: return "Aipom";
		case Species::Sunkern: return "Sunkern";
		case Species::Sunflora: return "Sunflora";
		case Species::Yanma: return "Yanma";
		case Species::Wooper: return "Wooper";
		case Species::Quagsire: return "Quagsire";
		case Species::Espeon: return "Espeon";
		case Species::Umbreon: return "Umbreon";
		case Species::Murkrow: return "Murkrow";
		case Species::Slowking: return "Slowking";
		case Species::Misdreavus: return "Misdreavus";
		case Species::Unown: return "Unown";
		case Species::Wobbuffet: return "Wobbuffet";
		case Species::Girafarig: return "Girafarig";
		case Species::Pineco: return "Pineco";
		case Species::Forretress: return "Forretress";
		case Species::Dunsparce: return "Dunsparce";
		case Species::Gligar: return "Gligar";
		case Species::Steelix: return "Steelix";
		case Species::Snubbull: return "Snubbull";
		case Species::Granbull: return "Granbull";
		case Species::Qwilfish: return "Qwilfish";
		case Species::Scizor: return "Scizor";
		case Species::Shuckle: return "Shuckle";
		case Species::Heracross: return "Heracross";
		case Species::Sneasel: return "Sneasel";
		case Species::Teddiursa: return "Teddiursa";
		case Species::Ursaring: return "Ursaring";
		case Species::Slugma: return "Slugma";
		case Species::Magcargo: return "Magcargo";
		case Species::Swinub: return "Swinub";
		case Species::Piloswine: return "Piloswine";
		case Species::Corsola: return "Corsola";
		case Species::Remoraid: return "Remoraid";
		case Species::Octillery: return "Octillery";
		case Species::Delibird: return "Delibird";
		case Species::Mantine: return "Mantine";
		case Species::Skarmory: return "Skarmory";
		case Species::Houndour: return "Houndour";
		case Species::Houndoom: return "Houndoom";
		case Species::Kingdra: return "Kingdra";
		case Species::Phanpy: return "Phanpy";
		case Species::Donphan: return "Donphan";
		case Species::Porygon2: return "Porygon2";
		case Species::Stantler: return "Stantler";
		case Species::Smeargle: return "Smeargle";
		case Species::Tyrogue: return "Tyrogue";
		case Species::Hitmontop: return "Hitmontop";
		case Species::Smoochum: return "Smoochum";
		case Species::Elekid: return "Elekid";
		case Species::Magby: return "Magby";
		case Species::Miltank: return "Miltank";
		case Species::Blissey: return "Blissey";
		case Species::Raikou: return "Raikou";
		case Species::Entei: return "Entei";
		case Species::Suicune: return "Suicune";
		case Species::Larvitar: return "Larvitar";
		case Species::Pupitar: return "Pupitar";
		case Species::Tyranitar: return "Tyranitar";
		case Species::Lugia: return "Lugia";
		case Species::Ho_Oh: return "Ho-Oh";
		case Species::Celebi: return "Celebi";
		
		// Generation 3
		case Species::Treecko: return "Treecko";
		case Species::Grovyle: return "Grovyle";
		case Species::Sceptile: return "Sceptile";
		case Species::Torchic: return "Torchic";
		case Species::Combusken: return "Combusken";
		case Species::Blaziken: return "Blaziken";
		case Species::Mudkip: return "Mudkip";
		case Species::Marshtomp: return "Marshtomp";
		case Species::Swampert: return "Swampert";
		case Species::Poochyena: return "Poochyena";
		case Species::Mightyena: return "Mightyena";
		case Species::Zigzagoon: return "Zigzagoon";
		case Species::Linoone: return "Linoone";
		case Species::Wurmple: return "Wurmple";
		case Species::Silcoon: return "Silcoon";
		case Species::Beautifly: return "Beautifly";
		case Species::Cascoon: return "Cascoon";
		case Species::Dustox: return "Dustox";
		case Species::Lotad: return "Lotad";
		case Species::Lombre: return "Lombre";
		case Species::Ludicolo: return "Ludicolo";
		case Species::Seedot: return "Seedot";
		case Species::Nuzleaf: return "Nuzleaf";
		case Species::Shiftry: return "Shiftry";
		case Species::Taillow: return "Taillow";
		case Species::Swellow: return "Swellow";
		case Species::Wingull: return "Wingull";
		case Species::Pelipper: return "Pelipper";
		case Species::Ralts: return "Ralts";
		case Species::Kirlia: return "Kirlia";
		case Species::Gardevoir: return "Gardevoir";
		case Species::Surskit: return "Surskit";
		case Species::Masquerain: return "Masquerain";
		case Species::Shroomish: return "Shroomish";
		case Species::Breloom: return "Breloom";
		case Species::Slakoth: return "Slakoth";
		case Species::Vigoroth: return "Vigoroth";
		case Species::Slaking: return "Slaking";
		case Species::Nincada: return "Nincada";
		case Species::Ninjask: return "Ninjask";
		case Species::Shedinja: return "Shedinja";
		case Species::Whismur: return "Whismur";
		case Species::Loudred: return "Loudred";
		case Species::Exploud: return "Exploud";
		case Species::Makuhita: return "Makuhita";
		case Species::Hariyama: return "Hariyama";
		case Species::Azurill: return "Azurill";
		case Species::Nosepass: return "Nosepass";
		case Species::Skitty: return "Skitty";
		case Species::Delcatty: return "Delcatty";
		case Species::Sableye: return "Sableye";
		case Species::Mawile: return "Mawile";
		case Species::Aron: return "Aron";
		case Species::Lairon: return "Lairon";
		case Species::Aggron: return "Aggron";
		case Species::Meditite: return "Meditite";
		case Species::Medicham: return "Medicham";
		case Species::Electrike: return "Electrike";
		case Species::Manectric: return "Manectric";
		case Species::Plusle: return "Plusle";
		case Species::Minun: return "Minun";
		case Species::Volbeat: return "Volbeat";
		case Species::Illumise: return "Illumise";
		case Species::Roselia: return "Roselia";
		case Species::Gulpin: return "Gulpin";
		case Species::Swalot: return "Swalot";
		case Species::Carvanha: return "Carvanha";
		case Species::Sharpedo: return "Sharpedo";
		case Species::Wailmer: return "Wailmer";
		case Species::Wailord: return "Wailord";
		case Species::Numel: return "Numel";
		case Species::Camerupt: return "Camerupt";
		case Species::Torkoal: return "Torkoal";
		case Species::Spoink: return "Spoink";
		case Species::Grumpig: return "Grumpig";
		case Species::Spinda: return "Spinda";
		case Species::Trapinch: return "Trapinch";
		case Species::Vibrava: return "Vibrava";
		case Species::Flygon: return "Flygon";
		case Species::Cacnea: return "Cacnea";
		case Species::Cacturne: return "Cacturne";
		case Species::Swablu: return "Swablu";
		case Species::Altaria: return "Altaria";
		case Species::Zangoose: return "Zangoose";
		case Species::Seviper: return "Seviper";
		case Species::Lunatone: return "Lunatone";
		case Species::Solrock: return "Solrock";
		case Species::Barboach: return "Barboach";
		case Species::Whiscash: return "Whiscash";
		case Species::Corphish: return "Corphish";
		case Species::Crawdaunt: return "Crawdaunt";
		case Species::Baltoy: return "Baltoy";
		case Species::Claydol: return "Claydol";
		case Species::Lileep: return "Lileep";
		case Species::Cradily: return "Cradily";
		case Species::Anorith: return "Anorith";
		case Species::Armaldo: return "Armaldo";
		case Species::Feebas: return "Feebas";
		case Species::Milotic: return "Milotic";
		case Species::Castform: return "Castform";
		case Species::Kecleon: return "Kecleon";
		case Species::Shuppet: return "Shuppet";
		case Species::Banette: return "Banette";
		case Species::Duskull: return "Duskull";
		case Species::Dusclops: return "Dusclops";
		case Species::Tropius: return "Tropius";
		case Species::Chimecho: return "Chimecho";
		case Species::Absol: return "Absol";
		case Species::Wynaut: return "Wynaut";
		case Species::Snorunt: return "Snorunt";
		case Species::Glalie: return "Glalie";
		case Species::Spheal: return "Spheal";
		case Species::Sealeo: return "Sealeo";
		case Species::Walrein: return "Walrein";
		case Species::Clamperl: return "Clamperl";
		case Species::Huntail: return "Huntail";
		case Species::Gorebyss: return "Gorebyss";
		case Species::Relicanth: return "Relicanth";
		case Species::Luvdisc: return "Luvdisc";
		case Species::Bagon: return "Bagon";
		case Species::Shelgon: return "Shelgon";
		case Species::Salamence: return "Salamence";
		case Species::Beldum: return "Beldum";
		case Species::Metang: return "Metang";
		case Species::Metagross: return "Metagross";
		case Species::Regirock: return "Regirock";
		case Species::Regice: return "Regice";
		case Species::Registeel: return "Registeel";
		case Species::Latias: return "Latias";
		case Species::Latios: return "Latios";
		case Species::Kyogre: return "Kyogre";
		case Species::Groudon: return "Groudon";
		case Species::Rayquaza: return "Rayquaza";
		case Species::Jirachi: return "Jirachi";
		case Species::Deoxys_Mediocre: return "Deoxys-Mediocre";
		case Species::Deoxys_Attack: return "Deoxys-Attack";
		case Species::Deoxys_Defense: return "Deoxys-Defense";
		case Species::Deoxys_Speed: return "Deoxys-Speed";
		
		// Generation 4
		case Species::Turtwig: return "Turtwig";
		case Species::Grotle: return "Grotle";
		case Species::Torterra: return "Torterra";
		case Species::Chimchar: return "Chimchar";
		case Species::Monferno: return "Monferno";
		case Species::Infernape: return "Infernape";
		case Species::Piplup: return "Piplup";
		case Species::Prinplup: return "Prinplup";
		case Species::Empoleon: return "Empoleon";
		case Species::Starly: return "Starly";
		case Species::Staravia: return "Staravia";
		case Species::Staraptor: return "Staraptor";
		case Species::Bidoof: return "Bidoof";
		case Species::Bibarel: return "Bibarel";
		case Species::Kricketot: return "Kricketot";
		case Species::Kricketune: return "Kricketune";
		case Species::Shinx: return "Shinx";
		case Species::Luxio: return "Luxio";
		case Species::Luxray: return "Luxray";
		case Species::Budew: return "Budew";
		case Species::Roserade: return "Roserade";
		case Species::Cranidos: return "Cranidos";
		case Species::Rampardos: return "Rampardos";
		case Species::Shieldon: return "Shieldon";
		case Species::Bastiodon: return "Bastiodon";
		case Species::Burmy: return "Burmy";
		case Species::Wormadam_Plant: return "Wormadam-Plant";
		case Species::Wormadam_Sandy: return "Wormadam-Sandy";
		case Species::Wormadam_Trash: return "Wormadam-Trash";
		case Species::Mothim: return "Mothim";
		case Species::Combee: return "Combee";
		case Species::Vespiquen: return "Vespiquen";
		case Species::Pachirisu: return "Pachirisu";
		case Species::Buizel: return "Buizel";
		case Species::Floatzel: return "Floatzel";
		case Species::Cherubi: return "Cherubi";
		case Species::Cherrim: return "Cherrim";
		case Species::Shellos: return "Shellos";
		case Species::Gastrodon: return "Gastrodon";
		case Species::Ambipom: return "Ambipom";
		case Species::Drifloon: return "Drifloon";
		case Species::Drifblim: return "Drifblim";
		case Species::Buneary: return "Buneary";
		case Species::Lopunny: return "Lopunny";
		case Species::Mismagius: return "Mismagius";
		case Species::Honchkrow: return "Honchkrow";
		case Species::Glameow: return "Glameow";
		case Species::Purugly: return "Purugly";
		case Species::Chingling: return "Chingling";
		case Species::Stunky: return "Stunky";
		case Species::Skuntank: return "Skuntank";
		case Species::Bronzor: return "Bronzor";
		case Species::Bronzong: return "Bronzong";
		case Species::Bonsly: return "Bonsly";
		case Species::Mime_Jr: return "Mime Jr.";
		case Species::Happiny: return "Happiny";
		case Species::Chatot: return "Chatot";
		case Species::Spiritomb: return "Spiritomb";
		case Species::Gible: return "Gible";
		case Species::Gabite: return "Gabite";
		case Species::Garchomp: return "Garchomp";
		case Species::Munchlax: return "Munchlax";
		case Species::Riolu: return "Riolu";
		case Species::Lucario: return "Lucario";
		case Species::Hippopotas: return "Hippopotas";
		case Species::Hippowdon: return "Hippowdon";
		case Species::Skorupi: return "Skorupi";
		case Species::Drapion: return "Drapion";
		case Species::Croagunk: return "Croagunk";
		case Species::Toxicroak: return "Toxicroak";
		case Species::Carnivine: return "Carnivine";
		case Species::Finneon: return "Finneon";
		case Species::Lumineon: return "Lumineon";
		case Species::Mantyke: return "Mantyke";
		case Species::Snover: return "Snover";
		case Species::Abomasnow: return "Abomasnow";
		case Species::Weavile: return "Weavile";
		case Species::Magnezone: return "Magnezone";
		case Species::Lickilicky: return "Lickilicky";
		case Species::Rhyperior: return "Rhyperior";
		case Species::Tangrowth: return "Tangrowth";
		case Species::Electivire: return "Electivire";
		case Species::Magmortar: return "Magmortar";
		case Species::Togekiss: return "Togekiss";
		case Species::Yanmega: return "Yanmega";
		case Species::Leafeon: return "Leafeon";
		case Species::Glaceon: return "Glaceon";
		case Species::Gliscor: return "Gliscor";
		case Species::Mamoswine: return "Mamoswine";
		case Species::Porygon_Z: return "Porygon-Z";
		case Species::Gallade: return "Gallade";
		case Species::Probopass: return "Probopass";
		case Species::Dusknoir: return "Dusknoir";
		case Species::Froslass: return "Froslass";
		case Species::Rotom: return "Rotom";
		case Species::Rotom_Heat: return "Rotom-Heat";
		case Species::Rotom_Wash: return "Rotom-Wash";
		case Species::Rotom_Frost: return "Rotom-Frost";
		case Species::Rotom_Fan: return "Rotom-Fan";
		case Species::Rotom_Mow: return "Rotom-Mow";
		case Species::Uxie: return "Uxie";
		case Species::Mesprit: return "Mesprit";
		case Species::Azelf: return "Azelf";
		case Species::Dialga: return "Dialga";
		case Species::Palkia: return "Palkia";
		case Species::Heatran: return "Heatran";
		case Species::Regigigas: return "Regigigas";
		case Species::Giratina_Altered: return "Giratina-Altered";
		case Species::Giratina_Origin: return "Giratina-Origin";
		case Species::Cresselia: return "Cresselia";
		case Species::Phione: return "Phione";
		case Species::Manaphy: return "Manaphy";
		case Species::Darkrai: return "Darkrai";
		case Species::Shaymin_Land: return "Shaymin-Land";
		case Species::Shaymin_Sky: return "Shaymin-Sky";
		case Species::Arceus: return "Arceus";

		// Generation 5
		case Species::Victini: return "Victini";
		case Species::Snivy: return "Snivy";
		case Species::Servine: return "Servine";
		case Species::Serperior: return "Serperior";
		case Species::Tepig: return "Tepig";
		case Species::Pignite: return "Pignite";
		case Species::Emboar: return "Emboar";
		case Species::Oshawott: return "Oshawott";
		case Species::Dewott: return "Dewott";
		case Species::Samurott: return "Samurott";
		case Species::Patrat: return "Patrat";
		case Species::Watchog: return "Watchog";
		case Species::Lillipup: return "Lillipup";
		case Species::Herdier: return "Herdier";
		case Species::Stoutland: return "Stoutland";
		case Species::Purrloin: return "Purrloin";
		case Species::Liepard: return "Liepard";
		case Species::Pansage: return "Pansage";
		case Species::Simisage: return "Simisage";
		case Species::Pansear: return "Pansear";
		case Species::Simisear: return "Simisear";
		case Species::Panpour: return "Panpour";
		case Species::Simipour: return "Simipour";
		case Species::Munna: return "Munna";
		case Species::Musharna: return "Musharna";
		case Species::Pidove: return "Pidove";
		case Species::Tranquill: return "Tranquill";
		case Species::Unfezant: return "Unfezant";
		case Species::Blitzle: return "Blitzle";
		case Species::Zebstrika: return "Zebstrika";
		case Species::Roggenrola: return "Roggenrola";
		case Species::Boldore: return "Boldore";
		case Species::Gigalith: return "Gigalith";
		case Species::Woobat: return "Woobat";
		case Species::Swoobat: return "Swoobat";
		case Species::Drilbur: return "Drilbur";
		case Species::Excadrill: return "Excadrill";
		case Species::Audino: return "Audino";
		case Species::Timburr: return "Timburr";
		case Species::Gurdurr: return "Gurdurr";
		case Species::Conkeldurr: return "Conkeldurr";
		case Species::Tympole: return "Tympole";
		case Species::Palpitoad: return "Palpitoad";
		case Species::Seismitoad: return "Seismitoad";
		case Species::Throh: return "Throh";
		case Species::Sawk: return "Sawk";
		case Species::Sewaddle: return "Sewaddle";
		case Species::Swadloon: return "Swadloon";
		case Species::Leavanny: return "Leavanny";
		case Species::Venipede: return "Venipede";
		case Species::Whirlipede: return "Whirlipede";
		case Species::Scolipede: return "Scolipede";
		case Species::Cottonee: return "Cottonee";
		case Species::Whimsicott: return "Whimsicott";
		case Species::Petilil: return "Petilil";
		case Species::Lilligant: return "Lilligant";
		case Species::Basculin_Red: return "Basculin-Red";
		case Species::Basculin_Blue: return "Basculin-Blue";
		case Species::Sandile: return "Sandile";
		case Species::Krokorok: return "Krokorok";
		case Species::Krookodile: return "Krookodile";
		case Species::Darumaka: return "Darumaka";
		case Species::Darmanitan: return "Darmanitan";
		case Species::Maractus: return "Maractus";
		case Species::Dwebble: return "Dwebble";
		case Species::Crustle: return "Crustle";
		case Species::Scraggy: return "Scraggy";
		case Species::Scrafty: return "Scrafty";
		case Species::Sigilyph: return "Sigilyph";
		case Species::Yamask: return "Yamask";
		case Species::Cofagrigus: return "Cofagrigus";
		case Species::Tirtouga: return "Tirtouga";
		case Species::Carracosta: return "Carracosta";
		case Species::Archen: return "Archen";
		case Species::Archeops: return "Archeops";
		case Species::Trubbish: return "Trubbish";
		case Species::Garbodor: return "Garbodor";
		case Species::Zorua: return "Zorua";
		case Species::Zoroark: return "Zoroark";
		case Species::Minccino: return "Minccino";
		case Species::Cinccino: return "Cinccino";
		case Species::Gothita: return "Gothita";
		case Species::Gothorita: return "Gothorita";
		case Species::Gothitelle: return "Gothitelle";
		case Species::Solosis: return "Solosis";
		case Species::Duosion: return "Duosion";
		case Species::Reuniclus: return "Reuniclus";
		case Species::Ducklett: return "Ducklett";
		case Species::Swanna: return "Swanna";
		case Species::Vanillite: return "Vanillite";
		case Species::Vanillish: return "Vanillish";
		case Species::Vanilluxe: return "Vanilluxe";
		case Species::Deerling: return "Deerling";
		case Species::Sawsbuck: return "Sawsbuck";
		case Species::Emolga: return "Emolga";
		case Species::Karrablast: return "Karrablast";
		case Species::Escavalier: return "Escavalier";
		case Species::Foongus: return "Foongus";
		case Species::Amoonguss: return "Amoonguss";
		case Species::Frillish: return "Frillish";
		case Species::Jellicent: return "Jellicent";
		case Species::Alomomola: return "Alomomola";
		case Species::Joltik: return "Joltik";
		case Species::Galvantula: return "Galvantula";
		case Species::Ferroseed: return "Ferroseed";
		case Species::Ferrothorn: return "Ferrothorn";
		case Species::Klink: return "Klink";
		case Species::Klang: return "Klang";
		case Species::Klinklang: return "Klinklang";
		case Species::Tynamo: return "Tynamo";
		case Species::Eelektrik: return "Eelektrik";
		case Species::Eelektross: return "Eelektross";
		case Species::Elgyem: return "Elgyem";
		case Species::Beheeyem: return "Beheeyem";
		case Species::Litwick: return "Litwick";
		case Species::Lampent: return "Lampent";
		case Species::Chandelure: return "Chandelure";
		case Species::Axew: return "Axew";
		case Species::Fraxure: return "Fraxure";
		case Species::Haxorus: return "Haxorus";
		case Species::Cubchoo: return "Cubchoo";
		case Species::Beartic: return "Beartic";
		case Species::Cryogonal: return "Cryogonal";
		case Species::Shelmet: return "Shelmet";
		case Species::Accelgor: return "Accelgor";
		case Species::Stunfisk: return "Stunfisk";
		case Species::Mienfoo: return "Mienfoo";
		case Species::Mienshao: return "Mienshao";
		case Species::Druddigon: return "Druddigon";
		case Species::Golett: return "Golett";
		case Species::Golurk: return "Golurk";
		case Species::Pawniard: return "Pawniard";
		case Species::Bisharp: return "Bisharp";
		case Species::Bouffalant: return "Bouffalant";
		case Species::Rufflet: return "Rufflet";
		case Species::Braviary: return "Braviary";
		case Species::Vullaby: return "Vullaby";
		case Species::Mandibuzz: return "Mandibuzz";
		case Species::Heatmor: return "Heatmor";
		case Species::Durant: return "Durant";
		case Species::Deino: return "Deino";
		case Species::Zweilous: return "Zweilous";
		case Species::Hydreigon: return "Hydreigon";
		case Species::Larvesta: return "Larvesta";
		case Species::Volcarona: return "Volcarona";
		case Species::Cobalion: return "Cobalion";
		case Species::Terrakion: return "Terrakion";
		case Species::Virizion: return "Virizion";
		case Species::Tornadus_Incarnate: return "Tornadus-Incarnate";
		case Species::Tornadus_Therian: return "Tornadus-Therian";
		case Species::Thundurus_Incarnate: return "Thundurus-Incarnate";
		case Species::Thundurus_Therian: return "Thundurus-Therian";
		case Species::Reshiram: return "Reshiram";
		case Species::Zekrom: return "Zekrom";
		case Species::Landorus_Incarnate: return "Landorus-Incarnate";
		case Species::Landorus_Therian: return "Landorus-Therian";
		case Species::Kyurem: return "Kyurem";
		case Species::Kyurem_Black: return "Kyurem-Black";
		case Species::Kyurem_White: return "Kyurem-White";
		case Species::Keldeo: return "Keldeo";
		case Species::Meloetta: return "Meloetta";
		case Species::Genesect: return "Genesect";
	};
}

template<>
Species from_string(std::string_view const str) {
	static std::map<std::string_view, Species, lowercase_ordering> const converter {
		// Generation 1
		{ "bulbasaur", Species::Bulbasaur },
		{ "ivysaur", Species::Ivysaur },
		{ "venusaur", Species::Venusaur },
		{ "charmander", Species::Charmander },
		{ "charmeleon", Species::Charmeleon },
		{ "charizard", Species::Charizard },
		{ "squirtle", Species::Squirtle },
		{ "wartortle", Species::Wartortle },
		{ "blastoise", Species::Blastoise },
		{ "caterpie", Species::Caterpie },
		{ "metapod", Species::Metapod },
		{ "butterfree", Species::Butterfree },
		{ "weedle", Species::Weedle },
		{ "kakuna", Species::Kakuna },
		{ "beedrill", Species::Beedrill },
		{ "pidgey", Species::Pidgey },
		{ "pidgeotto", Species::Pidgeotto },
		{ "pidgeot", Species::Pidgeot },
		{ "rattata", Species::Rattata },
		{ "raticate", Species::Raticate },
		{ "spearow", Species::Spearow },
		{ "fearow", Species::Fearow },
		{ "ekans", Species::Ekans },
		{ "arbok", Species::Arbok },
		{ "pikachu", Species::Pikachu },
		{ "raichu", Species::Raichu },
		{ "sandshrew", Species::Sandshrew },
		{ "sandslash", Species::Sandslash },
		{ "nidoran-f", Species::Nidoran_F },
		{ "nidorina", Species::Nidorina },
		{ "nidoqueen", Species::Nidoqueen },
		{ "nidoran-m", Species::Nidoran_M },
		{ "nidorino", Species::Nidorino },
		{ "nidoking", Species::Nidoking },
		{ "clefairy", Species::Clefairy },
		{ "clefable", Species::Clefable },
		{ "vulpix", Species::Vulpix },
		{ "ninetales", Species::Ninetales },
		{ "jigglypuff", Species::Jigglypuff },
		{ "wigglytuff", Species::Wigglytuff },
		{ "zubat", Species::Zubat },
		{ "golbat", Species::Golbat },
		{ "oddish", Species::Oddish },
		{ "gloom", Species::Gloom },
		{ "vileplume", Species::Vileplume },
		{ "paras", Species::Paras },
		{ "parasect", Species::Parasect },
		{ "venonat", Species::Venonat },
		{ "venomoth", Species::Venomoth },
		{ "diglett", Species::Diglett },
		{ "dugtrio", Species::Dugtrio },
		{ "meowth", Species::Meowth },
		{ "persian", Species::Persian },
		{ "psyduck", Species::Psyduck },
		{ "golduck", Species::Golduck },
		{ "mankey", Species::Mankey },
		{ "primeape", Species::Primeape },
		{ "growlithe", Species::Growlithe },
		{ "arcanine", Species::Arcanine },
		{ "poliwag", Species::Poliwag },
		{ "poliwhirl", Species::Poliwhirl },
		{ "poliwrath", Species::Poliwrath },
		{ "abra", Species::Abra },
		{ "kadabra", Species::Kadabra },
		{ "alakazam", Species::Alakazam },
		{ "machop", Species::Machop },
		{ "machoke", Species::Machoke },
		{ "machamp", Species::Machamp },
		{ "bellsprout", Species::Bellsprout },
		{ "weepinbell", Species::Weepinbell },
		{ "victreebel", Species::Victreebel },
		{ "tentacool", Species::Tentacool },
		{ "tentacruel", Species::Tentacruel },
		{ "geodude", Species::Geodude },
		{ "graveler", Species::Graveler },
		{ "golem", Species::Golem },
		{ "ponyta", Species::Ponyta },
		{ "rapidash", Species::Rapidash },
		{ "slowpoke", Species::Slowpoke },
		{ "slowbro", Species::Slowbro },
		{ "magnemite", Species::Magnemite },
		{ "magneton", Species::Magneton },
		{ "farfetch'd", Species::Farfetchd },
		{ "farfetchd", Species::Farfetchd },
		{ "doduo", Species::Doduo },
		{ "dodrio", Species::Dodrio },
		{ "seel", Species::Seel },
		{ "dewgong", Species::Dewgong },
		{ "grimer", Species::Grimer },
		{ "muk", Species::Muk },
		{ "shellder", Species::Shellder },
		{ "cloyster", Species::Cloyster },
		{ "gastly", Species::Gastly },
		{ "haunter", Species::Haunter },
		{ "gengar", Species::Gengar },
		{ "onix", Species::Onix },
		{ "drowzee", Species::Drowzee },
		{ "hypno", Species::Hypno },
		{ "krabby", Species::Krabby },
		{ "kingler", Species::Kingler },
		{ "voltorb", Species::Voltorb },
		{ "electrode", Species::Electrode },
		{ "exeggcute", Species::Exeggcute },
		{ "exeggutor", Species::Exeggutor },
		{ "cubone", Species::Cubone },
		{ "marowak", Species::Marowak },
		{ "hitmonlee", Species::Hitmonlee },
		{ "hitmonchan", Species::Hitmonchan },
		{ "lickitung", Species::Lickitung },
		{ "koffing", Species::Koffing },
		{ "weezing", Species::Weezing },
		{ "rhyhorn", Species::Rhyhorn },
		{ "rhydon", Species::Rhydon },
		{ "chansey", Species::Chansey },
		{ "tangela", Species::Tangela },
		{ "kangaskhan", Species::Kangaskhan },
		{ "horsea", Species::Horsea },
		{ "seadra", Species::Seadra },
		{ "goldeen", Species::Goldeen },
		{ "seaking", Species::Seaking },
		{ "staryu", Species::Staryu },
		{ "starmie", Species::Starmie },
		{ "mr. mime", Species::Mr_Mime },
		{ "mr mime", Species::Mr_Mime },
		{ "scyther", Species::Scyther },
		{ "jynx", Species::Jynx },
		{ "electabuzz", Species::Electabuzz },
		{ "magmar", Species::Magmar },
		{ "pinsir", Species::Pinsir },
		{ "tauros", Species::Tauros },
		{ "magikarp", Species::Magikarp },
		{ "gyarados", Species::Gyarados },
		{ "lapras", Species::Lapras },
		{ "ditto", Species::Ditto },
		{ "eevee", Species::Eevee },
		{ "vaporeon", Species::Vaporeon },
		{ "jolteon", Species::Jolteon },
		{ "flareon", Species::Flareon },
		{ "porygon", Species::Porygon },
		{ "omanyte", Species::Omanyte },
		{ "omastar", Species::Omastar },
		{ "kabuto", Species::Kabuto },
		{ "kabutops", Species::Kabutops },
		{ "aerodactyl", Species::Aerodactyl },
		{ "snorlax", Species::Snorlax },
		{ "articuno", Species::Articuno },
		{ "zapdos", Species::Zapdos },
		{ "moltres", Species::Moltres },
		{ "dratini", Species::Dratini },
		{ "dragonair", Species::Dragonair },
		{ "dragonite", Species::Dragonite },
		{ "mewtwo", Species::Mewtwo },
		{ "mew", Species::Mew },

		// Generation 2	
		{ "chikorita", Species::Chikorita },
		{ "bayleef", Species::Bayleef },
		{ "meganium", Species::Meganium },
		{ "cyndaquil", Species::Cyndaquil },
		{ "quilava", Species::Quilava },
		{ "typhlosion", Species::Typhlosion },
		{ "totodile", Species::Totodile },
		{ "croconaw", Species::Croconaw },
		{ "feraligatr", Species::Feraligatr },
		{ "sentret", Species::Sentret },
		{ "furret", Species::Furret },
		{ "hoothoot", Species::Hoothoot },
		{ "noctowl", Species::Noctowl },
		{ "ledyba", Species::Ledyba },
		{ "ledian", Species::Ledian },
		{ "spinarak", Species::Spinarak },
		{ "ariados", Species::Ariados },
		{ "crobat", Species::Crobat },
		{ "chinchou", Species::Chinchou },
		{ "lanturn", Species::Lanturn },
		{ "pichu", Species::Pichu },
		{ "cleffa", Species::Cleffa },
		{ "igglybuff", Species::Igglybuff },
		{ "togepi", Species::Togepi },
		{ "togetic", Species::Togetic },
		{ "natu", Species::Natu },
		{ "xatu", Species::Xatu },
		{ "mareep", Species::Mareep },
		{ "flaaffy", Species::Flaaffy },
		{ "ampharos", Species::Ampharos },
		{ "bellossom", Species::Bellossom },
		{ "marill", Species::Marill },
		{ "azumarill", Species::Azumarill },
		{ "sudowoodo", Species::Sudowoodo },
		{ "politoed", Species::Politoed },
		{ "hoppip", Species::Hoppip },
		{ "skiploom", Species::Skiploom },
		{ "jumpluff", Species::Jumpluff },
		{ "aipom", Species::Aipom },
		{ "sunkern", Species::Sunkern },
		{ "sunflora", Species::Sunflora },
		{ "yanma", Species::Yanma },
		{ "wooper", Species::Wooper },
		{ "quagsire", Species::Quagsire },
		{ "espeon", Species::Espeon },
		{ "umbreon", Species::Umbreon },
		{ "murkrow", Species::Murkrow },
		{ "slowking", Species::Slowking },
		{ "misdreavus", Species::Misdreavus },
		{ "unown", Species::Unown },
		{ "wobbuffet", Species::Wobbuffet },
		{ "girafarig", Species::Girafarig },
		{ "pineco", Species::Pineco },
		{ "forretress", Species::Forretress },
		{ "dunsparce", Species::Dunsparce },
		{ "gligar", Species::Gligar },
		{ "steelix", Species::Steelix },
		{ "snubbull", Species::Snubbull },
		{ "granbull", Species::Granbull },
		{ "qwilfish", Species::Qwilfish },
		{ "scizor", Species::Scizor },
		{ "shuckle", Species::Shuckle },
		{ "heracross", Species::Heracross },
		{ "sneasel", Species::Sneasel },
		{ "teddiursa", Species::Teddiursa },
		{ "ursaring", Species::Ursaring },
		{ "slugma", Species::Slugma },
		{ "magcargo", Species::Magcargo },
		{ "swinub", Species::Swinub },
		{ "piloswine", Species::Piloswine },
		{ "corsola", Species::Corsola },
		{ "remoraid", Species::Remoraid },
		{ "octillery", Species::Octillery },
		{ "delibird", Species::Delibird },
		{ "mantine", Species::Mantine },
		{ "skarmory", Species::Skarmory },
		{ "houndour", Species::Houndour },
		{ "houndoom", Species::Houndoom },
		{ "kingdra", Species::Kingdra },
		{ "phanpy", Species::Phanpy },
		{ "donphan", Species::Donphan },
		{ "porygon2", Species::Porygon2 },
		{ "stantler", Species::Stantler },
		{ "smeargle", Species::Smeargle },
		{ "tyrogue", Species::Tyrogue },
		{ "hitmontop", Species::Hitmontop },
		{ "smoochum", Species::Smoochum },
		{ "elekid", Species::Elekid },
		{ "magby", Species::Magby },
		{ "miltank", Species::Miltank },
		{ "blissey", Species::Blissey },
		{ "raikou", Species::Raikou },
		{ "entei", Species::Entei },
		{ "suicune", Species::Suicune },
		{ "larvitar", Species::Larvitar },
		{ "pupitar", Species::Pupitar },
		{ "tyranitar", Species::Tyranitar },
		{ "lugia", Species::Lugia },
		{ "ho-oh", Species::Ho_Oh },
		{ "celebi", Species::Celebi },

		// Generation 3	
		{ "treecko", Species::Treecko },
		{ "grovyle", Species::Grovyle },
		{ "sceptile", Species::Sceptile },
		{ "torchic", Species::Torchic },
		{ "combusken", Species::Combusken },
		{ "blaziken", Species::Blaziken },
		{ "mudkip", Species::Mudkip },
		{ "marshtomp", Species::Marshtomp },
		{ "swampert", Species::Swampert },
		{ "poochyena", Species::Poochyena },
		{ "mightyena", Species::Mightyena },
		{ "zigzagoon", Species::Zigzagoon },
		{ "linoone", Species::Linoone },
		{ "wurmple", Species::Wurmple },
		{ "silcoon", Species::Silcoon },
		{ "beautifly", Species::Beautifly },
		{ "cascoon", Species::Cascoon },
		{ "dustox", Species::Dustox },
		{ "lotad", Species::Lotad },
		{ "lombre", Species::Lombre },
		{ "ludicolo", Species::Ludicolo },
		{ "seedot", Species::Seedot },
		{ "nuzleaf", Species::Nuzleaf },
		{ "shiftry", Species::Shiftry },
		{ "taillow", Species::Taillow },
		{ "swellow", Species::Swellow },
		{ "wingull", Species::Wingull },
		{ "pelipper", Species::Pelipper },
		{ "ralts", Species::Ralts },
		{ "kirlia", Species::Kirlia },
		{ "gardevoir", Species::Gardevoir },
		{ "surskit", Species::Surskit },
		{ "masquerain", Species::Masquerain },
		{ "shroomish", Species::Shroomish },
		{ "breloom", Species::Breloom },
		{ "slakoth", Species::Slakoth },
		{ "vigoroth", Species::Vigoroth },
		{ "slaking", Species::Slaking },
		{ "nincada", Species::Nincada },
		{ "ninjask", Species::Ninjask },
		{ "shedinja", Species::Shedinja },
		{ "whismur", Species::Whismur },
		{ "loudred", Species::Loudred },
		{ "exploud", Species::Exploud },
		{ "makuhita", Species::Makuhita },
		{ "hariyama", Species::Hariyama },
		{ "azurill", Species::Azurill },
		{ "nosepass", Species::Nosepass },
		{ "skitty", Species::Skitty },
		{ "delcatty", Species::Delcatty },
		{ "sableye", Species::Sableye },
		{ "mawile", Species::Mawile },
		{ "aron", Species::Aron },
		{ "lairon", Species::Lairon },
		{ "aggron", Species::Aggron },
		{ "meditite", Species::Meditite },
		{ "medicham", Species::Medicham },
		{ "electrike", Species::Electrike },
		{ "manectric", Species::Manectric },
		{ "plusle", Species::Plusle },
		{ "minun", Species::Minun },
		{ "volbeat", Species::Volbeat },
		{ "illumise", Species::Illumise },
		{ "roselia", Species::Roselia },
		{ "gulpin", Species::Gulpin },
		{ "swalot", Species::Swalot },
		{ "carvanha", Species::Carvanha },
		{ "sharpedo", Species::Sharpedo },
		{ "wailmer", Species::Wailmer },
		{ "wailord", Species::Wailord },
		{ "numel", Species::Numel },
		{ "camerupt", Species::Camerupt },
		{ "torkoal", Species::Torkoal },
		{ "spoink", Species::Spoink },
		{ "grumpig", Species::Grumpig },
		{ "spinda", Species::Spinda },
		{ "trapinch", Species::Trapinch },
		{ "vibrava", Species::Vibrava },
		{ "flygon", Species::Flygon },
		{ "cacnea", Species::Cacnea },
		{ "cacturne", Species::Cacturne },
		{ "swablu", Species::Swablu },
		{ "altaria", Species::Altaria },
		{ "zangoose", Species::Zangoose },
		{ "seviper", Species::Seviper },
		{ "lunatone", Species::Lunatone },
		{ "solrock", Species::Solrock },
		{ "barboach", Species::Barboach },
		{ "whiscash", Species::Whiscash },
		{ "corphish", Species::Corphish },
		{ "crawdaunt", Species::Crawdaunt },
		{ "baltoy", Species::Baltoy },
		{ "claydol", Species::Claydol },
		{ "lileep", Species::Lileep },
		{ "cradily", Species::Cradily },
		{ "anorith", Species::Anorith },
		{ "armaldo", Species::Armaldo },
		{ "feebas", Species::Feebas },
		{ "milotic", Species::Milotic },
		{ "castform", Species::Castform },
		{ "kecleon", Species::Kecleon },
		{ "shuppet", Species::Shuppet },
		{ "banette", Species::Banette },
		{ "duskull", Species::Duskull },
		{ "dusclops", Species::Dusclops },
		{ "tropius", Species::Tropius },
		{ "chimecho", Species::Chimecho },
		{ "absol", Species::Absol },
		{ "wynaut", Species::Wynaut },
		{ "snorunt", Species::Snorunt },
		{ "glalie", Species::Glalie },
		{ "spheal", Species::Spheal },
		{ "sealeo", Species::Sealeo },
		{ "walrein", Species::Walrein },
		{ "clamperl", Species::Clamperl },
		{ "huntail", Species::Huntail },
		{ "gorebyss", Species::Gorebyss },
		{ "relicanth", Species::Relicanth },
		{ "luvdisc", Species::Luvdisc },
		{ "bagon", Species::Bagon },
		{ "shelgon", Species::Shelgon },
		{ "salamence", Species::Salamence },
		{ "beldum", Species::Beldum },
		{ "metang", Species::Metang },
		{ "metagross", Species::Metagross },
		{ "regirock", Species::Regirock },
		{ "regice", Species::Regice },
		{ "registeel", Species::Registeel },
		{ "latias", Species::Latias },
		{ "latios", Species::Latios },
		{ "kyogre", Species::Kyogre },
		{ "groudon", Species::Groudon },
		{ "rayquaza", Species::Rayquaza },
		{ "jirachi", Species::Jirachi },
		{ "deoxys-mediocre", Species::Deoxys_Mediocre },
		{ "deoxys", Species::Deoxys_Mediocre },
		{ "deoxys-attack", Species::Deoxys_Attack },
		{ "deoxys-defense", Species::Deoxys_Defense },
		{ "deoxys-speed", Species::Deoxys_Speed },

		// Generation 4	
		{ "turtwig", Species::Turtwig },
		{ "grotle", Species::Grotle },
		{ "torterra", Species::Torterra },
		{ "chimchar", Species::Chimchar },
		{ "monferno", Species::Monferno },
		{ "infernape", Species::Infernape },
		{ "piplup", Species::Piplup },
		{ "prinplup", Species::Prinplup },
		{ "empoleon", Species::Empoleon },
		{ "starly", Species::Starly },
		{ "staravia", Species::Staravia },
		{ "staraptor", Species::Staraptor },
		{ "bidoof", Species::Bidoof },
		{ "bibarel", Species::Bibarel },
		{ "kricketot", Species::Kricketot },
		{ "kricketune", Species::Kricketune },
		{ "shinx", Species::Shinx },
		{ "luxio", Species::Luxio },
		{ "luxray", Species::Luxray },
		{ "budew", Species::Budew },
		{ "roserade", Species::Roserade },
		{ "cranidos", Species::Cranidos },
		{ "rampardos", Species::Rampardos },
		{ "shieldon", Species::Shieldon },
		{ "bastiodon", Species::Bastiodon },
		{ "burmy", Species::Burmy },
		{ "wormadam-plant", Species::Wormadam_Plant },
		{ "wormadam", Species::Wormadam_Plant },
		{ "wormadam-sandy", Species::Wormadam_Sandy },
		{ "wormadam-trash", Species::Wormadam_Trash },
		{ "mothim", Species::Mothim },
		{ "combee", Species::Combee },
		{ "vespiquen", Species::Vespiquen },
		{ "pachirisu", Species::Pachirisu },
		{ "buizel", Species::Buizel },
		{ "floatzel", Species::Floatzel },
		{ "cherubi", Species::Cherubi },
		{ "cherrim", Species::Cherrim },
		{ "shellos", Species::Shellos },
		{ "gastrodon", Species::Gastrodon },
		{ "ambipom", Species::Ambipom },
		{ "drifloon", Species::Drifloon },
		{ "drifblim", Species::Drifblim },
		{ "buneary", Species::Buneary },
		{ "lopunny", Species::Lopunny },
		{ "mismagius", Species::Mismagius },
		{ "honchkrow", Species::Honchkrow },
		{ "glameow", Species::Glameow },
		{ "purugly", Species::Purugly },
		{ "chingling", Species::Chingling },
		{ "stunky", Species::Stunky },
		{ "skuntank", Species::Skuntank },
		{ "bronzor", Species::Bronzor },
		{ "bronzong", Species::Bronzong },
		{ "bonsly", Species::Bonsly },
		{ "mime jr.", Species::Mime_Jr },
		{ "mime jr", Species::Mime_Jr },
		{ "happiny", Species::Happiny },
		{ "chatot", Species::Chatot },
		{ "spiritomb", Species::Spiritomb },
		{ "gible", Species::Gible },
		{ "gabite", Species::Gabite },
		{ "garchomp", Species::Garchomp },
		{ "munchlax", Species::Munchlax },
		{ "riolu", Species::Riolu },
		{ "lucario", Species::Lucario },
		{ "hippopotas", Species::Hippopotas },
		{ "hippowdon", Species::Hippowdon },
		{ "skorupi", Species::Skorupi },
		{ "drapion", Species::Drapion },
		{ "croagunk", Species::Croagunk },
		{ "toxicroak", Species::Toxicroak },
		{ "carnivine", Species::Carnivine },
		{ "finneon", Species::Finneon },
		{ "lumineon", Species::Lumineon },
		{ "mantyke", Species::Mantyke },
		{ "snover", Species::Snover },
		{ "abomasnow", Species::Abomasnow },
		{ "weavile", Species::Weavile },
		{ "magnezone", Species::Magnezone },
		{ "lickilicky", Species::Lickilicky },
		{ "rhyperior", Species::Rhyperior },
		{ "tangrowth", Species::Tangrowth },
		{ "electivire", Species::Electivire },
		{ "magmortar", Species::Magmortar },
		{ "togekiss", Species::Togekiss },
		{ "yanmega", Species::Yanmega },
		{ "leafeon", Species::Leafeon },
		{ "glaceon", Species::Glaceon },
		{ "gliscor", Species::Gliscor },
		{ "mamoswine", Species::Mamoswine },
		{ "porygon-z", Species::Porygon_Z },
		{ "porygonz", Species::Porygon_Z },
		{ "gallade", Species::Gallade },
		{ "probopass", Species::Probopass },
		{ "dusknoir", Species::Dusknoir },
		{ "froslass", Species::Froslass },
		{ "rotom", Species::Rotom },
		{ "rotom-heat", Species::Rotom_Heat },
		{ "rotom-wash", Species::Rotom_Wash },
		{ "rotom-frost", Species::Rotom_Frost },
		{ "rotom-fan", Species::Rotom_Fan },
		{ "rotom-mow", Species::Rotom_Mow },
		{ "uxie", Species::Uxie },
		{ "mesprit", Species::Mesprit },
		{ "azelf", Species::Azelf },
		{ "dialga", Species::Dialga },
		{ "palkia", Species::Palkia },
		{ "heatran", Species::Heatran },
		{ "regigigas", Species::Regigigas },
		{ "giratina-altered", Species::Giratina_Altered },
		{ "giratina", Species::Giratina_Altered },
		{ "giratina-origin", Species::Giratina_Origin },
		{ "cresselia", Species::Cresselia },
		{ "phione", Species::Phione },
		{ "manaphy", Species::Manaphy },
		{ "darkrai", Species::Darkrai },
		{ "shaymin-land", Species::Shaymin_Land },
		{ "shaymin", Species::Shaymin_Land },
		{ "shaymin-sky", Species::Shaymin_Sky },
		{ "arceus", Species::Arceus },
		{ "arceus-bug", Species::Arceus },
		{ "arceus-dark", Species::Arceus },
		{ "arceus-dragon", Species::Arceus },
		{ "arceus-electric", Species::Arceus },
		{ "arceus-fighting", Species::Arceus },
		{ "arceus-fire", Species::Arceus },
		{ "arceus-flying", Species::Arceus },
		{ "arceus-ghost", Species::Arceus },
		{ "arceus-grass", Species::Arceus },
		{ "arceus-ground", Species::Arceus },
		{ "arceus-ice", Species::Arceus },
		{ "arceus-normal", Species::Arceus },
		{ "arceus-poison", Species::Arceus },
		{ "arceus-psychic", Species::Arceus },
		{ "arceus-rock", Species::Arceus },
		{ "arceus-steel", Species::Arceus },
		{ "arceus-water", Species::Arceus },

		// Generation 5	
		{ "victini", Species::Victini },
		{ "snivy", Species::Snivy },
		{ "servine", Species::Servine },
		{ "serperior", Species::Serperior },
		{ "tepig", Species::Tepig },
		{ "pignite", Species::Pignite },
		{ "emboar", Species::Emboar },
		{ "oshawott", Species::Oshawott },
		{ "dewott", Species::Dewott },
		{ "samurott", Species::Samurott },
		{ "patrat", Species::Patrat },
		{ "watchog", Species::Watchog },
		{ "lillipup", Species::Lillipup },
		{ "herdier", Species::Herdier },
		{ "stoutland", Species::Stoutland },
		{ "purrloin", Species::Purrloin },
		{ "liepard", Species::Liepard },
		{ "pansage", Species::Pansage },
		{ "simisage", Species::Simisage },
		{ "pansear", Species::Pansear },
		{ "simisear", Species::Simisear },
		{ "panpour", Species::Panpour },
		{ "simipour", Species::Simipour },
		{ "munna", Species::Munna },
		{ "musharna", Species::Musharna },
		{ "pidove", Species::Pidove },
		{ "tranquill", Species::Tranquill },
		{ "unfezant", Species::Unfezant },
		{ "blitzle", Species::Blitzle },
		{ "zebstrika", Species::Zebstrika },
		{ "roggenrola", Species::Roggenrola },
		{ "boldore", Species::Boldore },
		{ "gigalith", Species::Gigalith },
		{ "woobat", Species::Woobat },
		{ "swoobat", Species::Swoobat },
		{ "drilbur", Species::Drilbur },
		{ "excadrill", Species::Excadrill },
		{ "audino", Species::Audino },
		{ "timburr", Species::Timburr },
		{ "gurdurr", Species::Gurdurr },
		{ "conkeldurr", Species::Conkeldurr },
		{ "tympole", Species::Tympole },
		{ "palpitoad", Species::Palpitoad },
		{ "seismitoad", Species::Seismitoad },
		{ "throh", Species::Throh },
		{ "sawk", Species::Sawk },
		{ "sewaddle", Species::Sewaddle },
		{ "swadloon", Species::Swadloon },
		{ "leavanny", Species::Leavanny },
		{ "venipede", Species::Venipede },
		{ "whirlipede", Species::Whirlipede },
		{ "scolipede", Species::Scolipede },
		{ "cottonee", Species::Cottonee },
		{ "whimsicott", Species::Whimsicott },
		{ "petilil", Species::Petilil },
		{ "lilligant", Species::Lilligant },
		{ "basculin-red", Species::Basculin_Red },
		{ "basculin-blue", Species::Basculin_Blue },
		{ "sandile", Species::Sandile },
		{ "krokorok", Species::Krokorok },
		{ "krookodile", Species::Krookodile },
		{ "darumaka", Species::Darumaka },
		{ "darmanitan", Species::Darmanitan },
		{ "maractus", Species::Maractus },
		{ "dwebble", Species::Dwebble },
		{ "crustle", Species::Crustle },
		{ "scraggy", Species::Scraggy },
		{ "scrafty", Species::Scrafty },
		{ "sigilyph", Species::Sigilyph },
		{ "yamask", Species::Yamask },
		{ "cofagrigus", Species::Cofagrigus },
		{ "tirtouga", Species::Tirtouga },
		{ "carracosta", Species::Carracosta },
		{ "archen", Species::Archen },
		{ "archeops", Species::Archeops },
		{ "trubbish", Species::Trubbish },
		{ "garbodor", Species::Garbodor },
		{ "zorua", Species::Zorua },
		{ "zoroark", Species::Zoroark },
		{ "minccino", Species::Minccino },
		{ "cinccino", Species::Cinccino },
		{ "gothita", Species::Gothita },
		{ "gothorita", Species::Gothorita },
		{ "gothitelle", Species::Gothitelle },
		{ "solosis", Species::Solosis },
		{ "duosion", Species::Duosion },
		{ "reuniclus", Species::Reuniclus },
		{ "ducklett", Species::Ducklett },
		{ "swanna", Species::Swanna },
		{ "vanillite", Species::Vanillite },
		{ "vanillish", Species::Vanillish },
		{ "vanilluxe", Species::Vanilluxe },
		{ "deerling", Species::Deerling },
		{ "sawsbuck", Species::Sawsbuck },
		{ "emolga", Species::Emolga },
		{ "karrablast", Species::Karrablast },
		{ "escavalier", Species::Escavalier },
		{ "foongus", Species::Foongus },
		{ "amoonguss", Species::Amoonguss },
		{ "frillish", Species::Frillish },
		{ "jellicent", Species::Jellicent },
		{ "alomomola", Species::Alomomola },
		{ "joltik", Species::Joltik },
		{ "galvantula", Species::Galvantula },
		{ "ferroseed", Species::Ferroseed },
		{ "ferrothorn", Species::Ferrothorn },
		{ "klink", Species::Klink },
		{ "klang", Species::Klang },
		{ "klinklang", Species::Klinklang },
		{ "tynamo", Species::Tynamo },
		{ "eelektrik", Species::Eelektrik },
		{ "eelektross", Species::Eelektross },
		{ "elgyem", Species::Elgyem },
		{ "beheeyem", Species::Beheeyem },
		{ "litwick", Species::Litwick },
		{ "lampent", Species::Lampent },
		{ "chandelure", Species::Chandelure },
		{ "axew", Species::Axew },
		{ "fraxure", Species::Fraxure },
		{ "haxorus", Species::Haxorus },
		{ "cubchoo", Species::Cubchoo },
		{ "beartic", Species::Beartic },
		{ "cryogonal", Species::Cryogonal },
		{ "shelmet", Species::Shelmet },
		{ "accelgor", Species::Accelgor },
		{ "stunfisk", Species::Stunfisk },
		{ "mienfoo", Species::Mienfoo },
		{ "mienshao", Species::Mienshao },
		{ "druddigon", Species::Druddigon },
		{ "golett", Species::Golett },
		{ "golurk", Species::Golurk },
		{ "pawniard", Species::Pawniard },
		{ "bisharp", Species::Bisharp },
		{ "bouffalant", Species::Bouffalant },
		{ "rufflet", Species::Rufflet },
		{ "braviary", Species::Braviary },
		{ "vullaby", Species::Vullaby },
		{ "mandibuzz", Species::Mandibuzz },
		{ "heatmor", Species::Heatmor },
		{ "durant", Species::Durant },
		{ "deino", Species::Deino },
		{ "zweilous", Species::Zweilous },
		{ "hydreigon", Species::Hydreigon },
		{ "larvesta", Species::Larvesta },
		{ "volcarona", Species::Volcarona },
		{ "cobalion", Species::Cobalion },
		{ "terrakion", Species::Terrakion },
		{ "virizion", Species::Virizion },
		{ "tornadus-incarnate", Species::Tornadus_Incarnate },
		{ "tornadus-therian", Species::Tornadus_Therian },
		{ "thundurus-incarnate", Species::Thundurus_Incarnate },
		{ "thundurus-therian", Species::Thundurus_Therian },
		{ "reshiram", Species::Reshiram },
		{ "zekrom", Species::Zekrom },
		{ "landorus-incarnate", Species::Landorus_Incarnate },
		{ "landorus-therian", Species::Landorus_Therian },
		{ "kyurem", Species::Kyurem },
		{ "kyurem-black", Species::Kyurem_Black },
		{ "kyurem-white", Species::Kyurem_White },
		{ "keldeo", Species::Keldeo },
		{ "meloetta", Species::Meloetta },
		{ "genesect", Species::Genesect }
	};
	std::string normalized = std::string(str);
	// TODO: Do I still need this?
	std::replace(begin(normalized), end(normalized), '_', '-');
	auto const it = converter.find(normalized);
	if (it != end(converter)) {
		return it->second;
	} else {
		throw InvalidFromStringConversion("Species", str);
	}
}

}	// namespace technicalmachine
