// Type function definitions
// Copyright (C) 2018 David Stone
//
// This file is part of Technical Machine.
//
// Technical Machine is free software: you can redistribute it and / or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.

#include <tm/type/pokemon_types.hpp>

#include <tm/pokemon/pokemon.hpp>
#include <tm/pokemon/species.hpp>

#include <tm/generation.hpp>

#include <containers/algorithms/all_any_none.hpp>

namespace technicalmachine {

PokemonTypes::PokemonTypes(Generation const generation, Species const species):
	PokemonTypes([=]{ switch (species) {
		// Generation 1
		case Species::Bulbasaur: return PokemonTypes(Type::Grass, Type::Poison);
		case Species::Ivysaur: return PokemonTypes(Type::Grass, Type::Poison);
		case Species::Venusaur: return PokemonTypes(Type::Grass, Type::Poison);
		case Species::Charmander: return PokemonTypes(Type::Fire);
		case Species::Charmeleon: return PokemonTypes(Type::Fire);
		case Species::Charizard: return PokemonTypes(Type::Fire, Type::Flying);
		case Species::Squirtle: return PokemonTypes(Type::Water);
		case Species::Wartortle: return PokemonTypes(Type::Water);
		case Species::Blastoise: return PokemonTypes(Type::Water);
		case Species::Caterpie: return PokemonTypes(Type::Bug);
		case Species::Metapod: return PokemonTypes(Type::Bug);
		case Species::Butterfree: return PokemonTypes(Type::Bug, Type::Flying);
		case Species::Weedle: return PokemonTypes(Type::Bug, Type::Poison);
		case Species::Kakuna: return PokemonTypes(Type::Bug, Type::Poison);
		case Species::Beedrill: return PokemonTypes(Type::Bug, Type::Poison);
		case Species::Pidgey: return PokemonTypes(Type::Normal, Type::Flying);
		case Species::Pidgeotto: return PokemonTypes(Type::Normal, Type::Flying);
		case Species::Pidgeot: return PokemonTypes(Type::Normal, Type::Flying);
		case Species::Rattata: return PokemonTypes(Type::Normal);
		case Species::Raticate: return PokemonTypes(Type::Normal);
		case Species::Spearow: return PokemonTypes(Type::Normal, Type::Flying);
		case Species::Fearow: return PokemonTypes(Type::Normal, Type::Flying);
		case Species::Ekans: return PokemonTypes(Type::Poison);
		case Species::Arbok: return PokemonTypes(Type::Poison);
		case Species::Pikachu: return PokemonTypes(Type::Electric);
		case Species::Raichu: return PokemonTypes(Type::Electric);
		case Species::Sandshrew: return PokemonTypes(Type::Ground);
		case Species::Sandslash: return PokemonTypes(Type::Ground);
		case Species::Nidoran_F: return PokemonTypes(Type::Poison);
		case Species::Nidorina: return PokemonTypes(Type::Poison);
		case Species::Nidoqueen: return PokemonTypes(Type::Poison, Type::Ground);
		case Species::Nidoran_M: return PokemonTypes(Type::Poison);
		case Species::Nidorino: return PokemonTypes(Type::Poison);
		case Species::Nidoking: return PokemonTypes(Type::Poison, Type::Ground);
		case Species::Clefairy: return generation <= Generation::five ? PokemonTypes(Type::Normal) : PokemonTypes(Type::Fairy);
		case Species::Clefable: return generation <= Generation::five ? PokemonTypes(Type::Normal) : PokemonTypes(Type::Fairy);
		case Species::Vulpix: return PokemonTypes(Type::Fire);
		case Species::Ninetales: return PokemonTypes(Type::Fire);
		case Species::Jigglypuff: return generation <= Generation::five ? PokemonTypes(Type::Normal) : PokemonTypes(Type::Normal, Type::Fairy);
		case Species::Wigglytuff: return generation <= Generation::five ? PokemonTypes(Type::Normal) : PokemonTypes(Type::Normal, Type::Fairy);
		case Species::Zubat: return PokemonTypes(Type::Poison, Type::Flying);
		case Species::Golbat: return PokemonTypes(Type::Poison, Type::Flying);
		case Species::Oddish: return PokemonTypes(Type::Grass, Type::Poison);
		case Species::Gloom: return PokemonTypes(Type::Grass, Type::Poison);
		case Species::Vileplume: return PokemonTypes(Type::Grass, Type::Poison);
		case Species::Paras: return PokemonTypes(Type::Bug, Type::Grass);
		case Species::Parasect: return PokemonTypes(Type::Bug, Type::Grass);
		case Species::Venonat: return PokemonTypes(Type::Bug, Type::Poison);
		case Species::Venomoth: return PokemonTypes(Type::Bug, Type::Poison);
		case Species::Diglett: return PokemonTypes(Type::Ground);
		case Species::Dugtrio: return PokemonTypes(Type::Ground);
		case Species::Meowth: return PokemonTypes(Type::Normal);
		case Species::Persian: return PokemonTypes(Type::Normal);
		case Species::Psyduck: return PokemonTypes(Type::Water);
		case Species::Golduck: return PokemonTypes(Type::Water);
		case Species::Mankey: return PokemonTypes(Type::Fighting);
		case Species::Primeape: return PokemonTypes(Type::Fighting);
		case Species::Growlithe: return PokemonTypes(Type::Fire);
		case Species::Arcanine: return PokemonTypes(Type::Fire);
		case Species::Poliwag: return PokemonTypes(Type::Water);
		case Species::Poliwhirl: return PokemonTypes(Type::Water);
		case Species::Poliwrath: return PokemonTypes(Type::Water, Type::Fighting);
		case Species::Abra: return PokemonTypes(Type::Psychic);
		case Species::Kadabra: return PokemonTypes(Type::Psychic);
		case Species::Alakazam: return PokemonTypes(Type::Psychic);
		case Species::Machop: return PokemonTypes(Type::Fighting);
		case Species::Machoke: return PokemonTypes(Type::Fighting);
		case Species::Machamp: return PokemonTypes(Type::Fighting);
		case Species::Bellsprout: return PokemonTypes(Type::Grass, Type::Poison);
		case Species::Weepinbell: return PokemonTypes(Type::Grass, Type::Poison);
		case Species::Victreebel: return PokemonTypes(Type::Grass, Type::Poison);
		case Species::Tentacool: return PokemonTypes(Type::Water, Type::Poison);
		case Species::Tentacruel: return PokemonTypes(Type::Water, Type::Poison);
		case Species::Geodude: return PokemonTypes(Type::Rock, Type::Ground);
		case Species::Graveler: return PokemonTypes(Type::Rock, Type::Ground);
		case Species::Golem: return PokemonTypes(Type::Rock, Type::Ground);
		case Species::Ponyta: return PokemonTypes(Type::Fire);
		case Species::Rapidash: return PokemonTypes(Type::Fire);
		case Species::Slowpoke: return PokemonTypes(Type::Water, Type::Psychic);
		case Species::Slowbro: return PokemonTypes(Type::Water, Type::Psychic);
		case Species::Magnemite: return generation <= Generation::one ? PokemonTypes(Type::Electric) : PokemonTypes(Type::Electric, Type::Steel);
		case Species::Magneton: return generation <= Generation::one ? PokemonTypes(Type::Electric) : PokemonTypes(Type::Electric, Type::Steel);
		case Species::Farfetchd: return PokemonTypes(Type::Normal, Type::Flying);
		case Species::Doduo: return PokemonTypes(Type::Normal, Type::Flying);
		case Species::Dodrio: return PokemonTypes(Type::Normal, Type::Flying);
		case Species::Seel: return PokemonTypes(Type::Water);
		case Species::Dewgong: return PokemonTypes(Type::Water, Type::Ice);
		case Species::Grimer: return PokemonTypes(Type::Poison);
		case Species::Muk: return PokemonTypes(Type::Poison);
		case Species::Shellder: return PokemonTypes(Type::Water);
		case Species::Cloyster: return PokemonTypes(Type::Water, Type::Ice);
		case Species::Gastly: return PokemonTypes(Type::Ghost, Type::Poison);
		case Species::Haunter: return PokemonTypes(Type::Ghost, Type::Poison);
		case Species::Gengar: return PokemonTypes(Type::Ghost, Type::Poison);
		case Species::Onix: return PokemonTypes(Type::Rock, Type::Ground);
		case Species::Drowzee: return PokemonTypes(Type::Psychic);
		case Species::Hypno: return PokemonTypes(Type::Psychic);
		case Species::Krabby: return PokemonTypes(Type::Water);
		case Species::Kingler: return PokemonTypes(Type::Water);
		case Species::Voltorb: return PokemonTypes(Type::Electric);
		case Species::Electrode: return PokemonTypes(Type::Electric);
		case Species::Exeggcute: return PokemonTypes(Type::Grass, Type::Psychic);
		case Species::Exeggutor: return PokemonTypes(Type::Grass, Type::Psychic);
		case Species::Cubone: return PokemonTypes(Type::Ground);
		case Species::Marowak: return PokemonTypes(Type::Ground);
		case Species::Hitmonlee: return PokemonTypes(Type::Fighting);
		case Species::Hitmonchan: return PokemonTypes(Type::Fighting);
		case Species::Lickitung: return PokemonTypes(Type::Normal);
		case Species::Koffing: return PokemonTypes(Type::Poison);
		case Species::Weezing: return PokemonTypes(Type::Poison);
		case Species::Rhyhorn: return PokemonTypes(Type::Ground, Type::Rock);
		case Species::Rhydon: return PokemonTypes(Type::Ground, Type::Rock);
		case Species::Chansey: return PokemonTypes(Type::Normal);
		case Species::Tangela: return PokemonTypes(Type::Grass);
		case Species::Kangaskhan: return PokemonTypes(Type::Normal);
		case Species::Horsea: return PokemonTypes(Type::Water);
		case Species::Seadra: return PokemonTypes(Type::Water);
		case Species::Goldeen: return PokemonTypes(Type::Water);
		case Species::Seaking: return PokemonTypes(Type::Water);
		case Species::Staryu: return PokemonTypes(Type::Water);
		case Species::Starmie: return PokemonTypes(Type::Water, Type::Psychic);
		case Species::Mr_Mime: return generation <= Generation::five ? PokemonTypes(Type::Psychic) : PokemonTypes(Type::Psychic, Type::Fairy);
		case Species::Scyther: return PokemonTypes(Type::Bug, Type::Flying);
		case Species::Jynx: return PokemonTypes(Type::Ice, Type::Psychic);
		case Species::Electabuzz: return PokemonTypes(Type::Electric);
		case Species::Magmar: return PokemonTypes(Type::Fire);
		case Species::Pinsir: return PokemonTypes(Type::Bug);
		case Species::Tauros: return PokemonTypes(Type::Normal);
		case Species::Magikarp: return PokemonTypes(Type::Water);
		case Species::Gyarados: return PokemonTypes(Type::Water, Type::Flying);
		case Species::Lapras: return PokemonTypes(Type::Water, Type::Ice);
		case Species::Ditto: return PokemonTypes(Type::Normal);
		case Species::Eevee: return PokemonTypes(Type::Normal);
		case Species::Vaporeon: return PokemonTypes(Type::Water);
		case Species::Jolteon: return PokemonTypes(Type::Electric);
		case Species::Flareon: return PokemonTypes(Type::Fire);
		case Species::Porygon: return PokemonTypes(Type::Normal);
		case Species::Omanyte: return PokemonTypes(Type::Rock, Type::Water);
		case Species::Omastar: return PokemonTypes(Type::Rock, Type::Water);
		case Species::Kabuto: return PokemonTypes(Type::Rock, Type::Water);
		case Species::Kabutops: return PokemonTypes(Type::Rock, Type::Water);
		case Species::Aerodactyl: return PokemonTypes(Type::Rock, Type::Flying);
		case Species::Snorlax: return PokemonTypes(Type::Normal);
		case Species::Articuno: return PokemonTypes(Type::Ice, Type::Flying);
		case Species::Zapdos: return PokemonTypes(Type::Electric, Type::Flying);
		case Species::Moltres: return PokemonTypes(Type::Fire, Type::Flying);
		case Species::Dratini: return PokemonTypes(Type::Dragon);
		case Species::Dragonair: return PokemonTypes(Type::Dragon);
		case Species::Dragonite: return PokemonTypes(Type::Dragon, Type::Flying);
		case Species::Mewtwo: return PokemonTypes(Type::Psychic);
		case Species::Mew: return PokemonTypes(Type::Psychic);

		// Generation 2
		case Species::Chikorita: return PokemonTypes(Type::Grass);
		case Species::Bayleef: return PokemonTypes(Type::Grass);
		case Species::Meganium: return PokemonTypes(Type::Grass);
		case Species::Cyndaquil: return PokemonTypes(Type::Fire);
		case Species::Quilava: return PokemonTypes(Type::Fire);
		case Species::Typhlosion: return PokemonTypes(Type::Fire);
		case Species::Totodile: return PokemonTypes(Type::Water);
		case Species::Croconaw: return PokemonTypes(Type::Water);
		case Species::Feraligatr: return PokemonTypes(Type::Water);
		case Species::Sentret: return PokemonTypes(Type::Normal);
		case Species::Furret: return PokemonTypes(Type::Normal);
		case Species::Hoothoot: return PokemonTypes(Type::Normal, Type::Flying);
		case Species::Noctowl: return PokemonTypes(Type::Normal, Type::Flying);
		case Species::Ledyba: return PokemonTypes(Type::Bug, Type::Flying);
		case Species::Ledian: return PokemonTypes(Type::Bug, Type::Flying);
		case Species::Spinarak: return PokemonTypes(Type::Bug, Type::Poison);
		case Species::Ariados: return PokemonTypes(Type::Bug, Type::Poison);
		case Species::Crobat: return PokemonTypes(Type::Poison, Type::Flying);
		case Species::Chinchou: return PokemonTypes(Type::Water, Type::Electric);
		case Species::Lanturn: return PokemonTypes(Type::Water, Type::Electric);
		case Species::Pichu: return PokemonTypes(Type::Electric);
		case Species::Cleffa: return generation <= Generation::five ? PokemonTypes(Type::Normal) : PokemonTypes(Type::Fairy);
		case Species::Igglybuff: return generation <= Generation::five ? PokemonTypes(Type::Normal) : PokemonTypes(Type::Normal, Type::Fairy);
		case Species::Togepi: return generation <= Generation::five ? PokemonTypes(Type::Normal) : PokemonTypes(Type::Fairy);
		case Species::Togetic: return generation <= Generation::five ? PokemonTypes(Type::Normal, Type::Flying) : PokemonTypes(Type::Fairy);
		case Species::Natu: return PokemonTypes(Type::Psychic, Type::Flying);
		case Species::Xatu: return PokemonTypes(Type::Psychic, Type::Flying);
		case Species::Mareep: return PokemonTypes(Type::Electric);
		case Species::Flaaffy: return PokemonTypes(Type::Electric);
		case Species::Ampharos: return PokemonTypes(Type::Electric);
		case Species::Bellossom: return PokemonTypes(Type::Grass);
		case Species::Marill: return generation <= Generation::five ? PokemonTypes(Type::Water) : PokemonTypes(Type::Water, Type::Fairy);
		case Species::Azumarill: return generation <= Generation::five ? PokemonTypes(Type::Water) : PokemonTypes(Type::Water, Type::Fairy);
		case Species::Sudowoodo: return PokemonTypes(Type::Rock);
		case Species::Politoed: return PokemonTypes(Type::Water);
		case Species::Hoppip: return PokemonTypes(Type::Grass, Type::Flying);
		case Species::Skiploom: return PokemonTypes(Type::Grass, Type::Flying);
		case Species::Jumpluff: return PokemonTypes(Type::Grass, Type::Flying);
		case Species::Aipom: return PokemonTypes(Type::Normal);
		case Species::Sunkern: return PokemonTypes(Type::Grass);
		case Species::Sunflora: return PokemonTypes(Type::Grass);
		case Species::Yanma: return PokemonTypes(Type::Bug, Type::Flying);
		case Species::Wooper: return PokemonTypes(Type::Water, Type::Ground);
		case Species::Quagsire: return PokemonTypes(Type::Water, Type::Ground);
		case Species::Espeon: return PokemonTypes(Type::Psychic);
		case Species::Umbreon: return PokemonTypes(Type::Dark);
		case Species::Murkrow: return PokemonTypes(Type::Dark, Type::Flying);
		case Species::Slowking: return PokemonTypes(Type::Water, Type::Psychic);
		case Species::Misdreavus: return PokemonTypes(Type::Ghost);
		case Species::Unown: return PokemonTypes(Type::Psychic);
		case Species::Wobbuffet: return PokemonTypes(Type::Psychic);
		case Species::Girafarig: return PokemonTypes(Type::Normal, Type::Psychic);
		case Species::Pineco: return PokemonTypes(Type::Bug);
		case Species::Forretress: return PokemonTypes(Type::Bug, Type::Steel);
		case Species::Dunsparce: return PokemonTypes(Type::Normal);
		case Species::Gligar: return PokemonTypes(Type::Ground, Type::Flying);
		case Species::Steelix: return PokemonTypes(Type::Steel, Type::Ground);
		case Species::Snubbull: return generation <= Generation::five ? PokemonTypes(Type::Normal) : PokemonTypes(Type::Fairy);
		case Species::Granbull: return generation <= Generation::five ? PokemonTypes(Type::Normal) : PokemonTypes(Type::Fairy);
		case Species::Qwilfish: return PokemonTypes(Type::Water, Type::Poison);
		case Species::Scizor: return PokemonTypes(Type::Bug, Type::Steel);
		case Species::Shuckle: return PokemonTypes(Type::Bug, Type::Rock);
		case Species::Heracross: return PokemonTypes(Type::Bug, Type::Fighting);
		case Species::Sneasel: return PokemonTypes(Type::Dark, Type::Ice);
		case Species::Teddiursa: return PokemonTypes(Type::Normal);
		case Species::Ursaring: return PokemonTypes(Type::Normal);
		case Species::Slugma: return PokemonTypes(Type::Fire);
		case Species::Magcargo: return PokemonTypes(Type::Fire, Type::Rock);
		case Species::Swinub: return PokemonTypes(Type::Ice, Type::Ground);
		case Species::Piloswine: return PokemonTypes(Type::Ice, Type::Ground);
		case Species::Corsola: return PokemonTypes(Type::Water, Type::Rock);
		case Species::Remoraid: return PokemonTypes(Type::Water);
		case Species::Octillery: return PokemonTypes(Type::Water);
		case Species::Delibird: return PokemonTypes(Type::Ice, Type::Flying);
		case Species::Mantine: return PokemonTypes(Type::Water, Type::Flying);
		case Species::Skarmory: return PokemonTypes(Type::Steel, Type::Flying);
		case Species::Houndour: return PokemonTypes(Type::Dark, Type::Fire);
		case Species::Houndoom: return PokemonTypes(Type::Dark, Type::Fire);
		case Species::Kingdra: return PokemonTypes(Type::Water, Type::Dragon);
		case Species::Phanpy: return PokemonTypes(Type::Ground);
		case Species::Donphan: return PokemonTypes(Type::Ground);
		case Species::Porygon2: return PokemonTypes(Type::Normal);
		case Species::Stantler: return PokemonTypes(Type::Normal);
		case Species::Smeargle: return PokemonTypes(Type::Normal);
		case Species::Tyrogue: return PokemonTypes(Type::Fighting);
		case Species::Hitmontop: return PokemonTypes(Type::Fighting);
		case Species::Smoochum: return PokemonTypes(Type::Ice, Type::Psychic);
		case Species::Elekid: return PokemonTypes(Type::Electric);
		case Species::Magby: return PokemonTypes(Type::Fire);
		case Species::Miltank: return PokemonTypes(Type::Normal);
		case Species::Blissey: return PokemonTypes(Type::Normal);
		case Species::Raikou: return PokemonTypes(Type::Electric);
		case Species::Entei: return PokemonTypes(Type::Fire);
		case Species::Suicune: return PokemonTypes(Type::Water);
		case Species::Larvitar: return PokemonTypes(Type::Rock, Type::Ground);
		case Species::Pupitar: return PokemonTypes(Type::Rock, Type::Ground);
		case Species::Tyranitar: return PokemonTypes(Type::Rock, Type::Dark);
		case Species::Lugia: return PokemonTypes(Type::Psychic, Type::Flying);
		case Species::Ho_Oh: return PokemonTypes(Type::Fire, Type::Flying);
		case Species::Celebi: return PokemonTypes(Type::Psychic, Type::Grass);

		// Generation 3
		case Species::Treecko: return PokemonTypes(Type::Grass);
		case Species::Grovyle: return PokemonTypes(Type::Grass);
		case Species::Sceptile: return PokemonTypes(Type::Grass);
		case Species::Torchic: return PokemonTypes(Type::Fire);
		case Species::Combusken: return PokemonTypes(Type::Fire, Type::Fighting);
		case Species::Blaziken: return PokemonTypes(Type::Fire, Type::Fighting);
		case Species::Mudkip: return PokemonTypes(Type::Water);
		case Species::Marshtomp: return PokemonTypes(Type::Water, Type::Ground);
		case Species::Swampert: return PokemonTypes(Type::Water, Type::Ground);
		case Species::Poochyena: return PokemonTypes(Type::Dark);
		case Species::Mightyena: return PokemonTypes(Type::Dark);
		case Species::Zigzagoon: return PokemonTypes(Type::Normal);
		case Species::Linoone: return PokemonTypes(Type::Normal);
		case Species::Wurmple: return PokemonTypes(Type::Bug);
		case Species::Silcoon: return PokemonTypes(Type::Bug);
		case Species::Beautifly: return PokemonTypes(Type::Bug, Type::Flying);
		case Species::Cascoon: return PokemonTypes(Type::Bug);
		case Species::Dustox: return PokemonTypes(Type::Bug, Type::Poison);
		case Species::Lotad: return PokemonTypes(Type::Water, Type::Grass);
		case Species::Lombre: return PokemonTypes(Type::Water, Type::Grass);
		case Species::Ludicolo: return PokemonTypes(Type::Water, Type::Grass);
		case Species::Seedot: return PokemonTypes(Type::Grass);
		case Species::Nuzleaf: return PokemonTypes(Type::Grass, Type::Dark);
		case Species::Shiftry: return PokemonTypes(Type::Grass, Type::Dark);
		case Species::Taillow: return PokemonTypes(Type::Normal, Type::Flying);
		case Species::Swellow: return PokemonTypes(Type::Normal, Type::Flying);
		case Species::Wingull: return PokemonTypes(Type::Water, Type::Flying);
		case Species::Pelipper: return PokemonTypes(Type::Water, Type::Flying);
		case Species::Ralts: return generation <= Generation::five ? PokemonTypes(Type::Psychic) : PokemonTypes(Type::Psychic, Type::Fairy);
		case Species::Kirlia: return generation <= Generation::five ? PokemonTypes(Type::Psychic) : PokemonTypes(Type::Psychic, Type::Fairy);
		case Species::Gardevoir: return generation <= Generation::five ? PokemonTypes(Type::Psychic) : PokemonTypes(Type::Psychic, Type::Fairy);
		case Species::Surskit: return PokemonTypes(Type::Bug, Type::Water);
		case Species::Masquerain: return PokemonTypes(Type::Bug, Type::Flying);
		case Species::Shroomish: return PokemonTypes(Type::Grass);
		case Species::Breloom: return PokemonTypes(Type::Grass, Type::Fighting);
		case Species::Slakoth: return PokemonTypes(Type::Normal);
		case Species::Vigoroth: return PokemonTypes(Type::Normal);
		case Species::Slaking: return PokemonTypes(Type::Normal);
		case Species::Nincada: return PokemonTypes(Type::Bug, Type::Ground);
		case Species::Ninjask: return PokemonTypes(Type::Bug, Type::Flying);
		case Species::Shedinja: return PokemonTypes(Type::Bug, Type::Ghost);
		case Species::Whismur: return PokemonTypes(Type::Normal);
		case Species::Loudred: return PokemonTypes(Type::Normal);
		case Species::Exploud: return PokemonTypes(Type::Normal);
		case Species::Makuhita: return PokemonTypes(Type::Fighting);
		case Species::Hariyama: return PokemonTypes(Type::Fighting);
		case Species::Azurill: return generation <= Generation::five ? PokemonTypes(Type::Normal) : PokemonTypes(Type::Normal, Type::Fairy);
		case Species::Nosepass: return PokemonTypes(Type::Rock);
		case Species::Skitty: return PokemonTypes(Type::Normal);
		case Species::Delcatty: return PokemonTypes(Type::Normal);
		case Species::Sableye: return PokemonTypes(Type::Dark, Type::Ghost);
		case Species::Mawile: return generation <= Generation::five ? PokemonTypes(Type::Steel) : PokemonTypes(Type::Steel, Type::Fairy);
		case Species::Aron: return PokemonTypes(Type::Steel, Type::Rock);
		case Species::Lairon: return PokemonTypes(Type::Steel, Type::Rock);
		case Species::Aggron: return PokemonTypes(Type::Steel, Type::Rock);
		case Species::Meditite: return PokemonTypes(Type::Fighting, Type::Psychic);
		case Species::Medicham: return PokemonTypes(Type::Fighting, Type::Psychic);
		case Species::Electrike: return PokemonTypes(Type::Electric);
		case Species::Manectric: return PokemonTypes(Type::Electric);
		case Species::Plusle: return PokemonTypes(Type::Electric);
		case Species::Minun: return PokemonTypes(Type::Electric);
		case Species::Volbeat: return PokemonTypes(Type::Bug);
		case Species::Illumise: return PokemonTypes(Type::Bug);
		case Species::Roselia: return PokemonTypes(Type::Grass, Type::Poison);
		case Species::Gulpin: return PokemonTypes(Type::Poison);
		case Species::Swalot: return PokemonTypes(Type::Poison);
		case Species::Carvanha: return PokemonTypes(Type::Water, Type::Dark);
		case Species::Sharpedo: return PokemonTypes(Type::Water, Type::Dark);
		case Species::Wailmer: return PokemonTypes(Type::Water);
		case Species::Wailord: return PokemonTypes(Type::Water);
		case Species::Numel: return PokemonTypes(Type::Fire, Type::Ground);
		case Species::Camerupt: return PokemonTypes(Type::Fire, Type::Ground);
		case Species::Torkoal: return PokemonTypes(Type::Fire);
		case Species::Spoink: return PokemonTypes(Type::Psychic);
		case Species::Grumpig: return PokemonTypes(Type::Psychic);
		case Species::Spinda: return PokemonTypes(Type::Normal);
		case Species::Trapinch: return PokemonTypes(Type::Ground);
		case Species::Vibrava: return PokemonTypes(Type::Ground, Type::Dragon);
		case Species::Flygon: return PokemonTypes(Type::Ground, Type::Dragon);
		case Species::Cacnea: return PokemonTypes(Type::Grass);
		case Species::Cacturne: return PokemonTypes(Type::Grass, Type::Dark);
		case Species::Swablu: return PokemonTypes(Type::Normal, Type::Flying);
		case Species::Altaria: return PokemonTypes(Type::Dragon, Type::Flying);
		case Species::Zangoose: return PokemonTypes(Type::Normal);
		case Species::Seviper: return PokemonTypes(Type::Poison);
		case Species::Lunatone: return PokemonTypes(Type::Rock, Type::Psychic);
		case Species::Solrock: return PokemonTypes(Type::Rock, Type::Psychic);
		case Species::Barboach: return PokemonTypes(Type::Water, Type::Ground);
		case Species::Whiscash: return PokemonTypes(Type::Water, Type::Ground);
		case Species::Corphish: return PokemonTypes(Type::Water);
		case Species::Crawdaunt: return PokemonTypes(Type::Water, Type::Dark);
		case Species::Baltoy: return PokemonTypes(Type::Ground, Type::Psychic);
		case Species::Claydol: return PokemonTypes(Type::Ground, Type::Psychic);
		case Species::Lileep: return PokemonTypes(Type::Rock, Type::Grass);
		case Species::Cradily: return PokemonTypes(Type::Rock, Type::Grass);
		case Species::Anorith: return PokemonTypes(Type::Rock, Type::Bug);
		case Species::Armaldo: return PokemonTypes(Type::Rock, Type::Bug);
		case Species::Feebas: return PokemonTypes(Type::Water);
		case Species::Milotic: return PokemonTypes(Type::Water);
		case Species::Castform: return PokemonTypes(Type::Normal);
			// return PokemonTypes(Type::Fire);
			// return PokemonTypes(Type::Water);
			// return PokemonTypes(Type::Ice);
		case Species::Kecleon: return PokemonTypes(Type::Normal);
		case Species::Shuppet: return PokemonTypes(Type::Ghost);
		case Species::Banette: return PokemonTypes(Type::Ghost);
		case Species::Duskull: return PokemonTypes(Type::Ghost);
		case Species::Dusclops: return PokemonTypes(Type::Ghost);
		case Species::Tropius: return PokemonTypes(Type::Grass, Type::Flying);
		case Species::Chimecho: return PokemonTypes(Type::Psychic);
		case Species::Absol: return PokemonTypes(Type::Dark);
		case Species::Wynaut: return PokemonTypes(Type::Psychic);
		case Species::Snorunt: return PokemonTypes(Type::Ice);
		case Species::Glalie: return PokemonTypes(Type::Ice);
		case Species::Spheal: return PokemonTypes(Type::Ice, Type::Water);
		case Species::Sealeo: return PokemonTypes(Type::Ice, Type::Water);
		case Species::Walrein: return PokemonTypes(Type::Ice, Type::Water);
		case Species::Clamperl: return PokemonTypes(Type::Water);
		case Species::Huntail: return PokemonTypes(Type::Water);
		case Species::Gorebyss: return PokemonTypes(Type::Water);
		case Species::Relicanth: return PokemonTypes(Type::Water, Type::Rock);
		case Species::Luvdisc: return PokemonTypes(Type::Water);
		case Species::Bagon: return PokemonTypes(Type::Dragon);
		case Species::Shelgon: return PokemonTypes(Type::Dragon);
		case Species::Salamence: return PokemonTypes(Type::Dragon, Type::Flying);
		case Species::Beldum: return PokemonTypes(Type::Steel, Type::Psychic);
		case Species::Metang: return PokemonTypes(Type::Steel, Type::Psychic);
		case Species::Metagross: return PokemonTypes(Type::Steel, Type::Psychic);
		case Species::Regirock: return PokemonTypes(Type::Rock);
		case Species::Regice: return PokemonTypes(Type::Ice);
		case Species::Registeel: return PokemonTypes(Type::Steel);
		case Species::Latias: return PokemonTypes(Type::Dragon, Type::Psychic);
		case Species::Latios: return PokemonTypes(Type::Dragon, Type::Psychic);
		case Species::Kyogre: return PokemonTypes(Type::Water);
		case Species::Groudon: return PokemonTypes(Type::Ground);
		case Species::Rayquaza: return PokemonTypes(Type::Dragon, Type::Flying);
		case Species::Jirachi: return PokemonTypes(Type::Steel, Type::Psychic);
		case Species::Deoxys_Normal: return PokemonTypes(Type::Psychic);
		case Species::Deoxys_Attack: return PokemonTypes(Type::Psychic);
		case Species::Deoxys_Defense: return PokemonTypes(Type::Psychic);
		case Species::Deoxys_Speed: return PokemonTypes(Type::Psychic);

		// Generation 4
		case Species::Turtwig: return PokemonTypes(Type::Grass);
		case Species::Grotle: return PokemonTypes(Type::Grass);
		case Species::Torterra: return PokemonTypes(Type::Grass, Type::Ground);
		case Species::Chimchar: return PokemonTypes(Type::Fire);
		case Species::Monferno: return PokemonTypes(Type::Fire, Type::Fighting);
		case Species::Infernape: return PokemonTypes(Type::Fire, Type::Fighting);
		case Species::Piplup: return PokemonTypes(Type::Water);
		case Species::Prinplup: return PokemonTypes(Type::Water);
		case Species::Empoleon: return PokemonTypes(Type::Water, Type::Steel);
		case Species::Starly: return PokemonTypes(Type::Normal, Type::Flying);
		case Species::Staravia: return PokemonTypes(Type::Normal, Type::Flying);
		case Species::Staraptor: return PokemonTypes(Type::Normal, Type::Flying);
		case Species::Bidoof: return PokemonTypes(Type::Normal);
		case Species::Bibarel: return PokemonTypes(Type::Normal, Type::Water);
		case Species::Kricketot: return PokemonTypes(Type::Bug);
		case Species::Kricketune: return PokemonTypes(Type::Bug);
		case Species::Shinx: return PokemonTypes(Type::Electric);
		case Species::Luxio: return PokemonTypes(Type::Electric);
		case Species::Luxray: return PokemonTypes(Type::Electric);
		case Species::Budew: return PokemonTypes(Type::Grass, Type::Poison);
		case Species::Roserade: return PokemonTypes(Type::Grass, Type::Poison);
		case Species::Cranidos: return PokemonTypes(Type::Rock);
		case Species::Rampardos: return PokemonTypes(Type::Rock);
		case Species::Shieldon: return PokemonTypes(Type::Rock, Type::Steel);
		case Species::Bastiodon: return PokemonTypes(Type::Rock, Type::Steel);
		case Species::Burmy: return PokemonTypes(Type::Bug);
		case Species::Wormadam_Plant: return PokemonTypes(Type::Bug, Type::Grass);
		case Species::Wormadam_Sandy: return PokemonTypes(Type::Bug, Type::Ground);
		case Species::Wormadam_Trash: return PokemonTypes(Type::Bug, Type::Steel);
		case Species::Mothim: return PokemonTypes(Type::Bug, Type::Flying);
		case Species::Combee: return PokemonTypes(Type::Bug, Type::Flying);
		case Species::Vespiquen: return PokemonTypes(Type::Bug, Type::Flying);
		case Species::Pachirisu: return PokemonTypes(Type::Electric);
		case Species::Buizel: return PokemonTypes(Type::Water);
		case Species::Floatzel: return PokemonTypes(Type::Water);
		case Species::Cherubi: return PokemonTypes(Type::Grass);
		case Species::Cherrim: return PokemonTypes(Type::Grass);
		case Species::Shellos: return PokemonTypes(Type::Water);
		case Species::Gastrodon: return PokemonTypes(Type::Water, Type::Ground);
		case Species::Ambipom: return PokemonTypes(Type::Normal);
		case Species::Drifloon: return PokemonTypes(Type::Ghost, Type::Flying);
		case Species::Drifblim: return PokemonTypes(Type::Ghost, Type::Flying);
		case Species::Buneary: return PokemonTypes(Type::Normal);
		case Species::Lopunny: return PokemonTypes(Type::Normal);
		case Species::Mismagius: return PokemonTypes(Type::Ghost);
		case Species::Honchkrow: return PokemonTypes(Type::Dark, Type::Flying);
		case Species::Glameow: return PokemonTypes(Type::Normal);
		case Species::Purugly: return PokemonTypes(Type::Normal);
		case Species::Chingling: return PokemonTypes(Type::Psychic);
		case Species::Stunky: return PokemonTypes(Type::Poison, Type::Dark);
		case Species::Skuntank: return PokemonTypes(Type::Poison, Type::Dark);
		case Species::Bronzor: return PokemonTypes(Type::Steel, Type::Psychic);
		case Species::Bronzong: return PokemonTypes(Type::Steel, Type::Psychic);
		case Species::Bonsly: return PokemonTypes(Type::Rock);
		case Species::Mime_Jr: return generation <= Generation::five ? PokemonTypes(Type::Psychic) : PokemonTypes(Type::Psychic, Type::Fairy);
		case Species::Happiny: return PokemonTypes(Type::Normal);
		case Species::Chatot: return PokemonTypes(Type::Normal, Type::Flying);
		case Species::Spiritomb: return PokemonTypes(Type::Ghost, Type::Dark);
		case Species::Gible: return PokemonTypes(Type::Dragon, Type::Ground);
		case Species::Gabite: return PokemonTypes(Type::Dragon, Type::Ground);
		case Species::Garchomp: return PokemonTypes(Type::Dragon, Type::Ground);
		case Species::Munchlax: return PokemonTypes(Type::Normal);
		case Species::Riolu: return PokemonTypes(Type::Fighting);
		case Species::Lucario: return PokemonTypes(Type::Fighting, Type::Steel);
		case Species::Hippopotas: return PokemonTypes(Type::Ground);
		case Species::Hippowdon: return PokemonTypes(Type::Ground);
		case Species::Skorupi: return PokemonTypes(Type::Poison, Type::Bug);
		case Species::Drapion: return PokemonTypes(Type::Poison, Type::Dark);
		case Species::Croagunk: return PokemonTypes(Type::Poison, Type::Fighting);
		case Species::Toxicroak: return PokemonTypes(Type::Poison, Type::Fighting);
		case Species::Carnivine: return PokemonTypes(Type::Grass);
		case Species::Finneon: return PokemonTypes(Type::Water);
		case Species::Lumineon: return PokemonTypes(Type::Water);
		case Species::Mantyke: return PokemonTypes(Type::Water, Type::Flying);
		case Species::Snover: return PokemonTypes(Type::Grass, Type::Ice);
		case Species::Abomasnow: return PokemonTypes(Type::Grass, Type::Ice);
		case Species::Weavile: return PokemonTypes(Type::Dark, Type::Ice);
		case Species::Magnezone: return PokemonTypes(Type::Electric, Type::Steel);
		case Species::Lickilicky: return PokemonTypes(Type::Normal);
		case Species::Rhyperior: return PokemonTypes(Type::Ground, Type::Rock);
		case Species::Tangrowth: return PokemonTypes(Type::Grass);
		case Species::Electivire: return PokemonTypes(Type::Electric);
		case Species::Magmortar: return PokemonTypes(Type::Fire);
		case Species::Togekiss: return generation <= Generation::five ? PokemonTypes(Type::Normal, Type::Flying) : PokemonTypes(Type::Fairy, Type::Flying);
		case Species::Yanmega: return PokemonTypes(Type::Bug, Type::Flying);
		case Species::Leafeon: return PokemonTypes(Type::Grass);
		case Species::Glaceon: return PokemonTypes(Type::Ice);
		case Species::Gliscor: return PokemonTypes(Type::Ground, Type::Flying);
		case Species::Mamoswine: return PokemonTypes(Type::Ice, Type::Ground);
		case Species::Porygon_Z: return PokemonTypes(Type::Normal);
		case Species::Gallade: return PokemonTypes(Type::Psychic, Type::Fighting);
		case Species::Probopass: return PokemonTypes(Type::Rock, Type::Steel);
		case Species::Dusknoir: return PokemonTypes(Type::Ghost);
		case Species::Froslass: return PokemonTypes(Type::Ice, Type::Ghost);
		case Species::Rotom: return PokemonTypes(Type::Electric, Type::Ghost);
		case Species::Rotom_Heat: return generation <= Generation::four ? PokemonTypes(Type::Electric, Type::Ghost) : PokemonTypes(Type::Electric, Type::Fire);
		case Species::Rotom_Wash: return generation <= Generation::five ? PokemonTypes(Type::Electric, Type::Ghost) : PokemonTypes(Type::Electric, Type::Water);
		case Species::Rotom_Frost: return generation <= Generation::five ? PokemonTypes(Type::Electric, Type::Ghost) : PokemonTypes(Type::Electric, Type::Ice);
		case Species::Rotom_Fan: return generation <= Generation::five ? PokemonTypes(Type::Electric, Type::Ghost) : PokemonTypes(Type::Electric, Type::Flying);
		case Species::Rotom_Mow: return generation <= Generation::four ? PokemonTypes(Type::Electric, Type::Ghost) : PokemonTypes(Type::Electric, Type::Grass);
		case Species::Uxie: return PokemonTypes(Type::Psychic);
		case Species::Mesprit: return PokemonTypes(Type::Psychic);
		case Species::Azelf: return PokemonTypes(Type::Psychic);
		case Species::Dialga: return PokemonTypes(Type::Steel, Type::Dragon);
		case Species::Palkia: return PokemonTypes(Type::Water, Type::Dragon);
		case Species::Heatran: return PokemonTypes(Type::Fire, Type::Steel);
		case Species::Regigigas: return PokemonTypes(Type::Normal);
		case Species::Giratina_Altered: return PokemonTypes(Type::Ghost, Type::Dragon);
		case Species::Giratina_Origin: return PokemonTypes(Type::Ghost, Type::Dragon);
		case Species::Cresselia: return PokemonTypes(Type::Psychic);
		case Species::Phione: return PokemonTypes(Type::Water);
		case Species::Manaphy: return PokemonTypes(Type::Water);
		case Species::Darkrai: return PokemonTypes(Type::Dark);
		case Species::Shaymin_Land: return PokemonTypes(Type::Grass);
		case Species::Shaymin_Sky: return PokemonTypes(Type::Grass, Type::Flying);
		case Species::Arceus: return PokemonTypes(Type::Normal);

		// Generation 5
		case Species::Victini: return PokemonTypes(Type::Psychic, Type::Fire);
		case Species::Snivy: return PokemonTypes(Type::Grass);
		case Species::Servine: return PokemonTypes(Type::Grass);
		case Species::Serperior: return PokemonTypes(Type::Grass);
		case Species::Tepig: return PokemonTypes(Type::Fire);
		case Species::Pignite: return PokemonTypes(Type::Fire, Type::Fighting);
		case Species::Emboar: return PokemonTypes(Type::Fire, Type::Fighting);
		case Species::Oshawott: return PokemonTypes(Type::Water);
		case Species::Dewott: return PokemonTypes(Type::Water);
		case Species::Samurott: return PokemonTypes(Type::Water);
		case Species::Patrat: return PokemonTypes(Type::Normal);
		case Species::Watchog: return PokemonTypes(Type::Normal);
		case Species::Lillipup: return PokemonTypes(Type::Normal);
		case Species::Herdier: return PokemonTypes(Type::Normal);
		case Species::Stoutland: return PokemonTypes(Type::Normal);
		case Species::Purrloin: return PokemonTypes(Type::Dark);
		case Species::Liepard: return PokemonTypes(Type::Dark);
		case Species::Pansage: return PokemonTypes(Type::Grass);
		case Species::Simisage: return PokemonTypes(Type::Grass);
		case Species::Pansear: return PokemonTypes(Type::Fire);
		case Species::Simisear: return PokemonTypes(Type::Fire);
		case Species::Panpour: return PokemonTypes(Type::Water);
		case Species::Simipour: return PokemonTypes(Type::Water);
		case Species::Munna: return PokemonTypes(Type::Psychic);
		case Species::Musharna: return PokemonTypes(Type::Psychic);
		case Species::Pidove: return PokemonTypes(Type::Normal, Type::Flying);
		case Species::Tranquill: return PokemonTypes(Type::Normal, Type::Flying);
		case Species::Unfezant: return PokemonTypes(Type::Normal, Type::Flying);
		case Species::Blitzle: return PokemonTypes(Type::Electric);
		case Species::Zebstrika: return PokemonTypes(Type::Electric);
		case Species::Roggenrola: return PokemonTypes(Type::Rock);
		case Species::Boldore: return PokemonTypes(Type::Rock);
		case Species::Gigalith: return PokemonTypes(Type::Rock);
		case Species::Woobat: return PokemonTypes(Type::Psychic, Type::Flying);
		case Species::Swoobat: return PokemonTypes(Type::Psychic, Type::Flying);
		case Species::Drilbur: return PokemonTypes(Type::Ground);
		case Species::Excadrill: return PokemonTypes(Type::Ground, Type::Steel);
		case Species::Audino: return PokemonTypes(Type::Normal);
		case Species::Timburr: return PokemonTypes(Type::Fighting);
		case Species::Gurdurr: return PokemonTypes(Type::Fighting);
		case Species::Conkeldurr: return PokemonTypes(Type::Fighting);
		case Species::Tympole: return PokemonTypes(Type::Water);
		case Species::Palpitoad: return PokemonTypes(Type::Water, Type::Ground);
		case Species::Seismitoad: return PokemonTypes(Type::Water, Type::Ground);
		case Species::Throh: return PokemonTypes(Type::Fighting);
		case Species::Sawk: return PokemonTypes(Type::Fighting);
		case Species::Sewaddle: return PokemonTypes(Type::Bug, Type::Grass);
		case Species::Swadloon: return PokemonTypes(Type::Bug, Type::Grass);
		case Species::Leavanny: return PokemonTypes(Type::Bug, Type::Grass);
		case Species::Venipede: return PokemonTypes(Type::Bug, Type::Poison);
		case Species::Whirlipede: return PokemonTypes(Type::Bug, Type::Poison);
		case Species::Scolipede: return PokemonTypes(Type::Bug, Type::Poison);
		case Species::Cottonee: return generation <= Generation::five ? PokemonTypes(Type::Grass) : PokemonTypes(Type::Grass, Type::Fairy);
		case Species::Whimsicott: return generation <= Generation::five ? PokemonTypes(Type::Grass) : PokemonTypes(Type::Grass, Type::Fairy);
		case Species::Petilil: return PokemonTypes(Type::Grass);
		case Species::Lilligant: return PokemonTypes(Type::Grass);
		case Species::Basculin: return PokemonTypes(Type::Water);
		case Species::Sandile: return PokemonTypes(Type::Ground, Type::Dark);
		case Species::Krokorok: return PokemonTypes(Type::Ground, Type::Dark);
		case Species::Krookodile: return PokemonTypes(Type::Ground, Type::Dark);
		case Species::Darumaka: return PokemonTypes(Type::Fire);
		case Species::Darmanitan: return PokemonTypes(Type::Fire);
		// case Species::Darmanitan_Zen: return PokemonTypes(Type::Fire, Type::Psychic);
		case Species::Maractus: return PokemonTypes(Type::Grass);
		case Species::Dwebble: return PokemonTypes(Type::Bug, Type::Rock);
		case Species::Crustle: return PokemonTypes(Type::Bug, Type::Rock);
		case Species::Scraggy: return PokemonTypes(Type::Dark, Type::Fighting);
		case Species::Scrafty: return PokemonTypes(Type::Dark, Type::Fighting);
		case Species::Sigilyph: return PokemonTypes(Type::Psychic, Type::Flying);
		case Species::Yamask: return PokemonTypes(Type::Ghost);
		case Species::Cofagrigus: return PokemonTypes(Type::Ghost);
		case Species::Tirtouga: return PokemonTypes(Type::Water, Type::Rock);
		case Species::Carracosta: return PokemonTypes(Type::Water, Type::Rock);
		case Species::Archen: return PokemonTypes(Type::Rock, Type::Flying);
		case Species::Archeops: return PokemonTypes(Type::Rock, Type::Flying);
		case Species::Trubbish: return PokemonTypes(Type::Poison);
		case Species::Garbodor: return PokemonTypes(Type::Poison);
		case Species::Zorua: return PokemonTypes(Type::Dark);
		case Species::Zoroark: return PokemonTypes(Type::Dark);
		case Species::Minccino: return PokemonTypes(Type::Normal);
		case Species::Cinccino: return PokemonTypes(Type::Normal);
		case Species::Gothita: return PokemonTypes(Type::Psychic);
		case Species::Gothorita: return PokemonTypes(Type::Psychic);
		case Species::Gothitelle: return PokemonTypes(Type::Psychic);
		case Species::Solosis: return PokemonTypes(Type::Psychic);
		case Species::Duosion: return PokemonTypes(Type::Psychic);
		case Species::Reuniclus: return PokemonTypes(Type::Psychic);
		case Species::Ducklett: return PokemonTypes(Type::Water, Type::Flying);
		case Species::Swanna: return PokemonTypes(Type::Water, Type::Flying);
		case Species::Vanillite: return PokemonTypes(Type::Ice);
		case Species::Vanillish: return PokemonTypes(Type::Ice);
		case Species::Vanilluxe: return PokemonTypes(Type::Ice);
		case Species::Deerling: return PokemonTypes(Type::Normal, Type::Grass);
		case Species::Sawsbuck: return PokemonTypes(Type::Normal, Type::Grass);
		case Species::Emolga: return PokemonTypes(Type::Electric, Type::Flying);
		case Species::Karrablast: return PokemonTypes(Type::Bug);
		case Species::Escavalier: return PokemonTypes(Type::Bug, Type::Steel);
		case Species::Foongus: return PokemonTypes(Type::Grass, Type::Poison);
		case Species::Amoonguss: return PokemonTypes(Type::Grass, Type::Poison);
		case Species::Frillish: return PokemonTypes(Type::Water, Type::Ghost);
		case Species::Jellicent: return PokemonTypes(Type::Water, Type::Ghost);
		case Species::Alomomola: return PokemonTypes(Type::Water);
		case Species::Joltik: return PokemonTypes(Type::Bug, Type::Electric);
		case Species::Galvantula: return PokemonTypes(Type::Bug, Type::Electric);
		case Species::Ferroseed: return PokemonTypes(Type::Grass, Type::Steel);
		case Species::Ferrothorn: return PokemonTypes(Type::Grass, Type::Steel);
		case Species::Klink: return PokemonTypes(Type::Steel);
		case Species::Klang: return PokemonTypes(Type::Steel);
		case Species::Klinklang: return PokemonTypes(Type::Steel);
		case Species::Tynamo: return PokemonTypes(Type::Electric);
		case Species::Eelektrik: return PokemonTypes(Type::Electric);
		case Species::Eelektross: return PokemonTypes(Type::Electric);
		case Species::Elgyem: return PokemonTypes(Type::Psychic);
		case Species::Beheeyem: return PokemonTypes(Type::Psychic);
		case Species::Litwick: return PokemonTypes(Type::Ghost, Type::Fire);
		case Species::Lampent: return PokemonTypes(Type::Ghost, Type::Fire);
		case Species::Chandelure: return PokemonTypes(Type::Ghost, Type::Fire);
		case Species::Axew: return PokemonTypes(Type::Dragon);
		case Species::Fraxure: return PokemonTypes(Type::Dragon);
		case Species::Haxorus: return PokemonTypes(Type::Dragon);
		case Species::Cubchoo: return PokemonTypes(Type::Ice);
		case Species::Beartic: return PokemonTypes(Type::Ice);
		case Species::Cryogonal: return PokemonTypes(Type::Ice);
		case Species::Shelmet: return PokemonTypes(Type::Bug);
		case Species::Accelgor: return PokemonTypes(Type::Bug);
		case Species::Stunfisk: return PokemonTypes(Type::Ground, Type::Electric);
		case Species::Mienfoo: return PokemonTypes(Type::Fighting);
		case Species::Mienshao: return PokemonTypes(Type::Fighting);
		case Species::Druddigon: return PokemonTypes(Type::Dragon);
		case Species::Golett: return PokemonTypes(Type::Ground, Type::Ghost);
		case Species::Golurk: return PokemonTypes(Type::Ground, Type::Ghost);
		case Species::Pawniard: return PokemonTypes(Type::Dark, Type::Steel);
		case Species::Bisharp: return PokemonTypes(Type::Dark, Type::Steel);
		case Species::Bouffalant: return PokemonTypes(Type::Normal);
		case Species::Rufflet: return PokemonTypes(Type::Normal, Type::Flying);
		case Species::Braviary: return PokemonTypes(Type::Normal, Type::Flying);
		case Species::Vullaby: return PokemonTypes(Type::Dark, Type::Flying);
		case Species::Mandibuzz: return PokemonTypes(Type::Dark, Type::Flying);
		case Species::Heatmor: return PokemonTypes(Type::Fire);
		case Species::Durant: return PokemonTypes(Type::Bug, Type::Steel);
		case Species::Deino: return PokemonTypes(Type::Dark, Type::Dragon);
		case Species::Zweilous: return PokemonTypes(Type::Dark, Type::Dragon);
		case Species::Hydreigon: return PokemonTypes(Type::Dark, Type::Dragon);
		case Species::Larvesta: return PokemonTypes(Type::Bug, Type::Fire);
		case Species::Volcarona: return PokemonTypes(Type::Bug, Type::Fire);
		case Species::Cobalion: return PokemonTypes(Type::Steel, Type::Fighting);
		case Species::Terrakion: return PokemonTypes(Type::Rock, Type::Fighting);
		case Species::Virizion: return PokemonTypes(Type::Grass, Type::Fighting);
		case Species::Tornadus_Incarnate: return PokemonTypes(Type::Flying);
		case Species::Tornadus_Therian: return PokemonTypes(Type::Flying);
		case Species::Thundurus_Incarnate: return PokemonTypes(Type::Electric, Type::Flying);
		case Species::Thundurus_Therian: return PokemonTypes(Type::Electric, Type::Flying);
		case Species::Reshiram: return PokemonTypes(Type::Dragon, Type::Fire);
		case Species::Zekrom: return PokemonTypes(Type::Dragon, Type::Electric);
		case Species::Landorus_Incarnate: return PokemonTypes(Type::Ground, Type::Flying);
		case Species::Landorus_Therian: return PokemonTypes(Type::Ground, Type::Flying);
		case Species::Kyurem: return PokemonTypes(Type::Dragon, Type::Ice);
		case Species::Kyurem_Black: return PokemonTypes(Type::Dragon, Type::Ice);
		case Species::Kyurem_White: return PokemonTypes(Type::Dragon, Type::Ice);
		case Species::Keldeo: return PokemonTypes(Type::Water, Type::Fighting);
		case Species::Meloetta: return PokemonTypes(Type::Normal, Type::Psychic);
		// case Species::Meloetta_Pirouette: return PokemonTypes(Type::Normal, Type::Fighting);
		case Species::Genesect: return PokemonTypes(Type::Bug, Type::Steel);

		// Generation 6
		case Species::Chespin: return PokemonTypes(Type::Grass);
		case Species::Quilladin: return PokemonTypes(Type::Grass);
		case Species::Chesnaught: return PokemonTypes(Type::Grass, Type::Fighting);
		case Species::Fennekin: return PokemonTypes(Type::Fire);
		case Species::Braixen: return PokemonTypes(Type::Fire);
		case Species::Delphox: return PokemonTypes(Type::Fire, Type::Psychic);
		case Species::Froakie: return PokemonTypes(Type::Water);
		case Species::Frogadier: return PokemonTypes(Type::Water);
		case Species::Greninja: return PokemonTypes(Type::Water, Type::Dark);
		case Species::Bunnelby: return PokemonTypes(Type::Normal);
		case Species::Diggersby: return PokemonTypes(Type::Normal, Type::Ground);
		case Species::Fletchling: return PokemonTypes(Type::Normal, Type::Flying);
		case Species::Fletchinder: return PokemonTypes(Type::Fire, Type::Flying);
		case Species::Talonflame: return PokemonTypes(Type::Fire, Type::Flying);
		case Species::Scatterbug: return PokemonTypes(Type::Bug);
		case Species::Spewpa: return PokemonTypes(Type::Bug);
		case Species::Vivillon: return PokemonTypes(Type::Bug, Type::Flying);
		case Species::Litleo: return PokemonTypes(Type::Fire, Type::Normal);
		case Species::Pyroar: return PokemonTypes(Type::Fire, Type::Normal);
		case Species::Flabebe: return PokemonTypes(Type::Fairy);
		case Species::Floette: return PokemonTypes(Type::Fairy);
		case Species::Florges: return PokemonTypes(Type::Fairy);
		case Species::Skiddo: return PokemonTypes(Type::Grass);
		case Species::Gogoat: return PokemonTypes(Type::Grass);
		case Species::Pancham: return PokemonTypes(Type::Fighting);
		case Species::Pangoro: return PokemonTypes(Type::Fighting, Type::Dark);
		case Species::Furfrou: return PokemonTypes(Type::Normal);
		case Species::Espurr: return PokemonTypes(Type::Psychic);
		case Species::Meowstic: return PokemonTypes(Type::Psychic);
		case Species::Honedge: return PokemonTypes(Type::Steel, Type::Ghost);
		case Species::Doublade: return PokemonTypes(Type::Steel, Type::Ghost);
		case Species::Aegislash: return PokemonTypes(Type::Steel, Type::Ghost);
		case Species::Spritzee: return PokemonTypes(Type::Fairy);
		case Species::Aromatisse: return PokemonTypes(Type::Fairy);
		case Species::Swirlix: return PokemonTypes(Type::Fairy);
		case Species::Slurpuff: return PokemonTypes(Type::Fairy);
		case Species::Inkay: return PokemonTypes(Type::Dark, Type::Psychic);
		case Species::Malamar: return PokemonTypes(Type::Dark, Type::Psychic);
		case Species::Binacle: return PokemonTypes(Type::Rock, Type::Water);
		case Species::Barbaracle: return PokemonTypes(Type::Rock, Type::Water);
		case Species::Skrelp: return PokemonTypes(Type::Poison, Type::Water);
		case Species::Dragalge: return PokemonTypes(Type::Poison, Type::Dragon);
		case Species::Clauncher: return PokemonTypes(Type::Water);
		case Species::Clawitzer: return PokemonTypes(Type::Water);
		case Species::Helioptile: return PokemonTypes(Type::Electric, Type::Normal);
		case Species::Heliolisk: return PokemonTypes(Type::Electric, Type::Normal);
		case Species::Tyrunt: return PokemonTypes(Type::Rock, Type::Dragon);
		case Species::Tyrantrum: return PokemonTypes(Type::Rock, Type::Dragon);
		case Species::Amaura: return PokemonTypes(Type::Rock, Type::Ice);
		case Species::Aurorus: return PokemonTypes(Type::Rock, Type::Ice);
		case Species::Sylveon: return PokemonTypes(Type::Fairy);
		case Species::Hawlucha: return PokemonTypes(Type::Fighting, Type::Flying);
		case Species::Dedenne: return PokemonTypes(Type::Electric, Type::Fairy);
		case Species::Carbink: return PokemonTypes(Type::Rock, Type::Fairy);
		case Species::Goomy: return PokemonTypes(Type::Dragon);
		case Species::Sliggoo: return PokemonTypes(Type::Dragon);
		case Species::Goodra: return PokemonTypes(Type::Dragon);
		case Species::Klefki: return PokemonTypes(Type::Steel, Type::Fairy);
		case Species::Phantump: return PokemonTypes(Type::Ghost, Type::Grass);
		case Species::Trevenant: return PokemonTypes(Type::Ghost, Type::Grass);
		case Species::Pumpkaboo_Small: return PokemonTypes(Type::Ghost, Type::Grass);
		case Species::Pumpkaboo_Average: return PokemonTypes(Type::Ghost, Type::Grass);
		case Species::Pumpkaboo_Large: return PokemonTypes(Type::Ghost, Type::Grass);
		case Species::Pumpkaboo_Super: return PokemonTypes(Type::Ghost, Type::Grass);
		case Species::Gourgeist_Small: return PokemonTypes(Type::Ghost, Type::Grass);
		case Species::Gourgeist_Average: return PokemonTypes(Type::Ghost, Type::Grass);
		case Species::Gourgeist_Large: return PokemonTypes(Type::Ghost, Type::Grass);
		case Species::Gourgeist_Super: return PokemonTypes(Type::Ghost, Type::Grass);
		case Species::Bergmite: return PokemonTypes(Type::Ice);
		case Species::Avalugg: return PokemonTypes(Type::Ice);
		case Species::Noibat: return PokemonTypes(Type::Flying, Type::Dragon);
		case Species::Noivern: return PokemonTypes(Type::Flying, Type::Dragon);
		case Species::Xerneas: return PokemonTypes(Type::Fairy);
		case Species::Yveltal: return PokemonTypes(Type::Dark, Type::Flying);
		case Species::Zygarde_50: return PokemonTypes(Type::Dragon, Type::Ground);
		case Species::Zygarde_10: return PokemonTypes(Type::Dragon, Type::Ground);
		case Species::Zygarde_Complete: return PokemonTypes(Type::Dragon, Type::Ground);
		case Species::Diancie: return PokemonTypes(Type::Rock, Type::Fairy);
		case Species::Hoopa_Confined: return PokemonTypes(Type::Psychic, Type::Ghost);
		case Species::Hoopa_Unbound: return PokemonTypes(Type::Psychic, Type::Dark);
		case Species::Volcanion: return PokemonTypes(Type::Fire, Type::Water);

		// Generation 7
		case Species::Rowlet: return PokemonTypes(Type::Grass, Type::Flying);
		case Species::Dartrix: return PokemonTypes(Type::Grass, Type::Flying);
		case Species::Decidueye: return PokemonTypes(Type::Grass, Type::Ghost);
		case Species::Litten: return PokemonTypes(Type::Fire);
		case Species::Torracat: return PokemonTypes(Type::Fire);
		case Species::Incineroar: return PokemonTypes(Type::Fire, Type::Dark);
		case Species::Popplio: return PokemonTypes(Type::Water);
		case Species::Brionne: return PokemonTypes(Type::Water);
		case Species::Primarina: return PokemonTypes(Type::Water, Type::Fairy);
		case Species::Pikipek: return PokemonTypes(Type::Normal, Type::Flying);
		case Species::Trumbeak: return PokemonTypes(Type::Normal, Type::Flying);
		case Species::Toucannon: return PokemonTypes(Type::Normal, Type::Flying);
		case Species::Yungoos: return PokemonTypes(Type::Normal);
		case Species::Gumshoos: return PokemonTypes(Type::Normal);
		case Species::Grubbin: return PokemonTypes(Type::Bug);
		case Species::Charjabug: return PokemonTypes(Type::Bug, Type::Electric);
		case Species::Vikavolt: return PokemonTypes(Type::Bug, Type::Electric);
		case Species::Crabrawler: return PokemonTypes(Type::Fighting);
		case Species::Crabominable: return PokemonTypes(Type::Fighting, Type::Ice);
		case Species::Oricorio: return PokemonTypes(Type::Fire, Type::Flying);
		case Species::Oricorio_Pau: return PokemonTypes(Type::Electric, Type::Flying);
		case Species::Oricorio_Pom_Pom: return PokemonTypes(Type::Psychic, Type::Flying);
		case Species::Oricorio_Sensu: return PokemonTypes(Type::Ghost, Type::Flying);
		case Species::Cutiefly: return PokemonTypes(Type::Bug, Type::Fairy);
		case Species::Ribombee: return PokemonTypes(Type::Bug, Type::Fairy);
		case Species::Rockruff: return PokemonTypes(Type::Rock);
		case Species::Lycanroc_Midday: return PokemonTypes(Type::Rock);
		case Species::Lycanroc_Midnight: return PokemonTypes(Type::Rock);
		case Species::Lycanroc_Dusk: return PokemonTypes(Type::Rock);
		case Species::Wishiwashi_Solo: return PokemonTypes(Type::Water);
		case Species::Wishiwashi_School: return PokemonTypes(Type::Water);
		case Species::Mareanie: return PokemonTypes(Type::Poison, Type::Water);
		case Species::Toxapex: return PokemonTypes(Type::Poison, Type::Water);
		case Species::Mudbray: return PokemonTypes(Type::Ground);
		case Species::Mudsdale: return PokemonTypes(Type::Ground);
		case Species::Dewpider: return PokemonTypes(Type::Water, Type::Bug);
		case Species::Araquanid: return PokemonTypes(Type::Water, Type::Bug);
		case Species::Fomantis: return PokemonTypes(Type::Grass);
		case Species::Lurantis: return PokemonTypes(Type::Grass);
		case Species::Morelull: return PokemonTypes(Type::Grass, Type::Fairy);
		case Species::Shiinotic: return PokemonTypes(Type::Grass, Type::Fairy);
		case Species::Salandit: return PokemonTypes(Type::Poison, Type::Fire);
		case Species::Salazzle: return PokemonTypes(Type::Poison, Type::Fire);
		case Species::Stufful: return PokemonTypes(Type::Normal, Type::Fighting);
		case Species::Bewear: return PokemonTypes(Type::Normal, Type::Fighting);
		case Species::Bounsweet: return PokemonTypes(Type::Grass);
		case Species::Steenee: return PokemonTypes(Type::Grass);
		case Species::Tsareena: return PokemonTypes(Type::Grass);
		case Species::Comfey: return PokemonTypes(Type::Fairy);
		case Species::Oranguru: return PokemonTypes(Type::Normal, Type::Psychic);
		case Species::Passimian: return PokemonTypes(Type::Fighting);
		case Species::Wimpod: return PokemonTypes(Type::Bug, Type::Water);
		case Species::Golisopod: return PokemonTypes(Type::Bug, Type::Water);
		case Species::Sandygast: return PokemonTypes(Type::Ghost, Type::Ground);
		case Species::Palossand: return PokemonTypes(Type::Ghost, Type::Ground);
		case Species::Pyukumuku: return PokemonTypes(Type::Water);
		case Species::Type_Null: return PokemonTypes(Type::Normal);
		case Species::Silvally: return PokemonTypes(Type::Normal);
		case Species::Minior_Meteor: return PokemonTypes(Type::Rock, Type::Flying);
		case Species::Minior_Core: return PokemonTypes(Type::Rock, Type::Flying);
		case Species::Komala: return PokemonTypes(Type::Normal);
		case Species::Turtonator: return PokemonTypes(Type::Fire, Type::Dragon);
		case Species::Togedemaru: return PokemonTypes(Type::Electric, Type::Steel);
		case Species::Mimikyu: return PokemonTypes(Type::Ghost, Type::Fairy);
		case Species::Bruxish: return PokemonTypes(Type::Water, Type::Psychic);
		case Species::Drampa: return PokemonTypes(Type::Normal, Type::Dragon);
		case Species::Dhelmise: return PokemonTypes(Type::Ghost, Type::Grass);
		case Species::Jangmo_o: return PokemonTypes(Type::Dragon);
		case Species::Hakamo_o: return PokemonTypes(Type::Dragon, Type::Fighting);
		case Species::Kommo_o: return PokemonTypes(Type::Dragon, Type::Fighting);
		case Species::Tapu_Koko: return PokemonTypes(Type::Electric, Type::Fairy);
		case Species::Tapu_Lele: return PokemonTypes(Type::Psychic, Type::Fairy);
		case Species::Tapu_Bulu: return PokemonTypes(Type::Grass, Type::Fairy);
		case Species::Tapu_Fini: return PokemonTypes(Type::Water, Type::Fairy);
		case Species::Cosmog: return PokemonTypes(Type::Psychic);
		case Species::Cosmoem: return PokemonTypes(Type::Psychic);
		case Species::Solgaleo: return PokemonTypes(Type::Psychic, Type::Steel);
		case Species::Lunala: return PokemonTypes(Type::Psychic, Type::Ghost);
		case Species::Nihilego: return PokemonTypes(Type::Rock, Type::Poison);
		case Species::Buzzwole: return PokemonTypes(Type::Bug, Type::Fighting);
		case Species::Pheromosa: return PokemonTypes(Type::Bug, Type::Fighting);
		case Species::Xurkitree: return PokemonTypes(Type::Electric);
		case Species::Celesteela: return PokemonTypes(Type::Steel, Type::Flying);
		case Species::Kartana: return PokemonTypes(Type::Grass, Type::Steel);
		case Species::Guzzlord: return PokemonTypes(Type::Dark, Type::Dragon);
		case Species::Necrozma: return PokemonTypes(Type::Psychic);
		case Species::Necrozma_Dusk_Mane: return PokemonTypes(Type::Psychic);
		case Species::Necrozma_Dawn_Wings: return PokemonTypes(Type::Psychic);
		case Species::Necrozma_Ultra: return PokemonTypes(Type::Psychic);
		case Species::Magearna: return PokemonTypes(Type::Steel, Type::Fairy);
		case Species::Marshadow: return PokemonTypes(Type::Fighting, Type::Ghost);
		case Species::Poipole: return PokemonTypes(Type::Poison);
		case Species::Naganadel: return PokemonTypes(Type::Poison, Type::Dragon);
		case Species::Stakataka: return PokemonTypes(Type::Rock, Type::Steel);
		case Species::Blacephalon: return PokemonTypes(Type::Fire, Type::Ghost);
		case Species::Zeraora: return PokemonTypes(Type::Electric);
		case Species::Rattata_Alolan: return PokemonTypes(Type::Dark, Type::Normal);
		case Species::Raticate_Alolan: return PokemonTypes(Type::Dark, Type::Normal);
		case Species::Raichu_Alolan: return PokemonTypes(Type::Electric, Type::Psychic);
		case Species::Sandshrew_Alolan: return PokemonTypes(Type::Ice, Type::Steel);
		case Species::Sandslash_Alolan: return PokemonTypes(Type::Ice, Type::Steel);
		case Species::Vulpix_Alolan: return PokemonTypes(Type::Ice);
		case Species::Ninetales_Alolan: return PokemonTypes(Type::Ice, Type::Fairy);
		case Species::Diglett_Alolan: return PokemonTypes(Type::Ground, Type::Steel);
		case Species::Dugtrio_Alolan: return PokemonTypes(Type::Ground, Type::Steel);
		case Species::Meowth_Alolan: return PokemonTypes(Type::Dark);
		case Species::Persian_Alolan: return PokemonTypes(Type::Dark);
		case Species::Geodude_Alolan: return PokemonTypes(Type::Rock, Type::Electric);
		case Species::Graveler_Alolan: return PokemonTypes(Type::Rock, Type::Electric);
		case Species::Golem_Alolan: return PokemonTypes(Type::Rock, Type::Electric);
		case Species::Grimer_Alolan: return PokemonTypes(Type::Poison, Type::Dark);
		case Species::Muk_Alolan: return PokemonTypes(Type::Poison, Type::Dark);
		case Species::Exeggutor_Alolan: return PokemonTypes(Type::Grass, Type::Dragon);
		case Species::Marowak_Alolan: return PokemonTypes(Type::Fire, Type::Ghost);
	}}())
{
}

auto is_type(Pokemon const & pokemon, Type const type, bool const roosting) -> bool {
	return (type != Type::Flying or !roosting) and containers::any_equal(get_type(pokemon), type);
}

}	// namespace technicalmachine
