// Pokemon string functions
// Copyright (C) 2012 David Stone
//
// This file is part of Technical Machine.
//
// Technical Machine is free software: you can redistribute it and / or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.

#include "../pokemon.hpp"

#include <map>
#include <string>

#include "invalid_string_conversion.hpp"

namespace technicalmachine {

std::string Pokemon::to_string (Species name) {
	static std::string const name_to_string [] = {
		"Abomasnow", "Abra", "Absol", "Aerodactyl", "Aggron",
		"Aipom", "Alakazam", "Altaria", "Ambipom", "Ampharos",
		"Anorith", "Arbok", "Arcanine", "Arceus", "Ariados",
		"Armaldo", "Aron", "Articuno", "Azelf", "Azumarill",
		"Azurill", "Bagon", "Baltoy", "Banette", "Barboach",
		"Bastiodon", "Bayleef", "Beautifly", "Beedrill", "Beldum",
		"Bellossom", "Bellsprout", "Bibarel", "Bidoof", "Blastoise",
		"Blaziken", "Blissey", "Bonsly", "Breloom", "Bronzong",
		"Bronzor", "Budew", "Buizel", "Bulbasaur", "Buneary",
		"Burmy", "Butterfree", "Cacnea", "Cacturne", "Camerupt",
		"Carnivine", "Carvanha", "Cascoon", "Castform", "Caterpie",
		"Celebi", "Chansey", "Charizard", "Charmander", "Charmeleon",
		"Chatot", "Cherrim", "Cherubi", "Chikorita", "Chimchar",
		"Chimecho", "Chinchou", "Chingling", "Clamperl", "Claydol",
		"Clefable", "Clefairy", "Cleffa", "Cloyster", "Combee",
		"Combusken", "Corphish", "Corsola", "Cradily", "Cranidos",
		"Crawdaunt", "Cresselia", "Croagunk", "Crobat", "Croconaw",
		"Cubone", "Cyndaquil", "Darkrai", "Delcatty", "Delibird",
		"Deoxys-A", "Deoxys-D", "Deoxys-M", "Deoxys-S", "Dewgong",
		"Dialga", "Diglett", "Ditto", "Dodrio", "Doduo",
		"Donphan", "Dragonair", "Dragonite", "Drapion", "Dratini",
		"Drifblim", "Drifloon", "Drowzee", "Dugtrio", "Dunsparce",
		"Dusclops", "Dusknoir", "Duskull", "Dustox", "Eevee",
		"Ekans", "Electabuzz", "Electivire", "Electrike", "Electrode",
		"Elekid", "Empoleon", "Entei", "Espeon", "Exeggcute",
		"Exeggutor", "Exploud", "Farfetch'd", "Fearow", "Feebas",
		"Feraligatr", "Finneon", "Flaaffy", "Flareon", "Floatzel",
		"Flygon", "Forretress", "Froslass", "Furret", "Gabite",
		"Gallade", "Garchomp", "Gardevoir", "Gastly", "Gastrodon",
		"Gengar", "Geodude", "Gible", "Girafarig", "Giratina-A",
		"Giratina-O", "Glaceon", "Glalie", "Glameow", "Gligar",
		"Gliscor", "Gloom", "Golbat", "Goldeen", "Golduck",
		"Golem", "Gorebyss", "Granbull", "Graveler", "Grimer",
		"Grotle", "Groudon", "Grovyle", "Growlithe", "Grumpig",
		"Gulpin", "Gyarados", "Happiny", "Hariyama", "Haunter",
		"Heatran", "Heracross", "Hippopotas", "Hippowdon", "Hitmonchan",
		"Hitmonlee", "Hitmontop", "Ho-Oh", "Honchkrow", "Hoothoot",
		"Hoppip", "Horsea", "Houndoom", "Houndour", "Huntail",
		"Hypno", "Igglybuff", "Illumise", "Infernape", "Ivysaur",
		"Jigglypuff", "Jirachi", "Jolteon", "Jumpluff", "Jynx",
		"Kabuto", "Kabutops", "Kadabra", "Kakuna", "Kangaskhan",
		"Kecleon", "Kingdra", "Kingler", "Kirlia", "Koffing",
		"Krabby", "Kricketot", "Kricketune", "Kyogre", "Lairon",
		"Lanturn", "Lapras", "Larvitar", "Latias", "Latios",
		"Leafeon", "Ledian", "Ledyba", "Lickilicky", "Lickitung",
		"Lileep", "Linoone", "Lombre", "Lopunny", "Lotad",
		"Loudred", "Lucario", "Ludicolo", "Lugia", "Lumineon",
		"Lunatone", "Luvdisc", "Luxio", "Luxray", "Machamp",
		"Machoke", "Machop", "Magby", "Magcargo", "Magikarp",
		"Magmar", "Magmortar", "Magnemite", "Magneton", "Magnezone",
		"Makuhita", "Mamoswine", "Manaphy", "Manectric", "Mankey",
		"Mantine", "Mantyke", "Mareep", "Marill", "Marowak",
		"Marshtomp", "Masquerain", "Mawile", "Medicham", "Meditite",
		"Meganium", "Meowth", "Mesprit", "Metagross", "Metang",
		"Metapod", "Mew", "Mewtwo", "Mightyena", "Milotic",
		"Miltank", "Mime Jr.", "Minun", "Misdreavus", "Mismagius",
		"Moltres", "Monferno", "Mothim", "Mr. Mime", "Mudkip",
		"Muk", "Munchlax", "Murkrow", "Natu", "Nidoking",
		"Nidoqueen", "Nidoran-F", "Nidoran-M", "Nidorina", "Nidorino",
		"Nincada", "Ninetales", "Ninjask", "Noctowl", "Nosepass",
		"Numel", "Nuzleaf", "Octillery", "Oddish", "Omanyte",
		"Omastar", "Onix", "Pachirisu", "Palkia", "Paras",
		"Parasect", "Pelipper", "Persian", "Phanpy", "Phione",
		"Pichu", "Pidgeot", "Pidgeotto", "Pidgey", "Pikachu",
		"Piloswine", "Pineco", "Pinsir", "Piplup", "Plusle",
		"Politoed", "Poliwag", "Poliwhirl", "Poliwrath",
		"Ponyta", "Poochyena", "Porygon", "Porygon-Z", "Porygon2",
		"Primeape", "Prinplup", "Probopass", "Psyduck", "Pupitar",
		"Purugly", "Quagsire", "Quilava", "Qwilfish",
		"Raichu", "Raikou", "Ralts", "Rampardos", "Rapidash",
		"Raticate", "Rattata", "Rayquaza", "Regice", "Regigigas",
		"Regirock", "Registeel", "Relicanth", "Remoraid", "Rhydon",
		"Rhyhorn", "Rhyperior", "Riolu", "Roselia", "Roserade",
		"Rotom", "Rotom-C", "Rotom-F", "Rotom-H", "Rotom-S",
		"Rotom-W", "Sableye", "Salamence", "Sandshrew", "Sandslash",
		"Sceptile", "Scizor", "Scyther", "Seadra", "Seaking",
		"Sealeo", "Seedot", "Seel", "Sentret", "Seviper",
		"Sharpedo", "Shaymin-L", "Shaymin-S", "Shedinja", "Shelgon",
		"Shellder", "Shellos", "Shieldon", "Shiftry", "Shinx",
		"Shroomish", "Shuckle", "Shuppet", "Silcoon", "Skarmory",
		"Skiploom", "Skitty", "Skorupi", "Skuntank", "Slaking",
		"Slakoth", "Slowbro", "Slowking", "Slowpoke", "Slugma",
		"Smeargle", "Smoochum", "Sneasel", "Snorlax", "Snorunt",
		"Snover", "Snubbull", "Solrock", "Spearow", "Spheal",
		"Spinarak", "Spinda", "Spiritomb", "Spoink", "Squirtle",
		"Stantler", "Staraptor", "Staravia", "Starly", "Starmie",
		"Staryu", "Steelix", "Stunky", "Sudowoodo", "Suicune",
		"Sunflora", "Sunkern", "Surskit", "Swablu", "Swalot",
		"Swampert", "Swellow", "Swinub", "Taillow", "Tangela",
		"Tangrowth", "Tauros", "Teddiursa", "Tentacool", "Tentacruel",
		"Togekiss", "Togepi", "Togetic", "Torchic", "Torkoal",
		"Torterra", "Totodile", "Toxicroak", "Trapinch", "Treecko",
		"Tropius", "Turtwig", "Typhlosion", "Tyranitar", "Tyrogue",
		"Umbreon", "Unown", "Ursaring", "Uxie", "Vaporeon",
		"Venomoth", "Venonat", "Venusaur", "Vespiquen", "Vibrava",
		"Victreebel", "Vigoroth", "Vileplume", "Volbeat", "Voltorb",
		"Vulpix", "Wailmer", "Wailord", "Walrein", "Wartortle",
		"Weavile", "Weedle", "Weepinbell", "Weezing", "Whiscash",
		"Whismur", "Wigglytuff", "Wingull", "Wobbuffet", "Wooper",
		"Wormadam-P", "Wormadam-S", "Wormadam-T", "Wurmple", "Wynaut",
		"Xatu", "Yanma", "Yanmega", "Zangoose", "Zapdos",
		"Zigzagoon", "Zubat"
	};
	return name_to_string [name];
}

std::string Pokemon::to_string () const {
	return to_string (name);
}

Species Pokemon::from_string (std::string const & str) {
	static std::map <std::string, Species> const converter {
		{ "Abomasnow", ABOMASNOW },
		{ "Abra", ABRA },
		{ "Absol", ABSOL },
		{ "Aerodactyl", AERODACTYL },
		{ "Aggron", AGGRON },
		{ "Aipom", AIPOM },
		{ "Alakazam", ALAKAZAM },
		{ "Altaria", ALTARIA },
		{ "Ambipom", AMBIPOM },
		{ "Ampharos", AMPHAROS },
		{ "Anorith", ANORITH },
		{ "Arbok", ARBOK },
		{ "Arcanine", ARCANINE },
		{ "Arceus", ARCEUS },
		{ "Ariados", ARIADOS },
		{ "Armaldo", ARMALDO },
		{ "Aron", ARON },
		{ "Articuno", ARTICUNO },
		{ "Azelf", AZELF },
		{ "Azumarill", AZUMARILL },
		{ "Azurill", AZURILL },
		{ "Bagon", BAGON },
		{ "Baltoy", BALTOY },
		{ "Banette", BANETTE },
		{ "Barboach", BARBOACH },
		{ "Bastiodon", BASTIODON },
		{ "Bayleef", BAYLEEF },
		{ "Beautifly", BEAUTIFLY },
		{ "Beedrill", BEEDRILL },
		{ "Beldum", BELDUM },
		{ "Bellossom", BELLOSSOM },
		{ "Bellsprout", BELLSPROUT },
		{ "Bibarel", BIBAREL },
		{ "Bidoof", BIDOOF },
		{ "Blastoise", BLASTOISE },
		{ "Blaziken", BLAZIKEN },
		{ "Blissey", BLISSEY },
		{ "Bonsly", BONSLY },
		{ "Breloom", BRELOOM },
		{ "Bronzong", BRONZONG },
		{ "Bronzor", BRONZOR },
		{ "Budew", BUDEW },
		{ "Buizel", BUIZEL },
		{ "Bulbasaur", BULBASAUR },
		{ "Buneary", BUNEARY },
		{ "Burmy", BURMY },
		{ "Butterfree", BUTTERFREE },
		{ "Cacnea", CACNEA },
		{ "Cacturne", CACTURNE },
		{ "Camerupt", CAMERUPT },
		{ "Carnivine", CARNIVINE },
		{ "Carvanha", CARVANHA },
		{ "Cascoon", CASCOON },
		{ "Castform", CASTFORM },
		{ "Caterpie", CATERPIE },
		{ "Celebi", CELEBI },
		{ "Chansey", CHANSEY },
		{ "Charizard", CHARIZARD },
		{ "Charmander", CHARMANDER },
		{ "Charmeleon", CHARMELEON },
		{ "Chatot", CHATOT },
		{ "Cherrim", CHERRIM },
		{ "Cherubi", CHERUBI },
		{ "Chikorita", CHIKORITA },
		{ "Chimchar", CHIMCHAR },
		{ "Chimecho", CHIMECHO },
		{ "Chinchou", CHINCHOU },
		{ "Chingling", CHINGLING },
		{ "Clamperl", CLAMPERL },
		{ "Claydol", CLAYDOL },
		{ "Clefable", CLEFABLE },
		{ "Clefairy", CLEFAIRY },
		{ "Cleffa", CLEFFA },
		{ "Cloyster", CLOYSTER },
		{ "Combee", COMBEE },
		{ "Combusken", COMBUSKEN },
		{ "Corphish", CORPHISH },
		{ "Corsola", CORSOLA },
		{ "Cradily", CRADILY },
		{ "Cranidos", CRANIDOS },
		{ "Crawdaunt", CRAWDAUNT },
		{ "Cresselia", CRESSELIA },
		{ "Croagunk", CROAGUNK },
		{ "Crobat", CROBAT },
		{ "Croconaw", CROCONAW },
		{ "Cubone", CUBONE },
		{ "Cyndaquil", CYNDAQUIL },
		{ "Darkrai", DARKRAI },
		{ "Delcatty", DELCATTY },
		{ "Delibird", DELIBIRD },
		{ "Deoxys-A", DEOXYS_A },
		{ "Deoxys-a", DEOXYS_A },
		{ "Deoxys-F", DEOXYS_A },
		{ "Deoxys-f", DEOXYS_A },
		{ "Deoxys-D", DEOXYS_D },
		{ "Deoxys-d", DEOXYS_D },
		{ "Deoxys-L", DEOXYS_D },
		{ "Deoxys-l", DEOXYS_D },
		{ "Deoxys", DEOXYS_M },
		{ "Deoxys-M", DEOXYS_M },
		{ "Deoxys-m", DEOXYS_M },
		{ "Deoxys-S", DEOXYS_S },
		{ "Deoxys-s", DEOXYS_S },
		{ "Deoxys-E", DEOXYS_S },
		{ "Deoxys-e", DEOXYS_S },
		{ "Dewgong", DEWGONG },
		{ "Dialga", DIALGA },
		{ "Diglett", DIGLETT },
		{ "Ditto", DITTO },
		{ "Dodrio", DODRIO },
		{ "Doduo", DODUO },
		{ "Donphan", DONPHAN },
		{ "Dragonair", DRAGONAIR },
		{ "Dragonite", DRAGONITE },
		{ "Drapion", DRAPION },
		{ "Dratini", DRATINI },
		{ "Drifblim", DRIFBLIM },
		{ "Drifloon", DRIFLOON },
		{ "Drowzee", DROWZEE },
		{ "Dugtrio", DUGTRIO },
		{ "Dunsparce", DUNSPARCE },
		{ "Dusclops", DUSCLOPS },
		{ "Dusknoir", DUSKNOIR },
		{ "Duskull", DUSKULL },
		{ "Dustox", DUSTOX },
		{ "Eevee", EEVEE },
		{ "Ekans", EKANS },
		{ "Electabuzz", ELECTABUZZ },
		{ "Electivire", ELECTIVIRE },
		{ "Electrike", ELECTRIKE },
		{ "Electrode", ELECTRODE },
		{ "Elekid", ELEKID },
		{ "Empoleon", EMPOLEON },
		{ "Entei", ENTEI },
		{ "Espeon", ESPEON },
		{ "Exeggcute", EXEGGCUTE },
		{ "Exeggutor", EXEGGUTOR },
		{ "Exploud", EXPLOUD },
		{ "Farfetch'd", FARFETCHD },
		{ "Fearow", FEAROW },
		{ "Feebas", FEEBAS },
		{ "Feraligatr", FERALIGATR },
		{ "Finneon", FINNEON },
		{ "Flaaffy", FLAAFFY },
		{ "Flareon", FLAREON },
		{ "Floatzel", FLOATZEL },
		{ "Flygon", FLYGON },
		{ "Forretress", FORRETRESS },
		{ "Froslass", FROSLASS },
		{ "Furret", FURRET },
		{ "Gabite", GABITE },
		{ "Gallade", GALLADE },
		{ "Garchomp", GARCHOMP },
		{ "Gardevoir", GARDEVOIR },
		{ "Gastly", GASTLY },
		{ "Gastrodon", GASTRODON },
		{ "Gengar", GENGAR },
		{ "Geodude", GEODUDE },
		{ "Gible", GIBLE },
		{ "Girafarig", GIRAFARIG },
		{ "Giratina", GIRATINA_A },
		{ "Giratina-A", GIRATINA_A },
		{ "Giratina-a", GIRATINA_A },
		{ "Giratina-O", GIRATINA_O },
		{ "Giratina-o", GIRATINA_O },
		{ "Glaceon", GLACEON },
		{ "Glalie", GLALIE },
		{ "Glameow", GLAMEOW },
		{ "Gligar", GLIGAR },
		{ "Gliscor", GLISCOR },
		{ "Gloom", GLOOM },
		{ "Golbat", GOLBAT },
		{ "Goldeen", GOLDEEN },
		{ "Golduck", GOLDUCK },
		{ "Golem", GOLEM },
		{ "Gorebyss", GOREBYSS },
		{ "Granbull", GRANBULL },
		{ "Graveler", GRAVELER },
		{ "Grimer", GRIMER },
		{ "Grotle", GROTLE },
		{ "Groudon", GROUDON },
		{ "Grovyle", GROVYLE },
		{ "Growlithe", GROWLITHE },
		{ "Grumpig", GRUMPIG },
		{ "Gulpin", GULPIN },
		{ "Gyarados", GYARADOS },
		{ "Happiny", HAPPINY },
		{ "Hariyama", HARIYAMA },
		{ "Haunter", HAUNTER },
		{ "Heatran", HEATRAN },
		{ "Heracross", HERACROSS },
		{ "Hippopotas", HIPPOPOTAS },
		{ "Hippowdon", HIPPOWDON },
		{ "Hitmonchan", HITMONCHAN },
		{ "Hitmonlee", HITMONLEE },
		{ "Hitmontop", HITMONTOP },
		{ "Ho-Oh", HO_OH },
		{ "Ho-oh", HO_OH },
		{ "Honchkrow", HONCHKROW },
		{ "Hoothoot", HOOTHOOT },
		{ "Hoppip", HOPPIP },
		{ "Horsea", HORSEA },
		{ "Houndoom", HOUNDOOM },
		{ "Houndour", HOUNDOUR },
		{ "Huntail", HUNTAIL },
		{ "Hypno", HYPNO },
		{ "Igglybuff", IGGLYBUFF },
		{ "Illumise", ILLUMISE },
		{ "Infernape", INFERNAPE },
		{ "Ivysaur", IVYSAUR },
		{ "Jigglypuff", JIGGLYPUFF },
		{ "Jirachi", JIRACHI },
		{ "Jolteon", JOLTEON },
		{ "Jumpluff", JUMPLUFF },
		{ "Jynx", JYNX },
		{ "Kabuto", KABUTO },
		{ "Kabutops", KABUTOPS },
		{ "Kadabra", KADABRA },
		{ "Kakuna", KAKUNA },
		{ "Kangaskhan", KANGASKHAN },
		{ "Kecleon", KECLEON },
		{ "Kingdra", KINGDRA },
		{ "Kingler", KINGLER },
		{ "Kirlia", KIRLIA },
		{ "Koffing", KOFFING },
		{ "Krabby", KRABBY },
		{ "Kricketot", KRICKETOT },
		{ "Kricketune", KRICKETUNE },
		{ "Kyogre", KYOGRE },
		{ "Lairon", LAIRON },
		{ "Lanturn", LANTURN },
		{ "Lapras", LAPRAS },
		{ "Larvitar", LARVITAR },
		{ "Latias", LATIAS },
		{ "Latios", LATIOS },
		{ "Leafeon", LEAFEON },
		{ "Ledian", LEDIAN },
		{ "Ledyba", LEDYBA },
		{ "Lickilicky", LICKILICKY },
		{ "Lickitung", LICKITUNG },
		{ "Lileep", LILEEP },
		{ "Linoone", LINOONE },
		{ "Lombre", LOMBRE },
		{ "Lopunny", LOPUNNY },
		{ "Lotad", LOTAD },
		{ "Loudred", LOUDRED },
		{ "Lucario", LUCARIO },
		{ "Ludicolo", LUDICOLO },
		{ "Lugia", LUGIA },
		{ "Lumineon", LUMINEON },
		{ "Lunatone", LUNATONE },
		{ "Luvdisc", LUVDISC },
		{ "Luxio", LUXIO },
		{ "Luxray", LUXRAY },
		{ "Machamp", MACHAMP },
		{ "Machoke", MACHOKE },
		{ "Machop", MACHOP },
		{ "Magby", MAGBY },
		{ "Magcargo", MAGCARGO },
		{ "Magikarp", MAGIKARP },
		{ "Magmar", MAGMAR },
		{ "Magmortar", MAGMORTAR },
		{ "Magnemite", MAGNEMITE },
		{ "Magneton", MAGNETON },
		{ "Magnezone", MAGNEZONE },
		{ "Makuhita", MAKUHITA },
		{ "Mamoswine", MAMOSWINE },
		{ "Manaphy", MANAPHY },
		{ "Manectric", MANECTRIC },
		{ "Mankey", MANKEY },
		{ "Mantine", MANTINE },
		{ "Mantyke", MANTYKE },
		{ "Mareep", MAREEP },
		{ "Marill", MARILL },
		{ "Marowak", MAROWAK },
		{ "Marshtomp", MARSHTOMP },
		{ "Masquerain", MASQUERAIN },
		{ "Mawile", MAWILE },
		{ "Medicham", MEDICHAM },
		{ "Meditite", MEDITITE },
		{ "Meganium", MEGANIUM },
		{ "Meowth", MEOWTH },
		{ "Mesprit", MESPRIT },
		{ "Metagross", METAGROSS },
		{ "Metang", METANG },
		{ "Metapod", METAPOD },
		{ "Mew", MEW },
		{ "Mewtwo", MEWTWO },
		{ "Mightyena", MIGHTYENA },
		{ "Milotic", MILOTIC },
		{ "Miltank", MILTANK },
		{ "Mime Jr.", MIME_JR },
		{ "Minun", MINUN },
		{ "Misdreavus", MISDREAVUS },
		{ "Mismagius", MISMAGIUS },
		{ "Moltres", MOLTRES },
		{ "Monferno", MONFERNO },
		{ "Mothim", MOTHIM },
		{ "Mr. Mime", MR_MIME },
		{ "Mudkip", MUDKIP },
		{ "Muk", MUK },
		{ "Munchlax", MUNCHLAX },
		{ "Murkrow", MURKROW },
		{ "Natu", NATU },
		{ "Nidoking", NIDOKING },
		{ "Nidoqueen", NIDOQUEEN },
		{ "Nidoran-F", NIDORAN_F },
		{ "Nidoran-f", NIDORAN_F },
		{ "Nidoran-M", NIDORAN_M },
		{ "Nidoran-m", NIDORAN_M },
		{ "Nidorina", NIDORINA },
		{ "Nidorino", NIDORINO },
		{ "Nincada", NINCADA },
		{ "Ninetales", NINETALES },
		{ "Ninjask", NINJASK },
		{ "Noctowl", NOCTOWL },
		{ "Nosepass", NOSEPASS },
		{ "Numel", NUMEL },
		{ "Nuzleaf", NUZLEAF },
		{ "Octillery", OCTILLERY },
		{ "Oddish", ODDISH },
		{ "Omanyte", OMANYTE },
		{ "Omastar", OMASTAR },
		{ "Onix", ONIX },
		{ "Pachirisu", PACHIRISU },
		{ "Palkia", PALKIA },
		{ "Paras", PARAS },
		{ "Parasect", PARASECT },
		{ "Pelipper", PELIPPER },
		{ "Persian", PERSIAN },
		{ "Phanpy", PHANPY },
		{ "Phione", PHIONE },
		{ "Pichu", PICHU },
		{ "Pidgeot", PIDGEOT },
		{ "Pidgeotto", PIDGEOTTO },
		{ "Pidgey", PIDGEY },
		{ "Pikachu", PIKACHU },
		{ "Piloswine", PILOSWINE },
		{ "Pineco", PINECO },
		{ "Pinsir", PINSIR },
		{ "Piplup", PIPLUP },
		{ "Plusle", PLUSLE },
		{ "Politoed", POLITOED },
		{ "Poliwag", POLIWAG },
		{ "Poliwhirl", POLIWHIRL },
		{ "Poliwrath", POLIWRATH },
		{ "Ponyta", PONYTA },
		{ "Poochyena", POOCHYENA },
		{ "Porygon", PORYGON },
		{ "Porygon-Z", PORYGON_Z },
		{ "Porygon-z", PORYGON_Z },
		{ "Porygonz", PORYGON_Z },
		{ "Porygon2", PORYGON2 },
		{ "Primeape", PRIMEAPE },
		{ "Prinplup", PRINPLUP },
		{ "Probopass", PROBOPASS },
		{ "Psyduck", PSYDUCK },
		{ "Pupitar", PUPITAR },
		{ "Purugly", PURUGLY },
		{ "Quagsire", QUAGSIRE },
		{ "Quilava", QUILAVA },
		{ "Qwilfish", QWILFISH },
		{ "Raichu", RAICHU },
		{ "Raikou", RAIKOU },
		{ "Ralts", RALTS },
		{ "Rampardos", RAMPARDOS },
		{ "Rapidash", RAPIDASH },
		{ "Raticate", RATICATE },
		{ "Rattata", RATTATA },
		{ "Rayquaza", RAYQUAZA },
		{ "Regice", REGICE },
		{ "Regigigas", REGIGIGAS },
		{ "Regirock", REGIROCK },
		{ "Registeel", REGISTEEL },
		{ "Relicanth", RELICANTH },
		{ "Remoraid", REMORAID },
		{ "Rhydon", RHYDON },
		{ "Rhyhorn", RHYHORN },
		{ "Rhyperior", RHYPERIOR },
		{ "Riolu", RIOLU },
		{ "Roselia", ROSELIA },
		{ "Roserade", ROSERADE },
		{ "Rotom", ROTOM },
		{ "Rotom-C", ROTOM_C },
		{ "Rotom-c", ROTOM_C },
		{ "Rotom-F", ROTOM_F },
		{ "Rotom-f", ROTOM_F },
		{ "Rotom-H", ROTOM_H },
		{ "Rotom-h", ROTOM_H },
		{ "Rotom-S", ROTOM_S },
		{ "Rotom-s", ROTOM_S },
		{ "Rotom-W", ROTOM_W },
		{ "Rotom-w", ROTOM_W },
		{ "Sableye", SABLEYE },
		{ "Salamence", SALAMENCE },
		{ "Sandshrew", SANDSHREW },
		{ "Sandslash", SANDSLASH },
		{ "Sceptile", SCEPTILE },
		{ "Scizor", SCIZOR },
		{ "Scyther", SCYTHER },
		{ "Seadra", SEADRA },
		{ "Seaking", SEAKING },
		{ "Sealeo", SEALEO },
		{ "Seedot", SEEDOT },
		{ "Seel", SEEL },
		{ "Sentret", SENTRET },
		{ "Seviper", SEVIPER },
		{ "Sharpedo", SHARPEDO },
		{ "Shaymin", SHAYMIN_L },
		{ "Shaymin-L", SHAYMIN_L },
		{ "Shaymin-l", SHAYMIN_L },
		{ "Shaymin-S", SHAYMIN_S },
		{ "Shaymin-s", SHAYMIN_S },
		{ "Shedinja", SHEDINJA },
		{ "Shelgon", SHELGON },
		{ "Shellder", SHELLDER },
		{ "Shellos", SHELLOS },
		{ "Shieldon", SHIELDON },
		{ "Shiftry", SHIFTRY },
		{ "Shinx", SHINX },
		{ "Shroomish", SHROOMISH },
		{ "Shuckle", SHUCKLE },
		{ "Shuppet", SHUPPET },
		{ "Silcoon", SILCOON },
		{ "Skarmory", SKARMORY },
		{ "Skiploom", SKIPLOOM },
		{ "Skitty", SKITTY },
		{ "Skorupi", SKORUPI },
		{ "Skuntank", SKUNTANK },
		{ "Slaking", SLAKING },
		{ "Slakoth", SLAKOTH },
		{ "Slowbro", SLOWBRO },
		{ "Slowking", SLOWKING },
		{ "Slowpoke", SLOWPOKE },
		{ "Slugma", SLUGMA },
		{ "Smeargle", SMEARGLE },
		{ "Smoochum", SMOOCHUM },
		{ "Sneasel", SNEASEL },
		{ "Snorlax", SNORLAX },
		{ "Snorunt", SNORUNT },
		{ "Snover", SNOVER },
		{ "Snubbull", SNUBBULL },
		{ "Solrock", SOLROCK },
		{ "Spearow", SPEAROW },
		{ "Spheal", SPHEAL },
		{ "Spinarak", SPINARAK },
		{ "Spinda", SPINDA },
		{ "Spiritomb", SPIRITOMB },
		{ "Spoink", SPOINK },
		{ "Squirtle", SQUIRTLE },
		{ "Stantler", STANTLER },
		{ "Staraptor", STARAPTOR },
		{ "Staravia", STARAVIA },
		{ "Starly", STARLY },
		{ "Starmie", STARMIE },
		{ "Staryu", STARYU },
		{ "Steelix", STEELIX },
		{ "Stunky", STUNKY },
		{ "Sudowoodo", SUDOWOODO },
		{ "Suicune", SUICUNE },
		{ "Sunflora", SUNFLORA },
		{ "Sunkern", SUNKERN },
		{ "Surskit", SURSKIT },
		{ "Swablu", SWABLU },
		{ "Swalot", SWALOT },
		{ "Swampert", SWAMPERT },
		{ "Swellow", SWELLOW },
		{ "Swinub", SWINUB },
		{ "Taillow", TAILLOW },
		{ "Tangela", TANGELA },
		{ "Tangrowth", TANGROWTH },
		{ "Tauros", TAUROS },
		{ "Teddiursa", TEDDIURSA },
		{ "Tentacool", TENTACOOL },
		{ "Tentacruel", TENTACRUEL },
		{ "Togekiss", TOGEKISS },
		{ "Togepi", TOGEPI },
		{ "Togetic", TOGETIC },
		{ "Torchic", TORCHIC },
		{ "Torkoal", TORKOAL },
		{ "Torterra", TORTERRA },
		{ "Totodile", TOTODILE },
		{ "Toxicroak", TOXICROAK },
		{ "Trapinch", TRAPINCH },
		{ "Treecko", TREECKO },
		{ "Tropius", TROPIUS },
		{ "Turtwig", TURTWIG },
		{ "Typhlosion", TYPHLOSION },
		{ "Tyranitar", TYRANITAR },
		{ "Tyrogue", TYROGUE },
		{ "Umbreon", UMBREON },
		{ "Unown", UNOWN },
		{ "Ursaring", URSARING },
		{ "Uxie", UXIE },
		{ "Vaporeon", VAPOREON },
		{ "Venomoth", VENOMOTH },
		{ "Venonat", VENONAT },
		{ "Venusaur", VENUSAUR },
		{ "Vespiquen", VESPIQUEN },
		{ "Vibrava", VIBRAVA },
		{ "Victreebel", VICTREEBEL },
		{ "Vigoroth", VIGOROTH },
		{ "Vileplume", VILEPLUME },
		{ "Volbeat", VOLBEAT },
		{ "Voltorb", VOLTORB },
		{ "Vulpix", VULPIX },
		{ "Wailmer", WAILMER },
		{ "Wailord", WAILORD },
		{ "Walrein", WALREIN },
		{ "Wartortle", WARTORTLE },
		{ "Weavile", WEAVILE },
		{ "Weedle", WEEDLE },
		{ "Weepinbell", WEEPINBELL },
		{ "Weezing", WEEZING },
		{ "Whiscash", WHISCASH },
		{ "Whismur", WHISMUR },
		{ "Wigglytuff", WIGGLYTUFF },
		{ "Wingull", WINGULL },
		{ "Wobbuffet", WOBBUFFET },
		{ "Wooper", WOOPER },
		{ "Wormadam", WORMADAM_P },
		{ "Wormadam-P", WORMADAM_P },
		{ "Wormadam-g", WORMADAM_S },
		{ "Wormadam-S", WORMADAM_S },
		{ "Wormadam-s", WORMADAM_T },
		{ "Wormadam-T", WORMADAM_T },
		{ "Wurmple", WURMPLE },
		{ "Wynaut", WYNAUT },
		{ "Xatu", XATU },
		{ "Yanma", YANMA },
		{ "Yanmega", YANMEGA },
		{ "Zangoose", ZANGOOSE },
		{ "Zapdos", ZAPDOS },
		{ "Zigzagoon", ZIGZAGOON },
		{ "Zubat", ZUBAT }
	};
	auto const it = converter.find (str);
	if (it != converter.end ())
		return it->second;
	else
		throw InvalidFromStringConversion ("Species", str);
}

}	// namespace technicalmachine
