name: Build and test

on:
  schedule:
    - cron: '27 10 * * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    if: github.event_name != 'schedule'
    strategy:
      fail-fast: false
      matrix:
        clang_version: [ 'main', '22' ]
    uses: ./.github/workflows/build-and-test-impl.yml
    with:
      clang_version: ${{ matrix.clang_version }}

  nightly:
    if: github.event_name == 'schedule'
    uses: ./.github/workflows/build-and-test-impl.yml
