name: Build and test

on:
  schedule:
    - cron: '27 10 * * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get usage stats
      run: |
        cd ..
        git clone --depth 1 https://github.com/davidstone/pokemon-usage-stats.git
        echo "TM_USAGE_STATS_DIRECTORY=$PWD/pokemon-usage-stats" >> "$GITHUB_ENV"
    - name: Set settings directory environment variable
      run: echo "TM_SETTINGS_DIRECTORY=$PWD/settings" >> "$GITHUB_ENV"
    - name: Set test directory environment variable
      run: echo "TM_TEST_DIRECTORY=$PWD/test" >> "$GITHUB_ENV"
    - name: Get boost
      run: |
        cd ..
        wget https://archives.boost.io/release/1.87.0/source/boost_1_87_0.tar.bz2
        tar xf boost_1_87_0.tar.bz2
        mkdir -p boost/include
        ln -s $PWD/boost_1_87_0/boost boost/include/boost
    - uses: davidstone/cmake_strict_defaults@main
      with:
        dependencies: 'libtbb-dev'
        cmake_args: '-DBoost_INCLUDE_DIR="${{github.workspace}}/../boost/include" -DCMAKE_CXX_FLAGS="-Og"'
