name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  install-boost:
    runs-on: ubuntu-latest
    steps:
      - name: Install boost
        run: |
          sudo apt-get install libboost-all-dev
          ls /usr/include/boost
  build:
    needs: install-boost
    uses: davidstone/cmake_strict_defaults/.github/workflows/build-and-test.yml@main
