name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    uses: davidstone/cmake_strict_defaults/.github/workflows/build-and-test.yml@main
    with:
      dependencies: 'libboost-all-dev libtbb-dev'
  tmate:
    needs: build
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Set up tmate
        uses: mxschmitt/action-tmate@v3
