name: Build and test against clang trunk

on:
  schedule:
    - cron: '27 5 * * *'
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get usage stats
      run: |
        cd ..
        git clone --depth 1 https://github.com/davidstone/pokemon-usage-stats.git
        echo "TM_USAGE_STATS_DIRECTORY=$PWD/pokemon-usage-stats" >> "$GITHUB_ENV"
    - name: Set settings directory environment variable
      run: echo "TM_SETTINGS_DIRECTORY=$PWD/settings" >> "$GITHUB_ENV"
    - name: Set test directory environment variable
      run: echo "TM_TEST_DIRECTORY=$PWD/test" >> "$GITHUB_ENV"
    - name: Get boost
      run: |
        cd ..
        wget https://boostorg.jfrog.io/artifactory/main/release/1.84.0/source/boost_1_84_0.tar.bz2
        tar xf boost_1_84_0.tar.bz2
        mkdir -p boost/include
        ln -s $PWD/boost_1_84_0/boost boost/include/boost

    - uses: actions/checkout@v4
      with:
        submodules: true
  
    - name: Install clang
      shell: bash
      run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo add-apt-repository "deb https://apt.llvm.org/$(lsb_release -sc)/ llvm-toolchain-$(lsb_release -sc) main"
        sudo apt-get update
        sudo apt-get install mold libtbb-dev clang
        clang++ --version
        sudo apt-get install clang-tools-$(clang++ --version | head -n 1 | cut -f 4 -d ' ' | cut -f 1 -d '.')
  
    - uses: lukka/get-cmake@latest
  
    - name: Configure CMake
      shell: bash
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug -G"Ninja" -DCMAKE_CXX_COMPILER="clang++" -DCMAKE_CXX_COMPILER_CLANG_SCAN_DEPS="/usr/bin/clang-scan-deps-$(clang++ --version | head -n 1 | cut -f 4 -d ' ' | cut -f 1 -d '.')" -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=mold" -DBOOST_ROOT="${{github.workspace}}/../boost"
  
    - name: Build
      shell: bash
      run: cmake --build ${{github.workspace}}/build --config Debug
  
    - name: Test
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: ctest -C Debug --output-on-failure
